### ISSUE TITLE
Scheduled Export Reminder/Prompt

### ISSUE THREAD

**Issue by Ben-Voris** [strongbox-password-safe/Strongbox#12]
Using the Files app, I’ve been able to copy a safe from Google drive to the Strongbox folder in iCloud, which then served as a back up for the times that Google Drive is misbehaving. 

I would like a direct way to have a Strongbox create a back up on another cloud provider.

**Comment by mmcguill** [comment]
This could be generalised as a "Duplicate Database Somewhere" feature in general and accessed off of the Database List (Home Screen) - Slide Left (Edit Actions)

**Comment by mmcguill** [comment]
Hi @Ben-Voris - I've been thinking about this a little. Currently you can unlock your database and Export it via Files to anywhere you like. Is this this sufficient for you?

**Comment by Ben-Voris** [comment]
What you describe is the work around that I mention above. The problem with it is it I must remember to back up a file. (On Linux, I have a cron job that periodically creates a backup of the safe on that device.)

The intent of this request is more than a back up before a change. It is to provide resiliency in the face of an outage of one cloud provider. A number of times, I’ve been unable to access the current instance of a safe from some devices because changes made in on one device were unavailable on others because because  sync with one provider was temporarily down.

**Comment by mmcguill** [comment]
Ok, let's try to narrow this down a little. Is the current 'Export' functionality ok? 

You just want to have it done very quickly and possible scheduled?

**Comment by Ben-Voris** [comment]
I use the File app instead of 'Export', but yes.

Quickly isn't the key (though it would be nice). I'd like something along the line of "If the file has been changed since the last backup and the last backup of this file is more than *'d'* days old, create a backup at *'y'*" where *'y'* is a location available in Files. E.g., backup from Google Drive to iCloud every 7 days. A backup to a given location on each save would work. E.g., each time a file is saved to Google Drive, copy it to iCloud.

I looked at Cronios, but iOS restrictions made it too unreliable. It seems each app must be responsible for its own backups.

**Comment by mmcguill** [comment]
Ok, thanks @Ben-Voris - I think probably the best I can do here is to prompt you on a schedule to Export => which will then bring up the export dialog

**Comment by Ben-Voris** [comment]
A periodic reminder would be an improvement. The reminder interval should be configurable. For bonus points, remember the last backup/export and do not prompt if the file has not been modified since the last backup.
One part of using the export function for backup is that it overwrites the previous backup. Any chance of adding a date-time stamp to the end of the file name?

**Comment by mmcguill** [comment]
Sounds good @Ben-Voris - I'll try to take these things into account. Let's morph this issue into the primary Scheduled Export Reminder/Prompt issue

**Comment by Ben-Voris** [comment]
I agree.

**Comment by strongbox-mark** [comment]
Hi @Ben-Voris - This feature is now (finally) available in 1.52.19 available on the App Store now. It takes into account the last modified date also. Please let me know if there are any issues (you could open a separate bug for those).
