### ISSUE TITLE
Double TouchID Prompt on Mac

### ISSUE THREAD

**Issue by nicad** [strongbox-password-safe/Strongbox#129]
If I enable touchID I should get the touchID prompt any time I go to this database. Today I have to take my mouse and manually click on a button first. I'd like to be able to get to a password keyboard only (I can do that with KeePassXC or 1Password for example, even though KeePassXC is not great because I first have to hit ENTER to get the TouchID prompt but that's better than using the mouse)

**Comment by mmcguill** [comment]
Sounds like a bug, thanks.

**Comment by mmcguill** [comment]
This is ready for test now. You'll need to enable this in Preferences:

<img width="348" alt="image" src="https://user-images.githubusercontent.com/344791/61898792-b63e7f80-aedf-11e9-94ab-f01fa6c9aa27.png">

Please let me know if it works ok for you

**Comment by mmcguill** [comment]
Hi @nicad - Were you able to check if this is working as expect?

**Comment by nicad** [comment]
Sorry for the delay, seems to work. If I cancel though the prompt keeps coming back. To reproduce: CMD-L to lock, then hit Cancel.
If I unlock with TouchID I can a second prompt about authorizing "Open database" that is very sketchy. Plus it seems to always happen, so need to double authenticate with TouchID.
See the attached screenshot
<img width="444" alt="Screen Shot 2019-09-15 at 3 23 39 PM" src="https://user-images.githubusercontent.com/1311134/64928433-3345f100-d7cd-11e9-90ee-618f53c8ea5c.png">

**Comment by mmcguill** [comment]
HI @nicad, thanks for getting back to me. Are the two prompts identical? What is sketchy about them?

**Comment by nicad** [comment]
Ok, it's actually twice the same prompt. What's sketchy is the wording is very generic "Open Database", maybe it should "open database {dbname}". I didn't realize it was the same prompt so the 2nd prompt could have authorized Strongbox to access anything with higher privileges. Now that I realize it's the same prompt it's clearly a bug ;-)
I've attached more helpful screenshots.
<img width="995" alt="Screen Shot 2019-09-15 at 5 10 32 PM" src="https://user-images.githubusercontent.com/1311134/64929531-1bc23480-d7dc-11e9-8651-d4e8a1b1913b.png">
<img width="998" alt="Screen Shot 2019-09-15 at 5 10 18 PM" src="https://user-images.githubusercontent.com/1311134/64929532-1bc23480-d7dc-11e9-835f-aacbff8559e4.png">

**Comment by mmcguill** [comment]
Ok thanks! I'll try patch this up for you soon!

**Comment by mmcguill** [comment]
This should be fixed now with 1.12.0 release. Please feel free to re-open if this is not working as expected.
