### ISSUE TITLE
Printing Emergency Sheet (a la KeePass)

### ISSUE THREAD

**Issue by mlfreeman2** [strongbox-password-safe/Strongbox#138]
Please clone the printing / PDF generation capabilities in KeePass for Windows.

I live in the lightning capital of the world (Florida), and I’ve had multiple lightning strikes at both my house and my parents’ house (where I keep offsite backups), so I keep a printed copy of everything super-critical just in case.

For now, I’m using KeePass on my Surface Book 2 to print a paper copy of my DB...it works, but it’d be nice to be able to print from either device.

One thing that KeePass doesn’t do out of the box that you could is print text/image attachments too. 

I’m sure this won’t be a small task but I figured it needed to be on your roadmap anyway.

Perhaps you could start by creating a clone of the KeePass Emergency Sheet and build from there.

**Comment by mmcguill** [comment]
Interesting, yes, sounds very doable. I'll investigate.

**Comment by mmcguill** [comment]
Available for test now @mlfreeman2 with Mac version 1.10.0. Let me know how it goes.

**Comment by mlfreeman2** [comment]
Finally got a chance to look at it. 
Looks great initially...got the username, password, URL, and additional fields (so security questions are included).

I want to sit down and compare it in depth with the output from KeePass soon.

**Comment by mlfreeman2** [comment]
Sorry for the long delay on this.
Data looks good. 

Nice touch including the custom fields by default.
I always had to turn that on in KeePass and could never get it to save as the default setting.

I did have one suggestion for two format options: 
1. Page Break on folders with entries immediately underneath.
2. Page Break on folders without entries immediately underneath.

Two things led to those ideas: 

- I have my file divided into two major groups: Online Accounts and Machine Credentials.
  - Those top level folders are empty because I divide online accounts by type and machine credentials by where the machine is. It'd be nice to have clean divisions of the printout into two sections.
- Also, sometimes folder titles for folders with entries would "start" right on the bottom of a page.

Since I'm sure there's no room in password manager files for formatting options, you'd have to store those at the MacOS user account level (e.g. in ~/Library/).

If you're generating a HTML file like KeePass and sending that to OS X for printing, you can do page breaks in CSS....check this out.

https://stackoverflow.com/questions/1664049/can-i-force-a-page-break-in-html-printing/1664058

**Comment by mlfreeman2** [comment]
Can you make the "Printed: (date)" a few points larger?
Also, can you leave out the Recycle Bin (or make an option to leave out folders that have nothing underneath)?

**Comment by mmcguill** [comment]
Thanks, noted

**Comment by jtkohl** [comment]
For iOS, I use the printing feature to store a backup copy on paper in my home safe.  One thing that's not quite right in the printed output:  the usernames and passwords that are references to other entries are printed as REF instead of printing the other entry's password.  That makes the paper backup less useful than it should be (especially in case a trusted family member needs to use the paper backup if I am unavailable).

So, could you update the printing code to dereference usernames/passwords?  Thanks!

**Comment by strongbox-mark** [comment]
Yes, good idea. Thanks.

**Comment by strongbox-mark** [comment]
Hi, the Print function should be much improved, we don't print the Recycle Bin items or Empty folders any more, also Referenced entries are probably dereferenced.
