### ISSUE TITLE
Configurable Database Encryption (Algorithm & Parameters)

### ISSUE THREAD

**Issue by milesmcclane** [strongbox-password-safe/Strongbox#147]
On other (desktop) versions of Keepass (unsure about strongbox for the desktop, I’m away from my computer and unable to check) you’re able to define further than just the type of encryption, you’re able to define the number of iterations etc. 

How possible would it be to have this ability on iOS/iPadOS versions of strongbox? Not necessarily for the ability to define such matters when creating a database, but also ability to alter other databases that may have been created using the desktop. 

I’m not sure I’m explaining myself properly!!

**Comment by mmcguill** [comment]
Hi @milesmcclane, yeah this is totally possible, no major technical difficulty. It's just not high up on the roadmap just yet. Let's use this ticket to track.

**Comment by milesmcclane** [comment]
Cool thanks for thinking about it! Loving all the flexibility of strongbox and your dedication!

**Comment by strongbox-mark** [comment]
@milesmcclane - These settings are now configurable on iOS with 1.54.0. Will leave open for MacOS implementation

**Comment by strongbox-mark** [comment]
Hi all, encryption is now configurable on macOS too with 1.18.2 :)
