### ISSUE TITLE
iOS 13 dark mode support

### ISSUE THREAD

**Issue by jtkohl** [strongbox-password-safe/Strongbox#160]
Please add support for dark mode colors when dark mode is enabled.

**Comment by mmcguill** [comment]
Sure, I'll probably wait until the Beta's become reasonably stable before doing this though.

**Comment by shad0whawk** [comment]
Dark mode support looks good so far. I haven’t noticed any glaring issues.

**Comment by mmcguill** [comment]
I think we're probably good to close here. There are probably one or two minor issues, please open separately.
