### ISSUE TITLE
List view still "jumps" a bit...

### ISSUE THREAD

**Issue by hajosc** [strongbox-password-safe/Strongbox#165]
...when coming from a dialog box, another view (e.g. edit) and then starting to scroll. Not a major issue but it feels a bit rough around the edges since you'll easily loose orientation about where on the list you are.

**Comment by mmcguill** [comment]
What version are you seeing this on? Would you be able to record a screen of this for me, I can't reproduce the issue here.

**Comment by hajosc** [comment]
V1.35.3 It’s more pronounced in an actual long record that I use (maybe more complex fields like more hidden, URLs, etc) but the effect can also be seen on a test entry I created. Note how it’s a bit “jumpy” after coming back from the preferences screen: 
https://share.icloud.com/photos/0E1SOuFu6s_BnJNbmcuwLO3Ew

**Comment by mmcguill** [comment]
I see, so this is not in the Browse/List view but rather in the Details view - If you switch to say preferences and then dismiss, you get a little jump, right? Ok Thanks for the report

**Comment by mmcguill** [comment]
I believe this is fixed now @hajosc - Could you confirm and close if so?

**Comment by hajosc** [comment]
Fixed; thx a lot :-)
