### ISSUE TITLE
Drag and Drop Functionality

### ISSUE THREAD

**Issue by shad0whawk** [strongbox-password-safe/Strongbox#166]
It would be nice to see drag and drop functionality added to the app that would allow the user to reorder the database list and the folders and entries within the database.

**Comment by mmcguill** [comment]
Hi @shad0whawk,

You should be able to re-order the databases (Tap Edit and you can move them up and down with the "gripper").

You should also be able to do this to your Folders and Entries but you need to set the Sort Order to 'Custom' first, then tap Edit, and again move them up and down with the 'Gripper'

Do those not work for you, or did you want something else?

**Comment by shad0whawk** [comment]
The method you described works and that’s what I use currently. I was thinking of a todo app called Things that I really like and use when I wrote this suggestion. I can tap, hold, and easily move items around within and between the list and sublist windows without having to go to a dedicated edit mode.  If it’s not feasible or undesired feel free to close this suggestion. I can provide you with a short video to demonstrate what I’m talking about if this doesn’t make sense.

**Comment by mmcguill** [comment]
Yep, sort of makes sense. A video would be cool

**Comment by shad0whawk** [comment]
Just sent it to your support mailbox.
