### ISSUE TITLE
Auto-Type

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#168]
I went through the list of issues for the macOS version of Strongbox. The only "Auto-Type" aka. "Autofill" related issue I could find is #21. On the [Compare Versions](https://strongboxsafe.com/feature-comparisons-ios-mac-free-pro/) page I only found iOS Autofill mentioned.

Auto-Type is an essential feature of KeePass and also the Strongbox app for iOS. Is there a chance we will see this in Strongbox for macOS in the future? I'd specifically be interested in Auto-Type for Google Chrome.

Thanks!

**Comment by georgesnow** [comment]
in the meantime if you wanted to. I believe you could change that script to work with Chrome. replace the tell application Safari with this:

`tell application Google Chrome to get URL of active tab of front window`

I would recommend using FastScripts (free for the first 10 hotkeys)

 https://red-sweater.com/fastscripts/

Then you can assign Global keyboard shortcut to that script to run. You will need to allow permissions for FastScripts to interact with Strongbox and Chrome (it will prompt you). 
(the script is as is, no warranty etc...)

**Comment by mmcguill** [comment]
Hi @dan-el - Yes you're right, this is an overlooked feature. I think a lot of people are using Tusk for Auto Fill on Chrome and Firefox though, which helps to alleviate the need for Auto Type. Have you given it a try or do you prefer to use Auto Type?

https://github.com/subdavis/Tusk

**Comment by dan-el** [comment]
Thanks, George and Mark,

To be honest I'd like to avoid workarounds as well as browser plugins. I never liked the idea of password manager browser integration...
Also  Tusk is not being actively maintained at the moment.

I guess I'll wait for a native Strongbox Auto-Type feature. In the meantime I bacame a Ninja to support the process :-)

Best
Daniel

**Comment by mmcguill** [comment]
Thanks @dan-el - Let's use this issue to track 
Best,
-Mark

**Comment by dan-el** [comment]
Hey @mmcguill 

Any progress with the auto-type feature for the macOS version of Strongbox?

**Comment by mmcguill** [comment]
Hi @dan-el - I'm afraid not and I'm afraid it would be tough to give you an ETA

**Comment by dan-el** [comment]
Hi Mark,

Checking on this once again :-) 
Any idea when this feature might happen?

I have been using Strongbox for a while now on macOS without AutoType.
At work we use 1Password and their AutoType implementation with the dropdown on form fields is driving me crazy, hence I turned it off all-together.

Bottomline: I get along pretty well without Auto-Type and I don't see other users needing Auto-Type on macOS in Strongbox.

Ready to close this one.

Best
Daniel

**Comment by strongbox-mark** [comment]
Hi @dan-el - thanks for checking in! :)  

With MacOS Big Sur, Password AutoFill is coming to Mac, like iOS AutoFill. So I'm hoping that will negate the need for AutoType completely.

**Comment by dan-el** [comment]
Cool, I am not yet up to date with the new features of Big Sur :-)

I'll go ahead and close this issue then.

Thank you!

**Comment by strongbox-mark** [comment]
Yes, well fingers crossed it's as good as iOS AutoFill... Cheers!

**Comment by kahunaoplomo** [comment]
Hi,

I did not migrate to Big Sur yet, does anyone have experience with Big Sur's auto type with Strongbox? Is experience comparable to keepass auto type on Windows?

Thx,
Tym

**Comment by strongbox-mark** [comment]
Hi @kahunaoplomo - AutoFill isn't really the same as AutoType, and I don't think the experience will be comparable. You can try it out though and see if it's of interest.

**Comment by 89sundown** [comment]
Any word on this feature being implemented?

**Comment by strongbox-mark** [comment]
Hi @89sundown - see #563 for more, but in short this isn't high on the priority list at the moment for a number of reasons. Have you tried the browser plugin for AutoFill? Might be helpful...

**Comment by niklzz** [comment]
Hi! I decided to try to switch from KeePassXC to your software, but I was surprised to find no auto-type feature! Friends, please add it, it is very necessary when a remote machine in Citrix is blocked and you need to enter a long password from the manager. Without this function you must type the password by hands!
