### ISSUE TITLE
iOS AutoFill proposal with old username shown

### ISSUE THREAD

**Issue by Slummi** [strongbox-password-safe/Strongbox#172]
I'm not sure if this is a bug in Strongbox or in the iOS AutoFill feature.

I modified the username of a KeePass entry a few days ago.
When I open the related website in Safari, iOS shows a proposal for that entry at the top of the keyboard, but with the old username. But after tapping it, the form is filled in with the new (correct) username.
When I tap the key icon (instead of the proposal), iOS shows me two proposals for the website: one with the old username and one with the new username (and the option to open Strongbox).
In the database there's only one entry for that website.

Then I deactivated AutoFill for that database and reactivated it and there was just one proposal left with the new username. So, I think this is a bug in the Strongbox AutoFill cache.

And one question:
Why does the iOS keyboard show a matching entry only for websites opened with Safari, but not for websites opened with other browsers like Firefox. In Firefox I have only the option to start Strongbox and then select the desired entry. Is this a limitation of third party apps?

**Comment by mmcguill** [comment]
Hi Slummi, how many AutoFill enabled databases do you have in Strongbox? If it is more than 1 then this is a expected (unfortunately). This is due to the way the QuickType API is designed, an App like Strongbox is only allow to enter one set of credentials (no matter how many it manages). 

For the second question, yeah, hard to say, and completely out of Strongbox's control. That entry point is really up to iOS as to when/what to show in what context/app...

**Comment by Slummi** [comment]
I had two databases with AutoFill enabled, but one of them only for test purposes.
I disabled AutoFill for that database, so that I have only one with AutoFill enabled and the behavior is the same. I can reproduce this all the time:

1. Edit the username of an entry
2. Open that website in Safari
3. QuickType shows the old username, but uses the new one
4. Open Database and disable AutoFill
5. Enable AutoFill again
6. Open that website in Safari
7. QuickType shows the correct new username

I thoght before that this is an iOS thing where QuickType works and where not.

**Comment by mmcguill** [comment]
Ok, interesting @Slummi - I'll try take a look into this soon. I know the AutoFill data that iOS uses can have a little lag, probably due to caching.

**Comment by mmcguill** [comment]
I think this is probably just a caching issue, no other reports of this since. Going to close out but feel free to reopen if you think it needs to be looked at
