### ISSUE TITLE
Adding second DB in same Webdav dir doesn’t work

### ISSUE THREAD

**Issue by maltokyo** [strongbox-password-safe/Strongbox#175]
As in title, I added one DB from my WebDAV dir no problem. Then when adding second separate DB (in exactly the same WebDAV dir), I get this error. Please help. 

Latest iOS version on iPhone 7. 

![C3C2BF86-34D3-408F-B39E-411D176EC33C](https://user-images.githubusercontent.com/1388507/62606808-45df2780-b8fd-11e9-85f3-4914b9cedbd8.png)

**Comment by mmcguill** [comment]
Hi @maltokyo - Are you using a different credentials to login the second time (different username/password)? If so, have you seen #120 ?

**Comment by maltokyo** [comment]
Hi @mmcguill , many thanks for the response. This was really my last “issue” I was having before signing up for the paid version. I have several DB files stored on this WebDAV server and will be testing new ones all the time, and making a new subdomain for each (while feasible) feels like too much of a workaround. Do you see it feasible to solve at some stage?

**Comment by mmcguill** [comment]
Hi, yes, it's definitely feasible, just a matter of scheduling. It's a non trivial fix, but very doable I believe... 

Just to be clear, are you using different credentials each time or no?

**Comment by maltokyo** [comment]
No I was using same url and same u/p

**Comment by mmcguill** [comment]
Oh, weird, then you shouldn't be affected by this #120 at all...

I just did a test and I can connect to 2 different databases in the same folder via WebDAV using the same user/password.

One to double check - Have you checked 'Allow Untrusted Certificate' in both cases? or do you have a good certificate so that this is not required?

**Comment by maltokyo** [comment]
I have a fully signed and valid letsencrypt cert. so no issues there. Shall I make you a user?

**Comment by mmcguill** [comment]
OK, sure... will help me debug. shoot me a mail support@strongboxsafe.com if you like

**Comment by maltokyo** [comment]
Done, thank you!

**Comment by mmcguill** [comment]
Confirmed with @maltokyo this appears to be some kind of server configuration problem. Closing.
