### ISSUE TITLE
Problem Saving: com.MattRajca.DAVKit.error error 507

### ISSUE THREAD

**Issue by bl4x1** [strongbox-password-safe/Strongbox#176]
When I try to save a new entry to my WebDAV Database this error message pops up. I cannot include a screenshot, because it would include a lot of private information and other database entries.

I‘m using the latest AppStore version of the App on an iPad Pro 11“. It doesn‘t matter if I try to create a new entry directly in the app or if I try to use the Browser „Add-In“ that comes up when the cursor enters a password or username field.

Please tell me if you need any additional information.

**Comment by mmcguill** [comment]
Hi there. That seems like it might be a HTTP 507 error from your WebDAV server.

https://httpstatusdogs.com/507-insufficient-storage

Have you run out of disk space on there?

**Comment by bl4x1** [comment]
Thank you for your quick answer, I wasn’t aware that it was simply a http status code. I‘ll get in touch with the cloud provider, but I certainly haven‘t run out of cloud space, it says 50MB of 40GB used.

**Comment by mmcguill** [comment]
Ok, it could be a quota limit, or a limit on the individual size of a HTTP request too, not necessarily just overall storage space... Hard to say, but your storage provider should be able to help... 

Maybe one test is to create a new database (which will be tiny) via Strongbox on there and see if that works.

**Comment by bl4x1** [comment]
I did a bit of testing today and I can‘t replicate the error. Maybe the storage provider changed something on their side. Thank you for your support anyways.
