### ISSUE TITLE
iOS 13 - AutoFill Not Working

### ISSUE THREAD

**Issue by shad0whawk** [strongbox-password-safe/Strongbox#177]
I’m opening this issue to get it on your radar but I haven’t had much time to test it. Autofill appears broke on 1.38.2 running iOS 13 beta 6. I’m not sure if it’s a Strongbox Issue or iOS issue. Autofill pops up in Safari and I authenticate, but nothing is filled. It’s a consistent issue. I’ve closed all apps and rebooted but the issue persists. I toggled the Autofill settings in Strongbox as well. I’ll add more detail as I figure out more. 

Update...

I tried version 1.38.0 that is still installed on my other phone which is also on iOS 13 beta 6 and it works as expected. I sent you a couple of videos showing the behavior—one using Safari and the other one Chrome. 

Update 2...

I turned Autofill off/on completely in the settings and now it seems to work again but only every other time and very consistently at that. I’ll send you another video of the behavior in case it helps.

**Comment by shad0whawk** [comment]
Well the more I play with it the less it works :-(  Now it’s back to not working at all again. I’ve turned everything off and on multiple times and I keep getting mixed results—sometimes it works intermittently and other times not at all. Is anyone else having this issue or just me?

**Comment by mmcguill** [comment]
Hi @shad0whawk - I haven't heard this before, but for the moment I won't be looking into iOS 13 issues until we get a very stable Beta.

**Comment by shad0whawk** [comment]
Unfortunately I had a feeling you were going to say that.  I'm going to see if I can replicate the behavior on iOS 12 and will report back if it happens there as well.  It's interesting that it happens on one device with iOS 13 but not the other running a slightly older version of Strongbox.  I need to extract the 1.38.1 ipa before I test it on iOS 12 so I can roll back if needed and maybe update the ios 13 device with issues with the slightly older ipa.

**Comment by shad0whawk** [comment]
Well going to close it since it seems to only be an issue with one of my devices and unfortunately my primary one.  Maybe it's beta-related glitch and will work itself out in the next update.  If not, I guess I'll have to try resetting my settings (ouch!) or reinstalling when the final is released (bigger ouch!).
