### ISSUE TITLE
Sometimes Auto Fill doesn't Populate Field

### ISSUE THREAD

**Issue by shad0whawk** [strongbox-password-safe/Strongbox#178]
I do have an iOS 12.4 issue with autofill on my iPad.  I'll send you a video of the behavior to your support box.  I've noticed it before where sometime it doesn't populate the entry the first time, but haven't messed it with much until now.  If I open a webpage in Safari, select the username or password box, select the autofill entry form Strongbox and authenticate, it will populate the username/password box every other time--so alternating between fill and not fill.

Steps to replicate:
1.  Select username/password box in Safari
2. Tap autofill entry prompted by Strongbox (entry populates)
3. Refresh web page to clear username/password boxes
4. Tap autofill entry prompted by Strongbox a second time (nothing populates)
5. Refresh web page to clear username/password boxes
6. Tap autofill entry prompted by Strongbox (entry populates)
7.  Repeat 1-6 with same results

**Comment by mmcguill** [comment]
Ok, thanks for the bug report.

**Comment by shad0whawk** [comment]
Of course.  It’s nothing major just something I’ve noticed across all of my devices.

Marc Burris
303.809.8149
marc.burris@gmail.com

________________________________

**Comment by mmcguill** [comment]
Hi @shad0whawk  @georgesnow - as mentioned in other issues, 1.42.0 comes with some performance enhancements I believe will fix these issues. 

Could you test and let me know?

**Comment by georgesnow** [comment]
so far i haven't encountered this issue.

**Comment by mmcguill** [comment]
I'm going to close off here without further feedback, this is likely to be an iOS issue if anything
