### ISSUE TITLE
What does new 'Status Indicator' icon mean?

### ISSUE THREAD

**Issue by Ben-Voris** [strongbox-password-safe/Strongbox#180]
There is a new-ish eyeglass appearing next to some of my safe names. This icon is in the same position as the rocket icon that denotes the default safe and can be disabled by turning off "Show Status Indicator". What is it trying to tell me?

**Comment by Slummi** [comment]
That‘s the indicator for a read-only database. ;)

**Comment by mmcguill** [comment]
Yes, @Slummi is correct, it's currently only used to indicate if the database is:

- Quick Launch
- Read-Only
- In an iCloud Conflicted state

**Comment by Ben-Voris** [comment]
Thanks.
