### ISSUE TITLE
iOS 13 couldn't access icloud for some time (FYI)

### ISSUE THREAD

**Issue by jtkohl** [strongbox-password-safe/Strongbox#183]
iOS public beta 6, 13.0 17A5572a
app version 1.40.0

Unable to read database stored in iCloud.  Attempting this gets error about being unable to read file.
In preferences, Cloud "use iCloud" was greyed out, showing unavailable.

But then I went back to reproduce all of this, and it started working.  So something unwedged itself along the way.

So I figured I'd file this as an FYI.

As a workaround I was opening the file with "Add existing database" and using "Files..." application integration.  That seemed to work fine but I didn't know if that would manage off-line and careful accesses to get safer database syncing among devices?

**Comment by mmcguill** [comment]
This should be ok now with 1.42.0 and iOS13 GM. Could you confirm and close if so... @jtkohl

**Comment by jtkohl** [comment]
So far so good with 1.42.0, but it happened intermittently before.  I'll close it now but reopen if I hit the problem again, OK?
