### ISSUE TITLE
[Bug] Autofill and app password 

### ISSUE THREAD

**Issue by georgesnow** [strongbox-password-safe/Strongbox#185]
I found an issue when i got to website that doesn't present a quick type option. i can't unlock the database it just brings me back to the database list. 
Select "Passwords"
Click any Database (using a pin or manually enter password)
Enter PiIN or Password 
Returns you to the database selection

gif below (it only shows the me testing against my test databases for obvious reasons)

![storngbox-issue](https://user-images.githubusercontent.com/12751441/63950259-a586a980-ca49-11e9-80a9-d4158e2bfce4.gif)

**Comment by georgesnow** [comment]
follow up so i select username i get Passwords option. I select password field and I get presented with a quicktype entry option. I selected the quick type entry entered my PIN. Strongbox is now stuck on Loading Strongbox Autofill

**Comment by georgesnow** [comment]
ok so i installed the latest strongbox update and tried again. it got worse now in  the actual strongbox app. it is stuck showing this. (attached screenshot)
and i can't unlock any of the databases. i get stuck in that loop above. if i try. closing the app and reopening brings me to the app password. which I enter. i then get stuck with the Reading... issue again.


![Screen Shot 2019-08-29 at 10 53 05 AM](https://user-images.githubusercontent.com/12751441/63951068-19758180-ca4b-11e9-8ff0-37cd341d5971.png)

**Comment by georgesnow** [comment]
and the only way i got around it was. 
Quit the app
Re-open App
Reset pin (to the same thing)
Quit app
Re open enter app pin (asked for it twice)
Select hamburger in top left 
Then click done to go back to databases ("Reading ..." cleared out)
Select desired database and enter PIN or Password (db dependent)

Works again.

**Comment by mmcguill** [comment]
Ok, very strange, thanks for the bug report @georgesnow - I'll look into this shortly.

**Comment by georgesnow** [comment]
Some more info

This is site I used to double check I could make it happen else where 

https://aavtrain.com/

Then I just had this happen just now which was the next time I used the app today

![5823E5D1-5B11-4577-86FB-BAEFE28F04F2](https://user-images.githubusercontent.com/12751441/63979132-28c5f080-ca86-11e9-9f45-81f8bac2ef0d.png)

**Comment by mmcguill** [comment]
Thanks George, how large is your database (File Size, and number of entries if you can)

**Comment by georgesnow** [comment]
![D761A949-CA65-4A17-862C-7E1EF6A657E1](https://user-images.githubusercontent.com/12751441/64572232-884cb780-d334-11e9-94b6-b325710d8146.jpeg)
![A6AC938F-0AD4-444A-8128-8AD2F0103B2F](https://user-images.githubusercontent.com/12751441/64572233-884cb780-d334-11e9-9085-00343e466efc.jpeg)


Here you go.

**Comment by mmcguill** [comment]
Thanks! And what's the physical file size of your database?

**Comment by georgesnow** [comment]
4mb according to Finder

**Comment by mmcguill** [comment]
Hi @georgesnow - I'm hoping that some recent performance enhancements will address this. Could you get the latest version (1.42.0) and let me know if it improves things?

**Comment by georgesnow** [comment]
appears to be fixed. I used the test site that i could replicate it on. issue appears to be gone. thanks!
