### ISSUE TITLE
iPadOS 13, potential bug

### ISSUE THREAD

**Issue by milesmcclane** [strongbox-password-safe/Strongbox#186]
I cannot open any databases on my iPad since the second to last public beta. (Ios13 not 13.1.)

I attached a jpg of the error message, but it says -

 "no valid file provider found with identifier com.apple.icloud.drive.file-provider."

I have tried to reimport the databases, use different databases and even uninstalled and reinstalled the app, to no avail.
The databases are still running fine in the same locarion on my iPhone without a beta os.

Any thoughts?

![IMG_0063](https://user-images.githubusercontent.com/27552949/64079137-2e207680-cce4-11e9-9118-1d943174801e.jpeg)

**Comment by mmcguill** [comment]
Thanks for the heads up @milesmcclane - Still holding out on iOS 13 bugs for another couple of weeks... Can you add via the "Files" method instead?

**Comment by milesmcclane** [comment]
Ok thanks. Figured as much - I know I’m running a beta, but worth letting you know. I think I already tried that method, but can’t be sure so will try again tomorrow and let you know here. Cheers!

**Comment by mmcguill** [comment]
1.42.0 released now which should work well on iOS13. Could you give it a try and let me know if it works ok?

**Comment by milesmcclane** [comment]
Sorry for the delay. All works as expected so far. Thanks!
