### ISSUE TITLE
The preview image function is not smooth

### ISSUE THREAD

**Issue by ghost** [strongbox-password-safe/Strongbox#187]
Hi I'm using Strongbox in the current version (1.40.0) and iPad Air 2 with iOS 12.4.1.

When I open the pictures under attachments function and the window closes again.

You can clearly see how the animation is slow and it stutters in general. In the background you can also see the shadow from window for short moment.

Not as well solved as the windows of Apple apps e.g. App Store

**Comment by mmcguill** [comment]
That's interesting, I haven't noticed any issue here - Is anyone else experiencing slow previews?

**Comment by iOS6martinaa** [comment]
Always click on the button "done". Then you should see immediately. The shadow from window for short moment + the position is wrong.
![85450FE3-5AC5-444F-8E8E-EEF999893FD2](https://user-images.githubusercontent.com/54778167/64087656-40c79980-cd3e-11e9-9b1b-53d0d0a91aeb.png)

**Comment by mmcguill** [comment]
Yes I confirm I see the same issue. Not sure what could be causing this, but it is cosmetic and so will take a low priority right now. Hope you can live with it.

**Comment by strongbox-mark** [comment]
I believe this is just a system issue and there's nothing Strongbox can do here. Closing out.
