### ISSUE TITLE
Option to keep original timestamps on Copy/Paste entries

### ISSUE THREAD

**Issue by ghost** [strongbox-password-safe/Strongbox#188]
Hello I have in Strongbox iOS app an old Keepass (version 1) database and the current Keepass (version 4).

I want to select all entries from the old database and copy them to the current database.

Note!

You also have to copy the original timestamps.

**Comment by mmcguill** [comment]
I'm not sure I can or want to support this for iOS - Have you checked out the Mac app - This functionality is available for Copy/Paste or Drag/Drop... though not including the timestamp options.

**Comment by iOS6martinaa** [comment]
Ok. Can you including the timestamp options for the Mac version?

**Comment by mmcguill** [comment]
For Sure, let's use this issue to track...

**Comment by strongbox-mark** [comment]
#390 should handle this timestamp issue too - will update there...
