### ISSUE TITLE
Not all edit actions in Browse are visible

### ISSUE THREAD

**Issue by ghost** [strongbox-password-safe/Strongbox#189]
See my screenshot 
![94798356-81B1-4DA4-A7EC-61B1CC07DAD8](https://user-images.githubusercontent.com/54778167/64081206-4ac9a800-ccfe-11e9-9b42-4102b89e22a5.png)

you can see clearly if the users on the iPad edit any entries and only want to edit the folders.

Then the UI design in Strongbox is not good. It doesn't use the whole screen at all.

There are a lot of places in Strongbox where the texts are cut off or with 3 dots at the end (...).

My recommendation Strongbox should make a long tab bar.

When the users select an entry or arrange. The different options appear in the tab bar at the bottom.

if too difficult then maybe a context menu appears.

**Comment by iOS6martinaa** [comment]
Same problem in split view and slide over mode.

**Comment by mmcguill** [comment]
Hi @iOS6martinaa - thanks for that. I think a lot of this has come from the German localization work which is still a bit of a work in progress. 

Could you tell me what you mean when you say that Strongbox does "not use the whole screen at all"?

Also, please feel free to report truncations (...) - I'll have them fixed up.

**Comment by iOS6martinaa** [comment]
> Could you tell me what you mean when you say that Strongbox does "not use the whole screen at all"?

e.g the tab bar in Enpass. Ge
![3E8C7E60-5361-46B0-9EE2-CC04DB3561FE](https://user-images.githubusercontent.com/54778167/64087941-6c974f00-cd3f-11e9-81f2-213fa4520e94.png)
neral, the UI is better in Enpass.

**Comment by iOS6martinaa** [comment]
For me. The best UI design for all edit actions is from file explorer app (File Hub). Maybe these pictures will help you improve it.
https://apps.apple.com/app/file-hub-by-imoreapps/id730843281
![47157013-997F-41EC-A32D-695314931A18](https://user-images.githubusercontent.com/54778167/64088068-04953880-cd40-11e9-867b-2d87fdab2571.png)

**Comment by mmcguill** [comment]
Thanks for these samples... I'll try improve on this shortly

**Comment by strongbox-mark** [comment]
I believe this is much better now with the inclusion of Content menus and more compact slide left/right menus...

Please feel free to suggest more specific improvements in new issues.
