### ISSUE TITLE
Very slow in the subsequent processing of notes

### ISSUE THREAD

**Issue by ghost** [strongbox-password-safe/Strongbox#191]
Hi,

I've got a secure note here where over 25,000 characters has been written.

if you want to edit it. then it goes. but incredibly slow.

you can see in the Strongbox iOS app that the iOS keyboard input is very slow.

iPad Air 2 (iOS 12.4.1)
Strongbox iOS (1.40.0)

**Comment by mmcguill** [comment]
Hi @iOS6martinaa - This is probably just a limitation of the built in iOS Control. There's not much I can do here I think to improve performance. 25,000 characters is quite a large note and you may be better off storing as an Attachment, or perhaps archiving some of it.

**Comment by mmcguill** [comment]
I don't think there's any actionable response here, so I'm going to close off
