### ISSUE TITLE
Deleted password safe db listed when entering password and new files not shown

### ISSUE THREAD

**Issue by Ben-Voris** [strongbox-password-safe/Strongbox#192]
When I try to use the deleted file, StrongBox reports an error.  It wouldn’t occurred to me to try the deleted file except that the new file is not listed. 

I  forced closed swan box and the application requesting the password. The problem persists.

**Comment by mmcguill** [comment]
Hi @Ben-Voris I'm not sure I fully understand.

Is this is on iOS?

When you say you try to use the "Deleted File" what do you mean? If it is deleted, where is it deleted to, and where can you see it?

Did you delete the file from somewhere else (cloud perhaps)?

**Comment by Ben-Voris** [comment]
This is on iOS. I had a problem with a safe on a safe on OneDrive Business not syncing, so I deleted it. Login at Safari and in apps continued to show the deleted safe.

**Comment by mmcguill** [comment]
I think you must mean the in the "QuickType Auto Fill" context, i.e. above the keyboard?

If so, this is to be expected. There is just no way for the iPhone, nor Strongbox to know that you've deleted the underlying database file from OneDrive. If you had removed the database from Strongbox this would have cleared the AutoFill database and would not have appeared in Safari or whereever.

**Comment by Ben-Voris** [comment]
Sorry about being unclear. I deleted the save using the left swipe in Strongbox.

**Comment by mmcguill** [comment]
I think there's nothing much can be done for this issue from the Strongbox side, going to close out for now
