### ISSUE TITLE
Editable Tags

### ISSUE THREAD

**Issue by mmcguill** [strongbox-password-safe/Strongbox#193]
A user has requested or suggested the idea of tags. While this is not built in to the Password Safe or KeePass formats, this might be possible as a set of "Preset Searches" and some kind of fast or convenient way to execute them. Consider this an RFC of sorts.

**Comment by mmcguill** [comment]
Turns out this is built into KeePass2 so it should be possible to support this more easily for at least this format

**Comment by strongbox-mark** [comment]
Available now with MacOS release 1.15.8
