### ISSUE TITLE
Password Generator for Custom Fields

### ISSUE THREAD

**Issue by TechGuy2000** [strongbox-password-safe/Strongbox#197]
Please add the password generator option for custom fields. I often have entries with Password2 and Password3 and it would be helpful to be able to automatically generate passwords for them. (Likewise, I also often use diceware passwords for answers to security questions, and it would be nice to be able to generate those for Security Answer #1, etc. custom fields.)

Thanks!

**Comment by mmcguill** [comment]
Interesting! Never thought of that - good idea

**Comment by Ben-Voris** [comment]
I’d like to see this too. Since I use password safe, I keep all the questions and answers in the notes field. So I’d like to be able to generate a password to append to whatever is in the notes field

**Comment by mmcguill** [comment]
Hi @Ben-Voris, so you'd like to see a generate password button somewhere near the notes field which would append to the Notes field? Sounds reasonable.

**Comment by Ben-Voris** [comment]
I have no experience with UI design, so I'll leave that part of your question to you and others. 

What I do now when creating a new entry in one of my Password Safe files:
1. Set the password generation policy to whatever the site or app requires.
1. Generate a password.
1. Paste the generated password into the site.
1. Save the entry (I really don't want to lose the password).
1. When the site requires "security questions", I then:
    1. Edit the saved entry.
    1. If the password generation policy is not already Diceware, set it to Diceware.
    1. Copy and paste the saved password into the notes field (using them as a scratchpad).
    1. For each required question:
        1. Pick a question from the site and type the question into the notes field.
        1. Generate a Diceware password.
        1. Cut that password and paste it into both the site and the notes.
1. When done with the "security questions":
    1. Change the password generation policy back to what the site requires.
    1. Cut the original password from the notes field and paste it into the password field.
    1. Save the entry.

At the end, I have an entry that has the original password in the password field and a notes field with lines like:
- Q: What is your name?
- A: Word1Word2Word3
- Q: What is your quest?
- A: Word3Word4Word5
- Q: What is the airspeed velocity of an unladen swallow?
- A: Word6Word7Word8

So, what I'd like is to be able to generate a password and paste it directly into into the notes, at the current insertion point. That is, position after a question and paste the (generated) answer there. For me, a password pasted into the notes could always be Diceware.

**Comment by mmcguill** [comment]
Understood, thanks for the input @Ben-Voris

**Comment by milesmcclane** [comment]
Along a similar vain- perhaps coupled with a username generator, which can actually generate real sounding names to use for fake emails or other things that may require a real sounding name. not sure if there is a standardised diceware style dictionary which you could use to implement this?

**Comment by mmcguill** [comment]
Thanks @milesmcclane  - Do you have a couple of examples or more detail on what you had in mind?

**Comment by milesmcclane** [comment]
I was thinking of having a generator icon somewhere, perhaps standalone or perhaps in the user name field (which would be optional to use of course). Pressing it could give you various options to generate names, first name, last name, maybe middle name - perhaps girl/boy). 
The names generated could be any sensical word I suppose, like diceware, but better would be taken from some sort of list of real names. 
There maybe websites that do this (https://www.name-generator.org.uk/username/ - for example), but the reason I got the idea was apples game centre automatically does this upon creating a profile. 

It’s useful because I often (normally actually) don’t want to give my real name, or use the same pseudonym each time. 

I think it would be very cool- but maybe not a feature that is possible or that everyone would use? What do you think?

**Comment by mmcguill** [comment]
That makes sense @milesmcclane - Thanks - Could be a fun feature to implement alongside the Password generator UI improvements

**Comment by mlfreeman2** [comment]
Simpler idea: can you make it possible to open the password generation UI without even unlocking a file?

**Comment by mmcguill** [comment]
You can do this via Preferences > Password Generation from the main screen

**Comment by milesmcclane** [comment]
How feasible would it be to make a password/username generation widget with all the password generation rules and options right there on the widget or sharesheet section (iOS)? 
Enabling extremely quick access to these tools would be quite useful. Upon generation the widget could give options such as copy password to clipboard, copy password and username to new entry in strongbox, etc?

**Comment by mmcguill** [comment]
I’ve never built one before but I’m sure it’d be quite doable... however at the moment I’d prefer to concentrate on the core app.

**Comment by milesmcclane** [comment]
No problem at all! A thought for the future perhaps.

**Comment by TechGuy2000** [comment]
> How feasible would it be to make a password/username generation widget with all the password generation rules and options right there on the widget or sharesheet section (iOS)?
> Enabling extremely quick access to these tools would be quite useful. Upon generation the widget could give options such as copy password to clipboard, copy password and username to new entry in strongbox, etc?

A widget is an interesting idea. I wouldn't use it, personally, but I can see how it would appeal to some folks. However, it would be important to make sure that any capability to copy the password and username directly to a new entry in Strongbox (as opposed to copying to the clipboard) didn't somehow create a security hole in the way the databases are locked/unlocked.

**Comment by milesmcclane** [comment]
@mmcguill I see the username generator! Good call- very useful thanks! You’re building a perfect app!!

**Comment by mmcguill** [comment]
Thanks @milesmcclane - I'm going to close this one out now. If there are more specific requests, lets open new issues :)
