### ISSUE TITLE
Automatic Backups

### ISSUE THREAD

**Issue by TechGuy2000** [strongbox-password-safe/Strongbox#198]
Please add a feature to create automatic backups each time the database is saved (with the option to retain the backups for variable amounts of time, including forever, and then delete older backups). Thanks!

**Comment by mmcguill** [comment]
Sounds Good!

**Comment by TechGuy2000** [comment]
It might also be good to have an option to cap backups at a certain storage size (i.e., ____ MB) to prevent the space the app uses from growing too large without the user noticing. So (1) keep backups for X period of time (including forever--no automatic deletion of backups) and then automatically delete backups older than the cutoff, and (2) if a time period other than forever is set, if a new backup would exceed the cap set for backup storage space, then delete the oldest backup(s) as needed to make the backups including the new backup be under the storage cap, but (3) always keep at least one backup if the automatic backups are enabled.

**Comment by mmcguill** [comment]
Can you simplify this? Seems a little complicated... I think the size restriction makes things unnecessarily complex. I think this can probably be managed manually. If the total size is indicated on the backups screen and the user can manually delete

**Comment by TechGuy2000** [comment]
Fair enough. Maybe just display an alert to the user if the backup is over some size? 

Option: Enable Automatic Backups (to be created each time the database is saved) [ON / OFF]
- Keep backups for [Forever, 1 year, 9 months, 6 months, 3 months, 1 month, 14 days, 7 days]
Old backups will be deleted automatically when you open the app and unlock the database.
- Warn if backups exceed [numerical input] MB

**Comment by georgesnow** [comment]
if the concept is just to make backups. it might be simpler to have. 

Backup Location: (Folder)
Number of backups to keep: #
How often to back up (contingent upon app launch and database unlocking): (Daily, Weekly, Monthly)

I use an applescript that basically does this. Quicken for Mac does this also (on closing the app the back up occurs). My script just appends the name with Date-Time of when the back up was taken. I store the database for use on iCloud, but i back it up to another location incase I can't get access to iCloud. Currently,  I have to mainly trigger my backups (unless I want to create a cron job or something to schedule it)

An integrated solution could be a value add.

**Comment by TechGuy2000** [comment]
That makes sense for Mac. My suggestion was for iOS. ... Also, for maximum security, the backups should (at least by default) only be accessible from within the Strongbox app and not accessible in Files / iTunes.

**Comment by georgesnow** [comment]
I was thinking conceptually if you do it for iOS. You could select another provider that is available within the Files app on iOS (ie local as you suggested or OneDrive, Google Drive, NAS whatever).

Since within Strongbox you can access the Files API. It creates a layer of abstraction. Strongbox doesn't/shouldn't care where it is saving the backup just that _it can_ save to location.

**Comment by georgesnow** [comment]
oh you are saying "only within" the strongbox app? hmm..ok, thats a different approach

**Comment by Ben-Voris** [comment]
This is related to https://github.com/strongbox-password-safe/Strongbox/issues/12.  For me, I want the back ups to be somewhere else. If the safe is local I want its backup on the cloud. If it’s on the cloud, I want to the backup either on my device or another cloud provider.

**Comment by TechGuy2000** [comment]
I understand what you're saying, and that makes sense if the database on iOS is stored in Files or elsewhere. But for greater security, I keep my database local within the Strongbox iOS app only and use the Application Lock feature to restrict access to the app.

I see how it is related to #12. 

Maybe the ideal would be to implement the internal automatic backups (keeping backups within the iOS app), and then have an option to copy or move the backups somewhere else after they are created.

**Comment by mmcguill** [comment]
Thanks for all the comments/suggestions. 

I think it's important to distinguish between internal regular Strongbox backups, and Scheduled External Backups/Exports... Both are important and related. 

I think the approach I'd like to go with is:

- Internal Backups
    - Made on each save/write
    - Configurable number to keep (rolling) - Default: 10
    - Manually Deletable
    - File size and date of backup indicated in UI
    - Exportable (any export method, mail, files, etc...)
    - Not visible in Files/iTunes (private to App)
    - Accessible without unlocking the DB (in case of DB corruption some how)

- Export Backups (Scheduled)
    - Similar to current Export options (+ #12 )
    - Configurable Schedule (Asks user to export if last export was 1 week ago or whatever

**Comment by TechGuy2000** [comment]
@mmcguill That division of features makes sense. Good point about unlocking and DB corruption. I assume, however, that the internal backups would still only be accessible after unlocking the app if the Application Lock setting is enabled?

**Comment by mmcguill** [comment]
@TechGuy2000 - yeah for sure, the App Lock would protect against this.

**Comment by mmcguill** [comment]
This is ready to go now in 1.43.1 - Slide Left -> Backups... Feel free to open any issues if you find any problems.
