### ISSUE TITLE
Auto-Type in split screen mode (iOS on iPad)

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#199]
When working in split screen mode on the iPad with let's say Chrome and Strongbox (and Strongbox unlocked) I still need to use TouchID for Auto-Type in the Chrome app window even though Strongbox is already unlocked and visible on screen.

Is there a way to detect an unlocked Strongbox app in split screen mode to prevent the app from asking for TouchID again when performing Auto-Type? After all i could also just copy and paste the username/password from the app manually without having to use TouchID.

Split Screen on iPad: https://support.apple.com/en-us/HT207582

**Comment by mmcguill** [comment]
There's no way to detect this @dan-el - The app's are very tightly sandboxed. 

I'm considering trying to allow auto-unlock in Auto-Filll if convenience is setup and it's been < x minutes since last unlocked.

**Comment by dan-el** [comment]
Can you detect the app window width or something similar? Afaik the apps can have 25%, 50%, or 75% of the screen width. Or be a kind of „hover above column“ in combination with apps that do not support split screen properly.

Giving the original idea a second thought I am not so sure anymore it’s really important though to be honest. It’s the inconsistency which annoys me a bit - after all Strongbox is unlocked in split screen...

**Comment by mmcguill** [comment]
Yes, probably could try and detect this heuristically using screen size, but it'd be hacky... not an avenue I want to go down

**Comment by dan-el** [comment]
I agree. Better stay on the right track.

I'd close this issue then unless you want to keep it as a reference for the convenience unlocking change.

**Comment by mmcguill** [comment]
Thanks, yes please close I think we'll use #150 for that - it's an older one but I'm reconsidering how handy/useful it is to have auto-fill remain unlocked for a little while

**Comment by dan-el** [comment]
Looks good. Thank you!
