### ISSUE TITLE
Max. History entries and size changed when editing database 

### ISSUE THREAD

**Issue by limuc** [strongbox-password-safe/Strongbox#202]
Everytime i perform an edit, the max. number of history entries is changed to 10 and the size to 6 MB. (It deleted history entries, so that only 10 per entry remain)

It should stay at 10.000 and 100 MB.

**Comment by mmcguill** [comment]
Hi @limuc - Sorry about this, I see the issue, a simple oversight when working on the recent performance improvements, but obviously with a nasty impact for you. I have a fix on the way, but unfortunately it will take a couple of days to get through Apple's review and release (big delays at the moment)

**Comment by mmcguill** [comment]
Ok great, thanks for understanding

**Comment by mmcguill** [comment]
This should be fixed for you with 1.42.2, let me know

**Comment by limuc** [comment]
It's fixed, thank you!

**Comment by mmcguill** [comment]
Cheers!
