### ISSUE TITLE
Removing historical versions of an entry

### ISSUE THREAD

**Issue by xatage** [strongbox-password-safe/Strongbox#203]
When deleting a historical version for an entry it’s not removed from the list. You have to exit history first and open it again to see which versions were deleted. 

Btw. maybe you could also add a button to delete all history versions at once?

**Comment by mmcguill** [comment]
I'm planning on integrating history into the main "Details" view - So I think I will fix this then

**Comment by xatage** [comment]
Thanks!

**Comment by strongbox-mark** [comment]
I believe this is no longer an issue - Can you confirm and close?
