### ISSUE TITLE
Quick Launch with Long Press (previously 3D Touch) from Homescreen

### ISSUE THREAD

**Issue by Slummi** [strongbox-password-safe/Strongbox#204]
Hi,

what do you think about Quick Launch support from Homescreen via 3D Touch / press and hold the app icon to open a specific database?

Usually I use the same database and have Quick launch enabled for this one. But sometimes I need to open another database and than I have to wait until Quick launch has opened the database, than I close it and open the desired one.

This feature could „overwrite“ the default Quick Launch settings and directly open the desired database by selecting from a list on the app icon (after 3D Touch / Press and Hold). I think this feature would also be handy for people who often use different databases and won‘t enable Quick launch for a specific one.

Just an idea and not so important like other features.

**Comment by mmcguill** [comment]
Sounds interesting... curious to hear others thoughts...

**Comment by georgesnow** [comment]
I like it. I will miss 3D Touch since theyare phasing it out, but at least they are keeping the long press actions. Which I think are great. Also not sure if would be helpful to have the option to Create  New Entry in the default database.

**Comment by xatage** [comment]
I like the idea of opening different databases via 3D Touch shortcut, too.

**Comment by strongbox-mark** [comment]
This is now available with 1.55.8, long tap on App Icon and choose which database to "Quick Launch". Feel free to re-open if this isn't what was expected.

**Comment by Slummi** [comment]
Thanks for implementing! Works as expected.

Still a small suggestion for improvement:
As far as I know, the number of displayable options for Long Press gestures is limited (4 or 5 entries). So maybe it makes sense to display the databases in the order of the database list, so that the user can decide which DBs to display in the Long Press menu if you have more than 4 DBs. Currently the sorting is alphanumeric (descending).

**Comment by strongbox-mark** [comment]
Hi @Slummi - thanks!

For your suggestion, I don't think the sorting is alphanumeric, it should be in the same order as your databases. Are you not seeing that?

Note that if the menu opens "upwards" instead of "downwards" from the App Icon, the menu options appear in reverse order.

**Comment by Slummi** [comment]
Hi @strongbox-mark,

You are right. The order in the app icon menu is from bottom to top. The alphanumeric sorting was just a coincidence due to poorly chosen test data.
