### ISSUE TITLE
Strongbox Crashes on Database Open

### ISSUE THREAD

**Issue by shad0whawk** [strongbox-password-safe/Strongbox#206]
I just updated to version 1.43.0 on iOS 13.1.1.  I can’t open any existing databases without the Strongbox application crashing when I select the database to open from my list. I’ve tried multiple times with the same result. The workaround for me was to delete the existing databases and add them again. They’re a mix of OneDrive and local. Everything works fine after taking those steps. Just wanted to share my experience and see if anyone else is having the same issue.

**Comment by Slummi** [comment]
Up to now I haven’t had any issue with 1.43.0 and iOS 13.1.1. All databases can be opened without the steps you have described.

**Comment by shad0whawk** [comment]
Hmm does the exact same thing on my iPhone 8 with 13.1. The database prompts for Touch ID and then crashes as soon as I authenticate. Did the same thing on my other phone at the same point in the process with Face ID. Haven’t deleted and recreated the databases yet so it’s still doing it.

**Comment by mmcguill** [comment]
Hi @shad0whawk - Thanks for the report, I've had a couple more since. Can I ask if you are using a key file for these databases?

**Comment by Slummi** [comment]
Ok, I can reproduce this now. Tested another database with a key file and Strongbox crashes directly after opening the database via Face ID / Touch ID.

**Comment by mmcguill** [comment]
Thanks @Slummi - can you do this with a brand new database created with Strongbox or is it an older one?

**Comment by Slummi** [comment]
It‘s an old database. I tested to create a new one in Strongbox using the same key file and everything is working well.

**Comment by mmcguill** [comment]
Interesting, that's not what I was expecting but ok. Do you happen to have a crash log you could send me?

**Comment by Slummi** [comment]
I've just sent you an email with the crash log.

**Comment by cristamd** [comment]
I’m seeing the same issue using a database created by KeePassXC and synced through OneDrive. I’ll try to find the crash log.

**Comment by mmcguill** [comment]
Fix on the way, unfortunately it's been stuck in Apple review for 2 days now, not much I can do

**Comment by Slummi** [comment]
Now I’m getting an error message (with the old database) that the key file hasn’t been found in 1.43.1 instead of the app crash. But the file is there. Or do I have to import it from the local files folder?

**Comment by mmcguill** [comment]
For AutoFill you would need to import but for regular app use, no need

**Comment by Slummi** [comment]
Ok, but AutoFill isn‘t enabled for that database and I always get the error message when I try to open the database.

**Comment by cristamd** [comment]
I had to delete the database and keys from strongbox, clear the OneDrive session (in the strongbox settings), then set everything up again to get it working.

**Comment by mmcguill** [comment]
@Slummi - If you choose "Unlock Manually" (you may need to fail Touch ID one time to get this option to appear) and then choose your Key File again, in the dialog, does that work?

@cristamd Sorry you had to do all that. There was a change recently in how Key Files interact with Biometric ID which caused this but it's exacerbated by not completely clearing the Convenience Unlock settings

**Comment by Slummi** [comment]
@mmcguill - Yes, that works. And after that Face ID also works. Thanks!

**Comment by mmcguill** [comment]
Thanks @Slummi - I just need to change things so that a credential fail using Convenience Unlock clears Convenience Unlock rather than just displaying a message. I'll get that in in the next release.

**Comment by shad0whawk** [comment]
> Hi @shad0whawk - Thanks for the report, I've had a couple more since. Can I ask if you are using a key file for these databases?

Sorry been out of touch a bit and didn’t see your question. Yes I use a key file on these databases.

**Comment by mmcguill** [comment]
With 1.43.2 - this should be cleared up, if it can't find your Key file you will be asked to re-select it through the Manual Unlock dialog. After this everything should work again as expected.

**Comment by mmcguill** [comment]
Believe this is fixed now with 1.43.2+
