### ISSUE TITLE
Safari Extension for Autofill

### ISSUE THREAD

**Issue by georgesnow** [strongbox-password-safe/Strongbox#21]
Any thought about adding the option for a Safari Extension on the macOS client?

**Comment by mmcguill** [comment]
Not until now! :)

It's certainly something to add to the list. I've not done much in the line of browser integration before, so would take some research

**Comment by georgesnow** [comment]
found this:

https://developer.apple.com/documentation/safariservices/safari_app_extensions?language=objc

since this a place holder and this is some of the documentation on how to build the extension

**Comment by georgesnow** [comment]
i updated the applescripts for autofilling Safari. i noticed you moved some menu items for copying username and password.

these are just a workaround for anyone (like myself) who just happens to prefer Safari, but wants autofill
https://github.com/georgesnow/Strongbox-Applescripts

**Comment by mmcguill** [comment]
Thanks @georgesnow

**Comment by strongbox-mark** [comment]
HI @georgesnow - this is available for test now on. It only works on Big Sur (if you have that installed?) - be good to hear your feedback.

**Comment by georgesnow** [comment]
sure thing, I have to plans to install Big Sur on separate volume on my test Mac hopefully this week. does this make use of the  password manager capabilities so it can present passwords beyond safari (similar to iOS) or only in safari?

**Comment by strongbox-mark** [comment]
Cool. Yes, it does, but I have been unable to find another 3rd party app that integrates with the AutoFIll system on Big Sur... yet... 

So I've only been able to test in Safari. Be super interested to hear if you can use it in another app.

**Comment by gavia** [comment]
Hey @strongbox-mark Is this restricted just to username/password, or can it support OTP fields too?

**Comment by strongbox-mark** [comment]
HI @gavia - It will copy the TOTP if there is one if you select an entry with a TOTP field. So you just need to paste. But in general the AutoFill system is designed for a username/password pair keyed by a URL.

**Comment by brwolfgang** [comment]
Hi there, how one can test it? Is downloading the latest version from Mac AppStore enough?

**Comment by strongbox-mark** [comment]
That should do it @brwolfgang - Have you seen the blog post here:

https://strongboxsafe.com/updates/macos-big-sur-autofill/

Going to close this issue out now too.
