### ISSUE TITLE
Dutch/Nederlands translation

### ISSUE THREAD

**Issue by antelle** [strongbox-password-safe/Strongbox#210]
Hey!

Author of [KeeWeb](https://github.com/keeweb/keeweb) here ☺️

Thanks a lot for this app, enjoying it so far, purchased the one-time thing to support you. Also added a section about you on my iOS apps page: https://github.com/keeweb/keeweb/wiki/iOS#strongbox.

I'd be super happy if you add a Dutch (Nederlands) translation for iOS.

Keep up the good work, the project looks awesome!

**Comment by mmcguill** [comment]
Hi @antelle - 

Wow, kudos on KeeWeb I've only played with it a little bit but it looks great and I get many people emailing saying they like the it! Hats off! 

For sure, would love it if you could help out with the Dutch translation, can you shoot me an email and I'll get you an invite link straight away.

Best,
-Mark

**Comment by antelle** [comment]
I won’t be able to help with the translation itself, what do you think about opening a public translation center, so that everyone can contribute? The license doesn’t have to be the same as the project license, so you can do whatever you want with translations.
This way KeeWeb was translated to more than 10 languages absolutely for free, and the list is growing: https://keeweb.oneskyapp.com/

**Comment by mmcguill** [comment]
Ah I'm sorry I misread your message.

Yes, we have that just about setup now! We just need volunteers to translate :)

**Comment by antelle** [comment]
Awesome! Perhaps it makes sense to add a link to the app and the project readme? This can help finding volunteers.

**Comment by mmcguill** [comment]
For sure, it's on the way! Along with a link to KeeWeb :)
