### ISSUE TITLE
Remember key files option

### ISSUE THREAD

**Issue by BloodBladeW** [strongbox-password-safe/Strongbox#211]
I use a Mac without Touch ID, so I have choose key files every time. It would be helpful if add remember key files option.
Grateful

**Comment by mmcguill** [comment]
Makes sense. Added to the backlog. Thanks!

**Comment by shad0whawk** [comment]
Yeah I agree this would be nice to have implemented to avoid having to go find it every time.

**Comment by mmcguill** [comment]
This is now available on Mac! Closing out, feel free to open an issue if you find any bugs.
