### ISSUE TITLE
Webdav Timeout Too Short - Can Never Open Online Database

### ISSUE THREAD

**Issue by alexj-m** [strongbox-password-safe/Strongbox#214]
Hi there,

Thanks for the great product - I really like it.

I'm currently having an issue opening my Keepass Databases that are hosted on a Webdav server (Nextcloud). Strongbox times out before the file has been opened from the remote server and I have to open the Offline copy.

Admittedly my server isn’t the fastest going around, but Strongbox used to work fine until an update a few months ago and now it doesn't work at all. I don’t think my server has changed at all, as all my other applications work fine.

I know it is probably a pain, but would it be possible to get the Webdav timeout increased on Strongbox (maybe doubled) or an option to disable it or set the timeout manually? This would help me a lot as I currently can not use Strongbox as I can never open my Online databases.

I should mention that I am running iOS 13.1.2 and the latest Strongbox Pro.

Thanks Alex.

**Comment by mmcguill** [comment]
Hi, cheers! 

The timeout is currently 5 seconds, but I'll bump it to 15 which should hopefully fix things for you in the next release.

Cheers,
-Mark

**Comment by jumpinjackjones** [comment]
Yes please that would be great - I think I'm having the same problem.

**Comment by mmcguill** [comment]
This is available now in 1.44.0 - Let me know if it's working ok for you... will close off in a while if I hear nothing

**Comment by jumpinjackjones** [comment]
Works for me, thanks so much!

I love Strongbox by the way!

**Comment by mmcguill** [comment]
Great news! Thanks @jumpinjackjones

**Comment by alexj-m** [comment]
Sorry I'm late back to the party, but I wanted to say thanks for implementing this - it has solved my problem too.
