### ISSUE TITLE
Associate iOS app with certain username and password

### ISSUE THREAD

**Issue by alcroito** [strongbox-password-safe/Strongbox#215]
Hi,

Some iOS apps that show a username and password form, don't get the Autofill quick type icon, so you have to manually search through the database to find the user name and password.

Presumably this is because the App might not have an associated domain set?

I was wondering if the autofill api would somehow allow remembering what was the last choice for that app, and that on next log in Strongbox can automatically auto-fill it without having to search for the entry again.

**Comment by mmcguill** [comment]
I’m afraid there’s just no way to do this at the moment with the Autofill API
