### ISSUE TITLE
Create a new database in files app / move database to different storages

### ISSUE THREAD

**Issue by Slummi** [strongbox-password-safe/Strongbox#216]
Hi @mmcguill - I‘m wondering why it isn't possible to create a new database in the files app, but you can open an existing one from files. The files app is missing in the list of selectable storages when creating a new database. Could you implement this?

Would it also be possible to implement a function to move existing databases between different storages? At the moment this is only possible by exporting an existing database to the new location and then deleting the source. Would this also be possible directly from the database overview?

**Comment by mmcguill** [comment]
Yes I think both are possible! Let’s track here

**Comment by strongbox-mark** [comment]
Ability to Create a New Database in files is now available.

On the second issue, I don't think there's a huge desire to be able to move the database directly - This can be done by Export now directly from the Databases screen...
