### ISSUE TITLE
Inconsistent Preferences Icon

### ISSUE THREAD

**Issue by juanbretti** [strongbox-password-safe/Strongbox#218]
The icon for the "preferences" is different at the database listing and when the database is open.
Can you unify the icons?
See screencaptures:

**Database listing:**
![db list IMG_0109](https://user-images.githubusercontent.com/10165911/66985267-b7391480-f0bc-11e9-8356-70ecfa06e9f0.PNG)

**Database open:**
![db IMG_0110](https://user-images.githubusercontent.com/10165911/66985265-b43e2400-f0bc-11e9-9c02-231f6cf22868.PNG)

```
Strongbox version 1.43.3
iOS 13.1.3
```

**Comment by mmcguill** [comment]
Yes perhaps you’re right here... the idea behind this was to indicate that rather than just preferences this involved other operations? which is why it’s called Database Management rather than Preferences

**Comment by juanbretti** [comment]
@mmcguill , I understand your point.
But one is in the upper bar and the other in the lower bar. They are in different sections/screens of the application.
Same happens with the "View Sorted By" and "View Preferences": those affects different list, the .kdbx and the logins. Those two icons are not doing the same thing, but do have the same icon.

As before, just a suggestion.

**Comment by mmcguill** [comment]
Sure, I'll think about this one

**Comment by F3000** [comment]
@mmcguill  maybe you can find a good solution with SF Symbols . You can choose between 1500 different icons :)

Im sure there is an icon for that. 

Reference : https://github.com/strongbox-password-safe/Strongbox/issues/283

**Comment by mmcguill** [comment]
This should be fixed/cleaned up for you now in 1.47.3 @juanbretti - Can you confirm and close

**Comment by juanbretti** [comment]
Thank you! Look perfect!
