### ISSUE TITLE
Manual resync / pull down to refresh

### ISSUE THREAD

**Issue by Firestart3r** [strongbox-password-safe/Strongbox#221]
I'm using a Database in OneDrive, but I'm sorely missing the possibility to manually refresh the database, so that when i change something in my iPad or one of my PC's i can refresh the db.

The feature is useful if you don't want to close the database on your phone and reopen it, so that a new entry you created on anther device appears on your phone.
For example: you configure your new wifi router with your pc and store the wifi data in keepass. Keepass syncs with onedrive. Now on your phone you do not need to close the database and open it back up again. You just pull down to refresh, and can connect your phone to your new WiFi without a problem.
Or another example: you just changed a password on your phone, but you need it on your pc as well. Just pull down to refresh (so that all changes are commited to and from the database). The changes will be available to all other devices.

**Comment by mmcguill** [comment]
Ok interesting feature, thanks for the idea!

**Comment by arazer91** [comment]
periodic check for changed timestamp/file-change on the remote while the DB is opened and the app is active additionally would be nice as well for this case..

**Comment by strongbox-mark** [comment]
This is available now with the latest iOS release.

**Comment by adamdehaven** [comment]
@strongbox-mark one feature request that would be great, similar to this implementation: could a setting be added that would essentially “auto-refresh” the database (e.g. so a user doesn’t have to remember to manually pull down and refresh) whenever the app is launched/relaunched/unlocked? I am looking into using Sync.com and after some initial testing, pulling down to refresh (in app on device A) after I make a change on another device (device B) seems to be a valid workaround to trigger the Files app to update the file (prob needs more testing).

(I’m on my phone or else I’d have opened an actual issue/feature request)

**Comment by strongbox-mark** [comment]
This appears to work well. Closing out.
