### ISSUE TITLE
Integrate with "Have I been pwned"

### ISSUE THREAD

**Issue by arazer91** [strongbox-password-safe/Strongbox#223]
Data breaches happen and most people are unaware or do not check automatically/recurring .. 

two pairs of shoes here:
* Cross-checking of email-addresses for previous data breaches
* Check passwords for occurrence in data breaches (this is anonymous, only the first 5 characters of the hash are send, HIBP server responds with all matches, then compare locally .. ) (https://haveibeenpwned.com/API/v3#PwnedPasswords)

**Comment by mmcguill** [comment]
Yes really like this idea

**Comment by strongbox-mark** [comment]
This has been subsumed under general Auditing and is available for a while now on iOS.
