### ISSUE TITLE
Large notes text renders the app unresponsive

### ISSUE THREAD

**Issue by wilhelmtell** [strongbox-password-safe/Strongbox#224]
Some StrongBox operations are unresponsive when an entry's notes field has a lot of text. Things I noticed rendering the app unresponsive:

* Collapsing the entry's notes field.
* Expanding the entry's notes field.
* Tapping the entry to view its detail, regardless of whether the notes are collapsed or expanded.
* Tapping the back button to leave the entry details view, then tapping the entry to get back in to its detail view.

Also, viewing or adding attachments becomes “laborious” when the notes are expanded, as I have to scroll through the entire text to get to the bottom of the screen where the attachments are.

To reproduce this, try pasting the text content of this file,

 https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt

into an entry's notes field. That file contains 7776 short lines of ASCII text. Then try the operations I mentioned above.

Observed with
* StrongBox 1.44.2
* iOS 12.4.2
* iPhone 6

**Comment by mmcguill** [comment]
Hi @wilhelmtell - could you use a file attachment here instead? Would probably perform better

**Comment by mmcguill** [comment]
I'm not sure there's much can be done here, for something like this you probably should use a file attachment... closing out for now
