### ISSUE TITLE
Support KeePass Tags

### ISSUE THREAD

**Issue by shad0whawk** [strongbox-password-safe/Strongbox#228]
I use the tags functionality in KeePass 2.  It would be useful if I could edit those tags and/or search and filter using the tags in Strongbox. Just a thought...

**Comment by mmcguill** [comment]
Yes! Agreed, added to the list

**Comment by mmcguill** [comment]
Connected to #193

**Comment by F3000** [comment]
You can combine it when you begin work for the watch app in future : 

All entrys with a tag called „Apple Watch“ are displayed on the watch 👍

**Comment by shad0whawk** [comment]
I see you added I’m this to the latest release. I tried it out and works great. Thanks for adding it!

**Comment by mmcguill** [comment]
Great to hear it's working ok! :)

**Comment by F3000** [comment]
@mmcguill where I can find the “Tag” option ?

**Comment by Slummi** [comment]
@F3000 In details view you have a tag field and in editing mode you can add/delete tags.

@mmcguill I determined that you have to press return to create a new tag even if you want to create only one. Is that intended? Typing and then switch to another field or press done (without a return) doesn’t work.

**Comment by mmcguill** [comment]
Interesting Slummi - I didn't realise that. Not sure if it's an easy fix but could you create an issue to track?

**Comment by Slummi** [comment]
Sure. Will do it tomorrow.

**Comment by F3000** [comment]
What do you think of the idea to colorize Tags ?

**Comment by Slummi** [comment]
@F3000 Why should you do that?

**Comment by mmcguill** [comment]
Colorized Tags isn't support by the underlying KeePass format so I don't think this is a runner. I can see the attraction, just don't think it brings a lot of value right now.

**Comment by F3000** [comment]
Ok when it’s not supported than forgot it ;)

**Comment by F3000** [comment]
@mmcguill  what do you think of pre defined standard tags from you ? 

e.g. finance . The user only have to click on that tag to activate it (when clicked the text get colored etc..) 

When a user didn’t find any tag that’s useful for him he can add his own like now .

**Comment by strongbox-mark** [comment]
Hi, I don’t think this is something I’m want to do. Why not just create them yourself?
