### ISSUE TITLE
Show File Size in Database Management -> Properties

### ISSUE THREAD

**Issue by acheronfail** [strongbox-password-safe/Strongbox#232]
It’s already pretty awesome that we can customise the list of vaults to show file name, storage or the last cached date. 

This ticket is a feature request to add the vault’s file size as an option too. 

Thanks for the great app!

**Comment by mmcguill** [comment]
Sounds good - again, as with Last Modified, needs to be async, refreshable and work across various providers...

**Comment by mmcguill** [comment]
Sounds good - again, as with Last Modified, needs to be async, refreshable and work across various providers...

**Comment by strongbox-mark** [comment]
This and Date Modified are now available as Subtitles on the Databases screen.
