### ISSUE TITLE
Password on Windows reports "duplicate UUID field" after adding entry from Strongbox

### ISSUE THREAD

**Issue by Ben-Voris** [strongbox-password-safe/Strongbox#234]
Password safe V3.48 (g3645d1eb+) 64-bit reports 

```
Report of Validate function started at 2019...
on database C:\....psafe3

Start Report


The following ERRORS were detected and were FIXED.

The following entries had a duplicate UUID field.  This has been corrected.
	Group='admin', Title='xxx', User='admin' 

End Report
--------------------------------------------------------------------------------
```

I've not seen this before, but this is the first time I've used Strongbox to add an entry where the user name matches the group name. This group contains another entry with the same user name.

Based on quick skim of https://github.com/pwsafe/pwsafe.git, I believe that this error is detected in 
```
 void TestAndFixDupUUID(CItemData &ci_temp, const PWScore &core,
                              std::vector<st_GroupTitleUser> &vGTU_DUPLICATE_UUID,
                              st_ValidateResults &st_vr)
```

This method is called for each entry.

**Comment by mmcguill** [comment]
That's weird @Ben-Voris - Can you list the steps you took to reproduce this? Maybe from a blank or new DB if possible. Will help me investigate. Ta!

**Comment by mmcguill** [comment]
@Ben-Voris bump

**Comment by Ben-Voris** [comment]
I have not been able to create this with a blank safe. For future reference, what I tried was:
1. create a local db with Strongbox 1.45.0 on iOS 13.2.3
2. create a group titled `admin`
3. create a entry in `admin` titled `1` with a user name of `admin`
4. copy `1` (which creates `1 Copy`)
5. copy the local safe to a cloud provider
6. open the safe with Password Safe V3.49.01 (g0f38b76cf+) 64-bit

No errors. 

(I'm sorry my response is so delayed, but I lost a number of password changes due some Strongbox sync error, and I've just recovered access to my Github account.)

**Comment by mmcguill** [comment]
Ok thanks @Ben-Voris - Do you use any other Password Safe clients? 

Can you still reproduce this with your existing db?

Sorry to hear about the sync errors, is there an issue with Strongbox do you think?

**Comment by Ben-Voris** [comment]
I only use Strongbox and the Windows version from https://pwsafe.org/. (Running under Wine on Linux.)

I do not have the original file. As I understand the Windows version, it repairs this by assigning a new uuid. And, that seems to have happened.

As for the sync errors, I don't know. I usually make changes in Strongbox because I like its password generator. I sync the changes to my Linux and Windows PC but this is almost always a read.

At least sometimes, what seems to be happening is that occasionally, one iOS device doesn't push changes. I wonder if what's happening is something like:

1. change password on device A
2. sync fails without visible error
3. change another password on device B
4. sync on B is successful
5. change from A is lost

**Comment by mmcguill** [comment]
OK @Ben-Voris - There's nothing actionable here really... if you manage to find any more information, or how to reproduce this, let's re-open at look at it then. Closing out for now.

**Comment by Ben-Voris** [comment]
I discovered that do have the file that reports duplicate uuid. Obviously, I can't share the file, but is there any information I can gather from it?

**Comment by mmcguill** [comment]
I'm afraid not, I really need to be able to reproduce the issues, ideally a list of steps I can perform - then I can fix
