### ISSUE TITLE
Fandom-Inspired Wordlists

### ISSUE THREAD

**Issue by jgallias** [strongbox-password-safe/Strongbox#236]
Could you add the Fandom-Inspired Wordlists from EFF?

Source:
https://www.eff.org/deeplinks/2018/08/dragon-con-diceware

**Comment by mmcguill** [comment]
Yes for sure! I'll try get them in the next release... stay tuned 😁

**Comment by mmcguill** [comment]
These are available now with 1.45.0 but I'll keep open until Mac version is done...

**Comment by mmcguill** [comment]
Mac done! Hope you like!
