### ISSUE TITLE
Database considered invalid

### ISSUE THREAD

**Issue by pyro-dev** [strongbox-password-safe/Strongbox#238]
Since a few days I'm experimenting errors with Strongbox.
I'm using KeepassXC on my desktop, up-to-date.
I'm not sure what triggered the faulty behavior, I would need to put more time on this and re-save my database with a former version of the tool.
Anyway here is what I get when trying to open the file on IOS. The file is opened properly on Keepass, KeepassXC and on Keepass2Android. I just have issues with Strongbox now.

<img width="270" alt="signal-2019-12-09-191829" src="https://user-images.githubusercontent.com/12093095/70431435-ff4d3580-1a74-11ea-841f-984ab784e9ba.png">

**Comment by mmcguill** [comment]
That's strange @pyro-dev - What version of Strongbox are you running?

Where is it stored?

Are you running Mac/Linux/Windows on your laptop/desktop?

**Comment by pyro-dev** [comment]
I'm running Strongbox 1.45.0 on an IPad (up to date IOS 13.2.3).
My machines with KeepassXC are on Windows 10.
Strongbox is accessing my database file located on my Synology NAS. The file is send to the app via a "Send Copy" menu entry (I get a Copy to Strongbox option there). Same when copying first with the Files application.

**Comment by mmcguill** [comment]
Ok, interesting... What version of KeePassXC are you running, is it a beta by any chance?

If you feel comfortable with the command-line/powershell on Windows could you paste the first 12 bytes (in hex) of your file, example here:

https://superuser.com/a/1247756

Or would you be able to use iTunes Files Sharing to create a local copy? 

Or send your self the file by email attachment (open it in iOS) and see if that works?

**Comment by pyro-dev** [comment]
Version for KeepassXC is 2.5.1. It's not a beta as far as I know.
Here are the first bytes of the file.
00000000   03 D9 A2 9A 67 FB 4B B5 00 00 04 00 02 10 00 00

**Comment by mmcguill** [comment]
First 12 bytes are good - Whatever Synology Files integration is sending to Strongbox is not that... 

Could you try one of the above alternative methods of adding the database?

Does your NAS support SFTP/WebDAV?

**Comment by pyro-dev** [comment]
Did the test with a local copy instead. It indeed seems to work this way !
The weird thing is that the Synology app was last updated 7 months ago, and that things were definitely working until a couple of weeks ago.
In between, there were updates on IOS and on Strongbox, but not on the Synology side.

**Comment by mmcguill** [comment]
Yeah that is weird indeed... 

There have been so many problems with iOS 13 and the Files app recently that I'd be quite suspicious that's the culprit. Have you tried restarting your device, or removing reinstalling the Synology app?

**Comment by pyro-dev** [comment]
Restarting and then reinstalling the Synology app didn't work unfortunately.
Incidentally, I thought that deleting an app would delete all its setting as well on IOS, so I was surprised to see all my previous NAS settings just waiting there for me. This kind of makes me uncomfortable :/

**Comment by mmcguill** [comment]
Yeah I would have thought it would have removed all data... that is strange - Restarting/Upgrading iOS might help?

**Comment by pyro-dev** [comment]
Okay..... after rinsing and repeating several times the app delete/reinstall process, it seems to work fine now. Definitely something fishy going on there, but at that point it would be hard to put it on you ^^
Sorry for wasting your time on this !

**Comment by georgesnow** [comment]
@pyro-dev which Synology app are you using?

**Comment by pyro-dev** [comment]
I'm using DS File

**Comment by georgesnow** [comment]
my understanding from documentation is the DS File app does **not cache files**. Then it is possible that HTTPS request failed when trying to access your database, the file didn't fully download, DNS lookup issue, etc.... 

This means the system might have allowed Strongbox to try and attempt to open it because there was previous reference to the file (but not a cache), but as @mmcguill it is a bit of black box on the other side. Depending how deep you want to go and how often it happens. Synology NAS's have decent logs that you can see if the request on the NAS side from your iOS is failing for some reason.

**Comment by georgesnow** [comment]
I should what's confusing is the DS Photos and Movies apps seem to provide some caching. I mention the above about the Files app is because this was my experience when I was testing it for something else. 

From Synology's documentation:

> To release mobile space:
> Tap Free up Space to clear backed-up photos and videos, and to view the number of files to clear. Then tap Clear to delete files for more mobile space.

**Comment by mmcguill** [comment]
Gonna close this one out... appears to have an issue with Third Party app...
