### ISSUE TITLE
iOS Google Chrome Autofill with basic auth results in "goo"

### ISSUE THREAD

**Issue by christianschneider89** [strongbox-password-safe/Strongbox#239]
Hello

I use Google Chrome on my iPhone.
When I open a website which is using [basic authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) I hit the passwords button above the keyboard.
Strongbox opens and after I unlocked it with my finger the search-field is prefilled with "goo" instead of the url.
I can reproduce it on another iPhone with another database and another iOS.

Chris

**Comment by mmcguill** [comment]
Weird... The Auto Fill system passes Strongbox a hint (usually a URL or Domain) it can use to try locate the login. There is some logic in Strongbox to try to determine the login from the URL if it doesn't get a direct URL/Domain match. 

In this case Google would seem to be passing something funky, perhaps https://goo.gl/foo or something like that.

What happens when you try it in Safari?

**Comment by christianschneider89** [comment]
On safari the search field stays empty.

**Comment by mmcguill** [comment]
Yeah so as you can see this is dependent on the parent app (Chrome, Safari) and what they pass as a "hint"... 

If you have access to XCode, you can use the organiser to view the device console logs, from which you will be able to see the hint that is passed by the parent app... it's worth looking at this, it might indicate where things are going wrong or if there's enough information there to even make a valid search...

Perhaps there's a way to improve the search algorithm in Strongbox... if you feel comfortable please share the results of your investigations here or mail me privately if you prefer and I can see if something can be done...

**Comment by mmcguill** [comment]
Investigated this with a URL provided by @christianschneider89 - Not much can be done here as Google passes "goo.gl" as the hint. Safari appears to pass an empty string.
