### ISSUE TITLE
[Bug] iOS creating new entries in apps don't save

### ISSUE THREAD

**Issue by georgesnow** [strongbox-password-safe/Strongbox#240]
so I have encountered this twice recently. I created a new entry in app that I need to create password for. Mechanics are pretty basic:

1-Open app - need to sign in or sign up
2-on sign in screen tap field for username to get "Passwords" option form QuickType
3-Tap Create new entry - give it a name user name and auto gen password
4-Tap save
5-Now click sign up
6-fields don't normally show Quicktype for whatever reason...annoying, but I digress. I switch over to Strongbox top copy password
7-Search for entry....no entry....

Not sure if this Strongbox or limitation of Autofill/QuickType feature. Wonder if this is why some app use Share extensions instead. It's as though the entry is in memory, but never gets written out to the file.

**Comment by mmcguill** [comment]
Can you tell me what Storage Provider method you use? e.g. iCloud, Dropbox, iOS Files etc

**Comment by georgesnow** [comment]
I am using iCloud.

**Comment by mmcguill** [comment]
Thanks, aI presume you're using standard iCloud, and not using a database resident on iCloud somewhere but added via iOS Files?

**Comment by georgesnow** [comment]
Typo on step 5. That. is suppose to be **_sign in_**

**Comment by georgesnow** [comment]
Correct. It is in the Strongbox iCloud folder.

**Comment by mmcguill** [comment]
Cheers, that sounds odd, I'll take a look shortly

**Comment by georgesnow** [comment]
Awesome thanks. Let me know if there is anything else you need or want me to try.

**Comment by georgesnow** [comment]
@mmcguill wanted to mention I ran into this again. Oddly I can't remember if I changed anything since you added this feature. Do you happen to know a set known working settings when using this feature? In the meantime I am willing to modify my settings to avoid the issue.

**Comment by mmcguill** [comment]
Haven't gotten around to looking into this yet @georgesnow - might take another while

**Comment by mmcguill** [comment]
I have not been able to reproduce this on latest iOS using an iCloud database, though I have received another complaint via email about this...

Does it happen always for you? 

Or does it work sometimes, or is it possible that it updates eventually? 

Is your database a large file which could take time to sync over a bad network?

**Comment by georgesnow** [comment]
I am able to reproduce it every time. I have never seen the entry be there even after some time. Database is about 400 entries and 10mb. I believe I can reproduce with other databases in iCloud (these are test ones with 3-4 entries). I will confirm that though and let you know.

**Comment by georgesnow** [comment]
@mmcguill could you provide all the settings you used for the situation it works you? I have tried modifying a few. No change. 

However, I have run into this issue a few more times and at ask of creating a new account and not having the password would be rather unfortunate.

**Comment by mmcguill** [comment]
It was just a brand new (Express) database. Added like 1 entry. Then tried to add one in the Auto Fill context and it worked. Does that work for you?

I'm fairly sure the problem here is an Auto Fill crash during Save, but I'm going to add some messaging/logic to prove it.

**Comment by georgesnow** [comment]
@mmcguill so I tried your example it does works properly. So we are getting there.

 I  went back to same site and tried with my other database and the create new was greyed out. I went back to strongbox and the database is not marked read only. Not sure it is related but now I can’t attempt to make an entry

**Comment by mmcguill** [comment]
@georgesnow - if you're running the latest version there is new crash detection code. It will tell you when you open it up after a crash if it crashed last time

**Comment by georgesnow** [comment]
Just downloaded it I will give it go

**Comment by georgesnow** [comment]
so create new is still greyed our. I tried disabling the cache but that made no impact.

**Comment by mmcguill** [comment]
Create New is disabled for some providers. Where is your database stored? I thought you were using iCloud (which is available for new entry creation)

**Comment by F3000** [comment]
@mmcguill 

do you mean this message ? 
I have seen that today the first time . But don’t know what to do 🤔

![73568EEE-24F0-4575-A9A4-49BAD47D9BD6](https://user-images.githubusercontent.com/8161283/76150335-a019b400-60a9-11ea-8a6a-7b4f156f2b20.png)

**Comment by georgesnow** [comment]
Yes iCloud

**Comment by georgesnow** [comment]
Actually all the databases I have are iCloud now looking at them in strongbox

**Comment by mmcguill** [comment]
Are you using native iCloud or via iOS Files?

I see the 'Create New' button enabled if I create a new iCloud database...

**Comment by mmcguill** [comment]
Also, make sure you don't have 'Auto-Fill: Always use cache' checked inside Database Management (Spanner/Tool icon in the bottom left)

**Comment by georgesnow** [comment]
I fixed the create new. Apparently there is limit to number of databases you can have providing credentials for auto fill. And upon retrying auto fill immediately crashed

**Comment by mmcguill** [comment]
Yeah, so right now you can create a new entry in a new database, but using your other larger database you get a crash, right?

**Comment by georgesnow** [comment]
And now it crashes every time. My database is only about 7mb. So something else is tripping it off. 

As side note and just an idea. I don’t use Touch ID I have iPhone 7. However, my hone button is broken and I replaced it (no Touch ID) and I know this problem was been apparent since I got locked out of my database when it broke. Is extension checking by for the biometric on launch even though I don’t have one and it’s gettinf hung up that?

**Comment by georgesnow** [comment]
Correct the new single entry express database works. My everyday one does not work

**Comment by mmcguill** [comment]
Really difficult to say without a crash log. Can you send/submit to Apple?

Navigate to your device Settings > Privacy > Analytics > Analytics Data.Scroll through this list to find 'Strongbox' events. The list is alphabetical. Tap one of these events. Tap the share icon at the top right.

**Comment by georgesnow** [comment]
So there is only 2 for strong box from feb 13. Are they of any value to send to you?

**Comment by mmcguill** [comment]
No harm to send them I’ll take a look

**Comment by georgesnow** [comment]
Sent.

**Comment by georgesnow** [comment]
@mmcguill so I tried  whole bunch changes. It is only this database. I tried from iCloud and loading from the files app. Same behavior. What’s the limitation of size for the database? It says 64mb in the error, but my database (compressed) is 10.4mb. Is there way for me to see how much space it is once it is decompressed and unlocked?

**Comment by mmcguill** [comment]
What are your encryption settings/parameters?

**Comment by mmcguill** [comment]
You can find these by opening it up in say a desktop KeePass client or by scrolling to the bottom of the Database Management screen in Strongbox iOS. Looks like this:

![image](https://user-images.githubusercontent.com/344791/76169086-4a124280-6175-11ea-9c29-3e107beb092a.png)

**Comment by georgesnow** [comment]
![A5069656-54BE-41EB-B489-A587E8F934CD](https://user-images.githubusercontent.com/12751441/76169235-82515b00-614c-11ea-8080-cf680ebc47ae.jpeg)

**Comment by mmcguill** [comment]
Interesting... Do you have access to KeePass on desktop? 

There's a couple of things you could try that might help...

1) Try running Maintenance in KeePass, your database may have collected a lot of cruft over time and this can help
2) If you have access to KeePass or KeePassXC, you could try upgrading the KDBX format from 3.1 to 4 which might improve performance too.

I'd be interested to hear if either of these helped.

**Comment by georgesnow** [comment]
Will do. Didn’t know there was a maintenance feature.
I have back up copies so I can try it multiple ways and see if it’s one or combo of those to fix it. I will report back what I find.

**Comment by georgesnow** [comment]
alright Database maintenance worked! I ran both options and with the delete entries (I made it older then 800days). this seems to have fixed the issue.  thanks @mmcguill

**Comment by mmcguill** [comment]
Great to hear. I guess your database is significantly reduced in size now?

**Comment by georgesnow** [comment]
@mmcguill yes it went from ~10mb to ~4 mb

I had previously deleted a zip file I had in there and old entries. So something in there ballooning the size above the auto fill threshold.

**Comment by mmcguill** [comment]
Thanks for the update
