### ISSUE TITLE
Multiple URL support

### ISSUE THREAD

**Issue by Doc-Steve** [strongbox-password-safe/Strongbox#243]
### Situation:

Some sites use the same credentials but have different URLs (sometimes even the domains are different), e.g. for their store and for their forum. At the moment it is not possible to provide multiple URLs for one account, which are searched automatically when opening Strongbox. There's a workaround with "search in all fields" (in iOS Version) ...

### Proposed solution:
When searching for a match in URL not only search in the field "URL" but in all fields staring with "URL", e.g. also matching fields "URL2" or "URL-Forum".

**Comment by mmcguill** [comment]
Yes, sounds like a good idea - should be a quick one in the next release...

**Comment by gamewin1** [comment]
There exists something similar to what you want, it involves using the [field references](https://keepass.info/help/base/fieldrefs.html) feature built into KeePass. It accomplishes the same task as you want, but just gone about a different way.

Here’s an example of how I have two entries of mine set up. I copied the UUID field from the Apple metainfo and put that in the field references for my iCloud entry. Now when I copy the username or password field for the iCloud entry, it just grabs the username or password from the Apple entry. This way there’s only one entry I have to update, and all others linked to that entry reflect the latest changes.

![DF2F5A78-77C4-49DB-9F4B-9AC87A73EC55](https://user-images.githubusercontent.com/2367033/72326868-a5dcb580-3675-11ea-830d-aaefd1597a6d.jpeg)

![FBA2F0D9-DC33-4805-8055-B6BAA0303A63](https://user-images.githubusercontent.com/2367033/72326856-9f4e3e00-3675-11ea-9858-f99a00070c83.jpeg)

You can also set this up pretty quickly from the KeePass desktop version. You right click an entry and click duplicate, and check the box that says to replace the username and password with references. Then you can go to that entry and make any edits you wish to the URL and other fields.

**Comment by Doc-Steve** [comment]
Field references are very usefull for another purpose: you have two different pages you want to link together, e.g. single sign on with facebook credentials on another web page. The use case of this ticket is different: this is ONE account with different URLs, where you don't want to spread your notes etc. in different entries.

**Comment by mmcguill** [comment]
@Doc-Steve This is available now in 1.45.6 released today. Could you check it is working as expected? Any custom fields starting with URL* or KP2A_URL* are now considered alternative URLs and will match in a URL search...

**Comment by Doc-Steve** [comment]
Thanks, perfect! Works even better than expected. It works in the Strongbox GUI and also in the "quick select" before opening Strongbox GUI.

**Comment by mmcguill** [comment]
Cool!

**Comment by F3000** [comment]
@mmcguill 

Also fields with „URL 2“ (there is a blank between URL and the number)
