### ISSUE TITLE
Potential bug ios: Unexpected unlock behaviour 

### ISSUE THREAD

**Issue by milesmcclane** [strongbox-password-safe/Strongbox#246]
I have my main database locked with Touch ID and also a pin code which I have set to require after 1 minute of inactivity. 
I have set the the app with Touch ID set to immediately. 

This is so I can easily just use Touch ID to re-enter  straight away if necessary and not bother with the faff of the passcode, but the whole thing locks down automatically when I have finished. 

Three issues occur with this method, the main one is hitting cancel on the Touch ID dialogue actually cancels it and allows access without a finger print - obviously that’s not intended. 

A secondary issue is that I believe the screen should be masked under the Touch ID request. 

A third issue appears to be that the timer to lock the database doesn’t actually auto lock when I move away from the app, only when I close it down.

**Comment by milesmcclane** [comment]
Just realised this has been raised already, and restarting it as mentioned before did fix the state. 
I’ll keep testing and track with the other. Shall I close this issue?

**Comment by mmcguill** [comment]
Thanks @milesmcclane - yes this is a tough one to track down... it seems to only happen rarely... if you can think of anything that would help me reproduce this I would be grateful as I haven’t been able to get this reproduced in a test situation. I’ll close this as a duplicate and reference from #237
