### ISSUE TITLE
iOS bug- view attachment pool

### ISSUE THREAD

**Issue by milesmcclane** [strongbox-password-safe/Strongbox#247]
The view attachment pool section only appears to show the most recent attachments added. 

For example, I have 4 entries each with two photo attachments; When I create a 5th entry and add two photos attachments, scrolling through via the ‘view attachments pool’ only displays the last images added in that last single entry. 

The numbers described across the top are accurate, in this example 1/10, 2/10, 3/10 and so forth, but the images shown are the last two images added over and over again, and not all of the attachments with the database. 

Hope that makes sense!

**Comment by mmcguill** [comment]
I can't reproduce this at the moment @milesmcclane - Can you see this behaviour if you close and reopen?

**Comment by milesmcclane** [comment]
Yes it’s the same if I reopen, and the same on my iPad (using the original database I was referring to)

**Comment by mmcguill** [comment]
Bizarre, could you try creating a new dummy db and see if it also happens? 

Are the entries/attachments displaying correctly in Details view otherwise?

**Comment by milesmcclane** [comment]
I’ll try to recreate it. 

It’s noteworthy to mention that it was already a new database, dedicated for attachments. I created the original database in keepassxc, and saw this issue upon adding anything for the first time. 

I’ll try the whole thing again totally within strongbox to see if it’s related to using a database created with a different app. 

I would like to do that always and ditch keepassxc, but strongbox lacks some of keepassxc’s fundamental database creating options, namely (for me) the option to generate a key file and the option to set (and alter afterwards) the encryption parameters. Are these kind of options on the roadmap?

**Comment by milesmcclane** [comment]
And yes, all other views are working correctly.

**Comment by milesmcclane** [comment]
@mmcguill, I have recreated this and I think the issue lies when using the camera app to add the attachments directly, which is what I was doing as I was adding sensitive documents. 

In my tests using random pictures via the camera app yielded the same results as I’m the initial complaint. 
Importing via the camera roll resulted in normal behaviour. 

Hope this helps.

**Comment by mmcguill** [comment]
Thanks @milesmcclane - I'll try take a look at this shortly...

**Comment by mmcguill** [comment]
Hi @milesmcclane - I've tried to reproduce this and I just can't. Could you give your device a restart and see if you can give me some more details instructions to reproduce. It just seems like some kind of weird state bug from what you've described...

**Comment by milesmcclane** [comment]
The only way I can reproduce it is by using the camera app option to add the attachment. Did you try that?
All other things being equal that’s the only difference. I am able to reproduce it even right now on another new database. Restarting the device has made no difference and the issue runs across all apps on different devices. (iPad and iPhone, haven’t tied Mac)

**Comment by mmcguill** [comment]
Yes, have been trying only with Camera, would you mind sending me that dummy database? 

Also what device are you using?

**Comment by milesmcclane** [comment]
Yes I will do that when I get a sec, how can I send it to you? Email? 
iPhone 8+ and 12.9" iPad Pro 2018 version. Used the phone to add the database

**Comment by mmcguill** [comment]
Cool, both on iOS 13.x?

Yes email would be great. Thanks!

**Comment by milesmcclane** [comment]
Yes both on the latest iOS. I’ll email it ASAP

**Comment by mmcguill** [comment]
This should be fixed for you now with 1.45.8 @milesmcclane - could you confirm and close?

**Comment by milesmcclane** [comment]
Thank you! Confirmed and closed.
