### ISSUE TITLE
Yubikey TOTP Autofill

### ISSUE THREAD

**Issue by chrenderle** [strongbox-password-safe/Strongbox#248]
I recently transfered my TOTPs from Strongbox to my Yubikey using the Yubikey Authenticator app, because it is much more secure to have the TOTPs on a different device. But I would still like to use the Autofill feature or rather the auto copy to the clipboard feature. 

I read in another issue that you will implement the Yubikey unlock (not the workaround) when they implement this in their api. I would be pleased if you could also implement this feature:

I imagine it this way that when I autofill something I have to insert my Yubikey (my guess on how you’ll implement it). After Strongbox decrypts the database and I choose the entry I want to autofill, it reads the TOTP from the Yubikey and copies it to the clipboard. 

Would that be possible?

**Comment by mmcguill** [comment]
Hi @chrenderle - really hard to say if this is possible and my guess would be that it will not be possible...

Yubico would have to expose a method or API for Strongbox to ask for the TOTP for a certain entry (how to even ID this?)... If you know of a way, or if this is possible then let me know, but as far as I know this isn't currently possible. 

You could ask the Yubikey guys if it's possible for a third party application (like Strongbox) to request the current TOTP for any entry. 

For the moment, this is not actionable, but please feel free to re-open if you get any more information on this.

Thanks,
-Mark
