### ISSUE TITLE
Duplicate entry created in Password Safe db

### ISSUE THREAD

**Issue by Ben-Voris** [strongbox-password-safe/Strongbox#250]
PC Password safe reports:

The following ERRORS were detected and were FIXED.

The following entries were duplicates of an existing entry.
	Group='', Title='*title*', User='*user-name*' - Its title has been changed to:'*title* Duplicate # 1'

Note that the Group name is followed by two single quotes (i.e., the item not in any group). I replaced the actual names with *title* and *user-name* .

The two entries in Strongbox differ only in the `Created` date.

`Last Update App` shows `Strongbox v1.4...`

This can be created with a new Password Safe db by simply creating two entries.

I didn't find the 3.11 file format version, but I don't see a requirement for unique titles in [PasswordSafe database format description version 3.29](https://sourceforge.net/p/passwordsafe/bugs/1097/attachment/formatV3.txt). And, yet... Iirc, earlier version of the file format did not include a uuid and so might have required that the title be unique.

See https://github.com/pwsafe/pwsafe/issues/626

In case you wonder, this is a different Password Safe than the one from [Password on Windows reports "duplicate UUID field" after adding entry from Strongbox](https://github.com/strongbox-password-safe/Strongbox/issues/234).

**Comment by mmcguill** [comment]
Thanks @Ben-Voris - So just to be clear, could you list the exact set of reproduction steps for me?

**Comment by strongbox-mark** [comment]
Hi @Ben-Voris - Could you provide the exact repro steps here or close?

**Comment by Ben-Voris** [comment]
I cannot create this problem. The test case requires decrypting one of my passwords safes.
