### ISSUE TITLE
Custom icons disappear after saving

### ISSUE THREAD

**Issue by gamewin1** [strongbox-password-safe/Strongbox#252]
if I edit an entry and hit done without making any changes to the icon, after it finishes saving the other changes, the custom icon I had will be reverted back to the default key icon.

This seems to happen on iPhone and iPad, across iOS 12 and 13, using whatever saving method (i tested iOS files and dropbox)

The only thing I can narrow it down to is that it happens with a KeePass database that was made in the original KeePass program. From my testing, it happens to my KDBX 3.1 database that I’ve used since 2013, that same database upgraded to KDBX 4.0, and a new 4.0 database I made in KeePass today with a few dozen csv imported entries. The icon bug doesn’t happen with any databases made within the app though. I made new ones in the app to test using KDBX 3.1 and 4.0 and they both work fine

**Comment by mmcguill** [comment]
Thanks for the report, that is super strange. 

Do you have "Auto FavIcon on New" turned on? You can find this setting by tapping on any entry, and then tapping the "List/Meatballs/Spagetti" icon in the top right.

**Comment by gamewin1** [comment]
it seems to make the icons disappear regardless of that setting being on or off. although from more testing, i tried creating new entries in my normal database from within the app and the icons seem to work as intended until i edit the entry externally. so it may actually be something to do with the entries themselves being made or edited externally that causes the bug to happen

**Comment by gamewin1** [comment]
I've done a bit more testing: it seems any new entries made within the app will work fine up until the point that *any* changes are made to the database with the keepass desktop program (and presumably any other ported versions), once changes are made externally, the icon bug will happen to all entries in the database that existed before those external changes happened.

more testing may have to be done to narrow it down further, but i think that may be what it is

**Comment by mmcguill** [comment]
Ok, so just for my own testing, I should see this behaviour if I:

1) Create a new database in KeePass (on Windows) and add any entry with a Custom Icon
2) Open that same database in Strongbox from say Dropbox
3) Edit that entry without changing the icon

If I do this the custom icon will disappear? Sound right?

**Comment by gamewin1** [comment]
that is correct. i also just confirmed the steps myself

**Comment by Slummi** [comment]
I've just came across this issue.
I added a new custom field to an item with a custom icon in Strongbox. After saving, the entry had the icon of it's group.

I think this bug is new. I didn't see it in the past.

**Comment by mmcguill** [comment]
@gamewin1 This should be fixed with 1.45.6 released today. Could you confirm and close if so?

**Comment by mmcguill** [comment]
Believe this to be fixed @gamewin1 / @Slummi if you still have an issue let me know.
