### ISSUE TITLE
Transfer Over Local Network Should Support Key Files

### ISSUE THREAD

**Issue by nnpcYvIVl** [strongbox-password-safe/Strongbox#253]
The web interface currently supports transferring kbdx databases into the app. However when I try to copy a key file it fails with the error message `error: Failed uploading "KeyFile.key" to "/"`.

Can the web interface allow key files to be uploaded in the same way that databases are?

**Comment by Slummi** [comment]
In this case there shouldn‘t be any limitation to a special file type, because all extensions are allowed for key files.

**Comment by mmcguill** [comment]
Yes, makes sense, sounds like a bug. Will address shortly. Thanks

**Comment by mmcguill** [comment]
@nnpcYvIVl - I can't reproduce this. The only way I can get what you are describing is if the device locks - in which case Strongbox can no longer run the http server in the background.

Can you confirm that you cannot upload KeyFile.key when Strongbox is open/present on screen on device?

**Comment by nnpcYvIVl** [comment]
@mmcguill Thanks. I tried again and can confirm that it works when the device is not locked. Any files transferred after the phone screen goes black get the previously mentioned error message.

Perhaps the error message text in the browser can be changed to include language to prompt the user to make sure the screen is unlocked.

**Comment by mmcguill** [comment]
Yeah, good idea, will do.
