### ISSUE TITLE
KDBX file in iOS Files app shows russian characters

### ISSUE THREAD

**Issue by nnpcYvIVl** [strongbox-password-safe/Strongbox#254]
When I view a kdbx file in the stock iOS files app it shows russian characters in the filetype. Shouldn't this be in English? See attached screenshot.

![StrongBox iOS - KDBX file in iOS Files app shows russian characters](https://user-images.githubusercontent.com/8421414/72471896-22bc7c00-37a9-11ea-85b8-44b95dd2cd52.png)

**Comment by mmcguill** [comment]
@nnpcYvIVl This should be fixed with 1.45.6 out now. Could you confirm? Might require a device restart?

**Comment by nnpcYvIVl** [comment]
@mmcguill Thanks, the update fixed it. No device restart was required.
