### ISSUE TITLE
TouchID Reset bug?

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#255]
The reset just happened to me this morning even though I did not change/add/remove fingerprints.

Steps I did:
1) Opened Strongbox on my iPhone, decrypted with Touch ID.
2) Went to the Chrome App and navigated to github.com for login.
3) I intended to use Auto-Type but I then received the prompt that I needed my master pwd again after a biometric change.
4) Used app switch (double tap home button) to go back to the still active, but already locked Strongbox app. I was still able to use my Touch ID to unlock it again.
5) Only after quitting Strongbox completely and restarting it I had to enter my master pwd upon opening the app.
6) Then I quit and restarted the Chrome App, tried Auto-Type again and it still wanted my master pwd, even though I had just entered it in Strongbox before.

Questions:
1) Why did it ask for my master pwd even though I did not change my fingerprints?
2) Why is Auto-Type and the regular App treated differently in that regard?

**Comment by mmcguill** [comment]
Sounds like a bug @dan-el - possibly because the Biometric DB state is different for App Extensions vs the parent App... will investigate.

Does it happen repeatedly? Or just the once?

**Comment by dan-el** [comment]
So far it only happened once to me. Considering this feature is new, and the fact that I use Strongbox on my phone on a regular basis, I am sure it will occur again if it is really a bug. I'll keep a log here if you like and will also try to watch out for the circumstances under which it occurs.

**Comment by mmcguill** [comment]
Yes please @dan-el - Any observations welcome :)

**Comment by Slummi** [comment]
I can confirm this issue. Opening the Strongbox app works fine. Using Autofill doesn‘t. First time using Autofill I got the biometrics database changed message. Then I got the message (in the app) that the comfort password was wrong. After re-entering the master password and activating Face ID is working for the app but not for Autofill. I have to enter my master password in Autofill all the time.

**Comment by Slummi** [comment]
Prima facie, AutoFill looks good with 1.45.9. 👍🏻

**Comment by mmcguill** [comment]
Good to hear - @dan-el - Can you confirm and close?

**Comment by dan-el** [comment]
Alright, I can confirm it's working again. And it also survives a phone reboot.

**Minor note:**
After updating the App to 1.45.9 I was not able to get it to work properly until I _restarted my iPhone SE_. Several attempts of opening/closing the Strongbox App and the Google Chrome App consistently resulted in the same broken behaviour: Touch ID unlock in Strongbox was okay, TouchID unlock via Auto-Fill broke it again for both, app and Auto-Fill.

On my iPhone 8 I updated directly from 1.45.5 to 1.45.9 and experienced the same behaviour. I _had to restart the phone_ to make the constant master password prompting behaviour end. Also note that after the restart the master password was required once.
