### ISSUE TITLE
iOS: disable tip on every app page 

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#258]
Is there a way to deactivate the tip on every app view screen ? 

I other apps I have such tips only after first setup . 

And in German language the the text is too long to look nice on the layout 

![10900698-759C-4D8B-82DA-2A931B795A1C](https://user-images.githubusercontent.com/8161283/73303045-f9263a80-4215-11ea-9958-dbd2dd588e0e.jpeg)

**Comment by Slummi** [comment]
You can deactivate tips in the app settings (database view). It‘s the first option.

**Comment by mmcguill** [comment]
Yes, as @Slummi says. Cheers!
