### ISSUE TITLE
Flat List view should have index/alphabetical section scrolling

### ISSUE THREAD

**Issue by user858753257** [strongbox-password-safe/Strongbox#259]
I don’t find this setting in your app . 

Here is an example from Enpass/1password: 

They have two views ... one where the user see all entries sorted alphabetical 
Second the “group view” like yours where the user see only the entries from each group . 

Here is an example for the structure : 
![EDCAB079-5E85-45E3-AFC9-67183C937976](https://user-images.githubusercontent.com/8161283/73304002-bbc2ac80-4217-11ea-873d-f59b45907237.jpeg)

Would be cool when can implement this also :)

**Comment by mmcguill** [comment]
If you go to View Preferences > View As > Flat List you can see your database this way. Or slide down for Search mode and you will see all entries.

**Comment by F3000** [comment]
Ok I have found it . 

But there is no separation between the letters (see picture) And no sidebar on the right side with all letters from the alphabet. 

Is it possible to add it ?
![97F70B42-6937-45E8-A462-0539AA6FCF52](https://user-images.githubusercontent.com/8161283/73345468-6b356880-4284-11ea-81f8-c4c08ad6ab46.jpeg)

**Comment by mmcguill** [comment]
Yes, that might be a nice addition. Thanks.

**Comment by strongbox-mark** [comment]
This is now available for you in the latest release.

**Comment by user858753257** [comment]
Hey , 

Also in the newest beta version ?

**Comment by strongbox-mark** [comment]
Yes, you can tap on the sort button to configure these things
