### ISSUE TITLE
Keyboard commands for external keyboards 

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#261]
You can find some examples here :
https://9to5mac.com/2015/11/20/ipad-keyboard-shortcuts-cheat-sheet/#

**Comment by mmcguill** [comment]
Interesting idea, sounds like a handy feature... 

https://nshipster.com/uikeycommand/

**Comment by F3000** [comment]
I hope it is easy for you.  The menu for long press command key has every app that supports keyboards .

I think that Apple publish with iOS 14 a real mouse/keyboard API

**Comment by mmcguill** [comment]
It looks reasonably straightforward but unfortunately it will be down the priority list so could take a while to add.

Can you tell me what you mean when you say: "The menu for long press command key has every app that supports keyboards"?

**Comment by F3000** [comment]
Hi , 

I mean following menu.  You can open it bzw. long press Command key on the external keyboard 

![6A5A1E53-E1F5-4BD8-9924-E2591A04A279](https://user-images.githubusercontent.com/8161283/74284715-a58f1300-4d24-11ea-8831-56b911fae9e8.png)

**Comment by strongbox-mark** [comment]
We have Cmd+F now as a Keyboard shortcut with iOS13+ which activates the search bar... Please open another issue if you'd like further keyboard shortcuts.
