### ISSUE TITLE
Bug : when app opened in splitview and opened again , no password is needed for unlock

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#262]
Example : open any app on iOS which supports split view -> open dock (swipe up) -> choose strongbox -> put it on the right side of the screen 

Now is splitview enabled .... Now try to press homebutton . -> open taskswitcher -> open both apps from from switcher -> database is still open 
= as a user i expect that the database is closed here

**Comment by F3000** [comment]
Seen on iOS

**Comment by mmcguill** [comment]
What are your Database Auto Lock settings?

**Comment by F3000** [comment]
Where i can find these infos what zog are searching for ?

**Comment by mmcguill** [comment]
Database settings can be found by tapping the 'Spanner' icon in the bottom left corner when you open the database.

**Comment by mmcguill** [comment]
Is this still a bug do you believe or is it ok to close?

**Comment by dan-el** [comment]
**I tested this with the following workflow on my iPad:**
1. Open Safari
2. Swipe up from the bottom and open Strongbox in split view on the right side
3. Open my database in Strongbox
4. Opened App Switcher (double-tap home button)
5. Immediately select the split view app window with Safari and Strongbox.

**Outcome depending on app settings:**

**_Scenario 1:_**
* **Application Lock:**
  - Delay: None
  - Also Lock Preferences: On
* **Database Auto-Lock:**
  - Enabled: on
  - Delay: **1 min**
**_Outcome 1:_** App is immediately locked and upon unlocking it decrypts the database or just opens the database (if it did not run into auto-lock)

**_Scenario 2:_**
* **Application Lock:**
  - Delay: None
  - Also Lock Preferences: On
* **Database Auto-Lock:**
  - Enabled: on
  - Delay: **None**
**_Outcome 2:_** App is immediately locked and upon unlocking it decrypts the database. which means the database was properly locked!

Nota bene: I have only one database and it's set to quick launch AND I am also using Touch ID to unlock my database and to unlock the app.

Hope this helps to narrow down any issue if there is any. Setting database auto-lock delay to "None" should do the trick.

**Comment by mmcguill** [comment]
Thanks @dan-el - I don't think there is an issue here though your suggestion about better documentation is a good one. Thanks.
