### ISSUE TITLE
Feature request: add travel mode 

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#263]
Some idea from me . At the moment it is possible to enter a special pin to hide the database .

Can this be done via a switch too ? In the normal day to day usage i only use Face ID and don’t want to add every time the comfort PIN. 

Would be grade when zog can add this feature

**Comment by milesmcclane** [comment]
Yes- great plan! I want to secure my dB with a pin also, plainly for the delete dB if incorrect option., but it’s annoying to enter it each time.  If not a toggle switch to turn on and off, at least an ‘enter once, re-enter after Xtime after’ option.

**Comment by mmcguill** [comment]
I'm afraid I don't understand this feature from either of your comments. 

Can you describe in detail what this feature would look like and how you would expect it to work?

**Comment by milesmcclane** [comment]
As far as my comment was concerned:

Each and every time you enter the db you require Touch ID (which is fine) and the passcode (which can be annoying If going back and forth between the app and a website over the space of a few minutes - for example password/totp/secondary password). 
My proposal was simply to allow a timer type setting to allow the database to be opened without needing the passcode (whilst still requiring Touch ID) - for say 1 minute or 5 minutes or whatever. 

I’m not sure I fully understand the concept of the ops original comment now I’m reading it a second time but I would guess some sort of toggle on/off switch to disable the passcode option, without needing to set it all up again to re-enable it, say for crossing boarders etc

**Comment by F3000** [comment]
@milesmcclane correct . I mean the crossing border topic

**Comment by mmcguill** [comment]
Hi @F3000 - I'm afraid I still don't know what you mean at all. You will need to be very detailed and explicit please.

@milesmcclane - You can turn PIN on/off in settings (separately from Biometrics).

**Comment by F3000** [comment]
The thing what i want is an extra protection that when enabled (e.g. at a border) the app looks empty. So no police can see mz database. 

After passing border i can switch back to normal mode

**Comment by mmcguill** [comment]
@F3000 - You can use Duress mode for this - If you enter the Duress PIN you can have Strongbox do one of the following:

- Present a Dummy Database
- Present a Technical Error Message 
- Delete the database

Does that work for you? If not, please describe what you would like to see happen in step by step detail.

**Comment by F3000** [comment]
I think of the solution without a PIN . 1pssword have this feature with a simple switch setting

**Comment by mmcguill** [comment]
@F3000 - You need to describe the feature here in detail and how it will work, or I will have to close.

**Comment by F3000** [comment]
Ok put it in the backlog first . 

My Englisch is not the best unfortunately ;(

**Comment by mmcguill** [comment]
Hi @F3000 - No problems with your English, I'm 100% sure it's better than my German. However I do need a description of the feature request before I can add it to any backlog. I'm going to close this one out now, but once you've got a good spec of some kind for what you'd like to see, please feel free to open and issue. 
Thanks!
-Mark

**Comment by F3000** [comment]
@mmcguill 

I have found a better explanation from 1Password. Maybe you can lheave a look on it again 😄

https://support.1password.com/travel-mode/

**Comment by strongbox-mark** [comment]
Yeah, ok, I see what you're after there.

The thing is this makes sense for 1password because they control/own/manage your vaults. So they know which ones are safe for travel or not because you tell them.

In Strongbox this doesn't really make sense I think because where/who should know what "vaults" are safe for travel except you? There's no central third party managing your vaults, it's up to you to manage them.

If you're going to travel, then just remove the databases from Strongbox and that's it. Re-add them when you're "safe".

I don't think this makes sense for Strongbox because you manage storage.
