### ISSUE TITLE
Feature request: Support of field references in custom fields

### ISSUE THREAD

**Issue by Slummi** [strongbox-password-safe/Strongbox#265]
Hi,

it would be nice to have support of field references also for custom fields and not only for the standard fields.

In edit mode you could see and edit the reference and in entry view mode you could see the value of the (de)referenced field.

**Comment by mmcguill** [comment]
Interesting point, I thought these were excluded.

Do you know if other clients support dereferencing in Custom Fields? KeePassXC, KeePass?

**Comment by Slummi** [comment]
I would say that KeePass has partial support of references in custom fields. You can insert a reference in a custom field, but you can‘t see the dereferenced field in the custom fields window, because the values are masked out by asterisks and you can‘t change this behavior. But you can select „Copy custom field xyz“ from entry‘s context menu for example and then the field becomes dereferenced and the value of the referenced field is copied into clipboard.

I think the Strongbox UI is more flexible at this point and you can realize editing, viewing and copying in one place.

**Comment by mmcguill** [comment]
That's interesting, seems like I was wrong. It sounds like it does or is meant to work with custom fields... Should be a straightforward work item, and one worth bumping up the list. I'll try get this fixed shortly. If you happen to be able to test if KeePassXC supports this quickly, I'd be interested to hear too...

**Comment by Slummi** [comment]
I checked the KeePass documentation and the behavior of KeePass and KeePassXC. I think the behavior of the applications is a little bit different than described in the documentation.

Here's what you can do with KeePass and KeePassXC:
- Reference locally any field (custom and standard) within the same entry
- Reference a standard field of another entry in a standard field as well as in a custom field (you can't see the dereferenced field for custom fields, but you can copy the custom field and you'll get the dereferenced value

Here's what you can't do:
- Reference a custom field of another entry
- Show the value of a referenced field in custom fields (you will always see the reference string)

For the sake of completeness here's an extract from the KeePass documentation:

> Referencing fields of other entries only works with standard fields, not with custom user strings. If you want to reference a custom user string, you need to place a redirection in a standard field of the entry with the custom string, using {S:<Name>}, and reference the standard field.
> 
> Custom strings can locally (i.e. within an entry) be referenced using {S:<Name>}, see the page Placeholders for details.
> 
> You can use the O code to make KeePass search the database for custom string fields (to identify the referenced source entry), but O cannot be used to retrieve data from custom fields (i.e. the code can't be used as WantedField).

If you decide to implement this, you should support local references (within the same entry) and referencing of standard fields from other entries for custom fields. But please put this on the roadmap whereever you want. I think it's not that urgent.

I hope my explanations are fairly clear. References are somtimes a little bit confusing. :-/

**Comment by mmcguill** [comment]
Thank you very much for that research Excellent. Shouldn't be a biggie.

**Comment by F3000** [comment]
Short question : 

can you explain me for what we can use “referencing” in general ?

**Comment by Slummi** [comment]
Sure. With references you can use the same credentials for multiple entries without entering them again. If you change the credentials of the referenced entry they do also change for the other entries. This makes sense if the credentials / entries are dependent on each other.

**Comment by F3000** [comment]
Thanks . This is a good feature

**Comment by mmcguill** [comment]
@Slummi - This is available for you now in 1.46.8 and on Mac

**Comment by dan-el** [comment]
Another side note: the referencing is also VERY useful for auto-type with login forms that go beyond regular username and password fields (e.g. 3 input fields). So if we get auto-type on the macOS version at some point I am sure this will come in handy already.
