### ISSUE TITLE
Feature request : add possibility to change order of entry view

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#269]
Hi ,

the idea is to change the order of the fields in entry view . 

At the moment it is like: 

1) username 
2) password 
3) URL 
4 +x ) Custom fields 

the user should have the possibility to put a custom field e.g. at top of the view

**Comment by mmcguill** [comment]
Noted.

**Comment by strongbox-mark** [comment]
This will be possible with the addition of Templates support in #281
