### ISSUE TITLE
Issue to open database

### ISSUE THREAD

**Issue by wphe** [strongbox-password-safe/Strongbox#270]
Hi,
I have a database which I open with a key file. Since the update 1.12.14, I am unable to open it as password seems mandatory and I don't have a password for unlocking it.

**Comment by mmcguill** [comment]
Hi @wphe, sorry this came as a surprise, it was part of recent Unlock/Touch ID secret store improvements. The idea was to make the normal use case (password entry) a bit more reliable flow better. 

You can fix this by setting the preference (Menu: Strongbox > Preferences... or (Cmd+,)) under the General tab called 'Allow Empty/No Password Unlock (w/ KeePass Key File)'. Just check that box and you should be good.

**Comment by wphe** [comment]
Thanks @mmcguill for your prompt response ;)
