### ISSUE TITLE
Feature request : Add iOS shortcuts support 

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#271]
Hi , 

with this it is possible to build custom made shortcuts/automations in iOS . 

Also Siri support is possible .

**Comment by mmcguill** [comment]
Hi @F3000 - I'm afraid this is extremely under specified. Can you describe in fine detail what you'd like to see?

**Comment by F3000** [comment]
Ok . I think with iOS 12 Apple had implemented a new app where users can build self build automations . 
Most popular Apps have it today .  Combined with other shortcuts  a user could automatically copy a password etc... 



https://support.apple.com/de-de/guide/shortcuts/welcome/ios

https://www.macstories.net/shortcuts/

https://www.appcoda.com/siri-shortcuts/

**Comment by Slummi** [comment]
I think the question is if it makes sense to provide safety-relevant data in an unsecure way.

To provide data from an encrypted database via Siri Shortcuts you will either have to store the data itself or the masterkey unecrypted. Otherwise you have to authenticate everytime you want to execute a shortcut. And then you can't call it automation, I think.
I don't see the usecase of this. Do you have one?

**Comment by georgesnow** [comment]
I couldOf think of few but really depends if @mmcguill decides other implementations are better.

 Quickly add entries from Other apps, hone screen and strongbox could just prompt for auth. And shortcuts can be added to share sheet to access in other apps
—--but 3d Touch option’s in home screen and Share extension would also accomplish this

Get none password entries from the database kind of like auto type. I have credit card entry I need Cvv, expire date etc.. shortcut to that direct entry and again strongbox just auths before revealing or copying to clipboard. Similar to QuickType passwords but other entry types else where and user driven
—-but again 1password has spotlight integration, Or favorite entries in database so when unlocked they are the first entries you see.

I use shortcut for my vpn client but it has to jump back forth between strongbox and the app etc... part the app doesn’t seem to support the Password keyboard option. 

So shortcuts like Apple script on the Mac provide mechanism for user customization without developer having to add fringe features. And work arounds for other apps. Not saying it’s the best way but Just some ideas to think about.

**Comment by mmcguill** [comment]
Just FYI, Favourites or Pinned entries are already available (Slide Left on an Entry/Group to Pin).

Otherwise I guess these are some usual features worth considering...

**Comment by F3000** [comment]
Maybe other idea : display this pinned entry’s in the widget for short access to it . 

Does the pinning feature only work in your app or is that a keepass Standard that also show in other apps ?

**Comment by Slummi** [comment]
Pinning is not standardized. You can only see those entries as pinned when you use Strongbox.

**Comment by mmcguill** [comment]
Yes, I've mentioned it in the KeePassXC standardisation list just now

https://github.com/keepassxreboot/keepassxc/issues/4317

**Comment by F3000** [comment]
Thanks . Is this the list for the next Keepass updates/roadmap etc..?

**Comment by strongbox-mark** [comment]
Closing this one, I believe we need more specific requests here.
