### ISSUE TITLE
Dark Mode: Icon selection view is white

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#272]
See picture : 

![C18FE4B8-C33A-4D32-9B03-5C0D9AE41378](https://user-images.githubusercontent.com/8161283/74279148-a753d900-4d1a-11ea-8e8f-eb3877dce977.png)

**Comment by mmcguill** [comment]
Thanks for the report - very odd.

**Comment by mmcguill** [comment]
This is fixed as of 1.46.7

**Comment by F3000** [comment]
Yes it works :)
