### ISSUE TITLE
Make Custom Field URLs Clickable in Details View (a la the standard URL field)

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#274]
Info from Twitter Chat : 

Because in the first URL field the letters a blue and clickable . In custom fields not . 
There should be a request when adding a custom field , which type it is.

**Comment by mmcguill** [comment]
There's no real concept of a "Field Type" for custom fields in KeePass...

However, it might be nice to make custom field URLs clickable for sure. Let's use this issue to track

**Comment by strongbox-mark** [comment]
This is done now - please re-open if you believe there's an issue with this functionality.

**Comment by F3000** [comment]
Thanks ✌🏼
