### ISSUE TITLE
Remove minimum column width in macOS App

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#275]
Can the minimum column width restrictions be removed from the macOS App?

When I have several windows open and I want to have Strongbox side-by-side with other app windows on a 13 inch MacBook the available screen space quickly becomes an issue. It would help a lot if I could reduce the app window size of Strongbox below what is currently set as a hard coded (?) minimum.

Thanks,
as usual.

**Comment by mmcguill** [comment]
I guess you're speaking about the minimum window size rather than the individual Outline View columns? 

Have you tried hiding the Quick View panel (Cmd + /) which allows you to shrink it pretty far?

It's already pretty skinny but I can allow a user to make it very small in a way that will truncate/hide certain elements, which I'm usually reluctant to do.

**Comment by dan-el** [comment]
I created the below screenshot to illustrate where I think space could be saved without sacrificing feature visibility. 

- If it was possible to toggle the "Search in" buttons (green rectangle) and hide them on demand we could save the width of the orange rectangle No. 1
- Looking at the very left red arrow and the space between the buttons it is pointing at I thought maybe more buttons/ui elements could use the same narrow spacing? (other red arrows and orange rectangle No. 2)
- The width of rectangle No. 3 could be "saved" as well. In my opinion and experience the text fields (username, password, url) are wider than necessary for everyday use - we would not give up much there, besides there are the neat copy buttons to get a hold of the contents and the key combos too.
- One last option to save space would be to get rid of the "expand/collapse all" buttons. I never used them in any password manager including Strongbox and don't really see the use case. That's just my option in the end, but maybe the button functionality could toggle based on the state of the entry list. That way one button would be sufficient. 

**As for your suggestion to hide the Quick View panel:**
I want the Quick View panel to be visible because it provides access to custom fields without having to open a db entry. The contents of other fields like username, password, TOTP, etc. can be copied with CMD + something key combos, but not custom fields. Sometimes I also only need portions of the notes field rather than the whole notes field (CMD + Shift + N)

I hope these explanations help understand my request.

<img width="926" alt="Screenshot 2020-02-16 at 22 51 01" src="https://user-images.githubusercontent.com/19776691/74613593-1614a600-5110-11ea-9348-cfaa1c838472.png">

**Comment by mmcguill** [comment]
OK, thanks for all the suggestions!

**Comment by strongbox-mark** [comment]
Hi @dan-el - I think this one is stale now with the release of the NextGen UI.
