### ISSUE TITLE
Feature request : Add refresh option in Database picker 

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#278]
Option 1  via a new Symbol/Button
Option 2 via a pull down gesture in database picker

**Comment by mmcguill** [comment]
The idea here is to refresh what?

**Comment by F3000** [comment]
The database file e.g. from iCloud etc... 

So a user can force think the database

**Comment by mmcguill** [comment]
Understood. At the moment this might not make sense but with Background Refresh/Fully Local Copy & Sync coming up it will. Thanks.

**Comment by F3000** [comment]
What do you mean with local copy and sync ?

**Comment by F3000** [comment]
Just found this . It’s similar to my issue.....
https://github.com/strongbox-password-safe/Strongbox/issues/221

**Comment by mmcguill** [comment]
Yes, looks like a duplicate. Thanks.
