### ISSUE TITLE
Feature request : Display icon for Passwort weakness

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#279]
An example zu can find in the attachment. Following colors exist : 

Red = weak
Orange =  not so weak
Yellow = medium
Light green = good 
Dark green = very good

You can also implement this into the the password generator 

![FA71AA82-310D-482B-A883-87115C1A4D2D](https://user-images.githubusercontent.com/8161283/74783502-2068a880-52a6-11ea-8032-849ef713299a.jpeg)

**Comment by mmcguill** [comment]
Yes, it's a great idea but a duplicate of #19 I believe

**Comment by F3000** [comment]
Yes that’s right . It’s a duplicate
