### ISSUE TITLE
iOS 9 Support

### ISSUE THREAD

**Issue by BuongiornoTexas** [strongbox-password-safe/Strongbox#280]
Hi, 

I'm trying to use Strongbox on an old iphone and ipad (4S, ipad 3), both running IOS 9.3.6 after checking it out on my partner's newer hardware (It's an excellent app - thanks very much!). 

The app store has allowed me to install version 1.44.4 as the most recent version that supports my devices. When I start it up, the strongbox bluescreen/padlock flashes up briefly and disappears. If I try app switching, I can see the bluescreen/padlock, but if I switch to it, it flashes up and disappears again. I have tried restarting both devices with no effect. 

I'm guessing that this may be related to the 1.44.3 release with the comment that it has "Less severe version checking". If this is the case, is there any chance of reverting to the more severe version checking for IOS 9? (I'd be happier to take an older versions that works). 

I also understand that this may be a big ask for supporting older hardware, and I'd be equally happy to see this closed as "Will not fix" or similar.

Thanks again for a great app!

**Comment by mmcguill** [comment]
Hi @BuongiornoTexas - Thanks for raising. 

Unfortunately as you've suspected it's hard to prioritise anything on iOS 9... This wasn't done on purpose, Strongbox used to run just fine, but with XCode 11/iOS 13 something shifted/changed on Apple's side - completely disabling iOS 9. This is something that could possibly be fixed up, there is probably a way. It appears to be something to do with libraries/dependencies.

It's just that I haven't had the time to look into what on Earth is causing the issue, and so I explicitly removed support for iOS 9 in the Metadata. It would be easy to switch it back on if the bug can be identified/fixed. 

Thanks for the kind words about the App! :)

We can leave the issue open here for others/and to track, perhaps if I get a minute this could be an easy fix.

**Comment by BuongiornoTexas** [comment]
Hi Mark, 

Thanks for the very quick response. 

I've run into similar problems with other apps. These have often been resolved by the developer limiting the version on  the app store to an older one that works reliably with IOS 9 (so for StrongBox, I'd assume this was something a bit older than 1.44.4, which is the version the app store insists on installing for IOS 9). 

If this is something you would contemplate and you know which is the last version that worked reliably with IOS 9, I'm happy to spend some time digging to find the mechanism to link app version to IOS version. (Could take a while though - I know sweet bugger all about the app store and its mechanisms!).

**Comment by mmcguill** [comment]
I'm afraid this one snuck up on me so I don't know which was the last functioning version... It was definitely earlier than 1.44.4, possibly a good bit earlier. I only found out about it through an email/support complaint.

The problem now is that Apple don't really allow for rollbacks or editing old releases. So a full code-level patch and rebuild would be required here, as far as I can tell (happy to be corrected here!). 

Sorry, that's not exactly great news.

**Comment by BuongiornoTexas** [comment]
Thanks Mark - that's a clear explanation of the issue. 

I'll stick with my current solution and keep an eye on this thread.

**Comment by strongbox-mark** [comment]
This should be working again on iOS 9 with the release of 1.50.5. Appreciate if you could confirm and close.

**Comment by BuongiornoTexas** [comment]
Hi Mark, 

Thanks very much for resolving this issue - Strongbox is now working on IOS 9.3.6 on both iPad and iPhone. 

I have found two minor issues that I'll report here for completeness. 

1) The "Statistics & Properties" menu item causes an immediate crash. I will email a crash report if you want to investigate further.

2) The back arrow on individual key entries ("<") is slightly obscured by key titles, and can be quite hard to activate. I suspect this is down to the interface being setup for higher resolution devices by default. 

Neither of these impact usability in a meaningful way (especially given you are supporting devices a decade old here!), so I'm going to mark this issue as closed. Please re-open if you would want to keep these issues live. 

Thanks again, 

Larry

**Comment by strongbox-mark** [comment]
Thanks @BuongiornoTexas - Please do email the crash report. I'll see if there's a quick fix for the Back button but good news! :)
