### ISSUE TITLE
Use SF Symbols on iOS 13 +

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#283]
More Information you can finde here : 
https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/

You have to install a little Programm where you can drag the icons into Xcode. 

Most modern apps use these icons for the UI icons (settings etc...) .  

Also you can add these icons beside the standard Keepass icon pack for picking an new logo for an entry . 

The SF Symbols working on your Mac App too

**Comment by mmcguill** [comment]
Yes, would like to do this and have already looked at it. 

However I need to map 50+ icons from KeePass to SF Symbols and some just don't really work. For example I've struggled for these 2 amongst others.

C08_Socket
![image](https://user-images.githubusercontent.com/344791/76145292-8fa51180-6088-11ea-9c18-e020acd35c27.png)

C10_Kontact
![image](https://user-images.githubusercontent.com/344791/76145295-99c71000-6088-11ea-8900-c6c7979d4b22.png)

etc. 

If you want to help, you can map the existing set (full list [here](https://github.com/aramrami/KeePass-2.41/tree/master/Ext/Images_Client_HighRes)) to the corresponding SF Symbol set then send them my way! :)

Currently have the first 8 or so like this:

"lock",
"globe",
"exclamationmark.triangle",
"hifispeaker",
"pin.circle.fill",
"message.circle.fill",
"cube.box.fill",
"square.and.pencil",

**Comment by F3000** [comment]
I have a look . So you would only need the names of the new ones ? 

Maybe you can combine it . 

When you can’t find a good replacement leave the old . 

Or for people who like the standard iconset of keepass they have an option to choose a logo as this is implemented at the moment

**Comment by mmcguill** [comment]
Yeah, not going to accept partial, need full set of nice flat icons/glyphs.

There will be an option to use old KeePass style (as it currently is) and new modern flat glyphs.

Yep, all I need is the name.

**Comment by F3000** [comment]
@mmcguill 
So i have checked the icons and found most of them. Some like the Apple Szmbol you can use the Unicode standard like „“
 
Here is the list:


- C00 password 
    - mappin
    - mappin.circle
    - mappin.slash
    - Lock
- C01 package_network
    - globe
- C02 messagebox_warning
    - exclamationmark.triangle
- C03 Server
    - cube.box.fill
    - cube.box
- C04 Klipper
    - bookmark
    - Bookmark.fill
    - rectangle.and.paperclip
- C05 EDU
    - rectangle.stack.person.crop
    - rectangle.stack.person.crop.fill
    - person
    - Person.fill
- C06 KCMDF
    - hexagon.fill
- C07 Kate
    - square.and.pencil
- C08 Socket
    - 
- C09 Identity
    - rectangle.stack.person.crop
    - rectangle.stack.person.crop.fill
    - person.2.square.stack
    - person.2.square.stack.fill
- C10 Kontact
    - 
- C11 Camera
    - camera.circle
    - camera.circle.fill
    - camera
    - camera.fill
    - camera.on.rectangle
    - camera.on.rectangle.fill
- C12 IRKickflash
    - antenna.radiowaves.left.and.right
    - dot.radiowaves.left.and.right
- C13 KGPG
    - lock.shield
    - lock.shield.fill
- C14 Laptop Power
    - 
- C15 Scanner
    - tray
    - tray.and.arrow.down
    - camera.viewfinder
- C16 Mozilla Firebird 
    - 
- C17 CDromm
    - circle
    - stop.circle.fill
- C18_Display
    - tv
    - tv.fill
    - tv.circle
    - tv.circle.fill
    - desktopcomputer
- C19 Mail_generic
    - envelope.open
    - envelope.open.fill
- C20 Misc
    - gear
- C21 Organizer
    - 
- C22 ASCII
    - 
- C23 Icons
    - calendar
- C24 Connect_Established
    - bolt
    - bolt.fill
- C25 Folder_Mail
    - folder
    - folder.fill
- C26 FileSave
    - 
- C27 NFS
    - Server
- C28 Message
    - message
    - message.fill
    - message.circle
- C29 KGPG_Terminal
    - calendar.badge.minus
- C30 Konsole
    - Calendar 
    - text.bubble
- C31 FilePrint
    - printer.fill
    - printer
- C32 FSView
    - app
- C33 Run
    - arrowtriangle.right.square
    - arrowtriangle.right.square.fill
- C34 Configure
    - wrench
    - wrench.fill
- C35 KRFB
    - desktopcomputer
- C36 Ark
    - 
- C37 Percentage
    - percent
- C38 Samba Unmount
    - Server
- C39 History
    - clock
    - clock.fill
- C40 Mail Find
    - magnifyingglass.circle
    - magnifyingglass.circle.fill
- C41 VectorGfx
    - 
- C43 Trash
    - trash
    - trash.fill
    - trash.slash
- C44 Notes
    - t.bubble
    - t.bubble.fill
    - text.bubble
- C45 Cancel
    - multiply
- C46 Help
    - questionmark.circle
    - questionmark.circle.fill
- C47 Package
    - archivebox
    - archivebox.fill
- C48 Folder
    - folder
    - folder.fill
- C49 Folder open
    - folder.badge.plus
    - folder.badge.plus.fill
- C50 folder Tar
    - folder.badge.plus
    - folder.badge.plus.fill
- C51 Decrypted
    - lock.open
    - lock.open.fill
- C52 Encrypted 
    - lock
    - lock.fill
- C53  Apply
    - arrow.up.right.circle
- C54 Signatur
    -  pencil
- C55 Thumbnail
    - book
- C56 AdressBook
    - book.circle
    - book.circle.fill
- C57 View Text
    - square.and.pencil
- C58 KPGP
    - 
- C59 Package Development
    - hammer
    - hammer.fill
- C60 kfm Home
    - 
- C61 Services 
    - lightbulb
    - lightbulb.fill
- C62 Tux
    - 
- C63 Feather
    - 
- C64 Apple
    -  
- C56 W
    - w.circle
    - w.circle.fill
- C66 Dollar_Sign
    - dollarsign.circle
    - dollarsign.circle.fill
- C67 Certificate
    - rosette
- C68 Smartphone
    - phone
    - phone.fill

**Comment by mmcguill** [comment]
Thank you @F3000 - I worked on this a few days ago and came up with my own set, but this is very helpful! I'll check them out for sure. Look out for them in the next release.

**Comment by F3000** [comment]
@mmcguill  does tour set also exist from the SF symbols or do Zuordnen have mixed the icon set with self created icons ?

**Comment by mmcguill** [comment]
Hi @F3000 - I don't have any mixed/self created icons. Unfortunately I can't use the Apple symbol you suggested for a technical reason...

**Comment by F3000** [comment]
I have installed the latest update . Looks good 👍

Do you plan to also use SF symbols for all other menu icons (e.g. settings etc)

**Comment by mmcguill** [comment]
I wasn't planning on that no. SF Symbols are only available on iOS 13 whereas Strongbox supports iOS10+. Going to close this one out now.

**Comment by F3000** [comment]
He closing is ok . Is it possible for a developer that when a iOS device is on iOS 13 or newer the app shows  SF Symbols and on older versions the standard icons ?

Or is that to much effort for a maybe not so imported function ?

**Comment by mmcguill** [comment]
Yes, that's right. Most of your issues are cosmetic, and they're nice to haves, but they cost development time and I think most users want more functionality over prettier icons, or at least that's the assumption I'm working under and it's also my own preference for the direction of development.

**Comment by dan-el** [comment]
I prefer features over cosmetics any time and also happen to prefer the classic keepass icons - just too many memories.

Strongbox is a great app, but still has a way to go feature-wise. So as long as the UI is functional the focus should be features.

My 2 cents.

**Comment by mmcguill** [comment]
Thanks @dan-el - Curious to hear your thoughts on the most important non UI features you would like to see.

**Comment by F3000** [comment]
@mmcguill  please don’t understand it in the wrong way. I don’t want to prescribe you what you should do 👍 ☺️You are the developer and I think compared to other (keepass)password managers strongbox is a really great alternative .

I just post just my findings (also small) here as a an issue .

**Comment by mmcguill** [comment]
Yep, thanks @F3000 - Just letting you know where the priorities lie :)
