### ISSUE TITLE
iOS Bug :  Some areas of the app text looks messy in German translation

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#284]
First example in the following picture : 

Green = line height is not the same as on the other lines 
Red = the text is shortened . Do you have planned this ?

![2BC56E95-0E73-4B46-9E06-A04700E6D04E](https://user-images.githubusercontent.com/8161283/75121123-6c925f00-5691-11ea-8d26-eb38938bf32a.jpeg)

Please see this issue as a collection for more German issue in the future when i find some :) (i will add these here)

**Comment by mmcguill** [comment]
Thanks @F3000 - You can suggest localization fixes if you like via CrowdIn - mail me if you'd like to be added to that system, and we can work on it there. Going to try to keep this repo for non localization related changes for now.

**Comment by F3000** [comment]
Ok . You have a mail
