### ISSUE TITLE
Colorize Password Fields

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#286]
A user can better see the difference between lower/capital letters etc... 

![4A331C26-F9FD-461C-8965-387943CC18A3](https://user-images.githubusercontent.com/8161283/75296949-ddbb4900-582e-11ea-95bb-136f7a3c5a93.jpeg)

**Comment by dan-el** [comment]
Thanks @mmcguill for this - very convenient!

I was wondering if you could choose a "barrier free" color palette to also serve color blind users. I am not an expert on this subject but had to give it a thought in a personal project in the past. Something like this maybe: https://thenode.biologists.com/data-visualization-with-flying-colors/research/

I ended up using these colors:
- 255,0,0 (red)
- 255,255,0 (yellow)
- 0,255,255 (turquoise)
- 0,0,255 (blue)

**Comment by mmcguill** [comment]
Thanks @dan-el - I actually did consider this but ended up going down a rabbit-hole trying to find a good palette that worked well in Dark/Light mode on iOS - In the end I had to cut my efforts short and go with simple system colors... 

Using your suggested colors looks like this on a light background:

<img width="237" alt="image" src="https://user-images.githubusercontent.com/344791/75960799-0b546200-5ec1-11ea-8c21-0165e4a7c751.png">
<img width="187" alt="image" src="https://user-images.githubusercontent.com/344791/75960858-2626d680-5ec1-11ea-9d3e-201bf1072728.png">

which I don't think looks great... 

However I just took some time to play around using some of the colors from your link above and changing some for dark mode:

<img width="330" alt="image" src="https://user-images.githubusercontent.com/344791/75963244-6ab47100-5ec5-11ea-8d63-b2311146e8e5.png">

<img width="324" alt="image" src="https://user-images.githubusercontent.com/344791/75963342-96cff200-5ec5-11ea-8701-9dba3b9a4e55.png">

I think the following looks reasonable... happy to hear your thoughts...

Re: Mac app - yep, on the way.

**Comment by dan-el** [comment]
I agree, my color palette looks awful there. Please don't do that :-)

Your examples for light and dark mode look pretty good. Just not sure about the blue in dark mode. Imagine your screen brightness is set to low - it might barely be visible. Maybe use rather "bright" colors in dark mode, and rather "dark" ones in light mode if possible.

There is of course also the option to define a few light mode and dark mode palettes and let the user choose from settings with a default value that serves all users well. Sounds like overkill to me for just password coloring...

If, of course, you were to expand that color palette idea also to
- colored password strength indicator
- coloring http and https in URLs to alert users of good and bad links
- alert or info boxes within the app (iOS and macOS)
- etc.

the settings option makes a whole lot more sense. It's a long shot and probably requires additional work under the hood, but sounds like a good idea if you plan to make your app more accessible overall. You would have an ALERT color, and INFO color, a SECURE color, an INSECURE color, etc. -- in short **theming support** for your app.

**Comment by mmcguill** [comment]
OK, thanks for the hints and suggestions @dan-el

**Comment by mmcguill** [comment]
I think we're good to close this one out now...

**Comment by aglasson** [comment]
Just adding my 2c after the fact. This has become probably my favorite new feature of Strongbox. Just trying to work out how I can add this KeePass now. Keep up the incredibly great work you're doing Mark. More donations your way soon I thinks.

**Comment by strongbox-mark** [comment]
Thanks @aglasson
