### ISSUE TITLE
Upgeade Screen UI Improvements

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#287]
See pictures:

![796A00C9-14D2-4B99-A32C-CDC7EF2C5D5C](https://user-images.githubusercontent.com/8161283/75297152-5ae6be00-582f-11ea-9b73-f5dc6cc3f599.jpeg)

This screen is from the keyfile management:
![754517FE-2C56-429D-8CE6-E1EA839C046F](https://user-images.githubusercontent.com/8161283/75297161-5fab7200-582f-11ea-9afd-224f7abe4af3.jpeg)

**Comment by mmcguill** [comment]
This is fixed now in 1.46.8

**Comment by F3000** [comment]
In version 1.46.8 i see the same when i want to add the key file. 


I cant open the „upgrade“ screen again because i have bought it :)

**Comment by mmcguill** [comment]
Thanks @F3000
