### ISSUE TITLE
Feature request : Show Entropie in “Bit“ in password generator 

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#289]
Example see picture : I have marked a possible location for this 

![5CDE5080-A5D1-4029-A1CA-55007773D18C](https://user-images.githubusercontent.com/8161283/75497247-f6a93300-59c3-11ea-9ede-3224b7c75323.jpeg)

**Comment by mmcguill** [comment]
I think this is or will be covered by #19

**Comment by F3000** [comment]
Yes that’s correct 👍
