### ISSUE TITLE
Add 'Cancel' button in WebDAV configuration screen

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#291]
I’m stuck in that screen . Only app restart brings me back to the main screen. 

Green circle: suggestion for place here the back button . 

Red circle : wrong text layout 

![31EFCFB2-2BF9-4F16-8079-FA6957BDD15F](https://user-images.githubusercontent.com/8161283/75712953-2a889f00-5cc9-11ea-8815-ed196be1bc9a.jpeg)

**Comment by mmcguill** [comment]
You can hit "Abbrechen" here to exit, or swipe to dismiss, no?

**Comment by F3000** [comment]
Swiping doesn’t work for me (iPhone 11) 

two hours later I have figured out that only “Abbrechen” is working 😊

**Comment by mmcguill** [comment]
Swiping down doesn't work for you?

**Comment by F3000** [comment]
I got it 🤦‍♂️

That was easy
