### ISSUE TITLE
Keyboard hides initial auto fill popup (German)

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#292]
See picture : 

![65E9DE6A-2C31-43FC-8A8F-2A14541D028B](https://user-images.githubusercontent.com/8161283/75713261-cdd9b400-5cc9-11ea-861f-433fedac7026.png)

**Comment by mmcguill** [comment]
This is an issue but relatively minor, that popup is only displayed once on initial launch.

**Comment by strongbox-mark** [comment]
This is no longer shown in Auto-Fill as of 1.49.4 - so no longer an issue 👍
