### ISSUE TITLE
Use Large Titles in some contexts

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#293]
I’m not an iOS developer so I don’t now exactly the term . 

I mean the title bar of a view controller looks on newer iOS version different than yours:

Here is an example : 

Here is a new styled title bar . The red arrow shows that there is more space. 

![E08D4B02-9628-4B9B-8085-42CF5610C150](https://user-images.githubusercontent.com/8161283/75715239-61f94a80-5ccd-11ea-9ddb-98082d07bbdf.jpeg)

And here is it from your app . I think that this is pre iOS 12 design guidelines .

![2CD41B51-742A-48BA-8B08-9681635F33E8](https://user-images.githubusercontent.com/8161283/75715084-1e064580-5ccd-11ea-9fe2-482ba60594f2.jpeg)

Would be cool when you can implement some new apple design guidelines in your app 👍

**Comment by Slummi** [comment]
I can‘t really comprehend your example, because there are a cloud icon and a +-button between the iOS title bar and the headline. If you remove both, the spacing between title bar and headline won’t be larger than in the Strongbox example. So I think the examples aren‘t comparable.

**Comment by F3000** [comment]
I mean that in general . Apple introduced the “new” layout for all of his apps . 

Look at the Native settings app . That’s a better example . 

At the top there is a big headline , after that the content

**Comment by mmcguill** [comment]
So you can read the Apple guidelines for this here:

https://developer.apple.com/design/human-interface-guidelines/ios/bars/navigation-bars/

As you can see this is not a requirement but very context specific. In some cases it's nice and makes sense, in others it gets in the way...

You can suggest certain views that this might look well in (Preferences perhaps would work), and I'll consider it here, but the view you've given as an example (this is the Browse view) is not one I would consider as a great place for a large title.

Also, with the greatest level of respect, I'd ask that you please read the Apple Human Interface Guidelines before suggesting others do so and before requesting UI changes like these.

Thanks!

**Comment by mmcguill** [comment]
Closing out - no specific conclusions/actions to be taken here
