### ISSUE TITLE
Allow arrow keys to navigate search results

### ISSUE THREAD

**Issue by rob3c** [strongbox-password-safe/Strongbox#294]
I love the additional search flexibility in Strongbox now. Often my searches result in multiple results, as intended by my use of keywords/tags/etc.

I tend to prefer keyboard vs mouse interactions whenever possible on desktops, and it would be a nice additional tweak if we could use up/down arrows to select among search results instead of having to select them with the mouse. Right now, you have to tab a bunch of times to get to the results. I'd prefer if the up/down keys would navigate the results while the search box remains active (i.e. trap arrow keys while the search box remains focused.)

Thanks in advance!

**Comment by mmcguill** [comment]
Sounds like a good idea!

**Comment by F3000** [comment]
Hopefully with iOS 13.4 Apple publishes some enhancements for keyboards under iOS and ipadOS. (keyboard press event) 

When you have not included it in iOS yet , maybe the feature from @rob3c  can also be included for iOS 👍

**Comment by mmcguill** [comment]
@rob3c - The down arrow should now take you to the search results (if any) immediately. 

Can you confirm and close?

**Comment by rob3c** [comment]
@mmcguill It works great - thanks! I use Strongbox every day now, and this is already streamlining the experience.

I originally thought I'd want the search box to remain active, but your implementation that moves focus to the results with the arrow keys also allows additional search refinement with the keyboard. I can always jump back up quickly with CMD+F and not lose my search text.

Also, completely unrelated to this issue: thanks a ton for the TOTP support! I've already suffered through the pain of using device-specific apps and then having the devices die suddenly. Now, it's a non-issue - just install Strongbox on the new device, and everything just keeps working 👍

**Comment by mmcguill** [comment]
Thanks! Glad to hear it's working a bit better, and yes, I use TOTP myself, v. handy :)

**Comment by rob3c** [comment]
I noticed that the new version doesn't immediately focus the search box when you log in as it used to. Is that new behavior a byproduct of this new feature's implementation, or is it due to something else? It's easy enough to hit tab or cmd+F, but I was surprised by the change. I can't really tell what has initial focus, actually.
