### ISSUE TITLE
Feature request : iOS autofill should search not only in one database 

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#295]
Maybe this is already implemented ... 

Example : I have two databases in Strongbox. One personal and one for work . 
The privat one is set to open automatically when I open strongbox. 

When I visit a website where I have only one entry that is saved in in the work database , I open the app and copy the password etc. manually . 

Would be cool when this possible

**Comment by mmcguill** [comment]
So, I'm not clear what is being requested here...

Do you mean in the QuickType AutoFill context (e.g. a suggestion above keyboard in Safari) you get suggested 1 entry? If so that should just work when you tap on it.

**Comment by F3000** [comment]
Ok „QuickType“ is the correct word for that (just learned something ☺️) 

Does “quick type” searches all databases for a possible entry or only one database ?

**Comment by mmcguill** [comment]
Yep, all of those that are Auto-Fill enabled

**Comment by F3000** [comment]
All right .  I think you can close the issue

**Comment by mmcguill** [comment]
Cool, you can close issues yourself too! :)

**Comment by F3000** [comment]
In the mobile App i don’t have the Feature . Only in web view :) 

Next time
