### ISSUE TITLE
Make the buttons for “generate alternate strings” more meaningful

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#296]
When you look first time on this view it is unclear which button is for what 😊
A user find this out only through the try and error method 

![77FF8EE7-80D8-4628-A0AF-9E29D91F332F](https://user-images.githubusercontent.com/8161283/75914280-c72b7800-5e54-11ea-8949-8e9c7104b7f6.jpeg)

**Comment by mmcguill** [comment]
I'm afraid I'm struggling to come up with a good way to do this. If you have a suggestion (in detail) I'd be happy to consider it. Otherwise, trial and error isn't the worst way for a user to discover something cool like this...

**Comment by mmcguill** [comment]
Closing out, as I don't think there's much actionable here
