### ISSUE TITLE
Color Palette for Colored Passwords Feature

### ISSUE THREAD

**Issue by shad0whawk** [strongbox-password-safe/Strongbox#298]
I love the new colored passwords feature you added. It’s makes reading a password much easier and is similar to one of the plugins I use with Keepass. I liked the original color scheme much better than the softer pastels in the latest implementation. I understand why you changed it, but I found the first version with the darker reds and greens easier to read. The soft blue (symbols) and lighter black (lower case) are too similar in my opinion. Is it possible to you make the type of color palette a user option?  

Also, if you switch between light mode and dark mode manually with the app open, the color palette doesn’t always update correctly automatically until you hide and unhide the password value.

**Comment by mmcguill** [comment]
Hi @shad0whawk - yes, I have been experimenting with this and I sort of feel the same. The latest palette is colour blind friendly but just doesn't look as well as the original bright colours I think. 

So I think I will restore the brighter colours and insert a Colour-Blind friendly switch/preference to use the current ones.

**Comment by shad0whawk** [comment]
Thanks is for adding this option. I appreciate it! I’ll close this out.
