### ISSUE TITLE
Bug ? : During scrolling the item list isn’t scroll smoothly 

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#300]
Hi, 

I have noticed that randomly...  when i scroll the item list the movement is not as smooth as in other apps . 

Is it possible for you to optimize something ?  I cant record this behavior :(

**Comment by mmcguill** [comment]
This will be fixed in the next build or two. Fairly straightforward performance fix.

**Comment by mmcguill** [comment]
Wow you're fast, how do you get updates so quickly?

It was a simple enough fix, glad it's working.

**Comment by F3000** [comment]
Maybe the Apple server in Germany are fast or I was at the right time in the store ☺️
