### ISSUE TITLE
Feature request: Integrate popular Item icons 

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#302]
Instead of downloading every time a favicon the app could check , if the user adds e.g. a Facebook login and loads a predefined logo .

On small sites that a nit popular sites ... blogs etc.. here the app loads the the favicons as the same way as now

**Comment by mmcguill** [comment]
I think you are suggestion keeping some popular icons around/cached? 

If so, I don't think this is something I want to add.

**Comment by F3000** [comment]
Yes that right.

**Comment by mmcguill** [comment]
OK, I'm going to close this as won't fix. I don't see much upside here.
