### ISSUE TITLE
invalid database

### ISSUE THREAD

**Issue by fmms** [strongbox-password-safe/Strongbox#303]
Hi,

I have been using Keepass, KeepassX and KeepassXC for a long time on a windows notebook.
Today I tried strongbox on my iPhone.
However, I was not successfull. Neither opening the old historic file, nor opening a freshly created one.
Currenlty I am running KeePassXC 2.5.3.

The error message seems to have improved compared to the previously reported #23, #37, #238 .

![image](https://user-images.githubusercontent.com/908734/76700186-6a7e5780-66b5-11ea-8732-269ba091a3c2.png)

How do I have to configure KeepassXC to produce files that are compatible with Strongbox?

Thanks for your help
Felix

**Comment by mmcguill** [comment]
Hi, they should be compatible always, out of the box. What Strongbox is receiving there in terms of bytes is not a valid KDBX.
I've seen this before and it's usually to do with the OneDrive app sending incorrect data via the iOS Files system.

Are you using Files via the OneDrive app to access your database? If so can you try native OneDrive support or copying locally or to another cloud and see if that works for you

**Comment by fmms** [comment]
Hi @mmcguill,

I have been using the native OneDrive App opening the file there allows one to copy it to Strongbox.

As you suggested it might be OneDrive I have saved  the file on my phone from OneDrive to Files.
I tried to store it there locally and in iCloud.

Opening the file from Files either way gives exactly the same error.

regards

**Comment by mmcguill** [comment]
I don't think that will work either, as you're still going via the OneDrive app and Files which I believe is the issue. 

Can you copy the file from your laptop (where it works) into iCloud directly? Or you can use File Sharing or use Add Existing > Over Local Network in Strongbox to copy across.

Alternatively you can use Strongbox's native SDK integration, Add Existing Database > OneDrive > Sign In > Browse to your Database > Add

**Comment by fmms** [comment]
Thanks for your quick response @mmcguill .
The problem is indeed that my phone is managed via Intune. And thus the file has the following header:
![image](https://user-images.githubusercontent.com/908734/76702387-b5a26580-66c9-11ea-9ce4-0554a5519ea8.png) 
This is explained for example at https://social.technet.microsoft.com/Forums/en-US/94b9880d-fc2c-47e5-8d4d-eefcc72b66cc/intune-mam-allow-app-to-transfer-data-to-other-apps-policy-not-working-for-excel-in-ios?forum=microsoftintuneprod 

It would be cool if the App would recognize this MSMAMARPCRYPT header and inform users correspondingly.
I cannot user your native SDK integration as this requires Tenant Admin approval.

**Comment by mmcguill** [comment]
Yes, not a bad idea at all, I'll try add a little message about this.

Sorry you can't use native SDK or OneDrive app in that case, you will need to find another way.

**Comment by mmcguill** [comment]
Could you download the latest version from the App Store and see if you get an appropriate message now? Would be great to test this in the real world.

**Comment by fmms** [comment]
Currently I have version 1.46.8 which does not give a new error message yet. Which version contains the fix?

**Comment by mmcguill** [comment]
1.46.8 should have it, what message do you get? same as originally?

**Comment by fmms** [comment]
Hi @mmcguill ,

sorry, I have validated it. iOS did not update the app yet.
Now it is updated and working perfectly:
![image](https://user-images.githubusercontent.com/908734/77229674-7e332d80-6b8f-11ea-92d2-cf93659708ac.png)

regards

**Comment by mmcguill** [comment]
Awesome, thanks for the screenshot.

**Comment by Slummi** [comment]
Hi @mmcguill I think that string is missing on Crowdin and can‘t be translated.

**Comment by mmcguill** [comment]
Will add @Slummi

**Comment by artaparsi** [comment]
@mmcguill 
Hi Mark, 
I ran into this issue as well and I happen to be the Intune admin. I have access to modify the app protection policy to allow third party apps to read the encrypted data off the device.
For iOS devices I'll have to include a URL protocol as an exception string. Here is an example:
https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policies-exception#example
What would be the appropriate URL protocol that will allow StrongBox to open files?
Thanks,

**Comment by mmcguill** [comment]
Hi @artaparsi - good to hear the alert/info is working out there in the real world.

Re: The URL - I honestly don't know what this could be. I know URLs that are opened from the Files app look like:

file:///private/var/mobile/Containers/Shared/AppGroup/<GUID>/File%20Provider%20Storage/item%7C1%7CC2BB7ABA726F9E2A%2521677/database.kdbx

It looks like on Android you can specify a package name, on iOS this is probably equivalent to a Bundle ID. The Bundle ID for Strongbox is **com.markmcguill.strongbox**

It's not clear from Microsoft's site above how an app can register with them, but I'd be very open to trying to opt in somehow if there are any more details? I can't find anything obvious there.

**Comment by artaparsi** [comment]
Hi @mmcguill , 
The open in feature of iOS is also controlled in Intune and will filter out any apps that are unknow to Intune and not considered managed.
There is the option to register your app with MS and have it listed as one of the known Intune apps, but I don't know how long that process takes. Here is the link:
https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-get-started#if-your-app-is-internal-to-your-organization-and-will-not-be-publicly-available

based on the URL you provided above, I tried "file" as the protocol, the package name, the kdb and kdbx extensions, and any combination I could think of, but they don't seem to create exceptions in Intune. I'll keep digging.

In the meantime, I have allowed all apps to share Organization data in our own Intune tenant since this was for testing and demos only, but the workaround isn't something that can be recommended to clients.

**Comment by mmcguill** [comment]
Hi @artaparsi - Thanks for that. I've just had a read but I think perhaps if I need to register with Microsoft I also need to make code changes to Strongbox, to include their Intune SDK and that in itself is really non trivial (https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-ios).

Not 100% sure this is the case but it looks like it to me.

I wonder could you add Strongbox via InTune? https://docs.microsoft.com/en-us/mem/intune/apps/store-apps-ios

Maybe that would allow the data transfer? 

Feel free to drop me a line (mark@strongboxsafe.com) if you would like to talk further about this integration for you or your clients, I've done some work with InTune before.

**Comment by strongbox-mark** [comment]
Just in case others land here, you can find bundle ids and url scheme here:

https://strongbox.reamaze.com/kb/technical/what-is-strongboxs-url-scheme-and-bundle-id
