### ISSUE TITLE
Bug: on some entry’s I can’t open attachments 

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#304]
Hi ,

here are some screenshots : 

![30B1E47E-99A5-4A05-9511-ED59D686A71B](https://user-images.githubusercontent.com/8161283/76712925-4ce4d880-671d-11ea-9451-fff2b696b0ba.png)

The small thumbnail on the overview page is displayed correctly.

![2FC6A5BA-26A9-48F2-B41F-F457BB990EDE](https://user-images.githubusercontent.com/8161283/76712981-af3dd900-671d-11ea-9d70-ec09271d2f13.jpeg)

**Comment by mmcguill** [comment]
Yeah, this preview window is an Apple component and it doesn't know how to render your attachment. It may help if the attachment has an extension (.png or .jpg?). There's nothing that can be done here otherwise.

**Comment by F3000** [comment]
Ok . How can i change it ? I have imported it from the iOS native photos app .

Should i copy it to the Mac , rename it and put it back ?

**Comment by mmcguill** [comment]
Unfortunately you can't rename the attachment in app right now, but when you add the attachment you are prompted for a filename, here is where you could add a helpful extension

**Comment by F3000** [comment]
Thanks . Now it works . The last time I have have deleted the while field and replace it with my text :)
