### ISSUE TITLE
Preference: Do not colorize protected custom fields

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#305]
Nor sure if this is intended, but all "protected" custom fields display their contents in a monospaced and colored font now in both macOS and iOS versions of Strongbox.

Can we have an option to disable the coloring for custom field contents in case this behaviour is intended. Large notes in "protected" custom fields are pretty much unreadable. I know there is the regular "notes" field, but that one cannot be "protected" (aka. concealed)

**Comment by mmcguill** [comment]
Yeah, that's by design as you would expect protected fields to be password like. I can add a preference to turn this off. Let's use this issue then to track.

**Comment by dan-el** [comment]
Much appreciated as I often use the custom fields to store larger notes which I do not want to be visible while I browse my database - e.g. when I have somebody standing next to me.

**Comment by mmcguill** [comment]
Should be fixed for you in 1.47.3 - can you confirm/close @dan-el ?

**Comment by dan-el** [comment]
Preference item works. Thank you! Closed.
