### ISSUE TITLE
Bug: Text „create new entry“ is difficult to read in dark mode

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#306]
See that picture .. The dark blue letters on the dark background is in my opinion not the best color scheme.

What do you think about a light yellow/red color ?

![image](https://user-images.githubusercontent.com/8161283/77122242-68155800-6a3d-11ea-8cc2-22ee1922cfa8.jpeg)

**Comment by mmcguill** [comment]
I'd probably go with the same blue on the 'Abbrechen' button

**Comment by dan-el** [comment]
It's Dark Mode after all. The "Abbrechen" blue will be an improvement.

**Comment by F3000** [comment]
Yes that’s a good idea @dan-el

**Comment by mmcguill** [comment]
Fixed with 1.47.3

**Comment by F3000** [comment]
Much better . Thanks 👍
