### ISSUE TITLE
Bug: Version 1.46.8 display the database name in the titlebar cropped

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#307]
See an example in this picture :

![image](https://user-images.githubusercontent.com/8161283/77122614-58e2da00-6a3e-11ea-924f-8f83f32dca6f.jpeg)

**Comment by mmcguill** [comment]
Yeah, I have a small improvement on the way for this, but truncation is going to happen no matter what.

**Comment by F3000** [comment]
Thanks 👌
