### ISSUE TITLE
Small UI Bug :  Cropped text in icon picker screen

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#309]
You know me and here is a little UI Bug :) (so no high priority)

Look at the text above the icons . The sentences are cropped at the start and the ending.  

![image](https://user-images.githubusercontent.com/8161283/77123685-1ff83480-6a41-11ea-8531-9e8d7997e71d.jpeg)

**Comment by Slummi** [comment]
I‘ll try to shorten this. But I guess it will still be too long on smaller displays.

**Comment by mmcguill** [comment]
Yes, I can also add some limits/constraints so it truncates without overflowing but truncation will happen...
