### ISSUE TITLE
Autocorrect/Predictive Typing Does not Work in Notes Field

### ISSUE THREAD

**Issue by shad0whawk** [strongbox-password-safe/Strongbox#311]
Autocorrect (or predictive typing) does not work in the Notes field in the current implementation on iOS. I add a lot of text to this field and it’s annoying when I have to go back and edit text because a word is one letter off. Is it possible for you to add/enable this functionality?

**Comment by mmcguill** [comment]
Sounds like a bug, I'll get it fixed up in the next release.

**Comment by shad0whawk** [comment]
Awesome thanks!

**Comment by shad0whawk** [comment]
Seems to work great in the latest release! Thanks!
