### ISSUE TITLE
Feature request: Disable autohide of record when switching to another app

### ISSUE THREAD

**Issue by ronaldl** [strongbox-password-safe/Strongbox#312]
It would be good to add an option to disable autohiding open records if Strongbox is not in focus. There are times when I want to look a record (such as the notes field) while I'm entering data into a browser.

Strongbox 1.13.7 (2901)
macOS 10.15.3

**Comment by mmcguill** [comment]
Sounds reasonable! Thanks for the feature request

**Comment by ronaldl** [comment]
I noticed you labeled this with iOS. I'm actually reporting this issue on macOS.

**Comment by ronaldl** [comment]
Here's what I see when Strongbox is in focus and when I switch to another app:

![1](https://user-images.githubusercontent.com/7798849/78710681-9c589780-78ca-11ea-8d90-c5bce7b9beff.png)

![2](https://user-images.githubusercontent.com/7798849/78710704-a5e1ff80-78ca-11ea-9d03-f7255ec533c4.png)

**Comment by F3000** [comment]
@mmcguill  can you consider the iOS Plattform too ?

**Comment by mmcguill** [comment]
@ronaldl - Thanks, that's a bug for sure, hadn't noticed it.

@F3000 - Yes for sure

**Comment by mmcguill** [comment]
@ronaldl - This should be fixed for you in 1.13.8 now - Can you confirm and close?

**Comment by ronaldl** [comment]
I can confirm that the record is no longer hidden. The record seems to stay on top of other application windows though, is that expected? In the attached screenshot, Firefox is actually in focus but the record covers Firefox.

![Screen Shot 2020-04-22 at 9 52 49 PM](https://user-images.githubusercontent.com/7798849/80060576-c1acee80-84e3-11ea-896b-55d3fcb22ff7.png)

**Comment by dan-el** [comment]
This is a menu setting. Go check out "Float Details Window On Top" in the View preferences of the app. Also see #316

**Comment by ronaldl** [comment]
Thanks @dan-el, that was it. Closing out this issue.
