### ISSUE TITLE
Disable Handoff for clipboard

### ISSUE THREAD

**Issue by tobx** [strongbox-password-safe/Strongbox#314]
When copying a password and "Handoff" (Universal Clipboard) is enabled the clipboard gets copied to other devices automatically. E.g. an iOS app can read the password after it has been copied on a Mac.

This should be disabled for security reasons. E.g. KeePassXC disables Handoff when copying passwords. At least an option to disable this would be good.

More information about Handoff:
https://support.apple.com/en-us/HT209455

Universal Clipboard:
https://support.apple.com/en-us/HT209460

**Comment by milesmcclane** [comment]
There is an option to enable or disable this general settings. I actually requested the option to be added as originally the app didn’t support handoff at all. I find it useful to just use my phone to log in to various websites on my Mac.

**Comment by tobx** [comment]
Ok, this sounds good. It is definitely a great feature, but it comes with a security trade off. Anyway, I am not able to find it. Here are my general settings:

![screenshot](https://user-images.githubusercontent.com/6427718/78891324-a49a0980-7a67-11ea-9155-ea9cd3c998be.png)

**Comment by milesmcclane** [comment]
Ah, actually I was referring to the iOS version, I’m unsure of what the Mac allows at this time. @mmcguill?

**Comment by tobx** [comment]
Ok, I see, that is good, I have found the option on iOS (deactivated by default). So it would probably make event more sense to add the option also on the macOS version.

**Comment by georgesnow** [comment]
this is the swift version, but there is option for "current host only"

https://stackoverflow.com/questions/56904388/disable-universal-clipboard-temporarily

**Comment by georgesnow** [comment]
here is the objective-c from apple's development site:

https://developer.apple.com/documentation/appkit/nspasteboardcontentsoptions/nspasteboardcontentscurrenthostonly?language=occ

**Comment by mmcguill** [comment]
Hi, yes, good idea and should be relatively quick to implement on Mac. 

I think I'll also change the default as well to Disallow Handoff, seems like the right choice security wise.

**Comment by mmcguill** [comment]
Just to add that this is already disabled by default on iOS, so this is just a feature request for same on Mac

**Comment by strongbox-mark** [comment]
This one was added quite a while ago to MacOS, forgot to close this issue... doing so now :) Let me know if there's any problems.
