### ISSUE TITLE
missing German translation in “Add entry menu”

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#315]
See picture :

![image](https://user-images.githubusercontent.com/8161283/78930862-15abe200-7aa5-11ea-81ec-3fdcf83937df.jpeg)

**Comment by mmcguill** [comment]
Good catch, missed making this one localizable. It'll be available on CrowdIn to localize shortly. Thanks @F3000

**Comment by mmcguill** [comment]
Believe this is fixed @F3000 - Can you confirm and close?

**Comment by F3000** [comment]
Yes it is now in German . Thanks mark 👍
