### ISSUE TITLE
Feature Request: Add "always on top" option (macOS)

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#316]
Can we have an "always on top" View-Option for the macOS version? It would be nice since we do not have Auto-Type yet.

**Comment by mmcguill** [comment]
Hi @dan-el - I think this is already available for you:

<img width="289" alt="image" src="https://user-images.githubusercontent.com/344791/79456014-0f11f300-7fee-11ea-81af-6bd88be668c9.png">

Do you mean it should stay on top when you switch to another App?

**Comment by dan-el** [comment]
This is not what I meant. Sorry for the somewhat unprecise request description (I typed it on my phone on the go just to not forget about it)

What I want is that Strongbox always stay in the foreground when I switch to another app. On a small 13 inch screen like on my MacBook there is not always enough screen space to have 2 apps side-by-side - especially considering the minimum screen width Strongbox demands already by design (see [#275](#275 ) ).

So when I need to paste a username and password and TOTP into a web form for example I have to go back and forth between the browser app and Strongbox. Having Strongbox always on top would allow me to move it to the screen's edge so that just the part where I need to click on (the entry itself) would be "on top" even when I switch to the browser. That way I can easily copy-paste the needed data from Strongbox to the browser.

I know there are Trackpad gestures and keyboard shortcuts built into macOS already which do a similar job but I still think an "always on top" option would be nice to have. At least for me :-)

**Comment by mmcguill** [comment]
Right, got it. Good idea

**Comment by mmcguill** [comment]
This should be fixed in 1.13.8 - Can you confirm and close?

**Comment by dan-el** [comment]
Hi,

The details window of a single entry stays on top now - which means the menu option is now working as intended.
The whole app does not stay on top though. I often use keyboard shortcuts from the list entry in the main window.

**Let me further specify my request:**
*) the whole app should be able to stay on top with all its windows (main and details)
*) make this option configurable in the settings (i.e. add another option "Float Main Window On Top" or so)

thank you!

**Comment by ronaldl** [comment]
Just some feedback since this feature caught me off guard when I was confirming issue #312. Maybe this option shouldn't be enabled by default. Typically I don't expect applications to have windows that always stay on top of other applications. I think this is something that a user should choose to enable.

**Comment by mmcguill** [comment]
Yes, this feature needs to be redone. I think:

- It should be toggled by a Menu Item ('Always on Top') in the standard menu and not a 'Preference' in the Preferences window
- Default should be OFF
- It should apply to all windows (not details/main separately) to keep things simple

Let's keep this ticket open to track

**Comment by strongbox-mark** [comment]
Great to hear. Think this one can be closed out now, feature appears to be working well
