### ISSUE TITLE
Update OneDrive icon

### ISSUE THREAD

**Issue by juanbretti** [strongbox-password-safe/Strongbox#318]
Hello,
Could be considered to update the OneDrive icon?
Thank you!

![](https://hansbrender.files.wordpress.com/2019/04/blog-70.png)

**Comment by mmcguill** [comment]
For sure

**Comment by mmcguill** [comment]
This should be fixed for you in 1.47.5 available now. Can you confirm and close?

**Comment by juanbretti** [comment]
Perfect! Thank you.
