### ISSUE TITLE
command-D shortcut assigned to two functions

### ISSUE THREAD

**Issue by dkapitan** [strongbox-password-safe/Strongbox#319]
**Issue**
command-D shortcut is assigned to two functions:
- Edit item (shown in contextual menu upon right-click)
- Database manager

**Seen on**
- OSX 10.15.4
- Strongbox 1.13.7

**Comment by mmcguill** [comment]
Thanks, will change Edit Item (Item Details) to Cmd+Enter

**Comment by strongbox-mark** [comment]
This is done and I believe working ok... feel free to re-open if there's an issue...
