### ISSUE TITLE
Password Expiry

### ISSUE THREAD

**Issue by mmcguill** [strongbox-password-safe/Strongbox#32]
Both KeePass and Password Safe databases support the idea of password expiry. It would be good to display a warning, or perhaps a summary dialog of expired passwords.

**Comment by shad0whawk** [comment]
Any way to implement this in a way that we can also view and change it at the entry level?  That would be a nice feature to include along with the summary.

**Comment by mmcguill** [comment]
Along with this feature the following should be implemented:

- Show / Hide Expired Entries in UI or Search option (Hide by Default)
- Highlight Entries close to expiry in UI (Orange Title?)
- Ability to Edit expiry dates

**Comment by shad0whawk** [comment]
I’m curious to know where this falls on your current roadmap. I was updating a credit card entry today and realized that this is the only data attribute that I can’t update in Strongbox, but I can on a KeePass.

**Comment by mmcguill** [comment]
It's definitely on there but right now:

- Local / Group (Storage Options)
- Improved Password Generation
- Yubikey Challenge Response
- Browse Improvements (Recents/Favourites)
- Cryptomator Investigation Support
- Translations 

are I think a little more important, but that's a sort of a rough list, and it's sort of hard to say how much time all of these will consume

**Comment by shad0whawk** [comment]
Understood. I appreciate the update and insight into your roadmap. Thanks!

**Comment by Slummi** [comment]
Would be great to have the the expiry date in the entry's view, because it is the only KeePass default field, which you can neither see nor edit in Strongbox. Additional features based on the expiry date can be implemented later.

**Comment by shad0whawk** [comment]
Thank you for adding this small, but very useful feature! Tested it out and works great.  On suggestion, make it easy to set a date several years in the future by either adding a year option to the existing date settings, or allow users to type a specific date that Strongbox can use.

**Comment by shad0whawk** [comment]
Another suggestion, if the date on an entry is already set, then default the date ticker to that day which makes minor changes easy especially if the date is in the future (saves a lot of scrolling).

**Comment by shad0whawk** [comment]
BTW none of this is impossible in the current implementation, it would just save some clicks and fast scrolling.

**Comment by mmcguill** [comment]
For sure, noticed that it was awkward to do, expect separate date/time pickers in the next release

**Comment by Slummi** [comment]
Thank you for quickly implementing basic support of the expiry date!
I agree with the suggestions of shad0whawk, but for the first implementation it's absolutely ok.

**Comment by shad0whawk** [comment]
I like the changes. It’s very easy to set future dates now, and the date selector defaults to the current value which I think makes sense. Thank you!

**Comment by Slummi** [comment]
The current implementation (v. 1.35.0) of setting / editing the expiry date is very good! Thanks a lot!

**Comment by mmcguill** [comment]
Thank you, I'll keep this one open for some extra UI enhancements: 

- Show / Hide Expired Entries in UI or Search option (Hide by Default)
- Highlight Entries close to expiry in UI (Orange Title?)

**Comment by mmcguill** [comment]
Hi there. Do you mean like a push notification or something? Currently when you open the database it should show you entries close to expiry.

**Comment by xatage** [comment]
Yes, a push notification for﻿ any expiry﻿ or to be﻿﻿ expired﻿ password﻿ would be a nice feature.

**Comment by mmcguill** [comment]
I agree. Wonder if this can be done with Local notifications... Will investigate

**Comment by mmcguill** [comment]
Going to close this one out. Expiry Notifications should now fall under #277
