### ISSUE TITLE
FaceID error when creating new entry

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#320]
what does it mean ? 

I have seeing this after tipping “create new item” in safari 

![image](https://user-images.githubusercontent.com/8161283/79889317-23932880-83fe-11ea-8b80-79851b5da600.jpeg)

**Comment by mmcguill** [comment]
Hi, I'm not sure. Are you see this often?

You say you're seeing this after tapping Create New Item in Safari, but that can't be right? Isn't there something that happens in the meantime? Can you describe the exact set of steps taken to produce this error?

**Comment by F3000** [comment]
I see this after after trying to create an a new item via the native auto fill function from iOS . 

That was the same site like in my previous ticket . After typing in my database password I have never seen this again. 
I think this is the workaround .

In the last three month i have never seen the message except here :(

**Comment by mmcguill** [comment]
OK, I don't remember your previous ticket but can I ask, do this happen every time? Or only once in the last 3 months?

**Comment by F3000** [comment]
Only once 👍

**Comment by strongbox-mark** [comment]
Going to close this one, I don't think it's a Strongbox issue.
