### ISSUE TITLE
Strange behavior of “can’t find entry screen”

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#321]
Hi mark ,

today I tried to create new credentials for the website (pedelecforum.de) .
I created them over the popup menu (auto fill) over the iOS keyboard . 

In the First screen the strongbox extension recognize the site title correct . But can’t find any entry .
Until now all is correct .

![image](https://user-images.githubusercontent.com/8161283/79912432-4e8f7380-8422-11ea-85b2-f3b44f567d01.png)

I have clicked on “create new entry” . In the following screen the Site title is different . 
while a step back the title was recognized correctly. 

![image](https://user-images.githubusercontent.com/8161283/79912565-83032f80-8422-11ea-9a16-462fc0a3f388.png)

Do you see this behavior as a bug from the auto fill extension or only an specific issue with this site ?

**Comment by mmcguill** [comment]
Is the issue you are raising that the Title is "Www"?

**Comment by F3000** [comment]
> Is the issue you are raising that the Title is "Www"?

Yes . instead WWW , i think there should be the same title as the screen before . 

Right ?

**Comment by mmcguill** [comment]
Yeah, interesting, Strongbox is trying to be smart here but fails. Splits the host up on . and takes the first element (www)... 

Minor but worth fixing.

**Comment by strongbox-mark** [comment]
Should be fixed for you now @F3000 with 1.49.5 - can you verify and close

**Comment by F3000** [comment]
Hey ,


look at this video :

https://share.icloud.com/photos/02z3NEelRjWWwasM-9wGbiP0w

The page title is : mediengruppe 

But strongbox is taking "Intranet" as the name for the new entry .


Intranet is the first part of the URL . So I think he extracted this from the url

**Comment by strongbox-mark** [comment]
Yeah, it's pretty difficult actually to get what the title should be from a URL alone. There's no good way! I think there's not much more can done here. It's a best effort thing.

**Comment by F3000** [comment]
Sorry please ignore my comment above .

I have now revived the 1.49.5 update in the German store .

Now it works fine 👌

Many thanks

**Comment by strongbox-mark** [comment]
Excellent news! Thanks @F3000 - Closing out...
