### ISSUE TITLE
iOS audit configuration issues

### ISSUE THREAD

**Issue by Slummi** [strongbox-password-safe/Strongbox#323]
There are two issues with audit configuration (preferences view).

1. Automatic database locking doesn‘t work if you stay in the audit configuration screen. The database stays opened all the time even if you lock your device or send the app into background.

2. ‚Done‘ button is too close to the right edge compared to other screens.
![3FC32E3E-B5CA-431E-B271-AC0A0CD62B45](https://user-images.githubusercontent.com/42265381/80305849-c6152800-87bf-11ea-9f4d-62a7936c6170.jpeg)

**Comment by strongbox-mark** [comment]
Thanks @Slummi - Great feedback. I'll get these patched asap

**Comment by hcksw** [comment]
Hi Mark,

I noticed that if I disable empty password they still seem to be marked with an error. I believe it’s due to duplication, i.e. if I have two or more instances of empty password StrongBox views that as a duplicate! 

Great feature by the way.

**Comment by strongbox-mark** [comment]
Thanks for raising @hcksw - Fix on the way in the next release

**Comment by strongbox-mark** [comment]
This should be fixed now with 1.48.2 - could you confirm and close @Slummi

**Comment by Slummi** [comment]
Everything’s working now. Thanks for fixing!
