### ISSUE TITLE
Previous password not saved in Password Safe

### ISSUE THREAD

**Issue by Ben-Voris** [strongbox-password-safe/Strongbox#325]
In password safe format, and entry with two previous passwords saved and a maximum of six previous passwords, changing the password adds the new password to the previous password screen, but not the previous password. That is, the password that was just changed is lost.

I have replicated this with a new password safe database.

**Comment by strongbox-mark** [comment]
Sounds like a bug alright. I'll try get patched asap.

**Comment by strongbox-mark** [comment]
This should be fixed for you in 1.49.9 @Ben-Voris - Could you verify and close?
