### ISSUE TITLE
Unable to open DB using Key File

### ISSUE THREAD

**Issue by k8oi** [strongbox-password-safe/Strongbox#331]
Using 1.48.1

I am unable to open a DB on iOS using password, keyfile, and yubikey. I have eliminated the password and yubikey from this issue as if I pick one or both I can click "Unlock" and it fails to open the DB.

Whenever I attempt to use a Key File, I can click "Unlock" forever and it simply doesn't do anything.

**Comment by strongbox-mark** [comment]
HI @k8oi - Sorry about this, this is a bug in 1.48.1, a fix is on the way and is under review by Apple. I'd expect an ETA of around 6 hours at this point.

**Comment by k8oi** [comment]
Mark,
Thanks for the update - not a show stopper at the moment; I finally "upgraded" from an iPhone 6s to the SE2 and want to use the Yubikey NFC stuff...  I was fiddling around the key, yubikey, etc and thought I'd killed my existing key (overwritten it :) )

All's good - I love your product, get's all 5's from me!

---
Jim Bates
(804) 690-9143

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by strongbox-mark** [comment]
Thanks Jim, it only affects newly added databases using Key Files and only those who’ve updated to 1.48.1 but it’s still not not a great bug.

Thanks for the stars and enjoy the SE2! :)
-Mark

**Comment by strongbox-mark** [comment]
1.48.2 should be available for you now from the App Store with this fix

**Comment by k8oi** [comment]
Got v1.48.2 and all works as normal. Thank you!

**Comment by strongbox-mark** [comment]
Sweet, glad to hear it!

**Comment by spankywetfish** [comment]
Just installed this from the MacOS App Store, and it's still an issue.
Looks like ( at Version 1.13.9 (2911) ) the MacOS version is a few iterations behind?

![Screenshot 2020-05-14 at 12 53 36](https://user-images.githubusercontent.com/11835338/81931396-f0e5e580-95e1-11ea-8ec5-993dc41bc77e.png)

**Comment by strongbox-mark** [comment]
HI @spankywetfish - I think this will be a different issue.

Could you try:

1) Closing your database
2) Going to the Databases Manager (Cmd+D)
3) Find your database among the list and right (alternate) click
4) Select Remove

This will clear Strongbox's bookmark to your key file.

Now try opening your database, you'll need to select 'Browse' from the Dropdown and navigate to your key file.

Let me know how that goes

**Comment by spankywetfish** [comment]
The image posted previously was trying to add the xml-sample.key file to a new (test) database in order to change the master credentials.
I have also tried adding an existing database (one that is secured with a password and keyfile) to the DB manager and get the same error (after browsing for and selecting its keyfile).
This was all done on a fresh install of the app, so there would be no existing stongbox bookmark for the keyfile.

**Comment by strongbox-mark** [comment]
Weird, that does seem to be a bug then. Will investigate.

**Comment by strongbox-mark** [comment]
@spankywetfish Thus should be fixed for you now I'm 1.13.10 available on the App Store. Could you confirm?

**Comment by spankywetfish** [comment]
Just installed on a different machine, works a treat, thanks.
