### ISSUE TITLE
Auto-proceed AutoFill option

### ISSUE THREAD

**Issue by KoDoA** [strongbox-password-safe/Strongbox#335]
To speed up the process of AutoFill it’d be great to add new setting: whether AutoFill should auto-proceed when there is only one suitable entry.

**Comment by strongbox-mark** [comment]
Sounds like a reasonable request but I think it should be Opt-In and not on by default. Maybe Auto-Proceed after 500ms?

**Comment by KoDoA** [comment]
> but I think it should be Opt-In and not on by default
Agree.

> Maybe Auto-Proceed after 500ms?
The purpose of the Auto-Proceed is time saving. Delay is bad idea for me. If necessary maybe "Opt-In and not on by default".

**Comment by strongbox-mark** [comment]
This is available now with 1.49.5 under AutoFill Preferences (Open Auto-Fill and tap the Preferences icon (Gear))

Can you verify and close @KoDoA?

**Comment by KoDoA** [comment]
👍
