### ISSUE TITLE
Copy Password and Launch Url opens two Firefox windows

### ISSUE THREAD

**Issue by ronaldl** [strongbox-password-safe/Strongbox#337]
If Firefox is closed and I use the Copy Password and Launch Url option, two Firefox windows are opened. This option behaves normally if the Firefox application is already open (even if there are no open browser windows or tabs).

This may be a Firefox issue as I don't see this if my default browser is set to Chrome or Safari.

- macOS 10.15.4
- Strongbox 1.13.8 (2907)
- Firefox 76.0.1

**Comment by strongbox-mark** [comment]
HI @ronaldl - Yes this will be a Firefox issue, Strongbox just asks the system to open the URL in your default browser, from here it's over to the Browser.

**Comment by ronaldl** [comment]
Thanks @strongbox-mark. Closing issue.
