### ISSUE TITLE
iOS copy/move entry from database to another

### ISSUE THREAD

**Issue by georgesnow** [strongbox-password-safe/Strongbox#338]
I know in the macos version you added drag and drop between databases. I was wondering is it possible to add the ability to move or even copy an entry to another database? I have 2 dbs one personal and one shared. I saved an entry the wrong database and couldn’t get to my computer to move it.

**Comment by strongbox-mark** [comment]
Yes, interesting, and thanks for the suggestion. I mean it's definitely possible but I'm really not sure if it belongs in a mobile app... On the fence really here, apart from the fact it'd be a bit of a chunky piece of work for marginal value. Open to opinions...

**Comment by georgesnow** [comment]
well the other think of it is an import/export of entries. You offer an export option (although this would be specific entry or folder). I don't see import option though. So if you could export in a format that is easily importable. You could temporarily export and import to another database. Probably the same amount of work. but maybe more value to others if its import/export? I mean again it goes back to your question of it being in a mobile app. just throwing some ideas out

**Comment by chessgriffin** [comment]
This is a huge feature for me.  My wife and I each have separate databases and we'd like to share logins back and forth. Thanks.  Perhaps using the iOS share sheet.

**Comment by chessgriffin** [comment]
Just wanted to ping this feature request again.  Please consider adding this as a feature to Strongbox in the near future. Thanks!

**Comment by strongbox-mark** [comment]
Hi @chessgriffin - this is planned, and should be ready in the next month or so. It will allow users to copy entries from one database to another.

**Comment by chessgriffin** [comment]
\o/

Thanks! Very much looking forward to this feature.

**Comment by strongbox-mark** [comment]
Hi all, this is available now in 1.53.0. You now export items to other databases. Long tap on an item > Export Item. You can also select multiple items in "Select" mode, and export them. 

Please open new issues if you see any problems.

**Comment by chessgriffin** [comment]
I saw this feature added in the release notes when I updated the app - this is fantastic!  Thank you Mark.
