### ISSUE TITLE
Feature request: Add „cmd+f“ command on ios to open directly the search bar

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#340]
For me it is not possible to do tha with an external keyboard .

**Comment by strongbox-mark** [comment]
Sounds good. Not sure if Cmd+F will be available as might be used by system but will aim for that.

**Comment by F3000** [comment]
This command is app specific not global 👌

Apple uses this on the home screen for the spotlight search . 


At the moment I don’t use your Mac app but I can think that you can include it here to (when not already included) . 


Maybe other people can contribute some more suggestions for keyboard shortcuts ☺️

**Comment by strongbox-mark** [comment]
Hi @F3000 - Could you try out 1.50.1 and see if the Cmd+F works for you on your external keyboard?

**Comment by strongbox-mark** [comment]
@F3000 - Any luck testing this?

**Comment by F3000** [comment]
I can confirm that this is working now 👍
