### ISSUE TITLE
Can't open KDBX file created on Windows with Yubikey 

### ISSUE THREAD

**Issue by bone187** [strongbox-password-safe/Strongbox#341]
I updatet an existing database with enabled Yubikey support with KeePass 2.45 and the [KeeChallenge Plugin](http://richardbenjaminrush.com/keechallenge/) but I can not open the file with Strongbox. I already tried the recovery mode on the iOS device without no luck.
To test the recovery mode I tried it on my Windows system without any problem.

**Comment by strongbox-mark** [comment]
Hi @bone187 - I'm not sure that the KeeChallenge plugin is compatible with the "KeePassXC" method of Challenge Response.

Do you use a separate "Challenge" xml file alongside your database?

**Comment by bone187** [comment]
Hello @strongbox-mark thank you for your reply. Yes the extension uses an separate XML file.
So the solution is to use KeePassXC on Windows and not KeePass?

**Comment by strongbox-mark** [comment]
Yes, well it's up to you whether you'd want to do that but imho the KeePassXC has the advantage of not requiring this auxiliary XML file and also yes, it will work with Strongbox.

You probably need to disable the existing protection then use Strongbox or KeePassXC to add the new style of Challenge Response protection. Of course you should definitely make backups before all of this.

Let me know if you have trouble on the Strongbox side.

**Comment by bone187** [comment]
The process it self was without any problem.
But overall I'm very disappointed with Yubikey in my cross platform environment. 
The breaking point was now my iPad Pro with USB-C port which can not access the YubiKey 5Ci.
So after all I have to disable Yubikey for my KDBX file.

**Comment by strongbox-mark** [comment]
Yes, it is disappointing, speaking with Yubico apparently it's some kind of Apple hardware limitation, or at least that's their opinion on it.

**Comment by bone187** [comment]
Apple has sometimes very strange opinions…
It’s disappointing that they undermine with this kind of behavior the adaptation of good technology.
