### ISSUE TITLE
Autofill error with new iphone

### ISSUE THREAD

**Issue by tk0233** [strongbox-password-safe/Strongbox#342]
Hi - I love the app, I've just got stuck...

Migrated from iphone 7 where strongbox was working perfectly to iphone SE2020.

Whenever I attempt to autofill for the first time I get the message I must re-select the database. when I do this a new blank window appears and no further options other than try again which has no effect

. On next attempt I get the crash message about autofill memory. Reducing argon to 32MB on a new DB doesn't help. I have 211 database entries and the filesize is 175kB. Database was created using keepassxc 2.5.4 using defaults and keyfile.

I tried creating a database in strongbox - this works with a single dummy entry. When populated by merging the other entries in I have the same problem.

My storage method is perhaps unusual, I'm using Resilio file sync but the issues occur on local storage too. I don't believe its the issue given the recent iphone 7 functioning.

Previous issues haven't given me a place to start - what else could I try?
video available - https://vimeo.com/420837124

Thank you

Tom

**Comment by tk0233** [comment]
https://vimeo.com/user115985854/review/420837124/682440e088

**Comment by strongbox-mark** [comment]
Hi, thanks for the report. Sounds very strange. Couple of questions:

1) No problems with the same database on the iPhone 7?
2) When you say you merge in other entries, how do you do this?

Could you give your device a restart (sounds extreme I know) and try again?

**Comment by strongbox-mark** [comment]
I'd imagine this was some kind of weird caching or device issue solved by a restart? 

Could you close if this is no longer occurring?

**Comment by tk0233** [comment]
Hi Mark, thanks for the support. Sorry for slow reply, was away from home for couple of days.
I tried reboot of the phone unfortunately no change. 

In answer to your questions:
1. No problems on the iphone 7 or my other 6s I use for work. 
2. In this case I made a new database in Strongbox, then synced that to the PC. I used keepassxc "Merge from database..." function to copy in entries from my main database. Ideally I would have taken a smaller number to test whether the limits were off.

Could you confirm that my database size and number of entries should be OK?

**Comment by strongbox-mark** [comment]
OK, super weird... Based on a little googling, could you tell me if you have your "iCloud Drive" disabled for your Apple ID? I know you're not using iCloud or iCloud Drive but believe this could be causing the issue. You can check here:

Phone Settings > "Your Apple ID at top of screen" > iCloud > iCloud Drive

If you have it disabled can you try enabling it (restart may be necessary) and let me know if that helps?

**Comment by tk0233** [comment]
Mark - that's solved it. Now working perfectly.
I've no idea how you figured that out based on this info, seriously impressed.
Thanks again for the support and for a great app.

**Comment by strongbox-mark** [comment]
Sweet, great to hear it. Glad to have helped and thanks for getting back to me.
