### ISSUE TITLE
iOS: Database view shows only one flag at the same time

### ISSUE THREAD

**Issue by Slummi** [strongbox-password-safe/Strongbox#345]
Hi,

I think there’s a small bug in the database view. It shows only one flag at the same time. Example: If a database is read only and it is also the quick launch database there‘s only the rocket flag, but not the glasses flag.

I‘d expect that both flags are shown at the same time in that case.

**Comment by strongbox-mark** [comment]
Sounds like a good addition!

**Comment by Slummi** [comment]
This is now available with 1.49.0, so I think we can close it.

**Comment by strongbox-mark** [comment]
Yes, good spot @Slummi :)
