### ISSUE TITLE
iOS autofill: You can't open another database if you have already opened one

### ISSUE THREAD

**Issue by Slummi** [strongbox-password-safe/Strongbox#346]
It's not possible to select another database during autofill if you have once opened a database in the autofill dialogue and then close it to chose another one (e.g. because you don't want to use the quick launch database for autofill).

After pressing 'Cancel' in the opened database you just see the loading screen of Strongbox, but you don't get back to the database view.

![IMG_8262](https://user-images.githubusercontent.com/42265381/83392459-6c72cf80-a3f5-11ea-9633-55f91e09b1dd.PNG)

**Comment by strongbox-mark** [comment]
Thanks for the report @Slummi - looks like a bug alright! Cheers

**Comment by Slummi** [comment]
Hi @strongbox-mark - With 1.48.10 I can see the the database list, again.
Unfortunately I can't open my main database in auto fill dialogue any longer. I always get an error message: There was a problem opening the database. - Unknow error.

Already tried to deactivate and reactivate autofill for that database. But the error still occurs.
If I deactivate auto fill for that particular database it's still selectable in the auto fill dialogue. Other databases are ok, but I had to select the database file for auto fill once again.

Any ideas what I can do? In the main app there's no issue with that database.

**Comment by strongbox-mark** [comment]
Hi @Slummi - 

Where is you database stored? 
Are you using a "Files" based database or native provider?
Does a device restart help?

You might need to remove/re-add here as a final resort.

**Comment by Slummi** [comment]
It‘s a local database (documents).
Neither reboot nor deleting and re-adding all databases did help. Something is completely broken. When I have deleted all my databases, the auto fill dialogue still shows them.

Only a reboot refreshes the auto fill dialogue (e.g. if I enable/disable auto fill for a database or hide it from files I only see the changes in auto fill after a reboot, but I can’t open the database).

Very strange. Think I should try to re-install Strongbox. With the previous version everything was fine.

**Comment by Slummi** [comment]
After waiting the night, all my deleted databases were also back in the main app and I could open them in the app (not in auto fill), again. How can that be? I checked the iOS file system with an external application and the databases have definitely been deleted from the documents folder.

I‘ve just deleted Strongbox and re-added the databases. Still the same error. Can‘t open the database in auto fill dialogue any longer. Any ideas? Can I go back to the previous Strongbox version? Does Strongbox save any app specific settings in the database file, so that the file may have been corrupted? But why can I still open it in the Strongbox app or in KeePass, but not in auto fill?

**Comment by strongbox-mark** [comment]
Hi @Slummi - sounds like a few issues happening there and it's really important to keep them separate. I'll investigate now but there's no way to downgrade versions unfortunately, Apple just don't allow it... 

I'll report back here with findings.

**Comment by strongbox-mark** [comment]
Hi @Slummi - There's definitely a new Auto-Fill bug in the latest version (1.48.10) that affects databases that can only be read from a cache (that includes Documents based local databases, native providers like Dropbox/Google Drive too). It'll be a super quick fix which I'll hopefully get out today.

However it really doesn't address some of the other behaviours you have mentioned which sound extremely strange... Not really sure where to even start to address them. Did you restore from a backup at all?

I think you should be able to workaround the issue by using the fully supported Local Database location, rather than the Documents based Local Databases. I'm not sure if you need your databases to be in the Documents folder? Are you aware of the non-Documents based Local Database option? You can move between both options by sliding left on the Database and selecting "Show/Hide in Files"...

Local Databases that are hidden from Files work really well in Auto-Fill and you can even write to them.

**Comment by Slummi** [comment]
Hi @strongbox-mark - No, I didn't restore from a backup.
After re-installation of the app I manually added the database to Strongbox.

There are so many strange effects with auto fill in the current version.
I've already tried to hide the database from files before re-installation of the app. That didn't help.
Tried it once again after re-installtion. If the database is hidden from files, I can now open it from auto fill dialogue. If I make it visible again, I see a duplicate of that database in Strongbox, but not in auto fill dialogue and auto fill doesn't work. In that case the original and the duplicated databases are marked as "in documents" in Strongbox, but in auto fill the database is still marked as local (without documents). Hiding the database again removes the duplicate from Strongbox and auto fill works, again. Is that behavior related to the bug you've mentioned?

I don't need access from files app, but it should also work when the databse is visible in files as it did in the previous version.

**Comment by strongbox-mark** [comment]
OK, @Slummi - let's see where you are when 1.48.11 releases. After that, let's file separate issues for problems you're seeing.

**Comment by Slummi** [comment]
Thanks @strongbox-mark - I‘m looking forward to the next release.

**Comment by Slummi** [comment]
OK, 1.48.11 solved the issue that I couldn’t open the database in auto fill mode. Thanks!
But there are still other issues with auto fill and local databases. I will open new tickets later.

**Comment by strongbox-mark** [comment]
OK, great. Thanks @Slummi
