### ISSUE TITLE
iOS - Firefox + Strongbox - TouchID not working when autofill invoked from Firefox browser (mobile)

### ISSUE THREAD

**Issue by jescin** [strongbox-password-safe/Strongbox#347]
Hello,

I have an odd issue that seems to be happening in iOS. I’ve linked Strongbox to my google drive KeePass database, set everything up in iOS settings to use Strongbox as an autofill option, and set up my database to open with TouchID. When I invoke autofill from Safari, Strongbox works perfectly fine and properly (it asks me to verify my thumbprint, and shows my passwords). When invoked from Firefox, nothing works properly, and I even lose my database settings.

Steps to reproduce:

1)	Set KeePass database to open with TouchID.

2)	Close and re-open app, and verify TouchID works. Everything is good.

3)	Open Firefox browser, navigate to known site. Select Passwords button and choose Strongbox.

4)	Strongbox opens within Firefox, however it asks me for my database password rather than my TouchID.

5)	After entering my database password, I can select the credentials for my site just fine. However, if I reopen the Strongbox app, I find that all my database settings are now gone. TouchID is no longer enabled, and even my icon selection has reverted to it's default setting.

That’s pretty much it. Again, Strongbox works perfectly from Safari, it just seems to be buggy when used from Firefox.

Thanks,

-- Jesse

**Comment by jescin** [comment]
Well, nevermind me, I rebooted my phone and all the issues went away. I found a forum post that talked about a similar issue, and rebooting was the suggested fix:

https://www.reddit.com/r/strongbox/comments/gqnja8/autofill_no_auto_fill_cache_file_yet/

Guess I'll straight up close the issue. :)

Thanks,

-- Jesse

**Comment by strongbox-mark** [comment]
Awesome, great to hear it and thanks for getting back and closing.
