### ISSUE TITLE
Feature request : Hide password field when no password is entered

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#348]
Hi Mark , 

is it possible that a user doesn’t see an empty password field ? 

At the moment when no password is set , the user see the only the “eye” symbol and when click on it , the space is empty

**Comment by strongbox-mark** [comment]
There is a setting in View Preferences (Unlock DB > Preferences > View Preferences) called "Show Empty Fields". This hides empty fields. Does this work for you?

**Comment by Slummi** [comment]
I think that switch doesn’t work for the password field. I can see the field even if it is empty and the switch is enabled.

**Comment by strongbox-mark** [comment]
Weird, I can't see it? Are you sure?

**Comment by Slummi** [comment]
Yes, checked it twice and have just found out why. :)
The password field is always shown if you have activated the audit for empty passwords. In this case Strongbox wants to show the "empty password" indicator and therefore it ignores the settings to hide empty fields. ;)

**Comment by strongbox-mark** [comment]
Ha! OK, thanks! I think that's probably ok behaviour... 

@F3000 Work for you?

**Comment by F3000** [comment]
Hi Mark,

thanks for the hint 👌

I have tested both options (enable/disable) . In both states I see the password field without content .
In fields for Email/username the setting is correct .

**Comment by strongbox-mark** [comment]
Have you got the Empty password Audit on? Can you send screenshot of empty password field?

**Comment by F3000** [comment]
> Have you got the Empty password Audit on? Can you send screenshot of empty password field?

I have over read @Slummi posting . Sorry . 

Now it is working fine 👍

That’s not related to this issue but when a user wants to audit entries where is no password than it would make senses that the app offer the possibility to exclude entry’s for the audit feature . 


Here is my usecase :

I save software licenses in my password container too. Here I enter only
- Name 
- License code 
- sometimes license file 
So I hide the password field .

But it could be possible that Someone want to use the audit feature with  empty passwords and he can’t have both (my usecase and audit feature )

Hope it’s understandable ☺️

**Comment by strongbox-mark** [comment]
Yes, totally makes sense @F3000 - Exclude entries from Audit is coming in the next release, should do the trick for you! Let's close this one out...

**Comment by F3000** [comment]
Thanks 😊
