### ISSUE TITLE
Crash upon disabling Audit this item

### ISSUE THREAD

**Issue by brogers5** [strongbox-password-safe/Strongbox#350]
### Reproduction Steps
1. Open a database (my database is synced from Dropbox).
2. Decrypt the database (my database's master key uses both a master password and key file, but Face ID Unlock is enabled for convenience).
3. Under Quick Views, press Audit Issues.
4. Swipe right on an entry, and press the Audit Details button.
5. Under Preferences, set the Audit this Item switch to off.

### Expected Behavior
Auditing is disabled without issues.

### Actual Behavior
Application crashes. Auditing appears to be disabled for the entry when Strongbox is restarted.

### Other Notes
I've attached some example [crash logs](https://github.com/strongbox-password-safe/Strongbox/files/4741467/Strongbox.Logs.zip) to aid in debugging. I seem to notice this happening more with entries that are flagged as No Password.

**Comment by Slummi** [comment]
I can confirm the described behavior.

**Comment by strongbox-mark** [comment]
Thanks for the report and the crash logs...

**Comment by strongbox-mark** [comment]
Looks like a weird kind of concurrency issue and somehow connected with the Empty Table View component I use. Fix on the way...

**Comment by strongbox-mark** [comment]
This should be fixed with 1.48.11 now

**Comment by brogers5** [comment]
Updated to v1.48.11 and I've been unable to reproduce the issue. I think we can call this fix confirmed. Thanks for the quick turnaround!

**Comment by strongbox-mark** [comment]
Sweet.
