### ISSUE TITLE
Changing visibility of a local database creates duplicates of that database

### ISSUE THREAD

**Issue by Slummi** [strongbox-password-safe/Strongbox#351]
If you have a local database and you make it visible to Files, the database is duplicated.
If you hide the database from files again, the duplicate is removed.

I guess that only databases are affected, which have been added to Strongbox via iTunes file sharing. But I'm not sure.

@mmcguill I'll send you a video of this issue by mail.

**Comment by strongbox-mark** [comment]
Additional info from email:

> Normally the name of the duplicated database is exactly the same name as the original database has.
> But if I rename the original database before making it visible to files, then the name of the duplicate is that one before renaming.

Sounds like the Documents watcher is picking up the file at the same time as the "Transfer to Documents" function is adding/updating the existing reference. Solution will be to disable the Documents watcher during this transfer.

**Comment by Slummi** [comment]
Short note:
When I see the duplicated database in Strongbox (database is visible in Files) and I check the Files app or iTunes file sharing, there's still only one database. So I can see the duplicate in Strongbox only.

If I then hide the duplicate from Files (not the the original one) the duplicate disappears. After that I can hide and reveal the original database as much as I want without any new duplicates.

**Comment by Slummi** [comment]
Another addition:
Made more tests - This issue is only related to database files with umlauts in the name.

**Comment by strongbox-mark** [comment]
Yeah, this makes more sense. There is a background watcher process that picks up files in the Documents folder... Before it adds any, it checks if there is already a reference to this file in the databases list, i.e. it looks for duplicates. There must be some kind of bug here with the duplicate check and umlauts... 

Thanks for the research! Will fix in next release.

**Comment by strongbox-mark** [comment]
I couldn't reproduce this with 1.48.14 - Is it still happening?

**Comment by Slummi** [comment]
Yes, it‘s still happening in 1.48.14 with databases that have umlauts in their name.

**Comment by strongbox-mark** [comment]
I must be doing something wrong. Could you detail the exact set of steps to reproduce including a good example database name?

I tried creating a database with Umlauts, copied to Strongbox Documents folder, it appeared. Switched “Show/Hide from Files” a few times but couldn’t reproduce a duplicate.

Send to support email if you prefer.

**Comment by Slummi** [comment]
The simplest way to reproduce this are the following steps:

1. Tap on the ‚+‘ in the database list
2. New Database (Express)
3. Choose „Passwörter“ as database name and set any password
4. Swipe left on the new database -> More... -> Make visible in Files... and confirm the message

After that you have a duplicate of that database. But the steps you have described should also work.

**Comment by strongbox-mark** [comment]
Thanks, got it. Will be fixed in next release.

**Comment by Slummi** [comment]
This is now working with 1.48.15. Thanks!
