### ISSUE TITLE
Database list in auto fill dialogue is not up to date

### ISSUE THREAD

**Issue by Slummi** [strongbox-password-safe/Strongbox#352]
If you rename or delete a database in Strongbox the changes aren't visible in the database view for auto fill. You still see the old database names and you can also access databases that have been deleted.

@mmcguill I'll send you a video of this issue by mail.

**Comment by strongbox-mark** [comment]
This seems like the usual (stale shared data between App and App Extension) issue that happens every now and then. 

I’m guessing a device restart fixes? 

Perhaps this situation has gotten worse with iOS 13.5 (that is what version you are running?)

**Comment by Slummi** [comment]
Yes, a device restart refreshes the auto fill database list, but only once. If I make any changes to the database list (add, delete, rename, hide / make visible), I have to restart the device again to take effect.

I‘m currently using iOS 13.5.1.

**Comment by strongbox-mark** [comment]
Does this happen with multiple devices or just one? 
Can you say which is the third party app (Auto Fill host) you are using?
What is the model of device?

I can't reproduce here locally with some quick tests but there have been reports of stale database lists in Auto-Fill at times which appear to be down to system level caching.

**Comment by Slummi** [comment]
Tested with two devices and Firefox and Safari. In both apps the same issue.

**iPhone X**
System Version: 13.5.1
Ep: 1591519099
Bundle: com.markmcguill.strongbox - (1.48.11)
Flags: P[0[-1]110[4]0011]

**iPhone 7**
System Version: 13.5.1
Ep: 1557075792
Bundle: com.markmcguill.strongbox - (1.48.11)
Flags: P[1[-307]110[66]0000]

**Comment by strongbox-mark** [comment]
Not sure if you can do this or have the time for it, but would be interested to know if 

1) Deleting Strongbox app(s) completely
2) Restarting Device
3) Installing Strongbox and re-adding databases

Does that help?

**Comment by Slummi** [comment]
I've already tested re-installation of 1.48.10, device restart and then updated to .11.
That didn't help. But I'll test it again from the scratch with new databases created by Strongbox.

I get back to you soon.

**Comment by Slummi** [comment]
OK, here's what I've tested:

1. Closed Strongbox, Firefox and Safari
2. Disabled auto fill from Strongbox in the iOS settings
3. Deleted Strongbox
4. Restarted the device (iPhone X / iOS 13.5.1)
5. Reinstalled Strongbox from the App Store
6. Started Strongbox (by the way: first time that I've seen the welcome trial screen after a reinstallation of the app although I've bought the full version)
7. Added a new database (Express), opened and closed it
8. Sent Strongbox to the background and reactivated auto fill from Strongbox in the iOS settings
9. Started Safari, opened auto fill from a password form and saw the newly added database which I could also open
10. Switched back to Strongbox, added another new database
11. Switched back to Safari and saw both databases in auto fill
12. Renamed the database in Strongbox
12. Safari auto fill immediately showed the changes
13. Went back to Strongbox, deleted all databases
14. Safari showed no more database
15. **Added an existing database via iTunes file sharing**
16. **Opened Strongbox and saw the added database**
17. **Started auto fill in Safari and no database was available**
18. Hid database from files, started auto fill in Safari again and I saw the database and could open it
19. Made the database visible again, saw a duplicate in Strongbox and in Safari auto fill
20. Hid it from files and the duplicate was removed, Safari showed only that database
21. Renamed the database - Safari auto fill showed the changes
22. Started **Firefox** (for the first time) and autofill showed the database
23. **Renamed the database, tried again and Firefox didn't show the changes, but the database could still be opened with the old name**
24. Checked Safari, which showed the changes correctly
25. **Renamed the database again, no changes in Firefox visible, Safari was ok.**
**26. Killed Strongbox, Safari and Firefox - no changes to Firefox auto fill**
27. Restarted the device - Safari and Firefox auto fill were up to date
28. Renamed the database - Safari auto fill was up to date, Firefox not

**Conclusion**
With the exception of step 17 it seems that after re-installation the issue only occurs in Firefox or more precisely in all apps which don't use Safari as an in-app browser. I've also tested other apps (no browsers) that ask for passwords and the behavior is the same as in Firefox.
So it seems that re-installation solved the issue for auto fill in Safari, but not for auto fill in any other app which isn't using Safari.

**Comment by strongbox-mark** [comment]
Thanks for this... it's very difficult to say what's going on there but I don't think there's much Strongbox can do (apart from fix the Duplicate database issue in #351) given the above information... 

A question, does Firefox or other app eventually show the correct database list? Say after 6 hours or 24?

This seems to me to be some kind of system level caching, it's just not possible to Strongbox to maintain 2 different database lists for 2 different apps... I might need to raise an issue with Apple on this as I've seen the issue myself every now and then and others sometimes notice this, but it usually is short lived and rarely noticed as people don't change their DBs so often.

**Comment by Slummi** [comment]
> A question, does Firefox or other app eventually show the correct database list? Say after 6 hours or 24?

That‘s quite possible! After waiting a (long) while the database list is updated without a device restart.
I haven’t checked yet how long exactly. Will try to time it.

**Comment by strongbox-mark** [comment]
You mean it's updated in Firefox for you now since you posted the above 4 hours ago?

**Comment by Slummi** [comment]
Have just checked it and yes, it‘s up to date in Firefox now.
And I’m pretty sure that it has also been updated over the last night. Will test it this night again.

**Comment by Slummi** [comment]
No good news...
Started testing by modifying the database list and the issue is also back to Safari. The database views are not up to data - neither in Safari nor in Firefox. :(
Will wait and check the status tomorrow morning.

**Comment by Slummi** [comment]
Still no good news ...
I've been waiting until now (about 11 hours), but the auto fill database list is still not up to date in Safari and Firefox (and other apps).
I will wait a while before trying other steps.

**Comment by Slummi** [comment]
I'm going crazy!
I've been waiting for almost 36 hours since modifying the database list and still no update of the database list in auto fill (Safari and Firefox).
Have just opened Strongbox and what do I see... All the modifications are gone. The database list in Strongbox is the same as before modification. So at the moment the auto fill lists are up to date, but not the original list in Strongbox. How can that be? Is it possible that auto fill can overwrite the original database list in Strongbox (maybe by cached databases)? Maybe that would also explain issue #353.

**Comment by strongbox-mark** [comment]
@Slummi - thanks for the feedback and testing. It's definitely possible for the Auto-Fill component to write to the database list and if that was stale in the auto-fill component then it would make the main App list stale too... 

Obviously the source/cause of the Auto-Fill stale list is the problem. I have a suspicion that it could be related to the size of the default that are stored, which might cause sync issues, but can't be sure.

If you have time or are bored, try to see if it happens with a non "Files" based database, just a single database (e.g. a local database that doesn't use a key file (this affects size)). 

Does only 1 local db work? 
how about 2? 
what happens if you now add a "Files" based database? Is it broken, how about 2 files based databases?
etc... the idea being to build up the size of the data stored in the shared "settings" cache.

Thanks!

**Comment by Slummi** [comment]
Hi @strongbox-mark - Just a short feedback.
The last test was done with a single local database (not visible in files).
The database doesn't use a key file, but its size is about 1,2 MB.

Will start again with small databases, without umlauts etc. and gradually add additional and bigger databases.

**Comment by Slummi** [comment]
Next test:
1. Started again with the 1,2 MB database as a local database (not files)
2. Checked auto fill in Safari and Firefox - both were up to date
3. Renamed the database and checked auto fill - Safari was up to date, Firefox not
4. Added a new local database (Express), checked auto fill - Safari was up to date, Firefox not (only the first database was shown with the old name)
5. Waited several hours (can't say how long exactly), checked auto fill and Strongbox and in all three database lists there was only the first database with the old name available.

So somehow the database list has been completly overwritten. There's definitely a relation to #353.

Will test it again with a small new database after re-installation.

**Comment by strongbox-mark** [comment]
Thanks for the experimentation @Slummi

**Comment by Slummi** [comment]
First I performed another test without reinstallation of Strongbox. Deleted all databases, added a new local one via (Express), checked Safari and Firefox. Safari was up to date, Firefox not. Waited more than 12 h. Checked Firefox again. Still not up to date. Opened Strongbox and Safari. The database has been deleted and I had an empty database list.
At them moment my databases aren't really safe in Stronbox. :(

**Comment by strongbox-mark** [comment]
Yes, very odd, you're the only report of this issue so far but nothing has really changed with regards to this storage/shared app settings codewise so I'm starting to worry that there is possibly something odd with iOS 13.5.1. 

Not sure if you have the possibility to test on iOS 13.4?

**Comment by strongbox-mark** [comment]
@Slummi - I'm going to make a few changes to force the Auto-Fill component to be read-only when it comes to these settings. It'll be sort of an emergency release with little changed except this. The real solution is probably to find a better way to store the Database metadata, though really this should work and has worked very well up until now... The risk is too high however to let something like this continue. I'd expect the update to release probably Monday or Tuesday and I hope you'll have some more time to test then.

**Comment by Slummi** [comment]
> Not sure if you have the possibility to test on iOS 13.4?

Unfortuantely not, I could only test with an old iPhone 6 and iOS 12.4.7. Not sure if that makes sense.

> I'm going to make a few changes to force the Auto-Fill component to be read-only when it comes to these settings. It'll be sort of an emergency release with little changed except this.

Cool! Thank you @strongbox-mark! Sure, I will continue testing! Unfortunately I can't see any pattern until now, when this issue occurs. Can it make a difference whether to use the Auto-Fill cache or not?

**Comment by strongbox-mark** [comment]
Thanks @Slummi  If you could test with an iPhone 6 on 12.4.7 that would be great. 

My suspicion is something has shifted with the NSUserDefaults library in iOS 13.5(.1) as it's the only thing I can see that could cause something this extreme... 

I don't think the Use Auto-Fill Cache will be part of the problem...

If I'm going to do this emergency fix, I might as well spend some extra time and try to change the underlying database preferences storage mechanism to move away from NSUserDefaults as I just don't really trust it anymore and there's always been an issue with slightly stale settings necessitating a restart which was always an annoyance but now could become a real liability...

**Comment by Slummi** [comment]
I've just started testing with a newly installed iPhone 6 (iOS 12.4.7 and Strongbox 1.48.11).
What I can say immediately is that Firefox has the same problem that the database list in Auto-Fill is not up to date. I will wait and see if the databases are deleted or renamed after a while.

I don't kow why the behavior of Auto-Fill is different between Safari and other apps, because it always seems to be a Safari component even if you use another app like Firefox. If I change the language settings of Strongbox it still uses another language in Auto-Fill mode. Strongbox only changes the language in Auto-Fill mode if I also change the language of Safari. This applies also for Firefox and other apps. Changing the language of Firefox doesn't change the language that Strongbox is using in Auto-Fill, but changing the language of Safari also changes the language of Strongbox in Firefox (and other apps) Auto-Fill. So Auto-Fill must be based on Safari.

**Comment by strongbox-mark** [comment]
Weird issue with Firefox, the language is _supposed_ to depend on the host app for sure, so doesn't really make sense that the auto fill component is in Safari's language.

1.48.12 is available on the App Store now, it should definitely fix the stale overwrite problem, but not necessarily the Stale database list in Auto-Fill. 

Another fix is coming very shortly for that but it's a bigger job. I'm hoping we'll never see stale databases after 1.48.13.

**Comment by Slummi** [comment]
Hi @strongbox-mark - I think you're on the right track!
With 1.48.12 there's still the problem that Firefox Auto-Fill isn't up to date, but after waiting several hours it gets updated instead of renaming / deleting databases.

On my iPhone 6 I'm still testing with 1.48.11.

**Comment by strongbox-mark** [comment]
Thanks @Slummi - definitely seeming more and more like a subtle shift in NSUserDefault behaviour in 13.5(.1) - Just can't really trust it any more... Fuller sync fix in the pipeline... please keep us updated here with your experiments

**Comment by strongbox-mark** [comment]
@Slummi - Not sure if you use Key Files or not? 

If you do not, then you can try out 1.48.13. Unfortunately if you do, there is a bug and you should not upgrade.

Be interested to hear your results - The databases should now be up to date across Firefox/Safari etc...

**Comment by Slummi** [comment]
@strongbox-mark - Normally I use both types of databases. But at the moment I'm still in testing mode and so I'm using databases without key file.
I've already updated to 1.48.13 on my iPhone X with iOS 13.5.1. Up to now I can't see a change between .12 and .13. The database list in Firefox is still not up to date after modification of the database list in Strongbox. But in contrast to .11 it gets updated after a while (can't say how long exactly). Maybe I should try a re-installation of Stronbox, when .14 is released.

On my iPhone 6 with iOS 12.4.7 I'm still running Strongbox 1.48.11. I tried to repeat the tests where the databases were renamed / deleted under iOS 13.5.1. That did not happen until now. But the database list in Firefox Auto-Fill doesn't become updated even if I wait several days. A device restart updates the Auto-Fill list once.

So I would say there's a relation between the reported issues and iOS 13.5.x - at least in case of the unwanted database modifications like renaming / deletion.

**Comment by strongbox-mark** [comment]
That's interesting, I'd say that Firefox is actually holding an older binary version of the Auto-Fill component. My guess is that if you were to restart the device running 1.48.13 you will now see databases being updated as expected in Safari and Firefox... Worth a shot?

**Comment by Slummi** [comment]
I reinstalled 1.48.13 and restarted the device, but unfortunately the same behavior. Safari Auto-Fill is immediately updated after modifying the database list, Firefox is not.

Did you test Firefox yourself?

By the way, the app also crashes after reinstallation and re-adding databases with a key file based database . But .14 is already on the way.

**Comment by strongbox-mark** [comment]
I see the issue on Firefox too, yes. Pretty stumped as to what could be happening, need to investigate further, something is holding onto cached files/preferences and I'm not sure why.

**Comment by Slummi** [comment]
@strongbox-mark - Whatever you did, it helped! Firefox Auto-Fill is immediately updated with 1.48.15. :) Great job!

Do you think all issues with stale databases are solved now and we can close this?

**Comment by strongbox-mark** [comment]
Thanks @Slummi - Yeah I expect all stale issues are fixed now. Still can't explain the underlying system behaviour that caused this but I've worked around it...

**Comment by Slummi** [comment]
Ok, let's close this one. If there will be any issues with stale databases in the future, we can re-open it.
