### ISSUE TITLE
iOS: Deleted databases reappear after a while

### ISSUE THREAD

**Issue by Slummi** [strongbox-password-safe/Strongbox#353]
Databases which have been deleted from Strongbox (database view is empty after deletion) sometimes reappear after a while and you can also open them.

Tested with local databases and files based databases.

Unfortuenately I can't say, how long you have to wait until the databases reappear and I can't reproduce this issue all the time.

@mmcguill If I can record this issue in a video, I'll send it to you by mail.

**Comment by strongbox-mark** [comment]
Similar questions to #352 

Is this repeatable on all devices or just one?
iOS 13.5.1?
Device Models?

Super weird

**Comment by Slummi** [comment]
Up to now I've seen this on my iPhone X with iOS 13.5.1 only.
I'll try to reproduce it on other devices.

**Comment by Slummi** [comment]
I guess this is related to the stale database list and has been fixed with the latest updates? What do you think @strongbox-mark ?

**Comment by mmcguill** [comment]
Yes, definitely related and is fixed as of 1.48.12 - Feel free to close

**Comment by Slummi** [comment]
Thanks for fixing!
