### ISSUE TITLE
Bug : Transparent Background for autofill didn’t work in all apps

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#354]
Hi Mark ,

some updates ago you created a new feature to only show the Face/Touch ID animation when using autofill .

In safari and some other apps this works for me fine 👍

But today I have used the Browser “ICab Mobile” . Here I see the old behavior like before you introduced the feature . 

Doe the developer have to change something or do you think it’s a bug ?

**Comment by strongbox-mark** [comment]
Weird, not sure if you can share a (redacted) screenshot?

Does a restart help?

**Comment by F3000** [comment]
Restart didn’t help . Found this behavior on iPad and iPhone with iOS 13.5.1 

Here are the pictures

 ![image](https://user-images.githubusercontent.com/8161283/84447761-3c26fe80-ac49-11ea-8ac5-3ffda7bf9322.jpeg)

![image](https://user-images.githubusercontent.com/8161283/84447778-477a2a00-ac49-11ea-83e2-6b31d6f61bd9.jpeg)

**Comment by strongbox-mark** [comment]
This looks ok to me, what were you expecting? 

The transparency feature only makes sense in the QuickType biometric authentication context...

**Comment by F3000** [comment]
When i compare this view with my iPhone (same version) here i don’t see the “Choose a database screen” .

So im a little bit confused

**Comment by strongbox-mark** [comment]
In one case I think you're tapping a particular username in the Keyboard QuickType bar, but in the other you're tapping 'Passwords' which leads you to the Strongbox databases list where you need to select a database and search for a credential. Two different contexts, only the first supports transparency if you use Biometric unlock... 

Hope that makes sense... I don't think there's anyway to apply a transparency to the 2nd case?

**Comment by F3000** [comment]
Ok you are right . There are two different methods . 


On iPhone i had the big blue button (with username) :

https://share.icloud.com/photos/090c9m2ulQrw3lqABwij54KBw#Berlin


On iPad i have the other option with only „password“  :

https://share.icloud.com/photos/0rI-iiKF4qOMFUGRpXaYcKAOA#Berlin

But why i have two different behaviors (blue button/password-button) with the the same website and the same database ?

**Comment by strongbox-mark** [comment]
Good question! Are they running the same iOS version?

**Comment by F3000** [comment]
Yes all the same . And same Strongbox settings

**Comment by strongbox-mark** [comment]
And you're using the exact same database with the same entries/logins with Strongbox? 

They don't get presented to you on the iPad above the keyboard?

**Comment by F3000** [comment]
Yep . 

Database is saved in your iCloud implementation .

**Comment by strongbox-mark** [comment]
Seems like an iOS difference between iPad and iPhone then, there's nothing Strongbox can do here to change that

**Comment by F3000** [comment]
hmm ok .  Thanks . 


Maybe iOS 14 improve the situation
