### ISSUE TITLE
Bug : wrong audit animation flow

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#355]
hi Mark , 

just see this Minor UI thing (See Video) 

https://share.icloud.com/photos/0EhWrz8m5n_7ZuqFdYS4cEazA

When I filter after „Tags“ click on a Tag and choose one item and go back I see the „Tag“ list again . 
This is OK. 

Now when you choose one item from the filtered Tag list and swipe right to change the audit settings and click on „finish“ I see my complete list instead of the filtered tag list . 

Is this something you can change ?

**Comment by strongbox-mark** [comment]
Yeah, looks like on refresh the view doesn't maintain search state. Cosmetic but worth fixing.

**Comment by strongbox-mark** [comment]
Hi all, this is fixed now in 1.53.0. Please open new issues if you see any problems.
