### ISSUE TITLE
OneDrive authentication issue

### ISSUE THREAD

**Issue by akuja** [strongbox-password-safe/Strongbox#358]
Our company is starting to use OneDrive in managed Microsoft 365 infrastructure. Users would have the password file in OneDrive, so they are able to utilize that between devices.

We allowed Strongbox as an Enterprise app on our Azure AD for secure authentication in admin context, but unfortunately when we started testing it uses Graph API as a recourse in the AUTH, not the enterprise application that was added. This means that we are unable to create targeted access rules and exceptions for Strongbox with Azure Conditional Access, which is the access management engine of the cloud. 

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow

**Comment by strongbox-mark** [comment]
Hi @akuja - Thanks for raising the issue.

I'm not 100% sure I understand what the problem is exactly, I use Microsofts OneDriveSDK library to connect to OneDrive:

https://github.com/OneDrive/onedrive-sdk-ios

I know it uses the ADAL library under the hood but I think that this then makes a Graph API call. Are you saying that this is not the correct way to authenticate? There is a newer method?

One other option you could consider if adding the database through the "Files" method... You would need the OneDrive app installed on your device, this then makes files available view the iOS Files app. From here you can add to Strongbox. Would that work for you?

**Comment by akuja** [comment]
Thanks @strongbox-mark  for your fast reply.

That is not an option either, because we are using Conditional Access with settings that enforce All apps in Azure AD to use Microsoft based applications, and from those applications we have separated data from other apps on the mobile device. This means that Strongbox is unable to read such data from OneDrive app. This is the root cause for the issue, because we would need to exclude Strongbox from Conditional Access rules, because it is always unable to full fill the Microsoft based application requirement. Now if we exclude Strongbox the exclude is not working, because the resource it is using is Graph API (unable to target anything for this), not the API exposed for the application itself.

**Comment by strongbox-mark** [comment]
Thanks for the extra detail @akuja. Do you have more information on what would need to be done to get this working? This seems like more than just accessing your OneDrive for Business drive..

Are there other 3rd party apps like Strongbox that you can use successfully? 

Feel free to email support@strongboxsafe.com if you'd prefer to discuss privately.

I'm not sure what needs to be done from the Strongbox side to make it fit into this system or how I could I even setup a test environment to work on this? Is that something you could help with?

**Comment by strongbox-mark** [comment]
HI @akuja,

Today we released a new OneDrive integration that uses MSAL and we're hoping it will help with any authentication issues you might have. Are you still able to test this for us in your scenario, or indeed interested?

This is available as of 1.55.2+ and you would need to re-add any existing OneDrive databases to see this functionality. Please feel free to re-open if you have any issues or want to discuss integration further.
