### ISSUE TITLE
StrongBox crashes immediately

### ISSUE THREAD

**Issue by HongmouZhang** [strongbox-password-safe/Strongbox#359]
Today I have updated to the newest version of strongbox (1.48.13), but I cannot use it at all, the software crashes immediately after I launch it, and tried several times and restart my iphone, doesn't work. My phone is iphone 11 pro, IOS version is 13.5.1.

**Comment by strongbox-mark** [comment]
Hi @HongmouZhang - I'm afraid there is a bug in the latest release...  It looks like it has to do with the use of a Key File. 

I assume you are using one with one of your databases?

A fix is on the way... ETA is about 12-24 hours to get through Apple's review process. I will request an expedited review but this isn't guaranteed.

A possible workaround is available if you are comfortable with starting from a fresh copy of Strongbox and re-adding your database if it was not stored on just your local device.

**Instructions for Workaround**
==========================
**CAUTION**: Do **NOT** do this is you are not comfortable with re-adding your database to a fresh install of Strongbox. You must have access to your database and not be relying on just a local copy.

If that is ok follow these steps:

1) Remove/delete Strongbox from your device completely. This resets all settings and your database references. Any local databases/key files will be removed also, so you will need access to both to re-add them if you use them.
2) Re-install Strongbox from the App Store
3) Re-add your databases and key files etc

**Comment by HongmouZhang** [comment]
Yes, I am using a keyfile, and access password database via webdav. Thank you for your instruction, and I hope you already target the problem.

**Comment by Slummi** [comment]
This is now working again with 1.48.14.

**Comment by strongbox-mark** [comment]
Thanks all

**Comment by DennisBankmann** [comment]
This issue still occurs for me on Strongbox Pro 1.50.12 (2997) on iOS 14.2.1.
Once I choose a keyfile (128byte, made with KeepassXC), Strongbox freezes upon trying to unlock my database (made also with KeepassXC).

This happens both with the keyfile chosen from the "Files" app as well as loaded into the Strongbox app from a Mac via the Finder.

I can force-close the app and then retry, so I fortunately do not have the issue that the original report contained that the app would fail to launch. It appears that the app freezes before storing the updated configuration.

When I use the workaround above with going for single-use keyfile (spanner icon), the app works as expected.
This is however not very convenient to load the keyfile every time.

It thus seems that above issue persists at least on some configurations. Would be great if you could look into that.

**Comment by strongbox-mark** [comment]
Hi @DennisBankmann - That sounds very strange indeed. Have you tried restarting your device? Does that help at all?

Is it just this particular key file, or is it for any key file?

Is the Key File newly or recently created and with what version of KeePassXC.

**Comment by DennisBankmann** [comment]
> Hi @DennisBankmann - That sounds very strange indeed. Have you tried restarting your device? Does that help at all?
> 
> 
> 
> Is it just this particular key file, or is it for any key file?
> 
> 
> 
> Is the Key File newly or recently created and with what version of KeePassXC.

Restarting indeed fixed the issue for me -- many thanks!
Odd that I didn't think of that, I guess I assumed force-killing the app would clean all of the state of the app. Well, learned somethint new then 😀

To answer your questions, this was a single key file (so far) that had been created by KeepassXC 2.6.2 on Mac as few days ago.

Thanks again for the quick help!
