### ISSUE TITLE
Your users seem to be coming to the wrong issue tracker quite often

### ISSUE THREAD

**Issue by carlspring** [strongbox-password-safe/Strongbox#360]
Hi,

Congratulations on your number of followers!

We have a project with the same name (https://github.com/strongbox/strongbox/) which has had a significantly longer history here on Github than yours. (In fact, we have all of our sub-projects under the [Strongbox organization](https://github.com/strongbox/)). Lately, we've been getting quite a few issues reported in our issue tracker by mistake. Would it be possible for you guys to be more explicit and add a link in your application where to report bugs to?

Here are some recent examples:
* https://github.com/strongbox/strongbox/issues/1693
* https://github.com/strongbox/strongbox/issues/1700
* https://github.com/strongbox/strongbox/issues/1720
* https://github.com/strongbox/strongbox/issues/1729
* https://github.com/strongbox/strongbox/issues/1778
* https://github.com/strongbox/strongbox/issues/1794

Some options:
* Would you be willing to rename your project?
* As mentioned above, maybe you could add a link in your app to the correct issue tracker? This should help reduce this confusion some of your users seems to be having.

Kind regards and good luck with your project,

Martin

**Comment by strongbox-mark** [comment]
Hi Martin,

Thanks very much and sorry about the issue spam coming from our users! I will endeavour to make this more explicit and provide a link on the main website and in App. 

All the best with your project too :)

Cheers,
-Mark

**Comment by carlspring** [comment]
Hi Mark,

Thank you very much! :)

Cheers,

Martin
