### ISSUE TITLE
Strongbox 1.48.13 Crashes on iOS 13.5.1

### ISSUE THREAD

**Issue by shad0whawk** [strongbox-password-safe/Strongbox#361]
Updated to to the latest version today and it keeps crashing when I try to open it. I’ve restarted my device and still get the same behavior.

**Comment by strongbox-mark** [comment]
Hi @shad0whawk - see #359 - Fix on the way and workaround available there. Apologies

**Comment by shad0whawk** [comment]
Ah never mind should have looked at the other issue since this has been reported already.
