### ISSUE TITLE
Search result isn't shown after opening any menu

### ISSUE THREAD

**Issue by Slummi** [strongbox-password-safe/Strongbox#362]
The search result isn't shown any more after opening any menu (e.g. database settings, single entry settings like 'Audit Details' or 'Download FavIcon'), but the search bar still contains the search term.

Example:
1. Tap on the search bar and select "Audit Issues". (Strongbox shows only entries that have audit issues).
2. Swipe right -> Audit Details -> Change something or just tap "Done".

Result:
The entries view shows again all entries instead of only the audit issues, but the content of the search bar is still "strongbox:auditEntries". You have to tap on the search bar again to show the search results only.

I'd expect that the entries view only shows items that are matching the displayed search term. Just a cosmetical issue, but a little bit confusing.

Tested with iPhone X / iOS 13.5.1 / Strongbox Pro 1.48.14

**Comment by strongbox-mark** [comment]
Thanks, minor but worth a fix

**Comment by strongbox-mark** [comment]
Related to #355 I think...

**Comment by strongbox-mark** [comment]
Hi all, this is fixed now in 1.53.0. Please open new issues if you see any problems.
