### ISSUE TITLE
Question : Strongbox as default app for „.dat“ files on macOS right ?

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#364]
Hi Mark , 

is this your intention ? 

or a small minor issue ? 

Thanks

**Comment by strongbox-mark** [comment]
Yes, this is intentional, Password Safe files sometimes use .dat

**Comment by F3000** [comment]
Ok . I will close it . 

Because I have seen this when I connect SD-card from my raspberry pi to the Mac . Than there are lot of strongbox icons on it :)
