### ISSUE TITLE
Bug iOS14: Database rocket mode is unreliable

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#365]
Hi Mark , 

currently I have installed iOS 14 B1 to do a real life testing with the apps and OS. 

One thing that I experienced with your app so far  is that „auto-open“ (rocket symbol) with my standard database isn’t working every time. 

I think that you can’t fix iOS 14 bugs at the moment but you can take it to the backlog 😊

**Comment by strongbox-mark** [comment]
Hah, thanks Felix but I won't be accepting iOS 14 bugs until it's live. Too many other things to think about. :)
