### ISSUE TITLE
strongbox deleted my database

### ISSUE THREAD

**Issue by harvey1298** [strongbox-password-safe/Strongbox#366]
was just trying to open my database on strongbox, and now it's gone. no coding experience or anything here - quit and restarted the program (i'm on a mac) and it's still gone. help!

**Comment by strongbox-mark** [comment]
Do you have any more details on what happened here? 

Where was your database stored? 

What version of Strongbox are you running?

Are you using it only on a Mac?

Is it possible you moved/deleted the database yourself in Finder for example?

**Comment by strongbox-mark** [comment]
Have spoken with user over email, it looks like this was probably just database stored on a disk image/volume that was then unmounted. Things seem to be going fine now. Closing this one out.
