### ISSUE TITLE
Show Pinned Items below Search Results in AutoFill

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#367]
Hi , 

just a finding from today . In my library I have 5 pinned items .

When I press the auto fill button above the keyboard -> choose database -> the items are mixed . Some pinned I see at the top , but not all .

Is this something you can implement ?

**Comment by strongbox-mark** [comment]
Yeah good idea I think

**Comment by strongbox-mark** [comment]
Hi @F3000 - Yes, I hear what you're saying but the Pinned Items are different from this screen with the blue entry. Strongbox doesn't own and can't control that screen/menu... 

Honestly I think this is a won't fix/can't fix.

**Comment by F3000** [comment]
@strongbox-mark  noe I can remember the intention behind this :) 


example :

I have installed the apple feedback app to report issues . After some time the app logs me out . 

When I try to log in I tip on "passwords(auto fill)" and the strongbox extension open a new search entry field . 

But the search line is empty . 

In this case i need my AppleID credentials . I have pinned them in the database .

But when the autofill extension can't find items because the search bar is empty , it would be nice to have my pinned items here ;)

**Comment by strongbox-mark** [comment]
I guess it's not a bad idea to display pinned items below the search results... Let's go with that.

**Comment by strongbox-mark** [comment]
This is now available with 1.52.8 :)
