### ISSUE TITLE
Extend the area for show password button

### ISSUE THREAD

**Issue by sorhu** [strongbox-password-safe/Strongbox#368]
I don't like having passwords in my clipboard.

Unfortunately, tapping on the show password icon very often leads to activating copy password option as the icon is small. Especially on old iPhone SE screem...

Example:
When I tap on a marked area I got myseld a password in the clipbord which I don't wont to happen
![1](https://user-images.githubusercontent.com/49325622/86582882-a732cf00-bf82-11ea-8ae4-b532271392e1.png)

Proposal:
Extend the area that would activate show password option:
![2](https://user-images.githubusercontent.com/49325622/86582983-d0ebf600-bf82-11ea-852b-c9a0d33059c1.png)

**Comment by strongbox-mark** [comment]
Yes, good point. Thanks for raising, I've done this myself more than a few times too.

**Comment by strongbox-mark** [comment]
This should be fixed for you now with 1.49.8. Cheers!

**Comment by pbacz** [comment]
@strongbox-mark 
It work fine now. Thanks!

**Comment by sorhu** [comment]
@strongbox-mark 
It works fine now. Thanks!

**Comment by strongbox-mark** [comment]
Thanks @sorhu
