### ISSUE TITLE
<!--Please replace FORMULA in the title to the name of formula you want to be bottled-->

### ISSUE THREAD

**Issue by JavaDevStudent-MM** [strongbox-password-safe/Strongbox#370]
- - - 

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] checked that there aren't other open issues for the same formula bottle request?
- [ ] does the FORMULA not have the `bottle` block?
- [ ] ran `brew install FORMULA` and it succeeded?

_Originally posted by @JavaDevStudent-MM in https://github.com/JavaDevStudent-MM/linuxbrew-core/issues/1_

**Comment by strongbox-mark** [comment]
Reported for spam. Closing out. Please do not post nonsense in this repository again. It costs time and effort to report.
