### ISSUE TITLE
Share iOS crash to email doesn’t fill in email address

### ISSUE THREAD

**Issue by LegoChicken** [strongbox-password-safe/Strongbox#371]
Had a crash. Tried to share the crash via email. Dialogue box showed email address but when shared via email using Gmail app the address wasn't present so don't know where to send the report.

**Comment by strongbox-mark** [comment]
Thanks @LegoChicken - Can you send the info from the Preferences > About > Debug Info text box to support@strongboxsafe.com?

**Comment by LegoChicken** [comment]
I've sent the original crash details by email as I had the compose still open. Can you pass the email address via share to the email app?

**Comment by strongbox-mark** [comment]
Unfortunately no! Which is why this is so awkward. It's possible to do this for the built-in iOS Mail app but not via the Share sheet :( 

Thanks for sharing the crash, the issue has been fixed and will be available in the next release coming probably at the end of the week.

**Comment by LegoChicken** [comment]
Oh OK. As I use Gmail I decided to the Gmail app rather than the iOS email app as it works better with Gmail and I'm used to it (from Android). If (when :-)) I get another crash I'll send via email using the iOS app.
