### ISSUE TITLE
"Allow Apple Watch" toggle is misleading

### ISSUE THREAD

**Issue by WannabeSmith** [strongbox-password-safe/Strongbox#372]
If a user sets the “Allow Apple Watch” toggle to “off” while they have their password database open, they might mistakenly think that an adversary would now be unable to use a paired Apple Watch to get into their database. However, this toggle can be set back to “on” even after the database is locked, and without access to the master password. 

Maybe the “Allow Apple Watch” toggle belongs in the "Database > Database & Touch ID Properties” section since this appears to be locked when the database is locked.

**Comment by strongbox-mark** [comment]
Yes, I think you're right. This should be a database specific setting too. Thanks!

**Comment by strongbox-mark** [comment]
This is now the case with 1.15.4 - Touch ID/Watch settings are per database and can be set only when a database is unlocked.
