### ISSUE TITLE
Can't use Apple Watch but not Touch ID (and vice versa)

### ISSUE THREAD

**Issue by WannabeSmith** [strongbox-password-safe/Strongbox#373]
In the Strongbox settings, the user can choose to use Apple Watch and Touch ID to log in, but not one of them alone.

It would be nice if the user could use just Apple Watch but disable Touch ID since the Apple Watch has an extra layer of protection (passcode on the watch) while Touch ID doesn't. Moreover, if the user must use both when they only intended to use one, increases the attack surface.

**Comment by strongbox-mark** [comment]
Yes, I think this is worthwhile. Thanks for raising. So ability to choose 

- Just Watch, 
- Just Touch ID
- "Either Watch OR Touch ID"

**Comment by strongbox-mark** [comment]
This is now available on 1.15.4. Going to close this out, please raise a separate issue if there are bugs.
