### ISSUE TITLE
Open database outside strongbox folder on iOS

### ISSUE THREAD

**Issue by keitalbame** [strongbox-password-safe/Strongbox#376]
The documentation mentions that is not possible to open a database from outside strongbox folder in iCloud Drive. This is true on iPad OS 13.5.1 but I’m able to open the files from outside of strongbox folder on iOS 13.5.1.

**Comment by strongbox-mark** [comment]
This definitely is possible via iOS Files, so that documentation could be out of date. Where did you see it?

The native/old school iCloud method uses only the Strongbox folder... You can find more info here:

https://strongboxsafe.com/hrf_faq/what-is-the-best-way-to-use-icloud/

**Comment by keitalbame** [comment]
> This definitely is possible via iOS Files, so that documentation could be out of date. Where did you see it?

I saw it in FAQ, 1st entry(I cannot see a database I added in iCloud, where is it?) >> https://strongboxsafe.com/faq/

Meanwhile, I tried again to open a keepass file from other folder and is now working on my iPad.

At the time I opened the issue, There was no update available(forgot to checked the installed version).
Today I tried with 1.48.19 (installed 2 days ago) and it worked. Have to install the .20 version.

Not sure it the .19 version helped in some way or iCloud was messing around with incomplete syncs.

In some ocasions, when trying to add the file did not throw any errors(but not adding it) and sometimes was complaining about file size/Argon settings. The database file had ~170kb.

**Comment by strongbox-mark** [comment]
That FAQ is definitely out of date. I've updated it now. Previously iOS Files wasn't available as a method for adding a database.

No of the recent versions have changed anything really here with iCloud so it's unlikely your issues are related to a code change.

You should only get file size or Argon warnings when you open the database in Auto Fill mode (e.g. inside Safari or something like that). At 170KB the warning won't be about File Size, so perhaps double check your Argon2 memory setting... 

Is it about 64MB? This is likely to probably crash Strongbox when opened in Auto Fill mode.

**Comment by keitalbame** [comment]
> You should only get file size or Argon warnings when you open the database in Auto Fill mode (e.g. inside Safari or something like that). At 170KB the warning won't be about File Size, so perhaps double check your Argon2 memory setting... 
> 
> 
> 
> Is it about 64MB? This is likely to probably crash Strongbox when opened in Auto Fill mode.

Can you point out where to find this setting? I searched in both strongbox and database options and did not find anything related.

**Comment by strongbox-mark** [comment]
You can find the value in Strongbox by unlocking your database > Preferences > Statistics & Properties > Argon2 Memory...

Unfortunately you cannot set it yet in Strongbox, you would need to use a Desktop tool like KeePassXC or KeePass to change it... If you set it to something like 32MB you should have no issues in Auto Fill mode.

**Comment by keitalbame** [comment]
I did not find nothing mentioning Argon.
Adding screenshot from database properties field
![image](https://user-images.githubusercontent.com/16195977/88215683-f13ed480-cc53-11ea-929b-5b1ccc5e5d50.png)

**Comment by strongbox-mark** [comment]
That's strange @keitalbame - Do you know what your AES iterations are set to? You can find this in Security settings in KeePassXC? It may be high enough to peg the CPU and be terminated. Does it take a long time to unlock this database in normal mode?

**Comment by keitalbame** [comment]
@strongbox-mark No time at all. Almost instant. Never had issues while opening the database on all devices. I will check in keepassxc and let you know. I did not had issues in the meantime.

**Comment by strongbox-mark** [comment]
Thanks @keitalbame

**Comment by keitalbame** [comment]
Just checked in KeePassXC and encryption iteration is set to 1s. Min is 100ms and max 5s.

**Comment by strongbox-mark** [comment]
Thanks. Are you still having trouble unlocking in Auto-Fill mode?

**Comment by keitalbame** [comment]
No, we can close the issue for now. Thanks for the quick replies :)

**Comment by strongbox-mark** [comment]
Thanks @keitalbame
