### ISSUE TITLE
Improvement for OTP create screen

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#378]
Hi Mark , 

is it possible for you that the app can import a picture with a QR-Code and the app reads this code ? 

Problem : 
On some sites you only get a QR code (without a Nummer) . 

When you don't have a second device near you you can't add the QR-code into the database

**Comment by dan-el** [comment]
Usually sites offer an alphanumerical code option. Would be interesting to know which sites don’t. So far I did not come across any.

**Comment by strongbox-mark** [comment]
Maybe the best way to fix the second device problem here is for Strongbox to be able to Display a TOTP QR Code you can scan with your second device? Seems like a good way to fix this and also provide another useful function... Thoughts?

**Comment by F3000** [comment]
Should be possible . My second device is an iPad .

**Comment by strongbox-mark** [comment]
You can now scan a photo you've taken when creating an TOTP for an entry. You can also generate the TOTP QR Code by long tapping on it in Item Details so I believe all aspects of this are covered :)
