### ISSUE TITLE
bug: can't copy any item and can't back to Home page

### ISSUE THREAD

**Issue by nkiki** [strongbox-password-safe/Strongbox#383]
ios14

chekc this video  [https://i.imgur.com/VLa9fkf.mp4](url)

**Comment by strongbox-mark** [comment]
Thanks @nkiki - I'm afraid I can't support iOS 14 beta issues at the moment. Hopefully Apple will fix this shortly.

**Comment by nkiki** [comment]
thanks for your reply, but I tried KeePassium doesn't have this issue. lol

**Comment by strongbox-mark** [comment]
No worries at all.

**Comment by nkiki** [comment]
Done!
