### ISSUE TITLE
iOS: Format of mod date is different between AutoFill and main app

### ISSUE THREAD

**Issue by Slummi** [strongbox-password-safe/Strongbox#387]
Just a minor cosmetic issue:
The format of the modification date in the database list is different between AutoFill and main app.

Here‘s an example from the main app (German):
![B0A93C8A-7427-43E7-BD22-8719656481B8](https://user-images.githubusercontent.com/42265381/89577784-79ff6800-d831-11ea-80b0-a7ce26b43fdc.jpeg)

And here‘s the same database list in AutoFill view:
![CD82D5B1-7F5B-4101-AD98-50434F727600](https://user-images.githubusercontent.com/42265381/89577847-93a0af80-d831-11ea-8997-8f6f6a4e7947.jpeg)

Strongbox 1.49.0
iOS 13.6
iPhone X

**Comment by strongbox-mark** [comment]
Good catch. Will be a quick fix in the next release.

**Comment by Slummi** [comment]
Thanks for the quick fix with 1.49.2!
