### ISSUE TITLE
TOTP is custom field no longer automatically recognized

### ISSUE THREAD

**Issue by kumabon** [strongbox-password-safe/Strongbox#388]
I have a custom field in my database containing TOTP info (i.e. otpauth://totp/xxx@yyy.com?secret=ZZZ).

They used to be automatically recognized by Strongbox, both iOS and macOS versions, but I just noticed they do not do it anymore. Instead, I could manually add a TOTP field again. I am not sure which version was this feature added.

I really prefer the prior implementation for my usage, and I wonder if there is a good reason for the change, and whether the prior behavior can be preserved.

Thanks.

**Comment by strongbox-mark** [comment]
Hi @kumabon - Nothing has changed recently in Strongbox here. Has anything changed with your other clients? Do you use KeePassXC/KeePass? 

Is the TOTP visible in Details view or Browse/List View, or missing from both?

How do/did you add these originally?

**Comment by kumabon** [comment]
My apologies @strongbox-mark - This is my fault for an erroneous bug report. I tested this again with a known-good file and its working as expected. The earlier report was based on a defective file.

Thanks for the prompt response!
