### ISSUE TITLE
Database not reloaded

### ISSUE THREAD

**Issue by eric969** [strongbox-password-safe/Strongbox#389]
The database is not synced wen open the remote ( the key-password changed are not visible) :
even when forcing the reload in the iOS app menu.
I must recreate the database at each time, it is very annoying ...

version:  Strongbox Pro 1.49.1
IPadOS 13.5.1
remote: synology SDrive remote file

**Comment by strongbox-mark** [comment]
Hi @eric969 - I'm afraid this is a known issue with the Synology/DS File app iOS Files integration.

The only real way to connect to a database on Synology NAS is via SFTP or WebDAV which you would need to install/configure.

There is no possible way for Strongbox to fix this issue as it lies with the DS File app integration.
