### ISSUE TITLE
Simple UI for cloning entry with references

### ISSUE THREAD

**Issue by jtkohl** [strongbox-password-safe/Strongbox#390]
I can manually create a new entry that refers by UUID to another entry's username and password, but I'd much rather a simple UI for this, something like a "clone" operation similar to options in KeePass XC for Mac or Windows.

(You probably know why REFs are handy, such as having the same account used by login pages at foo.com and foo.net depending on which part of Foo's web site you go to)

I'd suggest the operation create the title as `CLONE: <original title>`, the username and password as `{REF:U@I:<uuid>}` and `{REF:P@I:<uuid>}`, and the URL blank, possibly the focus of the app after cloning.  Then the user can add the new URL and go edit the title as desired.

**Comment by strongbox-mark** [comment]
Thanks @jtkohl - Good idea - There is a feature already to Duplicate an entry but it should come with an option to reference the source password instead of copying if the DB supports it (KeePass)

**Comment by strongbox-mark** [comment]
Option to keep/preserve source timestamps should be on this advanced clone/duplicate dialog... as requested in #188

**Comment by strongbox-mark** [comment]
Hi all, this is available now in 1.53.0. You can make references to username/passwords and choose to preserve timestamps. Please open new issues if you see any problems.
