### ISSUE TITLE
iOS Renaming a database doesn't refresh the database list

### ISSUE THREAD

**Issue by Slummi** [strongbox-password-safe/Strongbox#392]
Again just a small cosmetic issue...
After renaming a (local) database in the database list, no refresh of the list is performed. So you can't see, if renaming was successful.

Strongbox should automatically refresh the database list after renaming.

--
Strongbox 1.49.3
iOS 13.6.1
iPhone X

**Comment by strongbox-mark** [comment]
Should be fixed in next update 👍

**Comment by strongbox-mark** [comment]
Should be fixed for you in 1.49.4 @Slummi

**Comment by Slummi** [comment]
Thanks for the quick fix @strongbox-mark !
