### ISSUE TITLE
"Enter“ key to proceed in auto fill screen

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#395]
Hi Mark , 

I have a suggestion for this screen:

![image](https://user-images.githubusercontent.com/8161283/90966838-b260a080-e4d7-11ea-818d-26b08d01a84c.jpeg)

Is it possible that when auto fill find only one matching entry the user can press "Enter" on a external keyboard and the login credentials are filled out ?

**Comment by F3000** [comment]
I have tested this out . It's working :) 


I would put this setting also in that main app e.g. in database Setting because when you have a device with Face ID you don't have the chance to tip the settings (gear) icon .

**Comment by strongbox-mark** [comment]
But you do have the opportunity once you unlock using Face ID and you can always get to the Auto-Fill settings by selecting "Passwords" instead of a particular Quick-Type entry. I think I'd like to keep these settings internal to Auto-Fill...

We can keep this open as the original feature , allow keyboard Enter to progress/select credentials

**Comment by Slummi** [comment]
But you can't go back to the AutoFill settings when you are on a site where AutoFill will only find a single matching entry. In that case the credentials are filled in immediately and you will leave the AutoFill dialogue.
But I like the idea that the AutoFill settings are placed in the AutoFill dialogue. You can solve the problem with the settings by letting FaceID fail (hide the sensor, look away) and then press 'Cancel'. After that you are in the database list of AutoFill and you can go to the settings.

**Comment by strongbox-mark** [comment]
That's fair - I guess these settings should be available from the main app... #397 created to track...

**Comment by F3000** [comment]
Thanks both 👍

**Comment by strongbox-mark** [comment]
Enter to proceed is now in place with 1.50.5 - Could you confirm and close?

**Comment by F3000** [comment]
Where can I find the setting ?

**Comment by strongbox-mark** [comment]
No setting for this at the moment, but Enter should just work...
