### ISSUE TITLE
Display custom icons for folders when moving an item

### ISSUE THREAD

**Issue by Slummi** [strongbox-password-safe/Strongbox#398]
Just cosmetic. When you are moving an item to another folder, the folders in the list of available target folders have default icons instead of custom icons.

Strongbox should display custom icons.

Strongbox 1.49.8

**Comment by strongbox-mark** [comment]
Good spot, hadn't noticed that. Thanks @Slummi

**Comment by Slummi** [comment]
Thanks for fixing in 1.50.6
