### ISSUE TITLE
Feature Comparisons page rendering on website

### ISSUE THREAD

**Issue by waynebloss** [strongbox-password-safe/Strongbox#399]
The [page for Feature comparisons at strongboxsafe.com](https://strongboxsafe.com/feature-comparisons-ios-mac-free-pro/) renders incorrectly on Chrome / Linux:

![image](https://user-images.githubusercontent.com/623736/92312704-4b3ff300-ef91-11ea-8128-182296f20d95.png)

It works in Firefox.

I tried also in Chrome without any extensions enabled and it still fails.

Chrome on Windows works fine. Not sure what the problem could be.

**Comment by strongbox-mark** [comment]
Strange, this is changing soon, so it should render correctly everywhere. Thanks for the report.

**Comment by strongbox-mark** [comment]
This should be a lot better for you now with the new website at:

https://strongboxsafe.com/comparison/
