### ISSUE TITLE
[Feature request] Support two different Yubikeys, for backup

### ISSUE THREAD

**Issue by zlorb** [strongbox-password-safe/Strongbox#404]
One may want to have an ability to recover from damaged/lost hardware key, by using another hardware key which was programmed before losing the first one. (iOS/mobile and MAC)

**Comment by strongbox-mark** [comment]
Hi @zlorb - You can do this already by making sure your second (or additional) YubiKeys are programmed with the same "Secret". This is the only way to do what you want.

**Comment by zlorb** [comment]
Thanks Mark for the quick response. I've tried that. The problem might be that the two keys use different interfaces - one key is NFC and other is lightning.

**Comment by strongbox-mark** [comment]
Hi @zlorb - I'm fairly certain it won't because of the interface. The keys just do a very simple HMAC with the key, no matter what the interface... 

One to check is to make sure you are using the right key on both, but also that you have both programmed with either "Fixed" or "Variable" length input. This is a switch on the Yubikey Manager/Personalization tool that will affect whether the keys work the same or not with KeePass.

**Comment by zlorb** [comment]
The two keys are configured the same way, same fixed inputs, same secrets and same PIN numbers.
Changing between lighting slot and NFC slot, only one is working (with the corresponding key), while the other returns an error about incorrect credentials. My hope was that with everything configured the same on the keys, pointing Strongbox to either slot-key pair will work.

**Comment by strongbox-mark** [comment]
Hi @zlorb, What do you mean when you say "PIN numbers" and "with the corresponding key" exactly? Those phrases do not make sense in this context for me.

If the two keys are programmed the same this will work, there's no way for it not to. They are doing a very simple HMAC... 

Cam you describe the platform, and tools you are using to program the YubiKeys?

You can use the 2nd slots if available to perform tests on a new dummy database if you prefer... This setup works for me using a 5Ci and an NFC Yubikey

**Comment by zlorb** [comment]
Hi @strongbox-mark,
I've followed the instructions on https://support.yubico.com/support/solutions/articles/15000006427 on how to setup HMAC-SHA1 Challenge-Response, and have each of the configurable values set to be the same on slot 2 of each of the keys. This is using the YubiKey manager on a Mac. I'll try a dummy database shortly and update.

**Comment by strongbox-mark** [comment]
Thanks @zlorb - there must be some kind of difference.

The Secret workaround field might be useful for debugging here too... but we can go into that later

**Comment by zlorb** [comment]
Tried with a new database and got the same behavior - only one of the keys is accepted as valid. 
Will go through all the steps again and see if I missed anything.

**Comment by zlorb** [comment]
Okay - found the configuration discrepancy between the keys and got it fixed. Working as expected now.
Thanks for the support along the way.
