### ISSUE TITLE
Monitor for External File Changes - does not work properly - MAC OS

### ISSUE THREAD

**Issue by kissi7** [strongbox-password-safe/Strongbox#408]
Feature "Monitor for External File Changes" does not work properly. It determinate external file only once! any other changes are ignored.

How to reproduce.
1 Launch Strongbox on your MAC and open DB from iCloud.
2 Make same changes in DB on iCloud (for example on mobile app) and save changes
3 Strongbox app which is still running on the MAC determinate change in DB and ask to reload. (click yes, to reload)
4 Make some other external changes
5 Strongbox does not determinate any new changes.

Expected behaviours:
Strongbox will monitor external changes in DB all the time it is running.

**Comment by strongbox-mark** [comment]
Can confirm this behavour - definitely a bug. Thanks for raising...

**Comment by strongbox-mark** [comment]
This should be fixed for you now in 1.13.20 - can you confirm and close?

**Comment by kissi7** [comment]
Hello, I just tried and it looks good now. You can close this issue. Thank you for FIX.
