### ISSUE TITLE
Could not unlock database

### ISSUE THREAD

**Issue by catrachotech** [strongbox-password-safe/Strongbox#411]
I'm using MacOS and with the app from the appstore I can open the file. Error "invalid database. Pws :[NO PWS3]. I'm using Google drive. It only happens on MacOS.
Any fix for this issue?

**Comment by strongbox-mark** [comment]
Hi, 

There should be a little extra info including the prefix bytes of the file which will help debugging. Could you send that/screenshot to support@strongboxsafe.com?

It's very likely that what Strongbox is trying to open is not actually a database file. 

Also, please let me know if you're using cryptomator or other intermediate encryption software on the way to/from Google Drive.

**Comment by strongbox-mark** [comment]
Did you manage to fix this? @catrachotech

**Comment by catrachotech** [comment]
Hi Mark,

Thanks for following up on this. After a lot of throubleshooting the only
way I can make it work is by making a copy of the file to the desktop. For
some reason if the file is in the Google drive is doesn't work. Do you have
any idea why the file cannot be opened from the Google drive? May be some
type of encryption is going on? Ps. I don't see any setting for encryption.

**Comment by strongbox-mark** [comment]
Thanks! 

Is this a corporate Google Drive?

There should be a little extra info including the prefix bytes of the file which will help debugging. Could you send that/screenshot to support@strongboxsafe.com?

**Comment by strongbox-mark** [comment]
This looks to be related to using the Key File field with a Password Safe database...
