### ISSUE TITLE
Potential bug with duress pin. 

### ISSUE THREAD

**Issue by milesmcclane** [strongbox-password-safe/Strongbox#413]
When setting a duress passcode, it has to be the same length as the original passcode. 
I’m sure this hasn’t always been the case. Is this intended?
My passcode is somewhat longer than I would like my dummy one to be.

**Comment by strongbox-mark** [comment]
Yes, this is a deliberate decision. The idea behind it is that say a malicious actor was able to view you entering your real PIN though the might not be able to see the digits, they may be able to count the Masked digits or the maybe able to determine the number of key presses... 

Then if they ask/force you under duress to enter your PIN and you entered a different number it would be immediately obvious that you're using a Duress PIN or that something funny was up.

The second reason is that it also works with the Instant PIN unlock system (which knows the length of your PIN and automatically tries it after the correct number of digits so you don't have to hit Enter).

This isn't something I'd be crazy about changing.

**Comment by milesmcclane** [comment]
Ok, I understand that point of view and agree with you now you have mentioned it. 

My issue: Say my pin is 14 digits long, I can do those 14 digits with my eyes closed backwards and upside down. My idea of the duress pin would be just type 4 digits (maybe the first for of your actual pin) to remain sure and fast at entering it during the charade. 

I wonder if there is some sort of implementation whereby you could enter *any* digits that total the  number of digits one has for the pin? Could be also a dangerous situation I suppose, if asked to verbally state the random numbers you just typed, but couldn’t. 

Just not sure about my ability to remember and enter a little used long duress pin with any confidence as to be believable. 

My conclusion (after writing all this!! Sorry!!) is that you’re right and I just need to learn a similar length duress pin and stop being a whiner! 
This issue can be closed 👍
