### ISSUE TITLE
iOS 14 Bug : search in auto fill extension doesn’t work

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#414]
Hi mark ,

on my device I can't search something here . When I click in the search field I see no keyboard .

Only in auto fill screen . When I open the app it works 

iOS 14.0.1 / iPhone 11

**Comment by strongbox-mark** [comment]
I believe this is an iOS 14 bug @F3000 - Should be fixed by Apple soon!

**Comment by F3000** [comment]
Hopefully 👍 we will wait

**Comment by strongbox-mark** [comment]
Is this fixed in 14.0.1 do you think?

**Comment by F3000** [comment]
I have installed ios 14.1 now and actually i don't see it on my iPhone . 

On iPad i never heard the problem . 

I would suggest to leave it open until 14.2 is released and maybe some others can also verify that this is fixed ☺️

**Comment by F3000** [comment]
Today I have setup a new iPhone .

I have the same problem as before

**Comment by strongbox-mark** [comment]
Super strange indeed... 

Could you try with 1.50.1 (you'll probably need to search for Strongbox on the App Store to see the Update button).

Could you give that version a try and let me know if it helps at all? 

If it doesn't, try tapping the Preferences button (Gear icon) bottom right and seeing if it helps.

**Comment by F3000** [comment]
So I have tried with 1.50.2/3 on my new phone . 

I think it is fixed now 😀

**Comment by strongbox-mark** [comment]
Thanks @F3000 - Closing out :)
