### ISSUE TITLE
Support for Google Titan Security Key

### ISSUE THREAD

**Issue by hul-rah** [strongbox-password-safe/Strongbox#417]
I like Strong Box and the MFA option for using a Security Key. Currently Strong Box only supports Yubikey, which you have to configure for a challenge response to be used with strongbox based on these [instructions](https://strongbox.reamaze.com/kb/yubikey/how-do-i-create-a-yubikey-protected)
I'd like to request an enhancement where Google Titan security keys are also supported as well. I am assuming some configuration of challenge response similar to Yubikey will be required. 

Thanks,
-- R

**Comment by strongbox-mark** [comment]
Hi, Thanks for the feature request. Do you know if these keys support HMAC-SHA1? and also if there is an iOS/Mac library for that?

**Comment by hul-rah** [comment]
hi Mark, sorry, I couldn't find anything on on SDK on google's developer page.

**Comment by strongbox-mark** [comment]
OK thanks @hul-rah - I couldn't find anything on this either.

**Comment by strongbox-mark** [comment]
I think without further detail this is unlikely to be a runner
