### ISSUE TITLE
[Feature request] force password after x amount of time when using Watch unlock 

### ISSUE THREAD

**Issue by kresdjan** [strongbox-password-safe/Strongbox#418]
I love the using Watch unlock feature. However, I think it would be great to have the option to force a user to type the master password once in awhile to keep it fresh in ones memory and not forget it.

**Comment by strongbox-mark** [comment]
Hi @kresdjan - This is already available under the Database > Database Preferences menu item

**Comment by kresdjan** [comment]
@strongbox-mark Indeed it is!!! I'm amazed that I didn't find that. Thanks.
