### ISSUE TITLE
App freeze after entering PIN code or Face ID.

### ISSUE THREAD

**Issue by coxde** [strongbox-password-safe/Strongbox#420]
Hi,

I'm experiencing a bug where the app won't unlock the database and freezes when I enter PIN (same when I try to use Face ID). Strangely enough, as far as I can remember, this bug only happens at night (with night mode and sleep mode enabled) and during the day it automatically goes back to normal. I wonder if this has something to do with iOS 14 or these modes? 

Thank you!

By the way, it also makes the app freeze when I click "Manual" on the PIN input interface.

Edit: I use Nextcloud (WebDAV) to connect to my database.

**Comment by strongbox-mark** [comment]
Sounds very strange. Could you specify App Version, OS Version. Does a restart help? Is this in AutoFill mode or regular App?

**Comment by coxde** [comment]
App Version: 1.49.21
OS Version: iOS 14.0.1
Both autofill and regular App have this problem.
And I tested it: turning on sleep mode or dark mode manually doesn't cause this problem, but it happened again last night when both modes were turned on automatically. I'll try a reboot when it happens tonight and let you know.

**Comment by coxde** [comment]
Update: Very strange, I test tonight and it completely normal. I'll keep track for a few days.

**Comment by coxde** [comment]
Update: The bug appeared again last night after sleep mode enabled,but after restarting it was back to normal.Also I did a few tests at random times during the day and everything was fine.

**Comment by strongbox-mark** [comment]
Thanks for the update. Could you upgrade to 1.49.22 and see if the issue persists?

**Comment by coxde** [comment]
Just upgraded, I'll keep tracking and let you know.

**Comment by coxde** [comment]
It seems to work, the bug has not reappeared since the upgrade. I'll keep track to confirm this!

**Comment by strongbox-mark** [comment]
Excellent, will leave open for another few days just in case.

**Comment by coxde** [comment]
Unfortunately, although everything worked fine on the first night, the bug appeared again on the second night...It's really confusing.

**Comment by strongbox-mark** [comment]
Yes, that's quite strange indeed. Would you be able to send me the debug information from the About screen?

**Comment by coxde** [comment]
OK, just send to support@strongboxsafe.com

**Comment by strongbox-mark** [comment]
Any news on this @coxde ?

**Comment by coxde** [comment]
> Any news on this @coxde ?

No, everything works perfectly now. Thank you!
