### ISSUE TITLE
UI Issue with Expiration Date/Time Functionality 

### ISSUE THREAD

**Issue by shad0whawk** [strongbox-password-safe/Strongbox#425]
The expiration date and time functionality don’t appear to render correctly when entering or editing a these elements. Maybe this is how it’s supposed to be now but it seems off.  I’m running version 1.50.0 on an 11 Pro Max running iOS 14. 

![Image](https://i.imgur.com/7MhHiin.jpg)
![Image](https://i.imgur.com/EYp5L89.jpg)

**Comment by shad0whawk** [comment]
If I select the date or time, an overlay appears where I can pick the value. I was expecting the calendar or date picker to pop up between the Cancel/Set menu and the date in the lower left. Either way, there’s a noticeable gap between the Cancel/Set menu and the date in the lower left where you can see the contents of the window beneath it.

**Comment by strongbox-mark** [comment]
Yeah, super weird, this used to work! 

You can still get the pickers by tapping on the Date/Time and you can still Set, so this is cosmetic but I think it must be a nice Apple iOS 14 issue... Thanks @shad0whawk

**Comment by strongbox-mark** [comment]
Should be fixed in 1.50.1 for you

**Comment by shad0whawk** [comment]
Yes it looks good now. Thanks for the quick fix!
