### ISSUE TITLE
Feature Request: credit-card specific expiration date handling

### ISSUE THREAD

**Issue by acrollet** [strongbox-password-safe/Strongbox#426]
Thanks for your hard work on this project! I'm a happy premium user.

I would consider it a big UX improvement if it was possible to only enter the month and year for credit card expiration dates. This is how they're shown on the card, and it adds mental overhead to think through what day and time one should enter when adding a card and reading the entry.

**Comment by strongbox-mark** [comment]
Thanks! Yes, I think this will probably fall under the "Templates" feature which is being considered in conjunction with the KeePassXC initiative [here](https://github.com/keepassxreboot/keepassxc/issues/863)... Good idea.

**Comment by milesmcclane** [comment]
I’m very much looking forwards to templates 👍 excellent.

**Comment by F3000** [comment]
Good idea 👍

**Comment by strongbox-mark** [comment]
This is probably best dealt with in #281 - WIll close this out with reference to that...
