### ISSUE TITLE
TTOP in notes of a Password Safe db

### ISSUE THREAD

**Issue by Ben-Voris** [strongbox-password-safe/Strongbox#428]
Mark, in [Thoughts on TOTP/HOTP support in PasswordSafe?](https://sourceforge.net/p/passwordsafe/mailman/message/36778451/) you said that Strongbox stores TTOP information in the notes field. What I see is something like this, including the dashed line:

```
-----------------------------------------
Strongbox TOTP Auth URL: [otpauth://totp/...?secret=...&algorithm=SHA1&digits=6&period=30&issuer=...]
```

My question is, does Strongbox place any restrictions on other entries in the notes field? For example must these two lines come first? If so, does Strongbox care if anything follows those two lines?￼

**Comment by strongbox-mark** [comment]
Hi Ben, no it doesn't matter where this is, usually it's appended on to the end of the notes, but it doesn't have to be at the end.

**Comment by Ben-Voris** [comment]
Is the dashed line important? It's not that I would intentionally delete it but if I accidentally remove a dash or two, would that prevent strongbox from finding the URL?Obviously, I'm trying to find out how careful I must be.

**Comment by strongbox-mark** [comment]
It is not important for the OTP function - Strongbox only looks for an OTPAUTH scheme'd URL in the notes.

However, Strongbox looks for this when you instruct it to "Clear" or "Remove" the TOTP code from an entry, so interfering with this will lead to Strongbox not being able to remove the TOTP code (fairly minor issue).

**Comment by Ben-Voris** [comment]
Thank you for the quick responses.
