### ISSUE TITLE
Cosmetic Feature Request: Big Sur Icon Padding

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#430]
Hi Mark,

Any chance you could change the icon padding to match the new Big Sur style? Basically there is more padding now.
About 50px in a 512px icon. See screenshot as reference.

I know it's not important, but it drives me nuts :-)

Thank you!

<img width="48" alt="Screenshot 2020-11-18 at 18 09 12" src="https://user-images.githubusercontent.com/19776691/99563415-861aca00-29c9-11eb-874e-2e8270753a65.png">

**Comment by strongbox-mark** [comment]
Ha, weird I thought this would have been automatic - do you have a link to any docs on this?

**Comment by Slummi** [comment]
That‘s a feature: The best apps get the biggest icons. ;)

**Comment by dan-el** [comment]
This page has the SF Symbols app as well as icon templates for iOS and macOS: [https://developer.apple.com/design/resources/](https://developer.apple.com/design/resources/)

And this page has the Icon design guidelines: [https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/)

Cheers!

**Comment by strongbox-mark** [comment]
OK, they're the standard guidelines but I thought you might have something else you've seen somewhere. I'll have to look into this...

**Comment by dan-el** [comment]
I created a 512px transparent template I use for other purposes myself. The corner radius is not exactly as in the design guidelines, but it's more or less okay. Happy to share if that helps you.

There are templates in the Photoshop files in the design guidelines. if you want me to extract them for you let me know.

**Comment by strongbox-mark** [comment]
Hi @dan-el - This should be fixed for you now with 1.14.4. Could you confirm and close?

Also, would you like to join the Beta Testers Group? Drop a mail to support@strongboxsafe.com if so :)

**Comment by dan-el** [comment]
just beautiful. closed!

and thanks :D
