### ISSUE TITLE
Bug: Hyperlinks in notes field on macOS

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#431]
There seems to be a bug in the notes field of Strongbox on macOS. Sometimes the whole notes field will be a clickable hyperlink.

**Steps to reproduce:**
1) Create a database entry and write only a hyperlink to the notes field.
2) Next save the entry!
3) Now add more text after the link, save the entry, and the whole notes field will be interpreted as link. See screenshot at the bottom.

I noticed this does not happen if the entry is never saved with only the hyperlink in the notes. Meaning if you save with notes like "https://www.strongbox.com more text" (note the whitespace and additional text after the link) Strongbox will properly detect the hyperlink. But once it turned the whole notes field into a hyperlink all subsequently added text will be part of the hyperlink.

<img width="450" alt="link" src="https://user-images.githubusercontent.com/19776691/99911221-25ee9580-2cf3-11eb-91dc-01cabe3a5ff9.png">

**Comment by strongbox-mark** [comment]
Thanks for raising, I've noticed this myself.

**Comment by dan-el** [comment]
Did the URL field reference bug fix completely remove hyperlinks from the notes section in strongbox on macOS, or did it break? I don't have any hyperlinks anymore in the notes section starting with 1.14.9

**Comment by strongbox-mark** [comment]
Hi @dan-el - This looks to be a system bug/issue with detecting links in NSTextViews so I disabled link detection entirely until I can find a solution to this. 

Not related to the URL Field Reference bug.

**Comment by strongbox-mark** [comment]
Going to leave this one as is. You can use a URL* custom field for extra URLs

**Comment by dan-el** [comment]
I tried adding a custom field named "URL*" and also tried "URL2" and it does not get detected as URL Field. Am I missing something obvious here? (By "detected as URL" I mean I can't click it to open the URL like with the built-in URL field (Arrow Icon))

**Comment by strongbox-mark** [comment]
Ah yes, this detection is planned in a future release
