### ISSUE TITLE
'Wormhole' doesn't seem to be working on Big Sur 11.0.1

### ISSUE THREAD

**Issue by WannabeSmith** [strongbox-password-safe/Strongbox#435]
Firstly, thank you for enabling autofill so quickly. It's wonderful to see this functionality come to macOS!

For the most part, it seems to be working in Safari. However, I seem unable to make use of this 'wormhole' functionality by using TouchID etc.

I have enabled Wormhole fill and TouchID unlock in Strongbox, as well as TouchID for password keychain in macOS. For example, if I use "Keychain" instead of "Strongbox" in the autofill dropdown, I can unlock the keychain with TouchID, but when I select Strongbox, I have to enter my master password. 

Thanks again for all your hard work!

**Comment by strongbox-mark** [comment]
Hi @WannabeSmith - Thanks for that.

Wormhole, at the moment only works when you tap on a QuickType suggestion (as opposed to tapping on 'Strongbox...') - Does that explain you issue?

Would definitely consider extending this wormhole to allow search / browse if that makes things quicker easier for people.

**Comment by WannabeSmith** [comment]
I see, I think my issue was that I was not being shown QuickType suggestions. I have solved this by ensuring that my password db specifies "**https://**example.com" rather than just "example.com".
