### ISSUE TITLE
MacOS Feature Request: Move password generator/settings out of prefs and on to main app + menubar

### ISSUE THREAD

**Issue by milesmcclane** [strongbox-password-safe/Strongbox#442]
Would be great to be able to quickly access this, like you can within keepassXC. I like the option of generating passwords independently of creating an entry (as you know because I have made a simliar request for the iOS app!!)

Would be a huge extra benefit if the option to generate a password could also be an option from the menubar icon, such as apps like Password Factory and PSWD have. Clicking it would create a flyout/dropdown window containg full password control so it’s simple to quickly grab a fresh password, diceware phrase or user name etc .

I hope it’s an optioon you could consider.

Miles.

**Comment by strongbox-mark** [comment]
Yes, I like the idea, do you mean the tray icon in the top right corner or the 'Strongbox' menu in the top left?

**Comment by milesmcclane** [comment]
I mean the menu bar / tray icon on top right.

**Comment by strongbox-mark** [comment]
Got it! thanks.

**Comment by milesmcclane** [comment]
![823AA790-B085-4B18-B751-AD82021C3619](https://user-images.githubusercontent.com/27552949/102725779-9223df80-4319-11eb-8420-36d3e6c291a0.png)
This kind of thing I envisage. This is password factory. It’s a good app but a little out of date and unverifiable.

**Comment by strongbox-mark** [comment]
Very cool, it would be great to have the current Password Generation screen drop from the tray!

**Comment by milesmcclane** [comment]
Yes absolutely. I love the current generator, would be ideal for this! Was just showing you so you can see the general idea

**Comment by milesmcclane** [comment]
Would be fab if you could username generation similar to the iOS app in there also though.

**Comment by strongbox-mark** [comment]
@milesmcclane Password generator now available quickly off of the system tray icon as of 1.15.19. Feedback welcome. Will keep this issue open as I refactor the settings out of the App Preferences to more accessible locations.

**Comment by milesmcclane** [comment]
It’s working perfectly and just how I imagined.

**Comment by strongbox-mark** [comment]
That's great to hear! Shall we close this one out?
