### ISSUE TITLE
Apple Silicon build

### ISSUE THREAD

**Issue by cyayon** [strongbox-password-safe/Strongbox#444]
Hi,
Do you plan to provide soon an Apple Silicon native build ?
Thanks.

**Comment by strongbox-mark** [comment]
Hi, yes definitely planned, should be late Jan or early February I would estimate. Works via Rosetta at the moment though so this isn't urgent.

**Comment by strongbox-mark** [comment]
Just an update. Currently blocked on this issue by YubiKey's libraries which do not support Silicon yet.

**Comment by Derad6709** [comment]
What about running iOS app on silicon instead macOS?
But autofill doesn't work :(
(but for example, NordPass works)

**Comment by strongbox-mark** [comment]
@Derad6709  Yes, technically it should be possible but since there's a native Mac app this isn't a development priority right now.

**Comment by Derad6709** [comment]
> @Derad6709  Yes, technically it should be possible but since there's a native Mac app this isn't a development priority right now.

Seems like it is just one bug, which it is possible to fix, I think it's faster than wait for optimization.
I don't know how to debug macOS apps and I don't know a lot in Objective-C, but seems like it's kind easy to fix, cause NordPass works well.

**Comment by ThomasWaldmann** [comment]
@strongbox-mark Would it be an option to unblock this by compiling **without** yubikey support for a universal binary also working on apple silicon / M1?

Guess there are a lot of users with M1 but without yubikey.

**Comment by strongbox-mark** [comment]
Hi @ThomasWaldmann - I think that would be an option. I definitely can't see any issue with it in principle. I'd just like to get the whole app functionality working with M1 instead... 

It should be possible to compile the Yubico binary for M1. I was hoping Yubico would get to this, but they don't seem overly interested in that....

It's something I might have to go and figure out how to do myself I think. That means it's just a matter of prioritisation, and given how well Strongbox runs under Rosetta, it's not something that I've been able to get to just yet. Would hope to look at it in the coming months.

**Comment by ThomasWaldmann** [comment]
Yeah, it runs quite ok with rosetta. Just concerned about rumours that apple might remove / disable rosetta at some time.

Also battery and memory consumption maybe, not sure.

**Comment by strongbox-mark** [comment]
Understood, yes, I think we've got time to work on this before anything like that happens. If it did happen, it would become an immediate priority. I'm sure we'll be able to get a full YubiKey enabled build going on M1 though...

**Comment by strongbox-mark** [comment]
Hi all, Apple Silicon build now available as of 1.15.19 on the App Store now (You may need to search for Strongbox to see the "Update" button)... 

Feedback welcome.

**Comment by pszypowicz** [comment]
Hi. 

I've just updated to the 1.15.19 from the App Store. But it seems to be still listed as "Intel" process in the "Activity Monitor"

```
Strongbox 1.15.19 Debug Information at 2021-08-24 10:20:04.752
--------------------
App Version: com.markmcguill.strongbox.mac [1.15.19 (3018)]
--------------------
Device
--------------------
Model: MacBookPro17,1
CPU: Intel 80486
System Name: MacOS
System Version: Version 11.5.2 (Build 20G95)
```

<img width="1084" alt="Screenshot 2021-08-24 at 10 20 49" src="https://user-images.githubusercontent.com/2733699/130582643-7042ccef-97a8-44a5-bf4f-b80e68edab42.png">

**Comment by strongbox-mark** [comment]
Thanks @pszypowicz - That's odd... I'll investigate this later today, I may have forgotten to configure something on the App Store side...

**Comment by strongbox-mark** [comment]
Hi @pszypowicz - Could you try 1.15.20 from the App Store and let me know if that works for you as expected?

**Comment by pszypowicz** [comment]
It works, and report to be "apple" process kind.

Congrats! 🥳

**Comment by strongbox-mark** [comment]
Nice! Thanks @pszypowicz - Please let me know if you experience any issues.

**Comment by ThomasWaldmann** [comment]
Can confirm, works as "Apple Silicon"!

Strange: when I just invoke the App Store and choose "Updates" (for everything) in the Sidebar, strongbox 1.15.20 did not show up (although I had only 1.15.18 installed).

But when I go to the strongbox appstore page, it shows me the update and installed 1.15.20.

**Comment by ThomasWaldmann** [comment]
@strongbox-mark Just upgraded to "Pro", thanks for supporting Apple Silicon on macOS!

**Comment by strongbox-mark** [comment]
Thank you so much @ThomasWaldmann Really appreciate the support!
