### ISSUE TITLE
Quick Launch only in AutoFill

### ISSUE THREAD

**Issue by shad0whawk** [strongbox-password-safe/Strongbox#445]
If I enable quick launch on my main database, Strongbox automatically opens the database and AutoFill automatically opens the database. If I disable quick launch neither the app nor Autofill automatically opens the database which makes sense. What I’d like to do is allow Autofill in Safari to automatically open the database upon authenticity without Strongbox opening the database each time I launch Strongbox. Is this possible and I’ve overlooked it, and if not is it a possible enhancement?

**Comment by strongbox-mark** [comment]
It's not currently possible but not a bad idea :) Let's use this ticket to track.

I imagine a switch available in AutoFill (long tap -> Quick Launch) would be sufficient to enable/disable?

**Comment by shad0whawk** [comment]
Thanks! That would work for me.

**Comment by lukefor** [comment]
It would be really good if it was possible to define one database to Quick Launch in AutoFill, and a different database to Quick Launch on starting the app 

(Use case: separate local-only TOTP database)

**Comment by strongbox-mark** [comment]
Thanks @lukefor - Yes, I think I'd prefer an explicit Quick Launch for AutoFill config instead of relying on there being only one enabled database. 

As that's the original request I think this would also work for you without changes.

**Comment by strongbox-mark** [comment]
With 1.52.8 - You can choose a separate Quick Launch database for AutoFill (Long tap on your database > AutoFill Quick Launch)...

Along with this there is also a preference to launch a single enabled AutoFill database automatically (Default ON).

This should cover both requests. Please open any issues separately.

**Comment by shad0whawk** [comment]
Thanks that works great! One quick cosmetic suggestion…

Enabling the quick launch option adds the rocket ship icon flag to the database list, so maybe enabling the autofill quick launch option should add the planet icon flag to the database list for consistency and serve as visual cue that it’s enabled.

**Comment by strongbox-mark** [comment]
Sure, I'll see about that in the next release. If both Quick Launches are on for a database I would only show the Rocket though.
