### ISSUE TITLE
Add support for duplicating database entries

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#447]
It would be convenient if there were options like
* Duplicate Entry (with and without history)
* Move Entry (to another group (folder) inside the database - I know this is supported already from within an opened entry)

in the right-click menu that appears when right-clicking a database entry.

Additionally the "Copy Email" right-click option does not seem to work for me. I tried with custom fields named "E-Mail" and named "Email". Maybe I am missing something? (I'd love to use the CMD + Shift + E shortcut for this one)

**Comment by strongbox-mark** [comment]
Duplicate sounds like a good idea.

For Move, are you aware you can just drag and drop an entry anywhere (including other databases)? Is this in addition to that functionality.

For Copy Email, sounds like a bug (probably only works for Password Safe databases as Email is a native field there). It should be hidden for KeePass but I don't hate trying to find a field matching email or e-mail in KeePass dbs. Would you mind opening another issue for that?

**Comment by dan-el** [comment]
Hi Mark,

I opened #448 for the "Copy Email" request.

I am aware of the drag and drop option. I have a rather big database with many subfolders and if all are expanded it becomes tedious moving stuff with drag and drop. So what I usually do is use the search field to find the entries I need. I'd like to be able to move them from there - only that drag and drop becomes less viable as all non matching folders are hidden from the UI once I use the search field. BUT the more I think about it, the more I have to conclude that "Duplicate" is really the only missing option in the context menu.

Let's rename this issue to "Add support for cloning database entries" I'd say and keep the focus on what matters :-)

**Comment by strongbox-mark** [comment]
No worries, a quick way to Duplicate is just to go Cmd+C, Cmd+V which should do this for you, but always good to have a Duplicate menu item.

**Comment by dan-el** [comment]
No way, I did not know that was possible.

Can we also  use "CMD + K" as the associated keyboard shortcut to duplicate entries? (much in line with the "Ctrl + K" of KeePass)

Thanks for the Copy-Paste Hint!

**Comment by strongbox-mark** [comment]
For sure :)

**Comment by strongbox-mark** [comment]
Duplicate menu item also now available in MacOS :)

**Comment by dan-el** [comment]
Thanks, Mark!
I had hoped for CMD + Shift + K like KeePass has it in Windows, but I'll learn to love CMD + Shift + D for sure ;-)

**Comment by strongbox-mark** [comment]
Should be able to change that for you no probs

**Comment by strongbox-mark** [comment]
@dan-el - It's Cmd+K for Duplicate right? Not Cmd+Shift+K

**Comment by dan-el** [comment]
I'd say `CMD + Shift + K` since most other shortcuts also use `CMD + Shift + XYZ` and also because you seem to have "translated" the Windows `Ctrl` to `CMD + Shift` with at least one other shortcut already. Image for reference.

It's a minor cosmetic issue at most. `CMD + Shift + D` makes a lot of sense as well, I just like the reference to KeePass' `Ctrl + K` because it does not make a lot of sense to me but over time I got so used to it that I can't imagine it any other way at this point. (Much like the `CMD + K` shortcut in Finder... because K... for Konnect ;-) )

<img width="500" alt="Screenshot 2021-02-23 at 19 22 44" src="https://user-images.githubusercontent.com/19776691/108890521-f9a62600-760d-11eb-9605-52cc1823b82f.png">

**Comment by strongbox-mark** [comment]
I think I'm going to try to aim for purity here and match KeePass - We'll see how it works out

**Comment by strongbox-mark** [comment]
This is in place now with 1.15.1.
