### ISSUE TITLE
Feature Request: Add Support for "Copy Email" context menu option for KeePass DBs

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#448]
As discussed in #447 it would be great if we could have support for the "Copy Email" right-click menu option in Strongbox on macOS also for KeePass databases.

(1) Maybe that option could look for a custom field named "email" or alike. Specifically I think these custom field names could be supported values:
* email
* Email
* e-mail
* E-Mail
* E-mail

(2) Maybe this could alternatively be baked into the UI of Strongbox somehow? Let's say an "Email" field directly underneath the "Username" field which creates a custom field upon filling? (Sort of a custom field template if you will) Then this field would be linked to the right-click option.

(3) Another way could be a checkbox in the "create new custom field" dialog that could be "treat as email field".

**Every option has its downsides though...**
* (1) What if several custom fields have the same name?
* (2) Why start displaying "special" custom fields in the UI differently than others at all?
* (3) This would introduce extra logic into the saving routine assuming that only one custom field could have the box checked.

**Comment by strongbox-mark** [comment]
Cheers @dan-el

**Comment by strongbox-mark** [comment]
This should be available for you @dan-el - Strongbox uses the "Email" field for this.
