### ISSUE TITLE
macOS UI improvement: Right Click

### ISSUE THREAD

**Issue by milesmcclane** [strongbox-password-safe/Strongbox#449]
Hi Mark,

Hope you had a good festive period and a great new year! As far as is possible right now, at least.

I had a few thoughts on the Mac app UI: 

Right click.

I think the order of right click menu is a little messy. The ‘Copy’ Functions should be at the top, in order of priority;  for example - Password first, then Username, then TOTP etc etc. I use right click all the time, and the one I want is always hidden halfway down the list. The top spot in the list, ‘Item Details’, is already prioritised via a double click.
I use keyboard shortcuts for every aspect of my computing generally, including to open and search in Strongbox, but for some reason copying and pasting passwords using the mouse has always felt more fluid. 
(The new built in autofill  function will certainly mitigate all this - but for now it’s not working that well for me. Namely; the support of third parties apps etc is lacking, and with Strongbox , the current lack of an easy access password in lieu of Touch ID - although I’m aware youre working on it.)
  
Item Details.

If you’re in Item Details, it’s far to easy to accidently regenerate an already established password. There should be an edit button to prevent accidently editing of any field in this view. I know it asks you to save any changes before you close the window, if you have done something you didn’t mean to do, but I think its a bit clunky using this as a fall back for an accidental ammendment.

All minor stuff to be honest, but always worth the mention. Once again, keep up the good work.

Cheers, 

Miles.

**Comment by strongbox-mark** [comment]
Thanks @milesmcclane - good points.

**Comment by dan-el** [comment]
Let's peek at KeePass for this one?
That would be Username, Password, URL, TOTP for the copy.

I myself have no specific preference as I am a fan of the keyboard shortcuts, but I think sticking to the KeePass way might please others?

![image](https://user-images.githubusercontent.com/19776691/104072992-e5989780-520c-11eb-8963-de04e0624649.png)

**Comment by strongbox-mark** [comment]
These are in place now with 1.15.1.
