### ISSUE TITLE
Bug [macOS]: Unable to resize when the window exceeds screen resolution

### ISSUE THREAD

**Issue by TheMadRuffian** [strongbox-password-safe/Strongbox#450]
When the password exceeds a certain count during generation, the window exceeds the screen resolution limits. There seems to be no way to resize the window to click on the buttons located at the bottom.

Device: Macbook Air 13
OS: macOS Big Sur

![Screenshot 2021-01-10 at 14 02 27](https://user-images.githubusercontent.com/42994263/104116239-b5a6dc80-5351-11eb-9b4b-413b7c2de85c.png)

**Comment by strongbox-mark** [comment]
Hi, does tapping one of the other tabs help reduce the size? Is this just a cosmetic bug?

**Comment by TheMadRuffian** [comment]
Yes, tapping the other tabs does help in reducing the size. It is just cosmetic in nature.

**Comment by strongbox-mark** [comment]
This should be fixed for you in the latest Mac build.

**Comment by TheMadRuffian** [comment]
I can confirm that it is fixed.

Thanks a lot.
