### ISSUE TITLE
Can't unlock db with key file format version 2.0

### ISSUE THREAD

**Issue by james-testified** [strongbox-password-safe/Strongbox#453]
I created my db and the key file with Keypass 2.74 for Windows. The key file has the format version 2.0, which is the default and recommended setting in Keppass for Windows. When I try to unlock the db with the key file on my iOS device with Strongbox, I can't open it -> incorrect password. I can unlock the db with the key file on my Windows device without any problems. However, if I create the key file in format version 1.0 (legacy), then I can unlock the db on my iOS device with Strongobx without any problems. 

Did I oversee something or are key files in format version 2.0 not (yet) supported? 

Just let me know if you need additional information. Thank you for the great app and the outstanding support!

**Comment by strongbox-mark** [comment]
Hi, this should be working for you in 1.51.3 (iOS) and 1.14.11 (Mac) - latest on App Store. Can you confirm your version?

**Comment by james-testified** [comment]
Hi, I was still using 1.51.2 (iOS) and didn't see the new update. I have updated to 1.51.3 (iOS). Unlocking my db with the key file in version 2.0 now works flawlessly. Again thank you so much for the great support! Issue is solved.

**Comment by strongbox-mark** [comment]
Awesome thanks for letting me know.
