### ISSUE TITLE
Strongbox should use NSFileProtectionComplete for data storage

### ISSUE THREAD

**Issue by metronidazole** [strongbox-password-safe/Strongbox#454]
Strongbox currently uses the default class for file protection for storage of its data, namely NSFileProtectionCompleteUntilFirstUserAuthentication, There is no need for Strongbox to use such a low level of protection as the app is only functional when the device is unlocked.

Instead it should use NSFileProtectionComplete.

See https://support.apple.com/en-au/guide/security/secb010e978a/web

**Comment by strongbox-mark** [comment]
Thanks for the suggestion, sounds like it might be a good additional layer of security.

Can you detail a little more your interest in this and the particular types of attacks or methodologies you are concerned about here?

Can you also, if you are technically proficient, detail any possible downsides that users could expect from this?

**Comment by metronidazole** [comment]
If a high level adversary were to gain kernel-level access to your iphone *, they would immediately have access to your keepass vault. Where as if this was used, they would not.

I don't see any downsides as long as strongbox doesnt do any functions in the background - which I don't think it does?

* see https://securephones.io/main.html

**Comment by strongbox-mark** [comment]
That's a great little resource. Yes, this sounds like a good idea to me. The only issue I can think of is the AutoFill component.

The AutoFill component is a separate little module/piece of code that runs in its own process completely isolated from the main Strongbox app but it uses the Shared App Group directory to access databases. I presume it will have access to the files in there even if the main App is not running or in the background.

I suppose the best way is to make this feature available and ask people to enable and see how it goes. If that goes well, then default it on.

I'd hope to be able to enable something like this in the next few weeks, would you be willing to try it out?

**Comment by metronidazole** [comment]
> The AutoFill component is a separate little module/piece of code that runs in its own process completely isolated from the main Strongbox app but it uses the Shared App Group directory to access databases. I presume it will have access to the files in there even if the main App is not running or in the background.

I'm not an iOS dev so I'm not aware of all the nuances, but I presume the autofill component isn't doing anything if the phone is locked so it shouldn't matter?

Happy to test it.

**Comment by strongbox-mark** [comment]
Yeah nothing in the background but a separate process. I'd be 90% sure this is fine and Apple will have covered this situation but we'll see...

Cheers.

**Comment by strongbox-mark** [comment]
Hi @metronidazole - This is now available for test in 1.52.0. To enable it, go into Preferences (Gear icon in top right) > Advanced > Miscellaneous > Complete File Protection - Switch this ON.

Could you let me know how it goes?

I will ask the Beta Testers to also enable it and see how it goes for them. My testing has all been positive.

**Comment by Slummi** [comment]
I‘m already testing it. So far I haven't seen any problems.

**Comment by metronidazole** [comment]
Awesome.

Doing some quick testing, I haven't encountered any issue yet.

**Comment by shad0whawk** [comment]
Same here--no issues so far

**Comment by strongbox-mark** [comment]
Great, all going well, I'll default this on in about 1 month.

**Comment by Ben-Voris** [comment]
So far, no visible change￼.￼

**Comment by strongbox-mark** [comment]
This is defaulted on now for new users. In the coming weeks if there are no issues, it will be turned on for all users. Looks to be a fairly pain free change...

**Comment by strongbox-mark** [comment]
This is now defaulted on for everyone with 1.52.7. Thanks for the suggestion and the feedback all.
