### ISSUE TITLE
Per database column preferences

### ISSUE THREAD

**Issue by milesmcclane** [strongbox-password-safe/Strongbox#457]
Hi,

The preferences I set in the outline view to dictate which column I want to show reset after restart or app lock.

I use several databases, and I have these preferences set a little different for each one. On would assume they should be kept after a restart, so I guess it's a bug? If not, can it be a feature request please?

Also, could you explain what you mean in preferences/outline view by title is editable? I click it and it doesn't seem to do anything. I got excited for a second as I thought it could mean that the title of the column could be changed, which would be useful to my niche uses of some databases.

EDIT* Whilst paying around in preferences with 'Title is Editable' I have discovered a bug; clicking the checkbox on and off, and clicking around in the database etc -  whilst leaving the preferences pane open - causes the app to crash. 
I'm trying to recreate the exact steps but it seems random, other than linked to the pane remaining open and the 'Title is Editable' checkbox.

**Comment by strongbox-mark** [comment]
Hi @milesmcclane,

The column settings are App Wide but if you like this could be a feature request to have them set on a per database basis.

If you have Title is Editable on, it means you can click once to select. Then click a second time on the Title of the entry/group to edit the title.

For the crash, just send the crash report to Apple or if you have the text of it, send it to support@strongboxsafe.com

Cheers!

**Comment by milesmcclane** [comment]
Hi Mark,

Oh thanks for the clarification RE: Title is Editable! Makes sense now. Though testing that just initiated another crash, I'll send the report to you directly.

I would love if you allowed the column setting per DB, that would be cool. Thanks!

Miles.

**Comment by strongbox-mark** [comment]
@milesmcclane - I believe this is fixed/available now with the NextGen UI? Right?
