### ISSUE TITLE
Documentation for sync features

### ISSUE THREAD

**Issue by TBugReporter** [strongbox-password-safe/Strongbox#458]
I noticed that some sync features have recently been added, but is there any documentation for them?  As you may know, I share several KeePass databases via DropBox, but as I've mentioned several times on SourceForge, I've had to treat them as read-only on iOS until now (and recommended to others that they do the same) for lack of an app with sync.  When I noticed this addition to Strongbox, I tried making a minor change to a file on my iPhone, but I couldn't figure out how to get that change to propagate to my PC's database.  I feel like I'm overlooking something that's obvious to others, but I can't figure out what it is.

**Comment by strongbox-mark** [comment]
HI @TBugReporter - There isn't a whole lot of documentation on this at the moment. Documentation is a little light at the moment. But this is one that "Should Just Work"...

If you like you could send to email support@strongboxsafe.com with the debug information from your About screen (Preferences > About Strongbox ... > Copy Debug Info) and I'll be happy to walk through this with you.

You'll also find useful information in the Sync Log. Long Tap on Database > Properties > View Sync Log.

This should work very well for you.

**Comment by strongbox-mark** [comment]
@TBugReporter - Please drop an email to support if you need any help/advice, this should just work for you. Going to close this one out now.
