### ISSUE TITLE
Prefix QuickType Username with Title

### ISSUE THREAD

**Issue by strongbox-mark** [strongbox-password-safe/Strongbox#459]
Sometimes the username is not a great way to identify which login will be used in AutoFill on the QuickType keyboard. 

It would be useful to prefix the username with the Title of the record. This should probably be the default with a switch to opt-out. 

For example:

Title: Joe
User: 173628

Title: Mary
User: 0582749

Instead of displaying "173628" or "0582749" we should display "Joe (173628)" and "Mary (0582749)" in the AutoFill QuickType bar.

Thoughts?

**Comment by Slummi** [comment]
That sounds reasonable.
I didn't know, that you can define what QuickType will display. Thought it always displays the username and that it is not configurable.

What will happen, if the title (and the username) are too long?

**Comment by Ben-Voris** [comment]
￼I vote for this because, ￼when I'm given the chance, I generate usernames from diceware, so they are not meaningful to me.

**Comment by strongbox-mark** [comment]
I'll take the silence to indicate happiness and close this one out, looks to work well. :)
