### ISSUE TITLE
Adding a (directly recorded) video as attachment to entry causes a crash. 

### ISSUE THREAD

**Issue by milesmcclane** [strongbox-password-safe/Strongbox#462]
As the title states: 

Go to entry (existing database or newly created database; existing entry or newly created entry), tap attachments, tap camera, swipe to video. App crashes. 

iOS 14.3, iPhone 8+

**Comment by strongbox-mark** [comment]
Thanks @milesmcclane - Will investigate

**Comment by strongbox-mark** [comment]
This should be fixed for you @milesmcclane in the latest release.

**Comment by milesmcclane** [comment]
Thanks @strongbox-mark - it’s fixed. Excellent quick response to important issues as ever! I’ll close it.
