### ISSUE TITLE
Changing master password - two new passwords don't have to match to change. 

### ISSUE THREAD

**Issue by ajwilberforce** [strongbox-password-safe/Strongbox#464]
1) when two new passwords match, set button will be abled. 

2) However, Even when set button is disabled, you can register by pressing return. 

3) In this case, only the first master password is recorded as the new master password

**Comment by strongbox-mark** [comment]
Wow, nice catch. Will patch in next release.

**Comment by strongbox-mark** [comment]
This should be fixed for you @ajwilberforce in the latest release.

**Comment by strongbox-mark** [comment]
Assuming this one is good, please re-open if not.
