### ISSUE TITLE
Ios Feature Request: Allow for forcing a character in generted password.

### ISSUE THREAD

**Issue by Starkman68** [strongbox-password-safe/Strongbox#465]
Many sites require a special character and a number when generating a PW.  The generator using the Diceware method only has words and maybe an optional suffix that is not guaranteed to be a special character or number.  Could you add an option to force a suffix to a pattern like !{int} to meet many web site requirements?

**Comment by dan-el** [comment]
Why not take it further and create password generator patterns with regex syntax?

Another solution would be to simply press the „generate password“ button several times. I often do that.

**Comment by strongbox-mark** [comment]
What about using L33tsp3ak @Starkman68 - This should add some numbers for you, pretty much most of the time. 

Alternatively as @dan-el says, just hit the generate button a few times should also help.

Happy to take this as a feature request but it's hard to prioritise this when the severity is so low and hitting the generate button fixes it for you.
