### ISSUE TITLE
Support for two Yubikey

### ISSUE THREAD

**Issue by Roy-H23** [strongbox-password-safe/Strongbox#468]
Dear Team,

I would highly appreciate if it would be possible to configure a second Yubikey for one database.
Would be nice to have a backup Yubikey.
It would also be possible to have one on your Mac and one with NFC on your keychain.
Let me know what you think about it.

**Comment by strongbox-mark** [comment]
Hi @Roy-H23 - Yes, this is totally possible if I understand you correctly. As long as you have the "secret" you programmed your first YubiKey with, you can create a second (or more) YubiKey that behaves exactly the same. You just need to program it using YubiKey's Personalization Tool to have the same "Secret".

Let me know if I've misunderstood

**Comment by Roy-H23** [comment]
Hi Mark,

That was the perfect tip.. Tried to register different secrets on Slot 1 and 2 but that did not work.
Same secret and same slot worked!

Thanks a lot!
