### ISSUE TITLE
Minimize usage of third party libraries/sdks where possible (e.g. Google Drive, Dropbox, OneDrive)

### ISSUE THREAD

**Issue by strongbox-mark** [strongbox-password-safe/Strongbox#469]
The idea is to reduce to the bare minimum the interfaces with third party storage provider SDKs to improve

- Privacy concerns
- App Load Times
- Maintenance headaches

**Comment by strongbox-mark** [comment]
With iOS 1.52.6 - There is now an explicit warning/caveat and a yes/no opt-in before using native storage provider SDK's for Google Drive, Dropbox and OneDrive.

**Comment by thepaulcooper** [comment]
Thanks for implementing this.  It really helps avoid any worry as to why SB is contacting cloud services that are not being used.  It just makes good sense from a privacy perspective.  However I have a question.  I only use iCloud for the SB database.  On my iPhone when I select Manage Cloud Provider Sessions, I get three options: 1) Clear Google Drive Session, 2) Unlink Dropbox and 3) Clear OneDrive Session.  But when I select any of these it says No Cloud Session Found (twice!) and an OK button.  On my iPad I don't get those three options as it seems to know that there are no Cloud session active.  Is this behaviour correct?

**Comment by strongbox-mark** [comment]
Hi @thepaulcooper - Yes, this is actually the expected behaviour. Basically Strongbox doesn't load these libraries/SDKs now until absolutely required and Opted-In to.

A side effect of this is we can't tell when you're signed in or not! It's a bit of a minor usability issue, this is a rarely used section/function in Strongbox (which still functions!). 

So when you click on one of those Sign Out buttons, Strongbox can then go and check if there's a session and signout/close it. It doesn't do so before hand, like it used to.

For your iPad, you're probably not on 1.52.6.

**Comment by strongbox-mark** [comment]
Going to close this one out, it's largely covered by the ongoing effort for #209
