### ISSUE TITLE
PSA — iOS 14.5 Beta 1 Breaks QuickType Authentication using Face ID

### ISSUE THREAD

**Issue by shad0whawk** [strongbox-password-safe/Strongbox#474]
I updated to the latest beta and it breaks the QuickType database authentication functionality when using Face ID. Face ID still works if you navigate to the Strongbox database and open it that way and then select the entry to autofill it. I've attached a screenshot below. 

![image](https://user-images.githubusercontent.com/6074105/107468804-ea12e180-6b25-11eb-8ccb-82963736a4cd.png)

**Comment by strongbox-mark** [comment]
Thanks @shad0whawk - Could you report this to Apple please? 

I will take a look on my side, but it's important to get this reported to Apple

**Comment by shad0whawk** [comment]
Done

**Comment by strongbox-mark** [comment]
@shad0whawk - Can you check if this is fixed in the latest Testflight Beta?

**Comment by shad0whawk** [comment]
I tried it when it was first made available and then again now after I saw your message, but the issue persists.

**Comment by shad0whawk** [comment]
I checked the latest App Store release and it still generates the Face ID error. I'm hoping they release the next beta tomorrow (or soon) and it resolves the issue. Will keep you posted.

**Comment by strongbox-mark** [comment]
Thank you @shad0whawk

**Comment by shad0whawk** [comment]
I updated to beta 2 and this issue persists unfortunately. On occasion after this error appears, it also clears the credentials from my database when I navigate to it using Autofill. This is rare but has happened a few time while testing over the last week.

**Comment by strongbox-mark** [comment]
Thanks @shad0whawk - Did Apple give any feedback to your report?

When is 14.5 due to release officially?

**Comment by shad0whawk** [comment]
Nah no response from them yet

**Comment by shad0whawk** [comment]
As a follow up to my previous comment, this error occurs occasionally during Autofill where it clears my credentials resulting in having to go back to the main application to reenter my password and select my key file again for an existing database. 
![image](https://user-images.githubusercontent.com/6074105/108279079-41720c80-7139-11eb-8ebc-2d01fb60a3d0.jpeg)

**Comment by strongbox-mark** [comment]
Thanks @shad0whawk - What does:

" it also clears the credentials from my database when I navigate to it using Autofill. "

mean? What happens, how does it manifest itself?

**Comment by shad0whawk** [comment]
Well everything works fine for a while except the QuickType Face ID authentication issue, and then suddenly that message pops up requiring me to enter my password and select the key file again in the AutoFill screen. Somehow my database credentials are cleared. I have to go back to the main app and reenter both for it to persist.

**Comment by strongbox-mark** [comment]
OK, this may just be a remnant of too many failed Biometric attempts.

**Comment by shad0whawk** [comment]
Just a quick update, the issue still persist in beta 3.

**Comment by strongbox-mark** [comment]
Thanks @shad0whawk - Any response from Apple yet? Any idea of official release date?

**Comment by shad0whawk** [comment]
Nope nothing from Apple. 

The issue is just with QuickType and the authentication mechanism. AutoFill by navigating to the database works as expected.￼ 

I started testing the latest build in TestFlight published today. My initial tests indicate your changes may have fixed the issue although sometimes Strongbox is a little slow to respond after selecting the QuickType entry (takes a second or two more  to respond compared to the previous Strongbox build on iOS 14.4). I'll test it a bit more and let you know if I find any issues.

**Comment by strongbox-mark** [comment]
@shad0whawk  - Could you try the latest beta on Testflight, this may be fixed now.

**Comment by shad0whawk** [comment]
My last comment was referring to the 3035 build on TestFlight. ￼There's still some lag after pressing the QuickType suggestion that can last up to three or four seconds at times but most of the time it's closer to two seconds￼

**Comment by strongbox-mark** [comment]
Thanks @shad0whawk - I'll see about the delay, let me know if you see any improvements in the public release today.

**Comment by armarti** [comment]
Build 3036 fixed it for me. I'm on 14.5 beta 3.

**Comment by shad0whawk** [comment]
The latest release seems faster than the previous one. The TOTP copy worked the first time for two different websites but then failed to copy when I refreshed the page and selected the QuickType prompt again.

**Comment by strongbox-mark** [comment]
Thanks @shad0whawk - I'll look into that copy TOTP issue.

**Comment by shad0whawk** [comment]
I'm not sure what changed in 1.52.9, but the TOTP copy after QuickType selections seems to work reliably again no matter what timeout settings I use.

**Comment by shad0whawk** [comment]
The latest build (1.52.9) works great on the 14.5 betas so I'll close this issue.
