### ISSUE TITLE
Issue with Changing Database Credentials

### ISSUE THREAD

**Issue by shad0whawk** [strongbox-password-safe/Strongbox#475]
I have a database that opens with a master password and a key file. I wanted to remove the key file and set the password to null for testing. I completed both of these steps in the "Set Master Credentials" settings. I closed the database, but the key file still appears by default when I try to unlock the database resulting in me having to manually remove it each time when unlocking. I checked the "Set Master Credentials" settings and confirmed that it no longer exits in the "Key file" field. I'd expect the key file not to appear when I go to unlock the database.

**Comment by strongbox-mark** [comment]
Sounds like a bug for sure, will investigate and fix...

**Comment by strongbox-mark** [comment]
Hi @shad0whawk - I'm afraid I can't reproduce this at all. Can you send a screen recording, or detailed steps to reproduce?

**Comment by shad0whawk** [comment]
I've been trying to reproduce it and it isn't happening now. I will close this issue unless it happens again and is reproducible.
