### ISSUE TITLE
Update Google Drive icon

### ISSUE THREAD

**Issue by juanbretti** [strongbox-password-safe/Strongbox#477]
Hello,
Could be considered to update the **Google Drive** icon?
Thank you!

<img width="191" alt="Screenshot 2021-02-14 161444" src="https://user-images.githubusercontent.com/10165911/107880550-ca8e0700-6edf-11eb-93df-e0eabcdc6800.png">

**Comment by strongbox-mark** [comment]
Will do :)

**Comment by strongbox-mark** [comment]
This is available now with 1.52.7.

**Comment by juanbretti** [comment]
Thank you! It's perfect.

**Comment by juanbretti** [comment]
Ups, I just noticed **Dropbox** also update his logo:

![image](https://user-images.githubusercontent.com/10165911/109200795-4ec67100-77a1-11eb-9198-21eebe1e0c5d.png)

Do you want me to open a new issue?

**Comment by strongbox-mark** [comment]
Ha, wow, ok. Yes please, if you can get the actual asset please that would be very helpful, it should be a png/pdf with transparency (512x512 would be great).
