### ISSUE TITLE
[Feature request - macOS] Pinning and syncing

### ISSUE THREAD

**Issue by TheMadRuffian** [strongbox-password-safe/Strongbox#478]
The iOS app allows pinning groups and records for quicker access. The similar could be implemented on macOS.

This could be taken one step further by syncing these pinned contents. When something gets pinned on iOS / macOS, it could be saved on the database thereby allowing it to sync across multiple devices when the user uses a 3rd party service for syncing.

**Comment by strongbox-mark** [comment]
Yes, for sure, definitely planned both:

- Pinned items on MacOS (and iOS/MacOS AutoFill)
- Syncing across devices (by saving in custom databases data section)

**Comment by strongbox-mark** [comment]
These are both implemented now in macOS and iOS and sync using the "Favorite" tag.
