### ISSUE TITLE
If TOTP is set up, copy it to clipboard after autofill

### ISSUE THREAD

**Issue by daletman** [strongbox-password-safe/Strongbox#479]
Basically what the title says. It would be a huge convenience plus for me not to open strongbox after auto fill to copy the TOTP

**Comment by strongbox-mark** [comment]
Hi, did you know that the TOTP is copied to the clipboard when you AutoFill, so just paste and it will fill in the TOTP :)

**Comment by daletman** [comment]
Wow I didn’t know that, that’s very nice, thanks!
