### ISSUE TITLE
iOS: Autofill for secondary passwords/security questions

### ISSUE THREAD

**Issue by milesmcclane** [strongbox-password-safe/Strongbox#480]
I’m not sure how this is supposed to work. When I want to autofill something other than the main password, I can’t seem to be able to stop the process of the main password being added automatically. This means one needs to then go into the app and manually search out secondary passwords and security question answers etc. 

Or have I missed the trick to this?

**Comment by strongbox-mark** [comment]
Nope, that's it. The iOS AutoFill system only allows username/password combos keyed by URL.

You could add a second entry with the same URL and change the title/username to something like 'Secret Question' and change the Password field to the answer to the secret question which would probably work for you.

**Comment by milesmcclane** [comment]
Ah ok then. Thanks I’ll look at workarounds similar to what you suggest!
