### ISSUE TITLE
Support for hiding items from search.

### ISSUE THREAD

**Issue by Daniel41920** [strongbox-password-safe/Strongbox#481]
Keepass has a property for folders to exclude them from searches, but Strongbox seems to ignore this and show all results. Could support for this feature be added?

**Comment by strongbox-mark** [comment]
For sure. This is on the backlog, and we should be able to get around to it pretty soon. I would say within the next 4-8 weeks.

**Comment by strongbox-mark** [comment]
This is available on Mac now, with iOS coming soon. The ability to enable/disable is still to come,  but search and AutoFill now respect this flag.

**Comment by strongbox-mark** [comment]
This is now available in iOS. Also, AutoFill is individually controllable separate from this, see #703
