### ISSUE TITLE
Update Dropbox icon

### ISSUE THREAD

**Issue by juanbretti** [strongbox-password-safe/Strongbox#482]
Hello,
Could be considered to update the Dropbox icon?
Thank you!

https://www.dropbox.com/branding

![128 512 Trim DropboxTransp](https://user-images.githubusercontent.com/10165911/109211014-efbb2900-77ad-11eb-9789-19c20156723a.png)

Resources: https://we.tl/t-3M3PtQlYXA

**Comment by strongbox-mark** [comment]
Amazing, thank you! :) Will get it in in the next release.

**Comment by strongbox-mark** [comment]
This is done with 1.52.8 :)
