### ISSUE TITLE
Entering URL in entries crashes Strongbox

### ISSUE THREAD

**Issue by srsp** [strongbox-password-safe/Strongbox#483]
Whenever I am adding an URL to a new entry or to an existing entry, Strongbox crashes. 

Here is my system information:

```
Process:               Strongbox [60357]
Path:                  /Applications/Strongbox.app/Contents/MacOS/Strongbox
Identifier:            com.markmcguill.strongbox.mac
Version:               1.15.0 (2997)
App Item ID:           1270075435
App External ID:       840524835
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Strongbox [60357]

Date/Time:             2021-02-27 22:05:52.120 +0100
OS Version:            macOS 11.2.2 (20D80)
Report Version:        12
Bridge OS Version:     5.2 (18P4347)

Time Awake Since Boot: 16000 seconds
Time Since Wake:       4100 seconds
```

I updated to Big Sur 11.2 today and noticed it since then. I don't know when Strongbox was last updated on my machine and cannot say whether that is related.

**Comment by strongbox-mark** [comment]
Hi @srsp - Could you update to 1.15.1 - this should be fixed for you.

**Comment by srsp** [comment]
Thank you very much, it works without problems now! 

Thank you for this nice and shiny password manager. I have been using so many ugly password managers before I discovered Strongbox.

**Comment by strongbox-mark** [comment]
Thank you! It will only get shinier in the future :)
