### ISSUE TITLE
Silent offline mode toggle

### ISSUE THREAD

**Issue by ankrman** [strongbox-password-safe/Strongbox#484]
Hi, as I have a multi-device setup, I‘m hosting my kdbxs centrally in my internal network. 
When I‘m not connected to my network (what is the case most of the time), everytime I unlock my DB, I‘m getting asked to open the DB offline. 

Would it be possible to create something like an auto-offline toggle or an ignore-sync-errors toggle (at least ignore when the remote host is not reachable)? 
I mean, in the end it really doesn‘t matter if you‘re up-to-date in this case. If one can‘t sync, the „offline mode“ is anyway better than not opening the DB at all. 
Next time when I can reach my destination and open SB the sync starts and all is fine again. 

Would be a huge time saver, thanks in advance 👍🏼

**Comment by strongbox-mark** [comment]
I have something like this planned, basically when Offline is detected you have 3 options:

- Ask if you want to use Offline (current default)
- Just open offline (this would be I believe what you want)
- Try to connect anyway (people need this if they use a local network db without broader Internet access)

I'm also thinking of adding a more permanent toggle to just always open offline until that setting is toggled off. I believe either of these will work for your scenario too.

**Comment by ankrman** [comment]
Ah, sounds great. Having the described options would probably cover all possible scenarios, yes. Thanks for the quick reply.

**Comment by strongbox-mark** [comment]
Both of these features are now available with 1.52.10. :)

**Comment by ankrman** [comment]
Hey Mark, thanks for implementing the option. Maybe it's only me, but I would have expected another behaviour though. 

My intention was to get practically two options:

1)SB can't reach database (stored on WebDAV, SFTP whatever)
2a) SB informs the user and offers to open the DB offline **or**
2b) SB silently opens the DB offline

Now my issues within the app:

- If I choose the option "open offline without notification", SB opens the DB **always** offline even though it could reach the file. That doesn't make sense to me as this equals the "always open offline" option one level higher.
- The "try to connect" option **always** tries to open the DB and throws a notification which is then equal to the first option "ask".

Sorry that I can't give you the exact options, I can't switch to English in the app manually (maybe an enhancement?)

**Comment by strongbox-mark** [comment]
Thanks @ankrman - I think this boils down to a new requirement/option:

Try to connect, then open offline (no prompt) if unsuccessful. I'll try add that into this weeks sprint.

**Comment by ankrman** [comment]
Great, thanks in advance. Still I'm curious if I understood something wrong. I still can't determine the difference between "try to connect" and "ask" and "open offline" and "always offline". At least on my device the effects seem to be identical.

**Comment by strongbox-mark** [comment]
Hi, with the release of 1.52.11 there are now 2 settings which affect Offline behaviour:

- **Internet Unavailable Behaviour** - This means if Strongbox detects that the wider Internet is unreachable (tested via a connection to https://duckduckgo.com) then Strongbox will do one of
   - _Prompt_ - Ask user if they want to open offline or try to connect anyway
   - _Try to connect_ - Try to connect anyway - useful if you're running on a LAN with restricted Internet
   - _Open Offline_ - Just open the database offline

- **Could Not Connect Behaviour** - This is the behaviour that occurs after the Internet Unavailable check, when Strongbox attempts to connect. Strongbox can do one of
   -  _Prompt_ - Ask user if they want to open offline
   - _Just open offline immediately_ (No Prompt)

Hope that makes some sense? I think it should cover all your bases/requirements? Will close out for now, and deal with any issues/comments separately.

**Comment by ankrman** [comment]
Hi @strongbox-mark,

it still doesn't seem to work 100% as expected. When I have set **Internet Unavailable Behaviour** to _Open Offline_ it **always** opens my DB offline even though https://duckduckgo.com is reachable.

But I'm fine, I got it somehow working for me using

- **Internet Unavailable Behaviour**: _Try to connect_ together with
- **Could Not Connect Behaviour**: _Just open offline immediately (No Prompt)_

Thank you very much for the addition!

**Comment by strongbox-mark** [comment]
This seems like a bug, investigating...

**Comment by ankrman** [comment]
Thanks for the fix, works perfectly now
