### ISSUE TITLE
Hardware Key Support for AutoFill

### ISSUE THREAD

**Issue by Bendodroid** [strongbox-password-safe/Strongbox#485]
Is this something that is planned or possible in the future? I would prefer to use my hardware key for AutoFill instead of storing the secret on my phone directly via a virtual key.
If this has been addressed elsewhere, I wasn't able to find it.

**Comment by strongbox-mark** [comment]
Hi @Bendodroid - This just isn't supported either at the OS level or at the OEM level. There's not much Strongbox can do here. 

You could raise these issues with Apple and your Hardware Key manufacturers.

**Comment by Bendodroid** [comment]
Now that I read my comment again, it might be unclear what I'm referring to here.

I mean this:

![IMG_0045](https://user-images.githubusercontent.com/26770477/110023365-68316500-7d2d-11eb-8306-23246dc2db07.jpeg)

I use my Yubikey as a second factor in addition to my password, but when using Autofill, this prevents me from opening the database

**Comment by strongbox-mark** [comment]
Hi @Bendodroid - maybe I'm not understanding you, but the reason you can't use your hardware key in AutoFill is because NFC and MFI are not supported by Apple and/or Yubico in the AutoFill context (technically _App Extension_ execution context).

Strongbox can't do anything about that, these are system or SDK limitations. 

Does that make sense?

**Comment by Bendodroid** [comment]
Yes, it does. Just wanted to make sure we were both on the same page. Then I'm going to complain to Apple and file a ticket at bugreport.apple.com .

**Comment by Bendodroid** [comment]
Has something related to this issue changed with the release of 14.5?

**Comment by strongbox-mark** [comment]
Hi @Bendodroid - I don't think anything has changed, unless you're aware of some news on this?

**Comment by Bendodroid** [comment]
No, I was not aware of any news on this, I was hoping you were :D
So far, no one has replied to my ticket, but usually that doesn't mean much.

**Comment by Bendodroid** [comment]
Does this mean Strongbox might also be able to use my USB-C Yubikey with iPadOS 16? :O

![image](https://user-images.githubusercontent.com/26770477/197636038-44665c24-436c-4623-859e-50b043571678.jpeg)

**Comment by strongbox-mark** [comment]
I don't think so, but you could give it a try, and please let us know how it goes

**Comment by Bendodroid** [comment]
The lightning options in the unlock menu don't work with a USB-C Key on my iPad. Seems changes are needed in Strongbox?

My guess is the Authenticator can now do it because of the new passkey-related stuff in iOS/iPadOS 16 and macOS 13? Sounds like there were API changes by Apple.

**Comment by strongbox-mark** [comment]
Hi @Bendodroid, we've asked Yubico about this here:

https://github.com/Yubico/yubikit-ios/issues/114

Fingers crossed, but I'm not optimistic here...

**Comment by Bendodroid** [comment]
Too bad 😔 

But thx for the effort.
