### ISSUE TITLE
Restore option to use previous macOS keyboard shortcuts

### ISSUE THREAD

**Issue by rob3c** [strongbox-password-safe/Strongbox#488]
Today, I was utterly shocked that pressing `cmd+shift+U` launched a URL instead of simply copying the username. This is completely surprising behavior, especially to enable without warning. After looking around, I see almost all of the shortcuts I routinely use as part of strongbox muscle memory have been changed, and not for the better IMO.

Please give an option to restore the previous shortcuts. Optionally, please provide the reason for this radical change, and especially why there wasn't any kind of notification to alert the user before unexpected actions started happening due to the remappings. I've been extremely happy with SB across all of my devices, but a willingness to instantly break such basic functionality has me completely reevaluating my use of SB. What other breaking changes will arrive with the next update?

**Comment by strongbox-mark** [comment]
HI @rob3c - Sorry about this surprise. 

The reason for the change is to come into line with the other KeePass clients (XC and KeePass Windows). I had received a lot of requests for those changes from existing KeePass users.

This wasn't messaged very well and I apologise for the inconvenience. I will increase the priority of #429 so we can get back to old shortcuts for you. 

For what it's worth I myself have found myself launching the URL as I am a heavy keyboard shortcut user too, but given the amount of existing KeePass users I thought it best to make the transition easy for them.

**Comment by rob3c** [comment]
Thanks for the quick reply @strongbox-mark . Your responsiveness to user issues is a large part of why I'm reluctant to stop using SB, along with a great experience across devices. I suspected there were business reasons like what you described. It was mostly the jarring launch of the browser slipping through your release process that gave me pause. That could've been any native code, and I realized I got a bit lazy in applying updates too quickly and without isolating them first in a VM as I usually do.

I suspect I'll have switched to the new mappings by the time #429 is completed, as using a mouse is even more annoying than this old dog learning a few new tricks 😆 It'll be nice to tweak any mappings that end up being too awkward (I'm looking at you, cmd+B), but otherwise please don't raise the priority of #429 on my account.

I'm going to close the issue now, but if you'd like to take some action about it anyway, please put the time towards re-evaluating how alerting users to breaking changes is handled moving forward. Thanks again for your excellent work.

**Comment by strongbox-mark** [comment]
Thanks @rob3c - the right way to do this was to bring in the configurable Key Bindings feature first and only transition new users to the new key configuration. I think I underestimated how attached users are to their key bindings. that's my bad. Will try to break less things moving forward. 

Unfortunately since the MacOS client is a good bit behind the iOS client, the MacOS client will bear the brunt of changes in the future as I'd like to bring it up to feature parity and improve the UI/UX. This does mean changes, but hopefully not breaking changes for you.
