### ISSUE TITLE
[Mac OS] Feature request - hide window to menu icon when minimized

### ISSUE THREAD

**Issue by genbushi** [strongbox-password-safe/Strongbox#489]
# Feature Request

On the MacOS version it would be great to have a `Hide window to menu tray icon when minimized` type of behavior.

Great app by the way, I'm 98.3% on linux with KeepassXC, but the new M1 laptops have lured me over a bit.

**Comment by georgesnow** [comment]
So along these lines it would be cool to have search mini option from the menu bar option.

sort akin to Alfred, Maccy but for passwords and pinned items. 1Password has something similar with its mini window option. So in the cases when auto fill isn’t an option or pieces of entry (licenses etc) need to be copied and pasted.

**Comment by milesmcclane** [comment]
Would fit nicely in with issue #442

**Comment by strongbox-mark** [comment]
Thanks for the request, but I'm not sure I fully understand it. At the moment the menu icon is always present if Strongbox is running. This is the case even if you minimize a window. What functionality is missing or required here?

**Comment by georgesnow** [comment]
So in the case like Alfred and 1Password etc...
It’s a separate “mini window” that can be display from status icon on the menu bar. It would show pinned items and search box to search for entries in your database.

effectively hide the dock icon and possibly global keyboard shortcut to show mini search box.

this is what 1Password looks like:

![image](https://user-images.githubusercontent.com/12751441/110822969-9f3cd480-825f-11eb-9cba-712ac8a3b7d2.jpeg)


Doesn’t have to be exactly like that but as general idea.

**Comment by strongbox-mark** [comment]
Thanks @georgesnow - My question was more aimed at @genbushi and the original idea behind his request.

**Comment by genbushi** [comment]
> At the moment the menu icon is always present if Strongbox is running. This is the case even if you minimize a window.

Yes, it's a rather minor thing and I didn't explain it well, apologies. Currently the window minimizes with an active dock icon in addition to the menu icon. What I was referencing was, minimizing/closing the active window would result in the application still being active with menu icon options - but with no visible dock icon unless an active window is open. Similar to 1password, keepassxc, etc.

**Comment by georgesnow** [comment]
@strongbox-mark sorry. yeah I was expanding on the hide the dock icon part with the menu bar icon

**Comment by strongbox-mark** [comment]
@genbushi Got it, thanks. Yes, that sounds fair, will add to the backlog.

**Comment by sindastra** [comment]
@strongbox-mark I'd suggest adding the option to "close to tray", so that when you close the window the database stays unlocked and can be brought back through the tray icon, however I'd not change the behavior of the minimize button as I imagine if someone specifically clicks minimize, they probably do want to minimize (I know I would at least).

**Comment by strongbox-mark** [comment]
Yes, I think we can add that as a feature/extension to this issue and track here

**Comment by strongbox-mark** [comment]
Also note, that the "Minimize to Tray" option is now available with 1.15.14 on the App Store now.
