### ISSUE TITLE
Edit custom field cosmetic display error (macOS)

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#491]
**In Strongbox on macOS:**

When adding or editing a custom field the highlight around the currently selected field overflows to the right. Just a cosmetic issue. See attached screenshot.

<img width="329" alt="Screenshot 2021-03-13 at 14 51 58" src="https://user-images.githubusercontent.com/19776691/111051733-a75e6500-8455-11eb-8d16-d00289961d80.png">

**Comment by strongbox-mark** [comment]
Noticed this too, thanks for raising @dan-el

**Comment by strongbox-mark** [comment]
This should be fixed for your @dan-el in latest release.

**Comment by dan-el** [comment]
Yes, this is fixed. Sorry I missed the Github notification somehow.

Much appreciated!
