### ISSUE TITLE
Option to open online when Always open offline is activated

### ISSUE THREAD

**Issue by daletman** [strongbox-password-safe/Strongbox#493]
Pretty much what the title says. When I have `Always open Offline` activated for a DB I don't see a way to open online once.

**Comment by shad0whawk** [comment]
Try pulling down to refresh. Does that work for you?

**Comment by daletman** [comment]
> Try pulling down to refresh. Does that work for you? If you want to go back to downloading from online each time you open you would have to disable "Always Open Offline".

https://github.com/strongbox-password-safe/Strongbox/issues/492#issue-835300232

**Comment by strongbox-mark** [comment]
Perhaps the best thing to do here is to allow a long tap menu option for 'Always Offline' databases > Open Online, like the current 'Open Offline' option we have for regular databases.

**Comment by daletman** [comment]
In the swipe left menu it still says „open offline“. Would be consistent to change this also to open online

**Comment by strongbox-mark** [comment]
Will do @daletman - I think otherwise we're good to close here with the addition of the Open Online menu item in 1.52.11.
