### ISSUE TITLE
About KeeOTP2 Support

### ISSUE THREAD

**Issue by solar-core** [strongbox-password-safe/Strongbox#498]
I saw that this app support "KeeOTP 1" plugin for KeePass.
Does it support "KeeOTP 2" plugin?
I tried to work with KeeOTP 2 plugin, but it seems, that it not recognize those additional fields from KeeOTP 1, because it asked me to configure OTP from "Zero".
Maybe there is other plugins that run with KeePass and StrongBox works well with them?

**Comment by shad0whawk** [comment]
I use the KeePassOTP plugin by Rookiestyle. I have no issues working seamlessly between Keepass on Windows and Strongbox on iOS and MacOS.

**Comment by solar-core** [comment]
Thank you, will try that.

**Comment by strongbox-mark** [comment]
Yes, TOTP support is now baked into the original KeePass app and Strongbox supports that convention as well as a few others. It is fairly unlikely that support for any other convention will be added now.

**Comment by solar-core** [comment]
@strongbox-mark You mean by KeePass the "KeePassXC" or original "KeePass" that supports OTP?

**Comment by strongbox-mark** [comment]
Yes, both now support OTP natively.

**Comment by solar-core** [comment]
@strongbox-mark Can't find any information about that original KeePass version 2.47 support OTP natively. I found just KeePassXC native support and KeePass using plugins. Do you have any information about that original KeePass works with OTP?

**Comment by solar-core** [comment]
Oh sorry didn't look at changelog, i found it at https://keepass.info/help/base/placeholders.html#otp if you mean this

**Comment by strongbox-mark** [comment]
Yes, that's it exactly. Strongbox will read/write these custom fields and display TOTP codes based on them. I believe KeePass on Windows doesn't display these codes but you can copy/paste/autotype them.

**Comment by solar-core** [comment]
Yes i tried them, it works good on Windows. Will try the pair keepass and strongbox.
