### ISSUE TITLE
[Suggestion] About autotype

### ISSUE THREAD

**Issue by solar-core** [strongbox-password-safe/Strongbox#500]
Hello, could you make an autocomplete work for Title too? With keeping priority to url field.
Example: I have many records in my KeePass on Windows, many of them have url field empty. But the title for every record is filled with information, it could be some of site name or half of its name.
Could Strongbox have functionality like:
I have
Title: "hotmail my email address bla bla bla..." or "hotmai bla bla bla" or "my email"
Username: "Someuser"
Password: "Somepass"
and i enter hotmail.com, Strongbox analyze my title, take words sequense, and suggest me some of the most suitable record from Strongbox.

**Comment by strongbox-mark** [comment]
I'm afraid not, if you're speaking about "QuickType" suggestions that appear above the keyboard? That is all controlled by Apple and they only support Domains/URLs.

**Comment by solar-core** [comment]
Oh ok, didn't know its controlled by apple, thank you
