### ISSUE TITLE
Info.plist has wrong icon reference for CFBundleDocumentTypes types

### ISSUE THREAD

**Issue by o11011o** [strongbox-password-safe/Strongbox#501]
Hi Mark,
when trying out KeePass compatible Mac OS clients, I first installed KeePassXC and afterwards Strongbox. I then deleted KeePassXC and set Strongbox as the default application to open 'kdbx' files. I then wondered, when saving a new 'kdbx' database with Strongbox, why the new file still appeared with the KeePassXC icon.

Looking into the 'Info.plist' of Strongbox, it appears that the wrong icon name 'AppIcon' is referenced for the 'CFBundleDocumentTypes' entries since the 'Assets.car' only contains icon entries for the 'AppIcon-BigSur-Pro' name.

<img width="1206" alt="Screenshot 2021-04-03 at 00 43 09" src="https://user-images.githubusercontent.com/74367197/113459516-122c0c00-9416-11eb-8211-2fb150283880.png">
 
This probably confuses the Launch Services Database.

Tested on:
OS X Big Sur 11.2.3 (20D91)
Strongbox Pro Version 1.15.7 (3004)

Thanks,
Oliver

**Comment by strongbox-mark** [comment]
Wow, hadn't noticed this, thanks Oliver! I'll investigate this shortly, it seems like a mistake for sure. Good catch.

**Comment by georgesnow** [comment]
I also encountered this to be honest I assumed it was macOS not updating the "default" application. I have noticed in the reverse on other apps. 

TextEdit and TextMate.

**Comment by strongbox-mark** [comment]
Could you check if this is fixed for you with 1.15.8?

**Comment by o11011o** [comment]
Hi Mark,
thanks for the fast update!

1.15.8 fixes the issue for the 'Strongbox App', but not for 'Strongbox Pro'.

The reason is, that the icon 'AppIcon-BigSur' that is specified as the document icon in the 'Info.plist' for 'Strongbox Pro' can not be found in the 'Assets.car' file when being inspected with:
`xcrun assetutil --info ./Strongbox.app/Contents/Resources/Assets.car`

In 'Assets.xcassets', there are two 'App Icon' resources:

![Screenshot 2021-04-10 at 10 53 13](https://user-images.githubusercontent.com/74367197/114264501-9f112f80-99eb-11eb-9d88-bf9428bf2887.png)

But only the one that is specified as the app icon is copied into the app:

![Screenshot 2021-04-10 at 10 55 41](https://user-images.githubusercontent.com/74367197/114264505-a59fa700-99eb-11eb-9263-09c74be3d5f4.png)

The document icon probably would best be added as a generic icon to the 'Assets.xcassets' asset catalog.

A good resource about document icons can be found here:
<https://developer.apple.com/news/?id=5i6jlf4d>

Thanks a lot for your great app,
Oliver

**Comment by strongbox-mark** [comment]
Thanks @o11011o - Will try fix this in the next release.

**Comment by strongbox-mark** [comment]
Hi @o11011o - I believe this should now be fixed with 1.15.9. Could you verify. I went with a dedicated/separate icon.

**Comment by o11011o** [comment]
Hi Mark, I'm happy to confirm that the issue is fixed with 1.15.9. Thanks!

**Comment by strongbox-mark** [comment]
That's great, I might try to improve on this with the more modern Big Sur style icon.
