### ISSUE TITLE
NSURLErrorDomain error -1012

### ISSUE THREAD

**Issue by TheRealWaldo** [strongbox-password-safe/Strongbox#504]
After a while, with a WebDAV based database, after an auto-lock, every attempt to open the database results in error NSURLErrorDomain error -1012

I confirmed the connection and database are fully functional using other software.  If I remove the database and re-add it, it works, up until it auto-locks.

**Comment by strongbox-mark** [comment]
Hi @TheRealWaldo - Could you upgrade to 1.15.8 and see if that fixes things?

**Comment by strongbox-mark** [comment]
Could you also double check the time is set correctly on your MacBook and/or check the certificate is ok on your server. If that doesn't help would you mind sending your debug information to support@strongboxsafe.com

**Comment by TheRealWaldo** [comment]
@strongbox-mark 

Same result on the latest version; time is good, cert is good.

Seems I can't get to debug without opening the database...  Is there another way?

Was working fine recently, an update broke it last week perhaps?

**Comment by strongbox-mark** [comment]
Hi @TheRealWaldo,

Just to be clear:

1. You were using an older version
2. You have removed then re-added your database and it's still not working - You'll need to re-add for this fix to work (sorry should have said)
3. It happens when you Auto Lock - Can you describe what this is exactly and how you initiate it. Does it happen when you lock the screen, or is it a timeout thing?
4. You can find the Debug Info under the Strongbox menu - About Strongbox

Cheers

**Comment by TheRealWaldo** [comment]
1. I was using the version available at the time of posting (1.15.4, I believe); an update was not available in the store until after you posted.  I tend to update the moment a new version is visible.
2. I did not; I will try that now.
3. I'm not sure which triggered it; I had a timeout set and screen lock set the first time; but after removing/re-adding, it looks like those settings went back to screen lock only.  I would have to assume that means it was screen lock.
4. Found it, thanks.  I will hold off on sending as it has some information I prefer not to transmit over email.

**Comment by TheRealWaldo** [comment]
@strongbox-mark so far, I haven't experienced that error with 1.15.8

I tried letting it time out, screen lock, and manual lock.  I will close for now and re-open if it happens again.

**Comment by strongbox-mark** [comment]
Sounds good.

**Comment by TheRealWaldo** [comment]
@strongbox-mark I'm experiencing this again with 1.15.11, this time error code -1005.  The problem that I have now is that I have added at least a half dozen new passwords that have not yet synced to the remote (and at least 2 do not have password recovery/reset functionality), so I cannot remove/re-add without data loss, and I also cannot open the database at all at the moment.

Have confirmed I can access the remote database just fine from other software.

**Comment by TheRealWaldo** [comment]
@strongbox-mark And as I just forced a cache refresh in the app store, I see 1.15.12 has been published, and it corrects this issue.  Thanks for the pre-emptive strike!
