### ISSUE TITLE
MacOS Bug: New strength indicator causing crash(Potenially)

### ISSUE THREAD

**Issue by milesmcclane** [strongbox-password-safe/Strongbox#505]
Just downloaded to test and am unable to use as app crashes.

Steps: create new password entry, press generate password. Causes crash 2 out of 5 times.
If no crash, open password genration settings to change size and style of passwords, causes crash eventually.

MacOS 11.2.3

**Comment by strongbox-mark** [comment]
@milesmcclane - Would you be able to send a crash log? Can't reproduce this at all. Video recording might be helpful too. You can send to support@strongboxsafe.com

**Comment by milesmcclane** [comment]
Sure give me a sec

**Comment by milesmcclane** [comment]
Hmm. Im afraid to say I can’t, the whole app has become unstable. 
I’m unable to open any database for any length of time, it crashes after a few seconds. I cant recreate any steps of find any logs before it crashes. I’m unable to create a new database also, the app crashes.
Is there another way to get the logs without starting the app?

**Comment by strongbox-mark** [comment]
OK. Very strange. Could you send the debug info. Strongbox menu > About > Copy Debug Info. No need to open a database. 

Do you see any kind of crash dialog, usually when an App crashes you get a crash dialog with a crash dump. This would be extremely helpful.

After that, could you try deleting Strongbox from the Applications folder and reinstalling?

**Comment by milesmcclane** [comment]
No crash dialogue appeared any of the times- spinning beachball, needed to force quit from finder. 

I’ll send you the logs the way you mentioned just no.  I’ll try reinstalling the app etc but will have to be tomorrow for that now.

**Comment by strongbox-mark** [comment]
Thanks @milesmcclane - Let me know how it goes. If it goes to spinning beachball, it might be worth waiting for quite a while, you may see the crash dialog then. So far you're the only report of an issue.

**Comment by milesmcclane** [comment]
I have spent the morning restarting my system, reinstalling strongbox and re-adding all databases etc, in various different orders but still haveing the same issues. I even left the beachball spinning whilst I went to have lunch - but it’s well and truly still spinning.

**Comment by strongbox-mark** [comment]
Hi Miles, thanks for the experiments.

It sound like you are able to get Strongbox running, in some cases. I wonder if you could describe when exactly things go wrong You're able to add a database, it seems like more than one actually.

- Can you open any?
- When does the spinning beachball start?
- Could you check the "Console" app (filter for Strongbox) do you see anything in there of interest?
- Does a device restart help at all?

Another thing to try is to delete/remove Strongbox complete as you have done, but also to remove any settings that may not have been cleared. You can do this by running:

`defaults delete com.markmcguill.strongbox.mac`

Thanks.

**Comment by milesmcclane** [comment]
Hi Mark,

I’m able to add and open databases, and I'm able to interact with them, retrieving passwords, editing locations of entries etc. These functions were not working in my prior complaint, but started working after a device restart and a strongbox reinstall. I uninstalled SB, restarted and then reinstalled SB. This is great because the app is now at least functional for basic use unlike initially.

What I seem unable to do still is any form of password editing, or anything to do with passwords in general, including;
Creating a new database - it crashes (actually, freezes with spinning beachball is more accurate, neeing a force quit) immediately upon new password entry.
Using the password generator, the same sympoms as above upon adjusting any field
Editing a current entry password in an extablished database., again the same symptoms only this time after hitting enter.
(I havent tried to edit an extablished database password as I have no active test databases, I can't create a new one and I’m unwilling to try on my working DB’s).

I have to go out for the afternoon but I’ll try reset prefs and check the cosole later on and let you know.

Thanks for checking it out,

Miles

**Comment by milesmcclane** [comment]
(I just sent a report via the in built mechanism for the last force quit - i’m not sure that gets to you or not).

**Comment by strongbox-mark** [comment]
Thanks @milesmcclane - It's not guaranteed to get to me, but fingers crossed. It's a bit of a black box what reports eventually end up getting to the developers.

**Comment by strongbox-mark** [comment]
Working with @milesmcclane offline, I believe we have narrowed this to a bug in the Password Generator in certain particular circumstances. A fix is in the works, and should be released shortly.

**Comment by strongbox-mark** [comment]
This should be fixed for you now @milesmcclane in the latest release

**Comment by milesmcclane** [comment]
Excellent work as always @strongbox-mark, the fix has fixed the issue. I’ll close it. Thanks!
