### ISSUE TITLE
Disclaimer for a single password HIBP check should be in the singular

### ISSUE THREAD

**Issue by thepaulcooper** [strongbox-password-safe/Strongbox#506]
Suggestion - in the Audit Details screen where you present the HIBP action, the wording of the HIBP Disclaimer should be in the singular - you are only sending one password not all of them.

**Comment by strongbox-mark** [comment]
Thanks @thepaulcooper - I think "password(s)" will do the trick in this case to cut down on redundancy/duplication. Cheers.

**Comment by thepaulcooper** [comment]
Ok, thanks. My only reason for raising it is that the first thought that I had when I read the disclaimer was "Is SB going to check all my passwords? I only want the current one checked."  It was this slight concern that led me to make the suggestion so that others don't have the same worry. But the expression "password(s)" may suffice.

**Comment by strongbox-mark** [comment]
Got it, yeah, totally understand. I think we can probably live with the (s) suffix here.
