### ISSUE TITLE
Spinning Beachball when saving database with YubiKey

### ISSUE THREAD

**Issue by o11011o** [strongbox-password-safe/Strongbox#507]
Hi!

I'm using a touch-enabled YubiKey for encryption of my database. When I want to save the database, I see a spinning beachball instead of the 'Please touch your YubiKey to authenticate' overlay. Only when touching the YubiKey, the overlay can briefly be seen. 

Steps to reproduce:
1.) Create and open database with Password and touch-enabled YubiKey. (Note: On creation and when opening a database, the overlay is shown directly without beachball)
2.) Add an entry to the database
3.) Hit cmd-s to save the database -> the spinning beachball appears
4.) Touch the YubiKey. 
Result: The 'Please touch your YubiKey to authenticate' can briefly be seen, followed by the 'Sync Succesfull' message
Expected: After hitting cmd-s, the 'touch your YubiKey' overlay should directly be visible

MacOS 11.2.3 (20D91)
Strongbox Pro 1.15.9

**Comment by strongbox-mark** [comment]
Thanks for the report - will investigate...

**Comment by o11011o** [comment]
I'm happy to confirm that this is fixed with Strongbox 1.15.15. 

Thanks a lot for the fix!
