### ISSUE TITLE
Folders on top when setting Sort to None

### ISSUE THREAD

**Issue by fgimian** [strongbox-password-safe/Strongbox#508]
Hey there guys, hope you're doing great.

When setting **Sort** to **None (Custom Order)**, I'm expecting folders to be listed at the top of the list, but instead Strongbox places them at the bottom.

Here's an example from a demo database.

**Strongbox**

![Photo 23-4-21, 4 45 40 pm](https://user-images.githubusercontent.com/1811813/115831758-5e86cc80-a455-11eb-97a4-c46e4dd1fd92.png)

**Keepassium**

![Photo 23-4-21, 4 46 41 pm](https://user-images.githubusercontent.com/1811813/115831770-62b2ea00-a455-11eb-99f7-b9ea81e7c1e9.png)

Would you consider either changing this behaviour or providing a way to place folders at the top of  the list when sorting is set to None?

I always prefer to set my sorting to None as my folders are ordered in a particular way where most important folders appear up top regardless of their name.

Kindest regards
Fotis

**Comment by strongbox-mark** [comment]
Sounds very reasonable. Basically what's happening here is that clients like KeePass and KeePassXC serialize the entries first, then the folders, leading to this kind of natural unsorted order (where the folders appear after the entries). With sorting set to None, you get this effect. 

Strongbox allows you to order folders above entries, so you could actually re-arrange your folders above the entries, by tapping More > Select > Grab the gripper to move the folder(s) up to the top > Done. However this will only remain in place until you save with KeePassXC/KeePass (not sure about Keepassium) when their serialization code will undo the Strongbox order.

I believe there are users that like this feature of Strongbox and don't use any other clients, so we need to be careful here not to affect them.

It does seem like a fairly common use case to sort folders above/separately from entries with custom ordering, so I think Strongbox should support this, possibly as the default. 

Will try fit this into the next development sprint. Thanks for raising!

**Comment by fgimian** [comment]
Thanks a lot!

**Comment by strongbox-mark** [comment]
Hi @fgimian - This should be available for you now with the latest release (1.52.15) - Could you verify and close?

**Comment by fgimian** [comment]
Thanks a lot, I can confirm everything looks good in the new version😊
