### ISSUE TITLE
Backup preferences

### ISSUE THREAD

**Issue by 4volodin** [strongbox-password-safe/Strongbox#509]
Maybe somebody knows.....
How to backup Preferences?
I didn't find strongbox folder or .plist in ~/Library/Preferences and /Library/Application Support/
Thanks for helping

**Comment by georgesnow** [comment]
You should be able to from terminal 

`defaults export com.markmcguill.strongbox fileparg/filename`

more flag the command 

`-app Strongbox`

**Comment by strongbox-mark** [comment]
What kind of preferences are you looking to export. There is a long standing request #282 which should look after this in some ways, so that your database retains preferences across installs/devices.
