### ISSUE TITLE
Quick Clear Password Text Field button

### ISSUE THREAD

**Issue by JLWFuQrioea69ugsykvQcg** [strongbox-password-safe/Strongbox#511]
It would be useful if the password field had a clear option (the "x" on the right side) similar to the title and username fields. This would speed up the process of deleting the existing value. Currently I have to either place the cursor at the end of the value and backspace, or double tap and drag the handles to the start and end of the value. Double tap would be okay but it only selects the main alpha value in the password which doesn't work very well with complex passwords.

**Comment by strongbox-mark** [comment]
Sounds good, I presume this is iOS?

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
Yea it's iOS

**Comment by strongbox-mark** [comment]
This is available now - there's a orange X clear button for quick clearing.
