### ISSUE TITLE
MacOS auto fill bug

### ISSUE THREAD

**Issue by georgesnow** [strongbox-password-safe/Strongbox#513]
I ran into an issue with auto filling view controller. The submit and cancel button don't  seem to work. I can search prsss enter to fill. And only the escape button allows to me exit the view to return to the webpage. 

Also I noticed the Mac version doesn't provide the option to create a new entry like the iOS version. Is it possible to add this feature?

**Comment by georgesnow** [comment]
Also the TOTP buttons are not clickable. Return works though

**Comment by strongbox-mark** [comment]
Hi @georgesnow - I think this is a duplicate of #502. But what do you mean about the TOTP button, which button is that?

**Comment by georgesnow** [comment]
Yup but it also happen when the next pop up that looks like that to inform you TOTP was copied and do you want to be noticed in the future. I can’t remember the exact wording. I will try and get a screenshot. And like the other issue keyboard works but not the mouse

**Comment by georgesnow** [comment]
![image](https://user-images.githubusercontent.com/12751441/123863080-2093a200-d8f7-11eb-85dd-dc9ce5cdb1f4.jpeg)


These buttons are not mouse clickable during any part of the auto fill process.

**Comment by georgesnow** [comment]
![image](https://user-images.githubusercontent.com/12751441/123863225-520c6d80-d8f7-11eb-9431-88c6a2b3cac9.jpeg)

Same for this one (it seems to be persistent for every one of these view controllers)

**Comment by georgesnow** [comment]
Yup, just yesterday noticed it still occurs. #502 appears to be related. However, one difference the mouse never works for me only keyboard navigation seems to work. I tried it on Monterey and it's present there as well.

**Comment by strongbox-mark** [comment]
Hi @georgesnow - Could you let me know if you're running 1.16.3?

**Comment by georgesnow** [comment]
Latest build fixes it. Good to close this ticket. Thanks!

**Comment by strongbox-mark** [comment]
Great, thanks @georgesnow - Let me know if it occurs again
