### ISSUE TITLE
MacOS auto fill extension - choose url type to match

### ISSUE THREAD

**Issue by georgesnow** [strongbox-password-safe/Strongbox#517]
I noticed that strongbox matches on just host. I didn't see an option to modify this. But I have subdomain sites that show up rather then the more strict match. 
Example:

SiteA.here.com

I have 10 entries that have:
Here.com

In their url 

But only one that has SiteA in the url for the subdomain.

Is there way to either per db, per site, and or per entry to pick the url type matching ?

**Comment by georgesnow** [comment]
Bummer. I can’t figure out how it prioritizes if any. Cause the subdomain match is almost always in the middle, but has note (this site) on it.

**Comment by ccolic** [comment]
I'm having the same issue. Is this something that can be fixed by Strongbox or is it just the Apple Autofill feature that works like that?

**Comment by jcausey-astate** [comment]
I have this issue as well - specifically, with work domains.  We have many different sub-domains, but most of them use a Single-Sign-On account.  I currently see 10 listings when I go to work sites, and unfortunately the SSO login credential is at the _bottom_ of the list.   If it isn't possible to prioritize entries for specific subdomains, it would be nice to specify a preferred ordering to bring the SSO to the top of the list.

**Comment by strongbox-mark** [comment]
You can use the "Favourite" functionality which should bring a preferred entry to the top of the suggestions list.

**Comment by jcausey-astate** [comment]
> You can use the "Favourite" functionality which should bring a preferred entry to the top of the suggestions list.

Good suggestion!  It fixes the main issue with the SSO appearing at the bottom of the list.  Thank you!  
It would still be nice to do more precise matching for subdomains that don't rely on the SSO, but it gets me 90% of the way there.

**Comment by howdytom** [comment]
Strongbox AutoFill in Chrome still shows a Loading... message when I mark an entry as favourite. ? Whereas url are detected using Safari Auto Fill. Is it limitation in the Chrome extension? Any workaround? This is an essential feature for me too.

**Comment by daletman** [comment]
@strongbox-mark Would it be possible to make subdomain match for the Browser extension of Firefox/Chrome?

**Comment by strongbox-mark** [comment]
This should work for you already @daletman - Could you describe the setup that's not working or what you mean by subdomain match?

**Comment by daletman** [comment]
I have multiple entries in my DB which have the same domain but different subdomain, like:

a.abc.de
b.abc.de
d.abc.de

When I go to a.abc.de the Strongbox extension lists under URL Matches all entries (a.abc.de, b.abc.de, d.abc.de).

I'm using Firefox with Strongbox extension version 1.0.2

**Comment by howdytom** [comment]
How many matching entries do have? I stumbled upon the same issue. I noticed that Chrome entries are limited to 42 entries. Everything above 43 entries will lead to the Loading... message. I don't know about Firefox. Did you check with Safari AutoFill?

**Comment by daletman** [comment]
@howdytom I have 8 entries in one DB and two other in a second DB which have this domain.

Total entries are 258 for the first DB and the second DB has 10 total entries.

**Comment by strongbox-mark** [comment]
@daletman - I see, ok, so you would want a strict match there. I believe, and correct me if I'm wrong, that the exact match should rank first in the list of matches?

**Comment by daletman** [comment]
@strongbox-mark That would be preferreble, yes.

But my main issue is not the List of Matches but the fact that the option "Fill on Load if Only Single Match Found" does rely on the same filter as the list, which means if there is more than one match in the List the auto fill will not be triggered.
So the most important thing for me would be that "Fill on Load if Only Single Match Found" does use a very strict match.

**Comment by strongbox-mark** [comment]
OK, would a separate feature: "Fill on single exact URL match" solve your problem?

**Comment by daletman** [comment]
I really love the auto fill feature so I would prefer an exact URL match auto fill. Either as a seperate option or in the current one.

No, I wasn't aware of the Cmd+Shift+L shortcut. Thanks for the tip.

**Comment by strongbox-mark** [comment]
@daletman - So a feature like "Fill on single exact URL match" solve your problem?

**Comment by daletman** [comment]
Yes

**Comment by dan-el** [comment]
In KeePass on Windows autotype can be disabled and also wildcards in urls and several urls per entry can be used. I think it’s  basically an „always exact“ match that can be adjusted with wildcards to match a wider criteria like a domain only.

this approach could help solve the fill on single match request and also help users across the board fine tune the auto type behaviour.

sorry for the late reply to this issue. I have been reading along for a while and meant to add my idea earlier 😄

**Comment by strongbox-mark** [comment]
Hi @georgesnow - I think/hope the sorting algorithm for subdomains/hosts is better in 1.58.10/11, would be interested to hear what you think or what's not working/working.

**Comment by daletman** [comment]
It works great so far

**Comment by strongbox-mark** [comment]
I think this issue has become less pressing or stale, especially with the ability now to exclude individual entries from AutoFill (see #703 )... Please raise fresh issues for any remaining improvements.

**Comment by comzine** [comment]
> Hi @georgesnow - I think/hope the sorting algorithm for subdomains/hosts is better in 1.58.10/11, would be interested to hear what you think or what's not working/working.

I do have 1.58.37. And I also have the same issue.
Autofill in portainer.example.com gives me the suggestion of c.example.com. In the list of other options I can choose portainer.istan.de and it says "From this domain".
Would be really nice, if there is a url matching feature like in KeepassXC.
