### ISSUE TITLE
Length in Passwort Quality Indicator

### ISSUE THREAD

**Issue by EdJoPaTo** [strongbox-password-safe/Strongbox#518]
I really like the new Password Quality Indicator!
As the length is often a criteria I would like to see the length also stated in the bottom right info section. Especially when the Audit shows "Password is too short" it might be interesting to see its current length.

When creating a password for a service which states "up to n" its also helpful to see its length in password generation as diceware sometimes creates shorter/longer passwords (#416).

**Comment by strongbox-mark** [comment]
Hi @EdJoPaTo - That's interesting, perhaps just a suffix or prefix indicating number of characters would suffice? I assume this should be on the View/Edit Details screen only?

**Comment by EdJoPaTo** [comment]
Personally I would be totally fine with just something like `L:42` or `42 characters` next to the bits / years.
Maybe `Strong (42 chars / 1337 bits / >42 years)` gets quite long but the font is also smaller. Not sure about it on smaller devices like the first SE. But shortening it further to something like `L:42` would end up needing more explanation.

I'm not sure about your last sentence there asking for "only". The password Quality Indicator is there for creating / editing / viewing an entry and I think its useful in all these cases. Is it also somewhere else where it is not helpful? Or have I misunderstood something there?

**Comment by strongbox-mark** [comment]
Yes, I think this would be an advanced preference with the default OFF just because it will consume extra screen real estate. As to screens, that's ok, you haven't misunderstood anything.

**Comment by strongbox-mark** [comment]
This has been added now to the strength indicator in the latest release. Cheers!

**Comment by Slummi** [comment]
Where can I find the password length? Can‘t see any changes on the strength indicator in v 1.52.18. Or do you mean a newer release?

**Comment by strongbox-mark** [comment]
It's just in the short strength description, the first number you see, before the entropy bits

**Comment by Slummi** [comment]
Mhh… I think the strength indicator looks the same as before.
![55FFF100-A066-476D-A1F7-0E01D25A2316](https://user-images.githubusercontent.com/42265381/119352030-74302180-bca1-11eb-9dd9-b20532b5ecf1.jpeg)

Is there any special switch to show the length?

**Comment by EdJoPaTo** [comment]
I worked for me without any additional changes after the update

**Comment by strongbox-mark** [comment]
yeah, no switch or anything, it's built in. Can you just double check you're on 1.52.18?

**Comment by Slummi** [comment]
I‘m definitely on 1.52.18, but nothing visible regarding password length. Tried also to create a new database. Same behavior there.

![A1EB0A30-5FBE-4CBD-9983-493016009AD6](https://user-images.githubusercontent.com/42265381/119362755-536dc900-bcad-11eb-82ce-e16b0992dafb.png)

**Comment by strongbox-mark** [comment]
I think this might be a Beta config issue. Were you using the Beta of this via Testflight, before running the Production version? 

If so, I think that you might have an old/stale config. Can you remove/reinstall Strongbox to see if that makes a difference?

**Comment by Slummi** [comment]
I‘m not sure if I have used the beta of 1.52.18, but I used the Beta of the version before. Will try reinstallation and I will also try another device without Testflight.

**Comment by Slummi** [comment]
OK, I've re-installed the app, added the databases and made all settings again and the behavior is the same as before. No password length in the strength indicator visible.

I updated the app on another device and there I can see the password length. Any ideas? Could it be a device specific issue? I'm using an iPhone X with iOS 14.5.1. My other device, which is working, is an iPhone 7 (also 14.5.1).

By the way  it would be nice to have an option for exporting/importing the Strongbox settings. I had several issues in the past where I had to re-install the app and it's no fun having to reconfigure everything again.

**Comment by strongbox-mark** [comment]
Do you happen to have the Outright Pro installed? This will keep settings. You would need to remove all copies of Strongbox to completely clear the settings.

It's not going to be device specific. 

Yes, for sure, import/export and storage of Strongbox preferences in the database are on the backlog :)

**Comment by Slummi** [comment]
I‘ve deleted all versions of Strongbox at the same time - that one with in-app purchases and the Pro version (family edition). All settings were gone. But still no length visible on my iPhone X. In the meantime I‘ve also updated iOS to 14.6. That didn‘t help either. Very strange…

**Comment by strongbox-mark** [comment]
Wow, yes, that is strange. I wonder if a restart of the device are deleting all Strongbox's will do the trick? 

I suspect that the AutoFill component may still be loaded in Safari and that might keep the settings present. Sorry this is probably very inconvenient!

**Comment by Slummi** [comment]
After hours of testing I found the root cause for the invisible length.

If you have once changed the adversary strength in the app settings from default to another value (e.g. 100 billion), the password length is no longer visible. This is irreversible. Even if you go back to the default of 1 billion it‘s still broken. I can reproduce this on my other devices.

**Comment by strongbox-mark** [comment]
Wow, that's amazing detective work @Slummi - Sounds like a bug. Will test this out and fix in the next release.

**Comment by Slummi** [comment]
The issue is solved in the Beta of 1.52.19. Thanks a lot!

**Comment by strongbox-mark** [comment]
That's great, thanks @Slummi

**Comment by Slummi** [comment]
Hi @strongbox-mark, I found another issue with the password strength indicator in the latest beta. I‘m not sure if this is new or if it‘s related to your fix of the length issue.

After editing or creating an item the whole strength indicator disappears until you‘ve left the entry. It does also disappear if you cancel editing. Shall I open a new issue for this bug?

**Comment by strongbox-mark** [comment]
Thanks @Slummi - It's ok, we can use this one. I'll re-open. Is it reasonably cosmetic, would you say?

**Comment by Slummi** [comment]
Yes, of course it‘s rather cosmetic. Thus no rush, but I think it should still be fixed at some point.

**Comment by Slummi** [comment]
Hi @strongbox-mark,

the password strength indicator is now visible all the time in 1.52.21. Thanks for fixing!

**Comment by strongbox-mark** [comment]
Thanks for letting me know! :)
