### ISSUE TITLE
Keep display on while creating / editing an entry

### ISSUE THREAD

**Issue by EdJoPaTo** [strongbox-password-safe/Strongbox#519]
When creating an entry I generate a new password and use it to log on to the service I am creating the account for.
This sometimes takes longer than the display stays on which sometimes resulted in locking and forgetting the just created password (as the save button wasn't hit yet as the password wasn't fully set yet).

I would like the display to just stay on for the time of the edit / add entry dialog. (Probably with a toggle in the settings)

Alternatively the create (maybe not the edit) screen should not be locked / should persist when the screen is turning off / app is in background for too long.

**Comment by strongbox-mark** [comment]
Hi @EdJoPaTo - Maybe a setting/preference under Auto Lock preferences to not lock if currently editing an entry?

**Comment by strongbox-mark** [comment]
This is available now in the latest release. Let me know if there are any issues.

**Comment by EdJoPaTo** [comment]
I am not sure this is working as intended. It does seem reproducible to me.

- Starting the App
- FaceID to unlock the single Database
- New Entry
- Wait for Display to go off
- Turn on / unlock phone, Strongbox requires FaceID and opens into the Database Overview, the new entry and its password is gone.

"Lock Even If Editing" is turned off, so I expect it to not lock as I am editing / creating something.

Should I create a new issue or keep this one?

**Comment by strongbox-mark** [comment]
Hi @EdJoPaTo - I can't reproduce this issue. Could you try restarting your device/Strongbox. If that doesn't work, would you be able to send the debug info and screen recording of the issue (suitably redacted) to support@strongboxsafe.com?

**Comment by strongbox-mark** [comment]
Hi @EdJoPaTo - I believe this issue should be fixed now in 1.55.5, could you verify?

**Comment by EdJoPaTo** [comment]
Looks like it works, thanks again for looking into it!

**Comment by strongbox-mark** [comment]
Great news. Thanks.
