### ISSUE TITLE
Ability to ignore/blacklist some entries from autofill search results?

### ISSUE THREAD

**Issue by azfar** [strongbox-password-safe/Strongbox#521]
Is there any way to exclude some entries from auto search results, I have some credentials applicable to same domain but only one of them is primary which I want to appear in autosearch.

**Comment by strongbox-mark** [comment]
The best way to do this at the moment is to place these entries in a separate folder and disable searching on that folder. The AutoFill suggestions scanner respects the 'Enable Searching' setting on folders. Unfortunately you would need to toggle this setting using a client like KeePassXC or KeePass on Windows as it's not currently exposed in the Strongbox UI.

**Comment by azfar** [comment]
It works but there is drawback that when I really have to search those entries those won't even appear in regular search. Still vouch for exclusion from autofill search only.

**Comment by strongbox-mark** [comment]
Hi @azfar - See #703 - This is now available for you.
