### ISSUE TITLE
Save Master Password into iCloud Keychain

### ISSUE THREAD

**Issue by azfar** [strongbox-password-safe/Strongbox#523]
Would be great to save the Master Password into iCloud Keychain to avoid repetitively entering it for Autofill Warmhole functionality.

**Comment by strongbox-mark** [comment]
I think this probably isn't something I want to add to Strongbox. There is already a Convenience Unlock period, that you can set so that you don't need to re-enter your password, and Touch ID Unlock is also available so this should make things pretty fluid/fast.

**Comment by azfar** [comment]
agreed and your points make sense.
