### ISSUE TITLE
macOS Version: Show/Hide Tab Bar option in Preferences

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#526]
Hi Mark,

Can the "Show/Hide Tab Bar" option also be added to "Preferences/View" rather than only being in the "View" menu bar item? (on macOS)
It's a bit confusing to not have it in the preferences.

Thank you!

**Comment by strongbox-mark** [comment]
OK, I'll see if this can be moved in there, it's a built-in standard OS menu item rather than a Strongbox specific item by the way.

**Comment by dan-el** [comment]
I think this one can be closed since there are now "View" Preferences anymore with the new UI.

**Comment by strongbox-mark** [comment]
OK, thanks @dan-el :)
