### ISSUE TITLE
Encrypting/unlocking Database with Yubikey 5 NFC fails if NFC Tag notification on tap is disabled in Yubico Authenticator

### ISSUE THREAD

**Issue by Bendodroid** [strongbox-password-safe/Strongbox#527]
If I disable the (imo annoying) notification for the yubico demo website when scanning my YubiKey 5 NFC in the Yubico Authenticator -> Settings -> Customize OTP interface:
![image](https://user-images.githubusercontent.com/26770477/121889372-73773200-cd19-11eb-9bd9-3304f8f8302b.jpeg)

I can no longer decrypt my database with strongbox until I reactivate this "feature".

I also can't add this YubiKey to an existing database as a hardware key. The encryption fails and Strongbox asks me if I want to revert to the last known good state.

(All on iPhone 12 Pro with latest Strongbox (1.52.20))

This demo website tap-thing shouldn't be required to use a YubiKey with Strongbox.

**Comment by strongbox-mark** [comment]
I don't think there's anything Strongbox can do here, this is probably one for Yubico.
