### ISSUE TITLE
WebDAV storage label not visible in iOS AutoFill (1.52.21)

### ISSUE THREAD

**Issue by Slummi** [strongbox-password-safe/Strongbox#528]
After updating to 1.52.21 the WebDAV storage label isn‘t visible in the database view of AutoFill. Instead of „WebDAV“ the name of the method is shown. I tried to add a screenshot, but it‘s not working at the moment. I‘ll try to add it later.

**Comment by Slummi** [comment]
OK, here's the screenshot. The upload via iPhone wasn't possible.
![IMG_014145](https://user-images.githubusercontent.com/42265381/122289253-c9eb9880-cef2-11eb-8ddf-54ada544b376.JPG)

**Comment by strongbox-mark** [comment]
Interesting, thanks for the report @Slummi - Probably a simple bug to fix.

**Comment by Slummi** [comment]
This has been fixed with 1.52.23. Thanks!
