### ISSUE TITLE
Feature Request: Option to Automatically close Database Manager window when opening a database

### ISSUE THREAD

**Issue by sindastra** [strongbox-password-safe/Strongbox#530]
### Feature Request:

I would like to request the option to automatically close the "Database Manager" window once opening a database.

### Detailed description:

Imagine you're on the "Database Manager" window, you have database.kdbx in the list, so you double-click it to open it and a new window for database.kdbx opens.

At this point, if the option to "Automatically close the Database Manager on open" has been checked in the preferences, the "Database Manager" should close and only the new window should be visible.

### Reason behind request:

After opening a database, the "Database Manager" window is a bit pointless and has to be closed manually each time, so an option to automatically close would help a lot.

**Comment by strongbox-mark** [comment]
Sounds reasonable!

**Comment by strongbox-mark** [comment]
This is available now with 1.15.18 and ON by default.
