### ISSUE TITLE
Database opening error

### ISSUE THREAD

**Issue by azfar** [strongbox-password-safe/Strongbox#531]
Few times on Macbook with TouchID it fails to open the database and returns an error (see attahced). This also happen on non TouchID Macbook as well and I will post the screenshot of it later.

https://ibb.co/k6NLLS2

**Comment by strongbox-mark** [comment]
Hi @azfar - could you update to 1.15.14 and let me know if this is still happening?

Assume you are running Catalina or older?

**Comment by azfar** [comment]
> Hi @azfar - could you update to 1.15.14 and let me know if this is still happening?
> 
> Assume you are running Catalina or older?

Sure, I am on BigSur (TouchID and non-TouchID MacBooks) and I will post my experiences after the update.

**Comment by strongbox-mark** [comment]
Interesting, does this happen after you update on another device, say KeePass on Windows? Where is the database stored?

**Comment by azfar** [comment]
> Interesting, does this happen after you update on another device, say KeePass on Windows? Where is the database stored?

It does not happen frequently so I have to wait and see on diff devices and i believe its not a case with windows (keepassxc). My database is on gdrive.

**Comment by strongbox-mark** [comment]
Hi @vbergl - Thanks for your report. Lots of questions:

- What happens to you everytime? You get a permissions error?
- You don't get the message on certain databases when opened in Strongbox - Is that correct?
- What does "old databases" mean? Are these ever edited? 
- Where is your database (the one that you get the errors with) stored?
- What version of MacOS are you running? If older than Big Sur, could you update Strongbox to 1.14.15 to see if that helps?

Thanks!

**Comment by vbergl** [comment]
Yes I get permission error.
I get errors on databases that were modified or just opened before by Stronbox
By old I meant those that were not even once opened by Stronbox, only KeepassXC. When I tried to open it second time I got "permission error".  It seems that Strongbox can it open only once.
Most of my databases are on local disk but I do have one on iCloud, it fails in the same way.
I have Catalina. I will upgrade to BigSur in near future, but I was not planning it now.

**Comment by strongbox-mark** [comment]
OK, that's odd. Before you upgrade to Big Sur, could you try:

1. Upgrade to 1.14.15 on the App Store now
2. If that doesn't help, could you try, removing and re-adding your database(s) in the Databases Manager window

Let me know how that goes...

**Comment by vbergl** [comment]
OK, seems like removing it from Database Manager fixes the problem. And suprisingly I can close it/open it repeatedly.
But: The problem reappears after I restart Strongbox.
I have 1.15.15

**Comment by strongbox-mark** [comment]
Thanks for the extra detail @vbergl - that does sound like a bug for sure. I will investigate that further...

**Comment by azfar** [comment]
same here, still facing the issue.

https://ibb.co/wMmnt69

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
I have also been getting this error the first time I try to unlock after I haven't used the app for a while. The first time fails with Touch ID and then I repeat the process and it works.

**Comment by strongbox-mark** [comment]
HI @azfar - Could you help by providing the info requested here: https://github.com/strongbox-password-safe/Strongbox/issues/531#issuecomment-867414727

@JLWFuQrioea69ugsykvQcg What version of MacOS are you running?

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
I'm running the latest final version of Big Sur (11.4?) on a MacBook Air M1.

**Comment by azfar** [comment]
I am on Big Sur 11.4 Intel.

**Comment by strongbox-mark** [comment]
Hi @azfar and @JLWFuQrioea69ugsykvQcg - Could you please let me know:

- Does this happen after you update on another device, say KeePass on Windows? or is it all the time?
- Where are your databases stored?

**Comment by azfar** [comment]
> Hi @azfar and @JLWFuQrioea69ugsykvQcg - Could you please let me know:
> 
> * Does this happen after you update on another device, say KeePass on Windows? or is it all the time?
> * Where are your databases stored?

I definitely have heterogenous env but I only update my file from either of my Mac and both Macs have same Intel Big Sur 11.4 and same Strongbox version. My storage is gdrive.

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
I store my database on OneDrive and sync between devices. I update it on Windows using the latest versions of Keepass 2 (2.48.1), Strongbox on iOS, and Strongbox on MacOS.

**Comment by strongbox-mark** [comment]
> > Hi @azfar and @JLWFuQrioea69ugsykvQcg - Could you please let me know:
> > 
> > * Does this happen after you update on another device, say KeePass on Windows? or is it all the time?
> > * Where are your databases stored?
> 
> I definitely have heterogenous env but I only update my file from either of my Mac and both Macs have same Intel Big Sur 11.4 and same Strongbox version. My storage is gdrive.

Thanks, do you notice any pattern in when this issue occurs? After an update to the database?

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
I've been able to test it some and it does seem to happen after an update occurs outside of Strongbox. I'll test it some more in the next day or two.

**Comment by strongbox-mark** [comment]
Thanks for the update. My guess is the update from an external app is invalidating the reference that Strongbox has to the file. There might be a way around this, but let me know how your testing goes...

**Comment by strongbox-mark** [comment]
I'm going to close this one out as I believe recent builds have addressed the issue. If there are still ongoing problems, then please feel free to open new issues.
