### ISSUE TITLE
Bug - macOS menu bar disabled

### ISSUE THREAD

**Issue by georgesnow** [strongbox-password-safe/Strongbox#532]
When using the minimize to tray option when activating strongbox via status bar icon the menu bar is disabled. keepassxreboot/keepassxc#6575 keepassxc had a similar issue. When setting the  activation policy via accessory or prohibited means it doesn't menu bar (and usually no dock icon). KPXC found some sort of work around to allow the dock icon re appear when activating and having menu bar work.

**Comment by strongbox-mark** [comment]
Thanks for the report @georgesnow - Sounds really strange but annoying. Will investigate.

**Comment by strongbox-mark** [comment]
@georgesnow This should be fixed for you now in 1.15.19. Please re-open if not.
