### ISSUE TITLE
macOS auto fill feature request

### ISSUE THREAD

**Issue by georgesnow** [strongbox-password-safe/Strongbox#533]
Is possible to add the option to create a new entry based on the current url? So you select strongbox you have search options but the ability to create a new one there and fill that entry would be nice.

**Comment by strongbox-mark** [comment]
Agreed.

**Comment by georgesnow** [comment]
Just curious if this is still well down the road? The create entry on iOS autofill has been great. 
I have run into a few times now when using my Mac where I need to create entry for a new account or one I somehow haven't added to my database.

**Comment by strongbox-mark** [comment]
Yep, absolutely still on the list... fairly important, but overhaul of the mac UI is a huge job that comes first...

**Comment by strongbox-mark** [comment]
Hi @georgesnow - This is available with Chrome/Firefox extension but not on Safari, just to clarify this is a request for Safari?

**Comment by pictosun** [comment]
> ...but not on Safari, just to clarify this is a request for Safari?

For me I would like to see it working with Safari. Overall I thought this is working without any issues, as it's one of a main component when using an integrated password manager.

**Comment by strongbox-mark** [comment]
Linked to #607 - will hopefully get to this in the next release, eta about a month, but might happen sooner.

**Comment by strongbox-mark** [comment]
@georgesnow This is available now on macOS
