### ISSUE TITLE
Press modifier key to show password(s)

### ISSUE THREAD

**Issue by notDavid** [strongbox-password-safe/Strongbox#540]
Please consider implementing the ability to display (all) passwords when a modifier key is pressed (macOS and iOS when using keyboard.)

The ⌥ (option) key would be a good default i think.

It's very convenient, thanks :)

https://user-images.githubusercontent.com/1530401/129445791-4a354a30-6f62-4509-9351-86709ebdd951.mp4

**Comment by strongbox-mark** [comment]
Sounds like a good idea, consider it added to the list.

**Comment by strongbox-mark** [comment]
Hi @notDavid - This is available now with 1.16.0. Holding down the option key will reveal the password.

Please let me know if there are any issues.
