### ISSUE TITLE
Face ID Failed

### ISSUE THREAD

**Issue by notDavid** [strongbox-password-safe/Strongbox#541]
Hi there,

I'm getting this error multiple times a day. I've **enabled** the `Quick launch & App lock: coalesce biometrics` setting, and what happens is, i open the app and the first FaceID succeeds, then the quick launch database is automatically opened and i immediately see a second FaceID check which fails with this error message.

Then, it asks me to manually enter the database password, and i click cancel. I click the database again, see FaceID again, and now it succeeds.

The way i understand the setting, the second FaceID check should not even be happening?

When this error happens, if i then close the app, lock the device, and then unlock the device, and open Strongbox again, i can no longer reproduce it: now i *can* open the app and the quick launch database will automatically open and it will only ask for the FaceID 1 time.

This is happening on both the latest iOS and iPadOS beta's by the way, not sure if that's related.

Strongbox Pro 1.53.0

iOS 15.0 beta6
iPadOS 15.0 beta6
iPhone 12 Pro
iPad Pro 12.9

![image](https://user-images.githubusercontent.com/1530401/130278811-b3c23239-ee49-4222-94bd-91d13c354d8a.jpeg)

**Comment by strongbox-mark** [comment]
Hi @notDavid - Sounds like a bug, could you send the debug info from your About screen? Send to support@strongboxsafe.com if not comfortable sharing here, or redact as you see fit.

**Comment by strongbox-mark** [comment]
Also, has this only started happening with iOS 15 Beta?

**Comment by notDavid** [comment]
Thanks for your reply, i've send the e-mail.

Not sure about the Beta, because i've only been using FaceID/the Pro version of Strongbox since i'm running the Beta...

**Comment by strongbox-mark** [comment]
Thanks @notDavid - Looking at your video, does this only happen when launched from Spotlight Search? or does it happen if you switch back to home screen and tap on the App?

**Comment by notDavid** [comment]
@strongbox-mark it also happens when i launch Strongbox the normal way, from the Home screen.

PS. I can't always reproduce it, not even when i reboot the device. I think it *always* happens every morning though, the first time i open/unlock Strongbox 🤷🏼‍♂️

I assume you can see these settings in the .log, but just in case it's relevant:

![image](https://user-images.githubusercontent.com/1530401/130324324-0f313871-d0a0-4d37-8ad7-aba2bea8c374.jpeg)

![image](https://user-images.githubusercontent.com/1530401/130324327-93054452-8ccd-4018-a869-9a8a66b08bc1.jpeg)

**Comment by strongbox-mark** [comment]
Thanks for the extra info... let's keep this open, perhaps others are experiencing similar?

**Comment by notDavid** [comment]
@strongbox-mark Can you also not reproduce the fact that the authentication often happens 2 times, even though the `Quick launch & App lock: coalesce biometrics` setting is enabled?

(the second authentication does not always show the error, sometimes it succeeds.)

**Comment by notDavid** [comment]
PS. I found [this](https://developer.apple.com/forums/thread/668815), not sure if useful to you...

**Comment by strongbox-mark** [comment]
Thanks @notDavid - Yes, I'm afraid I can NOT reproduce the issue, but I will investigate further.

**Comment by notDavid** [comment]
Sure, no worries. It could also be related to the Beta, so perhaps we should wait a bit until the beta GM/final release before you waste more time;

By the way, the second FaceID authentication happens very frequently. The error message only happens occasionally.

Also I just noticed another weird thing; when i "force close" the Strongbox app by swiping up in the app switcher, sometimes suddenly a FaceID authentication happens (while/right after killing the app.) After this authentication i continue back to the home screen. This happens on both my iPhone and iPad Pro.

**Comment by strongbox-mark** [comment]
I wonder, if you are willing, does a full remove/re-install of the App help?

**Comment by notDavid** [comment]
Sure I'll try that, but i seriously doubt it will work, because:

I had another older iPad laying around, a 10.5 Pro with TouchID (instead of FaceID.) This one also asks for the 'double authentication' check (with `Quick launch & App lock: coalesce biometrics` enabled), but i have not seen the error yet.

I *assume* the error doesn't appear because the TouchID check is presented in a modal popup window, which is very slow compared to the FaceID check on the new iPad Pro and iPhone 12 Pro. So the delay of the second TouchID check probably prevents the error from happening.

**Comment by strongbox-mark** [comment]
Thanks @notDavid - Would love to know if this is a Beta issue or not, but you're up to the bleeding edge on all your devices! :D

**Comment by notDavid** [comment]
Hah yes true... and yea i undestand that!

Okay so I'll downgrade the 10.5 iPad with TouchID to check if the "double authentication" bug still occurs after reinstalling Strongbox in iOS 14, assuming that would be useful.  I just double checked, and i can reproduce the "double authentication" quite easily/often.
It will take me a few hours time though to back up some data and such, as i can't simply do a downgrade (...who knows maybe you might even consider a macOS Stronghbox Pro license as compensation for the time 😉😅)
I don't get the actual error on this iPad though, but if the double authentication would be gone after a downgrade then i guess that would give you some more info...

I'll install it as a "clean" iOS15 beta first, and try to reproduce. Then reinstall again but now do a "transfer data/settings" of my other iPad, and try to reproduce again.

**Comment by notDavid** [comment]
Great, thank you! 🙏🏼

I just reproduced the "double authentication" (not the error, because TouchID and not FaceID) on 14.7.1 on the iPad 10.5, clean iOS install, with a new Strongbox sample database. I did change some settings on first open, like 'app lock delay' (i made a video of all settings i changed.)

I think it took me about 20 tries of opening/unlocking the app to reproduce.
I suspect i had to wait 15 minutes for the app lock to happen before i could reproduce.
So to reproduce faster, maybe set the 'app lock delay' to 'none'.

Will send the videos via e-mail 🙂

**Comment by notDavid** [comment]
PS. To reproduce it seems to help to very quickly do the authentication. So do not wait after the touch-id is asked. You want to basically do the touchID almost before the popup appears.

Waiting, seems to not trigger it.

**Comment by strongbox-mark** [comment]
Hi @notDavid - This should be fixed for you in latest release 1.53.1 on the App Store now. :)

**Comment by notDavid** [comment]
@strongbox-mark Unfortunately, I just got the error again, in 1.53.1
Also, the double authentication is still there.

![image](https://user-images.githubusercontent.com/1530401/132029238-bca3e654-f315-423a-86e9-2722a593194e.jpeg)

**Comment by notDavid** [comment]
PS. This is in the latest iOS & iPadOS Public Beta, from like 2 days ago...

**Comment by strongbox-mark** [comment]
Thanks @notDavid - Are you 100% sure you're running 1.53.1? Could you send me another screen recording of the issue? Thanks!

**Comment by notDavid** [comment]
100% sure. I will send you a video soon.

Also, FYI, i noticed another thing not working. Perhaps it is useful to know/related; The `convenience auto unlock` for AutoFill is not working either. I noticed it on amazon.nl where you first get a screen to enter the e-mail address and after submitting a new screen asks for the password. I have to do FaceID auth 2 times here (within like 15 seconds) even though the `convenience auto unlock` in the database settings is set to 5 minutes.

**Comment by strongbox-mark** [comment]
Thanks David

**Comment by strongbox-mark** [comment]
Hi @notDavid - Could you verify 1.54.0 fixes this issue for you, I believe it should?

**Comment by notDavid** [comment]
Yea, I was keeping an eye on it, haven't seen the issue yet it the past 24 hours. So looking good 😀 (until now...)

**Comment by strongbox-mark** [comment]
Great so far... Will close now and feel free to re-open.

**Comment by notDavid** [comment]
Yep, can confirm this is definitely solved now 👌🏼
