### ISSUE TITLE
Ability to search across all open databases (Mac)

### ISSUE THREAD

**Issue by rburgst** [strongbox-password-safe/Strongbox#542]
simliar to https://github.com/strongbox-password-safe/Strongbox/issues/401 but (also) for Mac OS.

**Comment by strongbox-mark** [comment]
OK, yes, thanks for the request.

**Comment by strongbox-mark** [comment]
Hi @rburgst - Bit of an old one, but we've added the ability to search across all open databases with the "Quick Search" feature (in 1.60.9) now. You can launch it from the tray icon with a click or use the hot key. Going to close this one out for now, but let me know if you have any trouble.
