### ISSUE TITLE
Hide on minimise (Mac)

### ISSUE THREAD

**Issue by SL93Code** [strongbox-password-safe/Strongbox#543]
Since I installed the latest update Strongbox will stay in the dock on minimising, although it is setup to hide and only show in menu bar.

**Comment by strongbox-mark** [comment]
Hi @SL93Code - This should be fixed in 1.15.21 available on the App Store now. Could you try it out?

**Comment by SL93Code** [comment]
Works fine now. Is it possible to implement a function to minimize the app on copying any data?

**Comment by strongbox-mark** [comment]
Thanks @SL93Code - Sure, could you just open a separate issue for that request?

**Comment by SL93Code** [comment]
Issue seems to be back.

**Comment by SL93Code** [comment]
It is gone if I disable and reactivate the feature in the settings.

**Comment by strongbox-mark** [comment]
Hi @SL93Code - Could you be more specific, or please send a screen recording of the issue as I can't reproduce.

**Comment by SL93Code** [comment]
I made screen record of the issue. Where can I send it to?

**Comment by strongbox-mark** [comment]
Hi @SL93Code - Could you send to support@strongboxsafe.com? Thanks!
