### ISSUE TITLE
Any way to copy the TOTP seed without going into edit mode?

### ISSUE THREAD

**Issue by gitbq** [strongbox-password-safe/Strongbox#544]
Hi Mark

Loving the app!!

I'm trying to share some 2fa TOTP seeds with other devices, and the only way I can see to do this is to "edit" the item, and then manually select the "seed" and copy.

Is there any way to copy just this seed to add on another device without entering "edit" mode where I could mistakenly change something?
Or is there some way to generate a qr code for sharing the seed? Some examples are Google Authenticator and KeepassXC.

Thanks

**Comment by strongbox-mark** [comment]
Hi and thanks!  If you have MacOS, you can get a QR Code quickly for this on the details screen. 

On iOS, there is a sort of way that might work better for you... First make sure that "Show TOTP Custom Fields" is on for the Details View (Unlock Database > More button > Customize View > Details View > Show TOTP Custom Field (ON)).

Now, tap in to the Entry and you can Long Tap on the Custom Field to get the "Large Text View". It's it's an OTP url you will probably be able to just scan it into a compatible app, but if it's just the secret you'll at least be able to view without editing.

**Comment by gitbq** [comment]
I'm using ios.
Perfect solution!! That's all I could have hoped for!
Thanks again.

**Comment by strongbox-mark** [comment]
No worries, it's a very overlooked feature (Large Text View), I need to make it more discoverable :)

I'll add a feature to the next release, so that a long tap on the actual TOTP code itself (in view mode) brings up an OTP URL and QR Code (like on Mac).

Let's consider this issue a "Feature Request" for that :)

**Comment by strongbox-mark** [comment]
Hi @gitbq - This is available with 1.53.1 on the App Store now. :)
