### ISSUE TITLE
iOS: Crash when creating new entry from within Safari

### ISSUE THREAD

**Issue by danielfomin96** [strongbox-password-safe/Strongbox#545]
Hello,

I am getting crashes every time when going to a login page in Safari, opening Strongbox from there and creating a new entry. This can be seen in the following video:
[Video](https://imgur.com/yPoJBgN.mp4)
The crash happens while submitting the entry. The entry can not be found after that in the databank.

iOS Version: 14.7.1
Strongbox version 1.53.1

**Comment by strongbox-mark** [comment]
Hi @danielfomin96 - Sorry about that. This is a known issue and it's due to your database size (17MB). We're working on a performance fix for this at the moment, but it could take a while to get out. Can I ask if your database is KDBX 4 or 3.1? You can see this in (Database Settings > Statistics & Properties)

**Comment by strongbox-mark** [comment]
Yes, it depends on the content of your database (lots of entries vs attachments) but usually below 5MB isn't a problem... The issue is in AutoFill Apple places a fairly tight limit on the amount of memory Strongbox can use... 

I'd expect a fix for this probably in the next 3 weeks or so...

**Comment by danielfomin96** [comment]
It is great to hear that this problem is fixable and a fix is underway!

**Comment by strongbox-mark** [comment]
Hi @danielfomin96 - Would you be willing to help test the Beta for this? If so could you drop us a mail support@strongboxsafe.com?

**Comment by danielfomin96** [comment]
Sure thing, I will send an email right away.

**Comment by strongbox-mark** [comment]
Hi @danielfomin96 - I believe things should be much improved here with 1.54.0. Could you confirm? Thanks!

**Comment by danielfomin96** [comment]
I can confirm. Works now without crashes. Thank you!

**Comment by strongbox-mark** [comment]
> Still crashes for me

Drop us a mail with you debug info and we'll try to help (support@strongboxsafe.com)
