### ISSUE TITLE
Add search capability to the Tray App

### ISSUE THREAD

**Issue by georgesnow** [strongbox-password-safe/Strongbox#551]
![image](https://user-images.githubusercontent.com/12751441/137526497-e4a7c9f5-11b8-47a5-94d1-82c810b22aef.png)

would be cool if you could have the database shoe in the mini window for quick searches for copying and grabbing a quick password or piece of information. particularly pinned items or TOTPs.

additionally would be set the initial search context based on the front most application when revealing the menu bar item.

**Comment by strongbox-mark** [comment]
Nice idea @georgesnow - thanks

**Comment by georgesnow** [comment]
just checking in if this something that is near or more the long term road map

**Comment by strongbox-mark** [comment]
Hey @georgesnow - We've added the ability to search across all open databases with the "Quick Search" feature (in 1.60.9) now. You can launch it from the tray icon with a click or use the hot key. Going to close this one out. Let me know if you have any trouble.
