### ISSUE TITLE
KeePass OTP fields other than TimeOtp-Secret-Base32 do not get parsed

### ISSUE THREAD

**Issue by mstarke** [strongbox-password-safe/Strongbox#552]
If an entry uses the custom field from windows, only ```TimeOtp-Secret-Base32``` is correctly read. Any of the other fields is not parsed correctly. I think it seems to be a simple copy and paste error in the code. I was about to open a PR but since you cannot merge I did not open one.

https://github.com/strongbox-password-safe/Strongbox/blob/860dbce9ea47110747c50a5d8072cf49cdb8cdc4/model/NodeFields.m#L881-L889

**Comment by strongbox-mark** [comment]
🤦‍♂️ Yup, looks like a copy/pasta bug on my part...

Thanks for raising @mstarke and hope this hasn't caused you much support trouble. Will get that patched up asap.

**Comment by strongbox-mark** [comment]
Hi @mstarke - This should be fixed for you in the latest builds. Apologies for the confusion and thanks for the bug report :)
