### ISSUE TITLE
Database Manager shows itself (when it shouldn't)

### ISSUE THREAD

**Issue by sindastra** [strongbox-password-safe/Strongbox#558]
When I launch Strongbox on Mac, the Database Manager instantly hides itself (as it should, since it's set to hide in the settings).

However, as soon as I click on a database to open (from the tray icon), the Database Manager pops up, which makes no sense to me and I have to manually close it every time.

It should be noted that, once I manually close the Database Manager, and then try to open any database again, it won't pop up again. So, I guess, the Database Manager never actually closes itself and instead really just "hides", at first, until manually closed.

I mean, the setting actually says "Hide", but it would be nice to have it actually close or stay hidden, and not randomly pop back up when using the tray.

I attached a screenshot of my preferences, in case that helps.

Oh and, while no big deal, might be nice for it to not even show in the first place (I mean, the momentary showing and hiding isn't that nice).

Maybe we need a new option/logic altogether: "Do not open Database Manager on startup".

###### On another note, while I love Strongbox on iPhone, I have to say the UX on Mac has been very confusing and inconsistent, especially window management and database locking/unlocking. It often gets in my way, and I just wanted to point that out. Maybe Strongbox should work as a single-window application, without the separate Database Manager. Perhaps look at KeePass XC for inspiration, I never had issues there. Let me know if I should open an issue for that suggestion. I'm not sure if feedback warrants an issue, which is why I'm mentioning it here instead.

![image](https://user-images.githubusercontent.com/1236984/141177880-770ca6b1-7223-4396-974a-df3e9a91a4bd.png)

**Comment by strongbox-mark** [comment]
Hi, I think probably best to add a setting to hide the Databases Manager window at Startup as the best interim stop gap for the moment. 

There are a lot of Mac UI changes planned, but at least for the foreseeable future I'm not attracted to the Single Window Application. I can see the attraction, but it's also nice to have the ability to have different databases in different windows and different tabs. Perhaps some kind of hybrid combination could work. This would have to be looked at after the other, rather large UI changes in the coming months.

**Comment by georgesnow** [comment]
I noticed this too with the database window. However the hide would do the trick for me and I do prefer multi-window style on macOS.

**Comment by sindastra** [comment]
Hi, please ensure that it stays hidden and does not pop up when choosing a database from the tray menu. That's the more annoying part (having to manually close it).

###### PS, If you'd like, I could open an issue for the other topic so that we don't get too off-topic on this here. When I originally mentioned it, I didn't think it would get much attention. Apologies for mentioning a separate thing earlier, at the time it just seemed "fitting".

**Comment by sindastra** [comment]
@strongbox-mark Hi, I just downloaded the latest update (1.16.4) and the new option resolved both issues for me. Thank you! (:

**Comment by strongbox-mark** [comment]
Thanks @sindastra - glad to hear it

**Comment by sindastra** [comment]
Hi there, I love the new UI redesign! But since that update, the database manager pops up again when choosing a database from the tray, which is why I'm reopening this issue. (:

**Comment by strongbox-mark** [comment]
Hi @sindastra - I believe this should be fixed for you with the latest release (1.57.2), could you confirm and close?

**Comment by sindastra** [comment]
Seems fixed.
