### ISSUE TITLE
iOS: Master password requested with "quick" Autofill, but not when "manually" choosing entry via Autofill

### ISSUE THREAD

**Issue by alcroito** [strongbox-password-safe/Strongbox#559]
Hi,

I'm using Face ID with Autofill on an iOS device and recently it's always been asking me to enter the master password instead of using Face ID if i select one of the suggested "quick" autofill options.

For example when i visit paypal.com with Safari as shown in the screenshot below, if I click the suggested autofill item, or click the key icon and then either of the suggested 2 entries, Face ID is entirely skipped and a master password is requested. 
If enter the password and then try to go through the process again, the master pass is requested again.

![IMG_5142](https://user-images.githubusercontent.com/252084/142691309-24e06410-0cd3-436f-8349-df9cc3d15aa1.jpg)
![IMG_5143](https://user-images.githubusercontent.com/252084/142691312-c39bb5bf-a2c9-49ea-a001-94b40c404b32.jpg)

If I select the Key icon and then choose "Strongbox" entry, Face ID successfully authorizes and brings me to the search page.
Opening the app directly also uses Face ID successfully.
I tried enabling / disabling the biometric settings options in the app, but that didn't help.

I'm fairly sure it used to work fine before.

Environment:
iOS: 15.1
Strongbox Pro: 1.54.2
iPhone 13 Pro

**Comment by strongbox-mark** [comment]
Sounds like it could be a bug, but you're the first report. Would you mind sending the debug info from your About screen to support@strongboxsafe.com?

**Comment by alcroito** [comment]
Sent the debug info

**Comment by alcroito** [comment]
Bah, it's suddenly working now. After entering the master password once via the Autofill suggestion, repeating the steps works fine and uses face id.

I'll report back if i get the issue again and notice any pattern. Feel free to close the issue if you wish.

**Comment by strongbox-mark** [comment]
Oh ok, super weird. If you've got QuickType AutoFill enabled for more than 1 database then it's quite possible to see "suggestions" that you think are in one (Face ID enabled) database, but are actually in another (none Face ID enabled) database, which is what I would hope was happening here... Otherwise it's a bug by the sound of things... 

Will close for now, but feel free to re-open.
