### ISSUE TITLE
Possible freeze when adding attachment(s)

### ISSUE THREAD

**Issue by sindastra** [strongbox-password-safe/Strongbox#561]
I was just setting up a few entries in my database, and attaching files (one by one) which worked fine, but when I chose two files in Finder to attach simultaneously, Strongbox froze and is giving me an endless spinning beach ball.

Note that I can see the two files successfully added in the attachments tab, but it froze right away.

I ended up force closing Strongbox after a few minutes, the Database luckily remained intact (and the files were actually attached on re-open).

I tried to reproduce it now, but it didn't freeze again. I still thought it might be worth bringing this up, in case anyone else notices similar behavior. Perhaps the adding of multiple files was just a coincidence, and the actual cause for the freeze was something else. But those were the steps leading up to the freeze:

1. Editing multiple entries
2. Adding files (one by one) to those entries
3. Drag and drop two files from the (dedicated) Finder window into the selection window, and then selecting to add them in Strongbox
4. Freeze (endless spinning beach ball until I force closed)

**Comment by sindastra** [comment]
Update: Just now, it froze while adding one attachment, so the multiple attachments seemed to be coincidence. There seems to be an issue with adding of attachments in general.

**Comment by strongbox-mark** [comment]
Hi @sindastra - would you be so kind as to include debug info?

**Comment by sindastra** [comment]
Hi @strongbox-mark I hope you mean the following from the about screen:

```
Strongbox 1.16.5 Debug Information at 2021-11-28 17:28:58.123
--------------------
App Version: com.markmcguill.strongbox.mac.pro [1.16.5 (3043)]
--------------------
Device
--------------------
Model: MacBookAir10,1
CPU: ARM64E
System Name: MacOS
System Version: Version 11.6.1 (Build 20G224)
--------------------
Preferences
--------------------
quickRevealWithOptionKey: 1
hideKeyFileNameOnLockScreen: 1
colorizeUseColorBlindPalette: 0
alwaysShowPassword: 0
doNotRememberKeyFile: 1
trayPasswordGenerationConfig: {length = 651, bytes = ***redacted*** }
closeManagerOnLaunch: 1
showDatabasesManagerOnEmptyStartup: 0
showDatabasesManagerOnCloseAllWindows: 0
showCustomFieldsOnQuickView: 0
hideDockIconOnAllMinimized: 1
showAttachmentImagePreviewsOnQuickViewPanel: 0
migratedConnections: 1
databases: {length = 3965, bytes = ***redacted*** }
autoSave: 1
showPasswordGenInTray: 1
showPasswordImmediatelyInOutline: 0
makeLocalRollingBackups: 1
fullVersion: 1
autoLaunchSingleDatabase: 1
clipboardHandoff: 1
miniaturizeOnCopy: 0
colorizePasswords: 1
showSystemTrayIcon: 1
hasMigratedToSyncManager: 1
clearClipboardAfterSeconds: 600
markdownNotes: 0
showAttachmentsOnQuickViewPanel: 0
```

Please note that I did not include the Sync info, since it includes parts of the WebDAV config and other info I'm not comfortable sharing.

**Comment by strongbox-mark** [comment]
That's great, thanks @sindastra

**Comment by strongbox-mark** [comment]
Hi @sindastra - We've been working on fix for this and it is now available on the App Store as version 1.16.7. Could you update and see if it fixes things for you?

To update, you might need to actively search for 'Strongbox' on the App Store, then click in to it to see the "Update" button as Apple are rolling the release out slowly.

**Comment by sindastra** [comment]
Hi, please excuse the delayed response, I am up-to-date (1.16.7), I did try to add/remove some attachment repeatedly, I even tried to hit &#8984;+S right after adding (which AFAIK should save and sync immediately, and might have been the cause of the freezes last time) to see if I can trigger a freeze, but so far none.

Since you claim it's fixed, and I didn't get a freeze so far with quick testing, and it's futile to try to prove a negative (I can't repeat this test forever), I will let you know if the issue happens again. (:

**Comment by strongbox-mark** [comment]
OK, great, we'll close out for now...
