### ISSUE TITLE
Can't Save/Upadte Passwords over WebDAV (com.MattRajca.DAVKit.error-Fehler 500.)

### ISSUE THREAD

**Issue by Litceo** [strongbox-password-safe/Strongbox#567]
I have my keepass file synced across my devices via nextcloud. I can read the keepass database with no problem but whenever I try to save a new password or update the kdbx file in any way I get this error `com.MattRajca.DAVKit.error-Fehler 500`. I have this problem on the desktop app (macos) as well as on the mobile app (ios) and whenever this happens i need to readd the database to the strongbox app. However when I use KeeWeb on my mac I can update the database over WebDav with no problems at all.

I could not find any other thread wich descibes this exact problem so maybe you can help me. Thank you:)

**Comment by strongbox-mark** [comment]
Hi @Litceo - Strange. The 500 error is coming from your Nextcloud server. Could you have a look in the server logs and see if you can see anything with a little extra detail there.
