### ISSUE TITLE
Use additional urls for favicon search

### ISSUE THREAD

**Issue by ispiropoulos** [strongbox-password-safe/Strongbox#568]
Hi, what about using any additional URL* found on the custom fields section to search for favicons?

**Comment by strongbox-mark** [comment]
Hi @ispiropoulos - Definitely possible, we can add this to our backlog.

**Comment by dan-el** [comment]
I'd love to see this feature!

**Comment by strongbox-mark** [comment]
This one should be available for you now with 1.58.32/33 on macOS/iOS :)

**Comment by ispiropoulos** [comment]
Thank you @strongbox-mark
