### ISSUE TITLE
Bug: Entering self created passwords doesn’t allow for spaces at the begin or at the end. 

### ISSUE THREAD

**Issue by milesmcclane** [strongbox-password-safe/Strongbox#571]
If you want to create your own password, and you have either a space at the beginning or a space at the end,  Strongbox will delete those blank characters upon saving.

**Comment by strongbox-mark** [comment]
Is this on iOS or macOS @milesmcclane

**Comment by milesmcclane** [comment]
This is on iOS, sorry for not being clear. I haven’t had chance to test macOS to see if the issue exits.

**Comment by strongbox-mark** [comment]
OK, got it. Will try to have a look at this for the next release or so.

**Comment by strongbox-mark** [comment]
@milesmcclane - This should be fixed for you - if you leave a leading or trailing whitespace, Strongbox will ask if you meant it.

**Comment by milesmcclane** [comment]
Thanks!
