### ISSUE TITLE
Cannot save file when home is on another volume

### ISSUE THREAD

**Issue by zaucks** [strongbox-password-safe/Strongbox#572]
Every time I try to save a file, it fails with an error (regardless of the format : KeePass or Password Safe)
I've pasted below the matching line in the Console.
As you can see my home is on a separate APFS volume (/Volumes/Users), which isn't the same as /var/folders (which is /System/Volumes/Data)
The error seems to come from `NSFileManager.replaceItemAtURL:withItemAtURL:` in [WorkingCopyManager .setWorkingCache:](https://github.com/strongbox-password-safe/Strongbox/blob/3b661717fb3285fecef1abc566f71d3d3aab73e4/Sync/WorkingCopyManager.m#L60)
Both parameters must be located on the same volume, see the [discussion](https://developer.apple.com/documentation/foundation/nsfilemanager/1412432-replaceitematurl#discussion) for the explanation and a solution.

```
App Version: com.markmcguill.strongbox.mac [1.16.7 (3045)]
--------------------
Device
--------------------
Model: MacBookPro11,1
CPU: Intel x86-64h Haswell
System Name: MacOS
System Version: Version 11.6.2 (assemblage 20G314)
```

```
SyncManager::replaceItemAtURL - failed with Error Domain=NSCocoaErrorDomain Code=512 "Impossible d’enregistrer le fichier « 33A74752-FC09-48BD-9A5B-0FB9535F3EC7 » dans le dossier « local »." 
UserInfo={
NSFileOriginalItemLocationKey=
  file:///Volumes/Users/sylvain/Library/Group%20Containers/group.strongbox.mac.mcguill/sync-manager/local/33A74752-FC09-48BD-9A5B-0FB9535F3EC7,
NSURL=
  file:///Volumes/Users/sylvain/Library/Group%20Containers/group.strongbox.mac.mcguill/sync-manager/local/33A74752-FC09-48BD-9A5B-0FB9535F3EC7,
NSFileNewItemLocationKey=
  file:///var/folders/mz/3wrdjkw518lb8pqxwrnq2xqc0000gn/T/com.markmcguill.strongbox.mac/_enc_stream/3BAC616C-3F62-400D-BF62-C279A1691C31,
NSUnderlyingError=0x600003d57510 {
  Error Domain=NSPOSIXErrorDomain Code=18 "Cross-device link" UserInfo={
  NSURL=file:///Volumes/Users/sylvain/Library/Group%20Containers/group.strongbox.mac.mcguill/sync-manager/local/33A74752-FC09-48BD-9A5B-0FB9535F3EC7}}}
```

**Comment by strongbox-mark** [comment]
Hi @zaucks - That's very interesting, I haven't come across this issue before. I will add this to the backlog, and try the suggested workaround in your linked article. We can then come back and see if it works for you.

**Comment by strongbox-mark** [comment]
HI @zaucks - Could you see if 1.16.8 fixes this for you? Available on the App Store now.

**Comment by zaucks** [comment]
It does. I've successfully saved and opened again 2 files.
Thanks a lot for the quick update.
