### ISSUE TITLE
Feature request: Paste Screenshot in attachments

### ISSUE THREAD

**Issue by roubles** [strongbox-password-safe/Strongbox#573]
Today, we can only upload files in the attachments pane. The ask here is to be able to paste a screenshot into the attachments directly.

The usecase is that when a site asks a user for 3-4 backup security questions, it is inconvenient to manually type those out in the notes section. It is easier to quickly screenshot them and attach the screenshot. However, in Strongbox today, it is not possible to paste a screenshot, which results in the additional step of first saving the screenshot as a file (insecure) and then attaching the file to the Strongbox entry.

**Comment by strongbox-mark** [comment]
Interesting idea, thanks, we'll add it to the backlog, might be a quick one...

**Comment by strongbox-mark** [comment]
Hi @roubles - This should work for you now in the latest "NextGen UI". You can paste and/or drag drop files on to the Attachments pane in the Edit screen.

**Comment by roubles** [comment]
This. is. awesome. 

I just tested it. It works good.
