### ISSUE TITLE
[FR]: As a User i would like to share/export a single database entry to another device

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#574]
Like discussed on Twitter here : 
https://twitter.com/StrongboxSafe/status/1476876447071485983

I have seen an un used button in the app when I mark one entry :
![image](https://user-images.githubusercontent.com/8161283/147884494-d3ea5908-e5de-4dc5-919a-2cee577c09c8.jpeg)

Goal : 

User can check one/many items -> click export -> iOS share sheet opens -> the entry can be shared e.g. via Airdrop

**Comment by strongbox-mark** [comment]
Thanks Felix, Export only works at the moment to another database.

What format would you expect the export item(s) to be in? Would it be in plain text, like a list of fields? e.g.

Titie: Foo
Username: Bar
Password: xyz

etc? Or CSV, or JSON? What is the target or destination App?

Have you seen other Password Managers offer this functionality? If so could you provide an example of how this would work? Right now, I'm afraid it's a little under specified.

Thanks!

**Comment by F3000** [comment]
Hi Mark , 


i only want to transfer some entry's between two Strongbox installations . 
It's not necessary to export to any other app for me . 

You can take your own file format here 🙏

Thanks Felix

**Comment by strongbox-mark** [comment]
I see, so you want to share an entry from Strongbox on one device to Strongbox on another device?

Could you use a database available to both devices? e.g. on iCloud?

**Comment by strongbox-mark** [comment]
Closing this one out due to under specification, lack of activity.
