### ISSUE TITLE
Truncated labels in details panel

### ISSUE THREAD

**Issue by zaucks** [strongbox-password-safe/Strongbox#576]
Several labels of the details panel are truncated in the French version, like "Nom d'utilisateur" & "Dernière modification"
The layout appears to use fixed sizes.

![image](https://user-images.githubusercontent.com/46299437/147934952-9e9c158d-1e60-4d3e-a90a-f77ac9e353bf.png)

**Comment by strongbox-mark** [comment]
This will be fixed in the upcoming new macOS UI, rolling out in the coming months. Thanks for the report.

**Comment by strongbox-mark** [comment]
The new UI shoudn't suffer from this issue and so we'll close it out as the old UI gets retired... Please upgrade to the NextGen UI as soon as you can.
