### ISSUE TITLE
Freeze on quit because of sync

### ISSUE THREAD

**Issue by sindastra** [strongbox-password-safe/Strongbox#579]
Hi, since recently, when quitting, Strongbox will start a sync and freeze at that (even if no changes were actually made to the DB, at least not manually/that I'm aware of):

<img width="263" alt="Screenshot 2022-01-13 at 22 20 52" src="https://user-images.githubusercontent.com/1236984/149411529-5827986a-baad-4cd5-aa7a-be8460e09e46.png">

<img width="213" alt="image" src="https://user-images.githubusercontent.com/1236984/149411369-a5b02864-5f52-4cff-bcd9-1a1b179be5db.png">

If you then close the window, the tray will be frozen with no way to bring the window back, and you can't force-quit either.

<img width="42" alt="image" src="https://user-images.githubusercontent.com/1236984/149411265-4ae59b14-9ac6-4bfd-b8dd-0129b4ee031b.png">

Debug info:

```
Strongbox 1.16.7 Debug Information at 2022-01-13 22:26:24.202
--------------------
App Version: com.markmcguill.strongbox.mac.pro [1.16.7 (3045)]
--------------------
Device
--------------------
Model: MacBookAir10,1
CPU: ARM64E
System Name: MacOS
System Version: Version 11.6.2 (Build 20G314)
--------------------
Preferences
--------------------
quickRevealWithOptionKey: 1
hideKeyFileNameOnLockScreen: 1
favIconDownloadOptions: {length = 398, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 0000012a }
colorizeUseColorBlindPalette: 0
alwaysShowPassword: 0
doNotRememberKeyFile: 1
trayPasswordGenerationConfig: {length = 651, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000001f5 }
showDatabasesManagerOnEmptyStartup: 0
showDatabasesManagerOnCloseAllWindows: 0
showCustomFieldsOnQuickView: 0
hideDockIconOnAllMinimized: 1
showAttachmentImagePreviewsOnQuickViewPanel: 0
showAttachmentsOnQuickViewPanel: 0
migratedConnections: 1
databases: {length = 4125, bytes = 0x62706c69 73743030 d4000100 02000300 ... 00000000 00000dc5 }
autoSave: 1
showPasswordGenInTray: 0
showPasswordImmediatelyInOutline: 0
makeLocalRollingBackups: 1
fullVersion: 1
autoLaunchSingleDatabase: 1
clipboardHandoff: 1
miniaturizeOnCopy: 0
colorizePasswords: 1
showSystemTrayIcon: 1
hasMigratedToSyncManager: 1
clearClipboardAfterSeconds: 600
markdownNotes: 0
closeManagerOnLaunch: 1
--------------------
Sync
--------------------
============== [database] Failed Sync to [DAV] ===============
Today, 13:30: Begin Sync [Interactive=NO, outstandingUpdate=YES, forcePull=0, provider=DAV, localMod=2022-01-13 02:26:46.376, lastRemoteSyncMod=2022-01-12 23:49:58.000]
Today, 13:30: Got Source DB OK [Mod=2022-01-13 03:02:48.000]
Today, 13:30: Source DB has changed since last sync. Last Sync Source Mod was [2022-01-12 23:49:58.000]
Today, 13:30: Update to Push but Source DB has also changed. Conflict. Auto Merging...
Today, 13:30: Error Domain=com.markmcguill.strongbox. Code=-1 "Cannot merge without Master Credentials." UserInfo={NSLocalizedDescription=Cannot merge without Master Credentials.}
```

Note that it says failed to sync at 13:30, but the time the error occurred is between 22:00 and 22:30, so I'm reporting it after it happened the second time (first time was yesterday). Also, it never asked for a password (referring to the fail in the debug message), the DB was already unlocked. I don't know if this has anything to do with my issue, which happened 9h later...

**Comment by strongbox-mark** [comment]
Hi @sindastra - Thanks for the report. Couple of questions:

1. Do you use a YubiKey with this database?
2. If you perform a change/update (say by adding a dummy folder somewhere) and saving, does that help?
3. If it doesn't, could you try removing and re-adding your database, does that help?

Thanks!

**Comment by sindastra** [comment]
> 1. Do you use a YubiKey with this database?

I don't use a YubiKey with this database, but I have a YubiKey plugged in (for other things).

> 2. If you perform a change/update (say by adding a dummy folder somewhere) and saving, does that help?

Forcing a manual sync did the trick, thanks!

However, I'm not closing this issue just yet because I found a way to partially reproduce this: Try hitting command + S and then command + Q right after, and it will be stuck in an endless sync loop (WebDAV Database BTW). (: 

Note: In my case, it was stuck between Strongbox restarts, but when trying to reproduce, force quit and Strongbox restart solves it, hence "partially reproduce".

**Comment by strongbox-mark** [comment]
Hi there, yes, we see the issue now. It is related to WebDAV. Long story, but during the Quit process the main queue/thread becomes blocked, but the WebDAV scheduler relies on the main thread for completing it's job. 

We have a fix on the way for this, and it will release hopefully this week as 1.16.9. Thanks for all the extra info.

**Comment by strongbox-mark** [comment]
This should be available for you to test on the App Store now. Let us know how it goes.

**Comment by sindastra** [comment]
It's fixed on my end, thanks! (:
