### ISSUE TITLE
4MB Limit on OneDrive Upload

### ISSUE THREAD

**Issue by JanPhill** [strongbox-password-safe/Strongbox#580]
Hi, since recently I am unable to write any updates to a certain database (file size 5.3 MB) stored on oneDrive (Business). Reading updates made on other devices works fine. I think it could somehow be related to file size as writing updates to another smaller database (3.3 MB) stored on the same oneDrive account works also fine.

Below is all the debug information, for security reasons I removed the identifiers.

17:42:05.519 [Fehler] - Error Domain=NSURLErrorDomain Code=-1001 "Zeitüberschreitung bei der Anforderung." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x2814b8270 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalUploadTask <4D12803D-5F0E-440C-BD8C-8EDC91D84BF9>.<28>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalUploadTask <4D12803D-5F0E-440C-BD8C-8EDC91D84BF9>.<28>"
), NSLocalizedDescription=Zeitüberschreitung bei der Anforderung., NSErrorFailingURLStringKey=https://graph.microsoft.com/v1.0/me/drives/[removed], NSErrorFailingURLKey=https://graph.microsoft.com/v1.0/me/drives/[removed]/content, _kCFStreamErrorDomainKey=4

Strongbox 1.54.6 Debug Information at 2022-01-16 16:27:53.934

App Version: com.markmcguill.strongbox [1.54.6 (3156)@2ac0c71]

Device

Model: iPhone
CPU: ARM64E
System Name: iOS
System Version: 14.8

Preferences

lastAskToEnableAutoFill: 2022-01-15 16:03:01 +0000
coalesceAppLockAndQuickLaunchBiometrics: 1
addOtpAuthUrl: 0
markdownNotes: 0
clipboardHandoff: 0
installDate: 2020-09-24 17:00:14 +0000
hideKeyFileOnUnlock: 0
iCloudPrompted: 1
lastEntitlementCheckAttempt: 2022-01-13 10:39:15 +0000
0D323BB1-0ACF-4162-A510-97598EF93D16-pw-has-expired: 0
hideTips: 1
pinYinSearchEnabled: 0
migratedQuickLaunchToAutoFill: 1
useIsolatedDropbox: 0
hideExportFromDatabaseContextMenu: 0
databasesAreAlwaysReadOnly: 0
instantPinUnlocking: 1
backupIncludeImportedKeyFiles: 0
mainAppDidChangeDatabases: 1
lastKnownGoodDatabaseState: {length = 32, bytes = 0xd18ad1cb ca27a026 0e318ef9 0dc1b95b ... e9463bdc 65e64326 }
migratedConnections: 1
allowThirdPartyKeyboards: 1
syncForcePushDoNotCheckForConflicts: 0
disableThirdPartyStorageOptions: 0
colorizeUseColorBlindPalette: 0
disableFavIconFeature: 0
legacyShowMetadataOnDetailsScreen: 1
scheduledTipsCheckDone: 1
favIconDownloadOptions: {length = 398, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 0000012a }
disableReadOnlyToggles: 0
iCloudWasOn: 0
haveAttemptedMigrationToFullFileProtection: 1
keePassEmailField: 0
suppressAppBackgroundTriggers: 0
haveAskedAboutBackupSettings: 1
migratedDatabasesToNewStore: 1
endFreeTrialDate: 2022-03-04 12:39:00 +0000
syncPullEvenIfModifiedDateSame: 0
userHasOptedInToThirdPartyStorageLibraries: 1
hasShownFirstRunWelcome: 1
backupFiles: 1
fullFileProtection: 1
hasMigratedDatabaseSubtitlesAug2020: 1
showAllFilesInLocalKeyFiles: 0
appLockMode2.0: 2
monitorInternetConnectivity: 1
disableNativeNetworkStorageOptions: 0
0D323BB1-0ACF-4162-A510-97598EF93D16-pw-expires-at: 2022-01-22 16:25:24 +0000
clearClipboardEnabled: 0
failedUnlockAttempts: 0
numberOfEntitlementCheckFails: 0
addLegacySupplementaryTotpCustomFields: 0
launchCount: 45
freeTrialNudgeCount: 1
lastFreeTrialNudge: 2021-12-04 12:38:25 +0000
migratedOfflineDetectedBehaviour: 1
Ep: 1600966814
Flags: F[1[47]101[45]0011]

Last Crash

Sync

Business (OneDrive Sync) => 2021-12-09 15:26:47.000 (3,3 MB)
Privat (OneDrive Sync) => 2022-01-15 17:41:02.637 (5,3 MB)

[preferences/databases.json] 8 KB - Heute, 16:27:23
[.com.apple.mobile_container_manager.metadata.plist] 381 Byte - 24.09.20, 18:59:15
[Library/Preferences/group.strongbox.mcguill.plist] 2 KB - Heute, 16:27:39

[Business] on [OneDrive] Config
{
    argon2MemReductionDontAskAgain = 0;
    auditConfig =     {
        auditInBackground = 1;
        caseInsensitiveMatchForDuplicates = 1;
        checkForCommonPasswords = 1;
        checkForDuplicatedPasswords = 1;
        checkForLowEntropy = 1;
        checkForMinimumLength = 0;
        checkForNoPasswords = 0;
        checkForSimilarPasswords = 0;
        checkHibp = 0;
        hibpCaveatAccepted = 0;
        hibpCheckForNewBreachesIntervalSeconds = 86400;
        lastKnownAuditIssueCount = 83;
        levenshteinSimilarityThreshold = "0.75";
        lowEntropyThreshold = 36;
        minimumLength = 12;
        showAuditPopupNotifications = 1;
        showCachedHibpHits = 1;
    };
    autoFillConcealedFieldsAsCreds = 0;
    autoFillConvenienceAutoUnlockTimeout = "-1";
    autoFillCopyTotp = 1;
    autoFillEnabled = 0;
    autoFillOnboardingDone = 0;
    autoFillScanAltUrls = 1;
    autoFillScanCustomFields = 0;
    autoFillScanNotes = 0;
    autoFillUnConcealedFieldsAsCreds = 0;
    autoLockOnDeviceLock = 1;
    autoLockTimeoutSeconds = 60;
    browseItemSubtitleField = 1;
    browseSortField = 1;
    browseSortFoldersSeparately = 1;
    browseSortOrderDescending = 0;
    browseViewType = 0;
    colorizePasswords = 1;
    colorizeProtectedCustomFields = 0;
    conflictResolutionStrategy = 0;
    convenienceExpiryOnboardingDone = 1;
    convenienceExpiryPeriod = "-1";
    couldNotConnectBehaviour = 0;
    databaseCreated = "660319852.833874";
    detailsViewCollapsedSections =     (
        0,
        0,
        0,
        0,
        1,
        1
    );
    doNotShowRecycleBinInBrowse = 0;
    doubleTapAction = 4;
    duressAction = 0;
    easyReadFontForAll = 0;
    emptyOrNilPwPreferNilCheckFirst = 0;
    failedPinAttempts = 0;
    fileIdentifier = "{\"driveId\":\"[removed]\",\"parentFolderId\":\"[removed]"}";
    fileName = "business.kdbx";
    forceOpenOffline = 0;
    hasAcknowledgedAppLockBiometricQuickLaunchCoalesceIssue = 0;
    hasBeenPromptedForConvenience = 1;
    hasBeenPromptedForQuickLaunch = 1;
    hasShownInitialOnboardingScreen = 1;
    hasUnresolvedConflicts = 0;
    hideIconInBrowse = 0;
    hideTotp = 0;
    hideTotpCustomFieldsInViewMode = 1;
    hideTotpInBrowse = 0;
    immediateSearchOnBrowse = 0;
    isAutoFillMemOnlyConveniencePasswordHasBeenStored = 0;
    isEnrolledForConvenience = 1;
    isTouchIdEnabled = 1;
    kdbx4UpgradeDontAskAgain = 0;
    keePassIconSet = 1;
    keyFileBookmark = "<Not Set>";
    lastSyncAttempt = "664039641.557766";
    lastSyncRemoteModDate = 660752807;
    likelyFormat = 1;
    lockEvenIfEditing = 0;
    longPressTapAction = 3;
    makeBackups = 1;
    maxBackupKeepCount = 10;
    nickName = Business;
    offlineDetectedBehaviour = 0;
    onboardingDoneHasBeenShown = 1;
    promptedForAutoFetchFavIcon = 0;
    quickTypeDisplayFormat = 0;
    quickTypeEnabled = 1;
    readOnly = 0;
    scheduleExportIntervalDays = 28;
    scheduledExport = 0;
    scheduledExportOnboardingDone = 0;
    showChildCountOnFolderInBrowse = 1;
    showConvenienceExpiryMessage = 1;
    showEmptyFieldsInDetailsView = 0;
    showExpiredInBrowse = 1;
    showExpiredInSearch = 1;
    showFlagsInBrowse = 1;
    showKeePass1BackupGroup = 0;
    showPasswordByDefaultOnEditScreen = 0;
    showQuickViewExpired = 0;
    showQuickViewFavourites = 1;
    showQuickViewNearlyExpired = 1;
    showRecycleBinInSearchResults = 0;
    storageProvider = 4;
    tapAction = 1;
    tripleTapAction = 8;
    tryDownloadFavIconForNewRecord = 1;
    unlockCount = 3;
    uuid = "[removed]";
}
[Privat] on [OneDrive] Config
{
    argon2MemReductionDontAskAgain = 0;
    auditConfig =     {
        auditInBackground = 1;
        caseInsensitiveMatchForDuplicates = 1;
        checkForCommonPasswords = 1;
        checkForDuplicatedPasswords = 1;
        checkForLowEntropy = 1;
        checkForMinimumLength = 0;
        checkForNoPasswords = 0;
        checkForSimilarPasswords = 0;
        checkHibp = 0;
        hibpCaveatAccepted = 0;
        hibpCheckForNewBreachesIntervalSeconds = 86400;
        lastKnownAuditIssueCount = 33;
        levenshteinSimilarityThreshold = "0.75";
        lowEntropyThreshold = 36;
        minimumLength = 12;
        showAuditPopupNotifications = 1;
        showCachedHibpHits = 1;
    };
    autoFillConcealedFieldsAsCreds = 0;
    autoFillConvenienceAutoUnlockTimeout = "-1";
    autoFillCopyTotp = 1;
    autoFillEnabled = 0;
    autoFillOnboardingDone = 0;
    autoFillScanAltUrls = 1;
    autoFillScanCustomFields = 0;
    autoFillScanNotes = 0;
    autoFillUnConcealedFieldsAsCreds = 0;
    autoLockOnDeviceLock = 1;
    autoLockTimeoutSeconds = 60;
    browseItemSubtitleField = 1;
    browseSortField = 1;
    browseSortFoldersSeparately = 1;
    browseSortOrderDescending = 0;
    browseViewType = 0;
    colorizePasswords = 1;
    colorizeProtectedCustomFields = 0;
    conflictResolutionStrategy = 0;
    convenienceExpiryOnboardingDone = 0;
    convenienceExpiryPeriod = "-1";
    couldNotConnectBehaviour = 0;
    databaseCreated = "663957620.486279";
    detailsViewCollapsedSections =     (
        0,
        0,
        0,
        0,
        1,
        1
    );
    doNotShowRecycleBinInBrowse = 0;
    doubleTapAction = 4;
    duressAction = 0;
    easyReadFontForAll = 0;
    emptyOrNilPwPreferNilCheckFirst = 0;
    failedPinAttempts = 0;
    fileIdentifier = "{\"driveId\":\"[removed]",\"parentFolderId\":\"[removed]\"}";
    fileName = "privat.kdbx";
    forceOpenOffline = 0;
    hasAcknowledgedAppLockBiometricQuickLaunchCoalesceIssue = 0;
    hasBeenPromptedForConvenience = 0;
    hasBeenPromptedForQuickLaunch = 0;
    hasShownInitialOnboardingScreen = 1;
    hasUnresolvedConflicts = 0;
    hideIconInBrowse = 0;
    hideTotp = 0;
    hideTotpCustomFieldsInViewMode = 1;
    hideTotpInBrowse = 0;
    immediateSearchOnBrowse = 0;
    isAutoFillMemOnlyConveniencePasswordHasBeenStored = 0;
    isEnrolledForConvenience = 0;
    isTouchIdEnabled = 0;
    kdbx4UpgradeDontAskAgain = 0;
    keePassIconSet = 1;
    keyFileBookmark = "<Not Set>";
    lastSyncAttempt = "664039643.395206";
    lastSyncRemoteModDate = 663704289;
    likelyFormat = 1;
    lockEvenIfEditing = 0;
    longPressTapAction = 3;
    makeBackups = 1;
    maxBackupKeepCount = 10;
    nickName = Privat;
    offlineDetectedBehaviour = 0;
    onboardingDoneHasBeenShown = 0;
    outstandingUpdateId = "CD4B896D-3E8F-4C12-8411-8C9D8FED5407";
    promptedForAutoFetchFavIcon = 0;
    quickTypeDisplayFormat = 0;
    quickTypeEnabled = 1;
    readOnly = 0;
    scheduleExportIntervalDays = 28;
    scheduledExport = 0;
    scheduledExportOnboardingDone = 0;
    showChildCountOnFolderInBrowse = 1;
    showConvenienceExpiryMessage = 1;
    showEmptyFieldsInDetailsView = 0;
    showExpiredInBrowse = 1;
    showExpiredInSearch = 1;
    showFlagsInBrowse = 1;
    showKeePass1BackupGroup = 0;
    showPasswordByDefaultOnEditScreen = 0;
    showQuickViewExpired = 0;
    showQuickViewFavourites = 1;
    showQuickViewNearlyExpired = 1;
    showRecycleBinInSearchResults = 0;
    storageProvider = 4;
    tapAction = 1;
    tripleTapAction = 8;
    tryDownloadFavIconForNewRecord = 1;
    unlockCount = 2;
    uuid = "[removed]";
}

**Comment by strongbox-mark** [comment]
Hi there, yes it looks like there is a limit of 4MB on the current API we are using. There is some development work that could be done to workaround this limit, but in the meantime, you could use the "Files" method for this larger database.

To do this you need the OneDrive app installed. Then you can add a database via + > Add Existing > Files > Browse to OneDrive.

Would that work for you?
