### ISSUE TITLE
Bug: Scrolling on preferences can activate toggles, iOS

### ISSUE THREAD

**Issue by sam-masaki** [strongbox-password-safe/Strongbox#581]
Starting a scroll gesture on a toggle can flip it on/off while still scrolling. Could go unnoticed if the user has haptics turned off. It doesn't seem to happen with any other controls in the preferences pages

**Comment by strongbox-mark** [comment]
Hi @sam-masaki - Could you be more specific, which toggle, screenshots or videos would be helpful. Thanks!

**Comment by sam-masaki** [comment]
This happens with every toggle in preferences. If I touch down with my finger on a toggle and swipe up or down, it flips the toggle and sometimes also scrolls. Demo in the video below. It doesn't happen every time in the video because I'm reaching around my laptop and holding my phone at an odd angle. In case it matters this is on an iPhone 11 with app version 1.54.7 and the latest iOS 15.2.1

https://youtu.be/OThZzSmPqRQ

**Comment by strongbox-mark** [comment]
Thanks @sam-masaki - Is this behaviour different than any other scrollable Preferences screen on iOS, e.g. doesn't this also happen with say the built in iOS preferences? This might just be standard behaviour (not say it's ideal).

**Comment by sam-masaki** [comment]
I wondered that as well and I confirmed that the Settings app doesn't do this (Sounds & Haptics page for example) before submitting the issue, but just yesterday I happened to find a similar problem in the default Shortcuts app. There, if you make a new shortcut, then press the settings in the upper right, you get a scrollable list of toggles contained in a sheet that can be dismissed with a swipe down which exhibits this same problem. Looks like it's standard

**Comment by strongbox-mark** [comment]
OK, @sam-masaki - I was sort of thinking that. We'll close this one out for now, thanks for the report.
