### ISSUE TITLE
Enhancement: Sort items by last modified

### ISSUE THREAD

**Issue by tjuerges** [strongbox-password-safe/Strongbox#582]
I honestly do not know how I came to like the sorting by last modified. But what I do know is that I especially like this sorting feature in KeepassXC. And I would really love to have it in Strongbox (Mac & IOS).

**Comment by tjuerges** [comment]
I just realised that the IOS version already supports sorting by modification date. Thanks!

Apparently it pays off if one checks from time to time what has changed in the preferences and DB settings. 😁

**Comment by strongbox-mark** [comment]
Yes, sorry meant to reply. The new macOS UI will have Last Modified as a sortable column too, so this is coming (very) soon...

**Comment by strongbox-mark** [comment]
Hi @tjuerges - just to let you know, you can now try this with 1.16.11 on the App Store now. Opt in to the new UI (Settings > Advanced > Use NextGenUI (BETA)) to see it :)

**Comment by tjuerges** [comment]
Hi Mark.

The update came in yesterday, I got curious and enabled the Beta GUI, found the Modified column and have been very happy ever since. 🕺🏻 🥳 

This was indeed quick. Thank you very much!
