### ISSUE TITLE
Unified or Multi-Database Search / Add

### ISSUE THREAD

**Issue by georgesnow** [strongbox-password-safe/Strongbox#583]
I saw the comments about keeshare. But I was thinking prior to that. Is global unlock and search for mobile and Mac. 

So optionally you could say unlock both these databases and search both and unified result. Then if you go to add a credential entry it just prompt which one do you want to add to?

**Comment by georgesnow** [comment]
Yeah option one probably would work best. Opt in. Touch ID unlocks x databases and search is across those unlocked databases that participate.

It was an idea around how to deal with multiple databases. I have 3, personal, shared family, and work. Kee share and merging isn’t an option. But access to all 3 is required regularly.

**Comment by strongbox-mark** [comment]
Similar to the other issues I've just closed @georgesnow - you can use the "Quick Search" feature (in 1.60.9) now. You can launch it from the tray icon with a click or use the hot key. Closing out this one.
