### ISSUE TITLE
Enhancement: Change Pane Layout (macOS version)

### ISSUE THREAD

**Issue by DrBrynzo** [strongbox-password-safe/Strongbox#585]
Strongbox won me over on iPhone and iPad in the last few months, amazing improvements from when I first tried it ages ago. Good stuff. I'm struggling with it a bit on Mac though.

Long time PWSafe -> KeePass -> KeePassX -> KeePassXC user. Having at least tried every alternative and even different formats like BitWarden, LastPass, 1Password, and even the pass CLI, I've found that the most useful, utilitarian GUI layout I've personally found is KeePassXC. I love being able to have the group list in one pane on the left for quick navigation, the list of items in that group in another pane on the top right, and the item details in a third pane on the bottom right. 

I don't like collapsing and expanding groups (or "tree view"). The real deal-breaker to me though is opening yet another window to edit an entry. This just annoys me to no end, to have to go chase it down somewhere on my desktop with multiple terminal windows and browser sessions. When building a tiled or otherwise organized workspace it's much more ideal if everything has its space and doesn't jump out and usurp screen real estate.

Can we get an option to change the pane layout and disable opening new windows to perform operations? Maybe asking to "make it just like KeePassXC" is too much but I would love the option to at least have some alternate layouts, especially some that stick to their own screen space.

Thank you for your consideration.

**Comment by strongbox-mark** [comment]
Hi @DrBrynzo - You're in luck, we've been working on a new macOS UI for the last couple of months and we're about to release it for Beta test, probably in the next couple of days. 

It hits both of your requests, we think it's probably the best way to do the interface. Will be interested to receive your feedback. 

Keep an eye out for the new update, there'll be a switch in Advanced settings to opt in to the new UI...

**Comment by georgesnow** [comment]
Super! That’s exciting

**Comment by strongbox-mark** [comment]
This is now available to test. To try it:

1. Update to 1.16.10 on the App Store (You might need to search Strongbox and click in to see the Update button)
2. Preferences > Advanced > Use NextGen UI (BETA)

Note: It's only available on Big Sur+ at the moment. We'd love any feedback you might have (support@strongboxsafe.com).

**Comment by georgesnow** [comment]
New Ui is definitely on good track. And liking. Maybe throw a tip jar in on macOS version when it rolls out 😉

**Comment by dan-el** [comment]
I love the new UI!
About that tip jar @georgesnow - I think that would be Mark's Patreon account: [https://www.patreon.com/strongboxpasswordsafe](https://www.patreon.com/strongboxpasswordsafe)

**Comment by andreasschmitz** [comment]
Thank you so much, the new GUI is looking amazing. 

I am a long time 1Password user and looking for alternatives, because of the changes 1Password 8 will bring. I was really struggling with the (old?) UI, even after testing it for a couple of weeks. The new one is a massive improvement and the last thing pushing me over to Strongbox Pro. Thanks a lot!

**Comment by DrBrynzo** [comment]
It's definitely an improvement. I would still like to see a horizontal split option for the entry (middle) and details panels.
The "edit" function still opening a new window was a little disappointing too. I can still make the KeePassXC window use much less screen real estate than the new UI and effectively display more information.

That being said, even though I don't like the separate editing window I do appreciate the layout of it. It's a nice clean display of the entry information. I just wish it stayed in the confines of the main window.

I think you're headed in the right direction.

**Comment by strongbox-mark** [comment]
Thanks @DrBrynzo - I think I'd like to close this one out now. We're pretty close. 

I don't think a horizontal split for list/details panels is on the cards any time soon to be honest. Appreciate your feedback.
