### ISSUE TITLE
Dock Icon doesn't do anything on click // Hide Dock Icon when all Miniaturized or Closed

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#586]
In Reference to #584 

**Steps to reproduce:**
1. Ensure the following Strongbox options are set:
-> Advanced -> Show Databases Manager When All Windows are Closed - UNCHECKED
-> Advanced -> Hide Databases Manager after Launching Database - CHECKED
**_-> General -> Hide Dock Icon when all Miniaturized or Closed_** - CHECKED
(Also requires -> General -> Show in System Menu Bar - CHECKED)
2. Open Strongbox and launch a database (regular Strongbox usage)
3. Close Strongbox using the red X in the top left corner.
-> Now we closed the last active app window. No database is launched, no databases manager window is open.
4. The little dot in the Dock next to the Strongbox **_is gone, making it appear as if Strongbox was not running at all._**
5. Click on the Strongbox icon in the Dock >> Nothing happens. That is the problem.

This one is even more confusing than #584 because the little dot next to the Dock icon is gone and Strongbox can only be opened by interacting with the System Menu Bar Icon and not at all via the Dock.

EDIT: I have Strongbox pinned to the Dock.

**Comment by strongbox-mark** [comment]
Hi @dan-el - This seems to me to be "By Design" - This is how I would expect Strongbox to function in this scenario/setup/configuration. 

Basically if you have chosen "Hide Dock Icon when all..." then you should not have Strongbox pinned to the Dock. There's no way for Strongbox to work around the Dock pinned setting.

**Comment by dan-el** [comment]
Hi @strongbox-mark - Even if this is by design I still think the app should work with or without the icon pinned to the Dock. There should not be a way for users to configure the app into a state that is problematic just by doing a very common thing like pinning the icon to the Dock. As mentioned in #584 maybe the menubar icon can be moved to a separate process?

Maybe #584 will resolve this issue as well. If not I'd love to see this one being reopened tbh.

If that's not an option I'll have to disable the menu bar option and go with "Quit Strongbox when all closed" since I expect the App to launch when I click the Dock icon no matter what.

**Comment by strongbox-mark** [comment]
The app should definitely launch when you click the dock icon, and I believe it does, unless there's a very strange configuration of attempting to hide and pin the dock icon simultaneously.

Ultimately, I suppose the question I have is why would anyone choose both "Hide Dock Icon" and also "Pin Dock Icon"?

**Comment by dan-el** [comment]
I think this will all be resolved as part of #584 :D
