### ISSUE TITLE
Bug: Strongbox crashes in icon selection screen (macOS)

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#587]
**Steps to reproduce:**
1. Right-click on an item (old and new UI) and select "Set Icon"
2. Start scrolling in the list of icons -> Strongbox crashes.

Editing an entry's icon by double-clicking the entry first, and then clicking on the icon does not lead to a crash in the old UI.
Doing the same in the new UI does lead to a crash.

Crash report: [https://gist.github.com/dan-el/53128f6d16926ef2a5b08df05d109e72](https://gist.github.com/dan-el/53128f6d16926ef2a5b08df05d109e72)

**Comment by strongbox-mark** [comment]
Cheers @dan-el - Fix on the way, only affects ARM architectures, super weird one...

**Comment by owenfiscus** [comment]
Hey @strongbox-mark this same issue is crashing the new UI for me on my Intel Mac as well (16" 2019 i9). I've attached a recording.

https://user-images.githubusercontent.com/8652398/152462690-8fdaa1b0-373a-41ac-91d0-632ede3d970a.mp4

.

**Comment by strongbox-mark** [comment]
Thanks @owenfiscus, didn't expect that. Could you try 1.16.11 on the App Store now, we're hoping this will fix the issue. @dan-el Should fix it on ARM too. Please let me know. 

NB: You might need to search for Strongbox in the App Store and click in to see the Update button.

**Comment by owenfiscus** [comment]
@strongbox-mark This issue seems to be resolved in my brief testing this morning. Thanks!

**Comment by strongbox-mark** [comment]
Awesome, thanks @owenfiscus

**Comment by dan-el** [comment]
Working for me as well. Thanks!
