### ISSUE TITLE
New UI: Add classic KeePass icons

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#588]
Can we have the classic stock KeePass icons in the new UI?
They are present in the old UI and I really prefer them over the modern "line style" icons.
Thanks!

**Comment by strongbox-mark** [comment]
Should be there for you, Database Preferences > Icon Set

**Comment by dan-el** [comment]
I fell for the same thing which confused me over and over again, which is that I can't remember which settings are "app settings" and which ones are "database settings".

In the old UI there were only the classic icons, right? Maybe I was confused because of that. Can the default state of the old UI (classic icons) also be the default state in the new UI?

I am also not sure why anyone would want different icon sets per database and think this would make more sense as an "app setting" instead of a "database setting" but I understand this is highly subjective.

So unless you think it makes sense to move this setting to an app wide setting I think the issue can be closed.
