### ISSUE TITLE
New UI: Search bar overflowing into neighbouring column

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#589]
In some cases it is possible to make the search bar overflow into the neighbouring column. This happens when the Strongbox app window is very small. See attached screenshots.

Dragged the app window smaller while the search bar was "active":
<img width="571" alt="Screenshot 2022-02-05 at 08 35 41" src="https://user-images.githubusercontent.com/19776691/152633302-3877d032-c660-4147-ad58-b89ad024b2e0.png">

"Activated" the search bar while the app window was small - more overflow:
<img width="569" alt="Screenshot 2022-02-05 at 08 37 18" src="https://user-images.githubusercontent.com/19776691/152633306-e34ca4bb-f755-443c-9694-c0faca9c0e53.png">

Overflow from the right column to the center column:
<img width="452" alt="Screenshot 2022-02-05 at 08 38 04" src="https://user-images.githubusercontent.com/19776691/152633310-82a23d75-9d64-4671-b84d-fd2624c62b78.png">

**Comment by strongbox-mark** [comment]
Hi @dan-el - Yes, seeing the same thing, apparently default behaviour for a transparent title bar, but we'll change it to an Opaque bar on the next release, it looks much better...

**Comment by strongbox-mark** [comment]
Yes, strange one, I believe it's an Apple bug, but switch from transparent to opaque fixes this.
