### ISSUE TITLE
New UI: "Customize Toolbar" Bug?

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#593]
I have not yet been able to consistently reproduce the below described behaviour but it has happened twice so far:

Sometimes when I right-click the toolbar in the new UI and select "Customize Toolbar..." the window with the available toolbar icons does not open and instead the icons on the toolbar just start shaking. I can perfectly drag them around and such, but I am not able to exit the "customize toolbar"-mode since the window with the "Done" button is not visible.
The only way to exit the App is to kill it since the "X" icon won't allow me to close Strongbox in that state.
After killing and re-launching the app the "missing window" usually appears just fine when trying to edit the toolbar.

I'll keep an eye on it and report any findings.

**Comment by dan-el** [comment]
So far it has not happened again. I'll try a bit more and close the issue if it can't be reproduced.

**Comment by strongbox-mark** [comment]
Any update on this one @dan-el ?

**Comment by dan-el** [comment]
I have not been able to reproduce the issue. If there really was an issue it appears to be resolved now :-)
