### ISSUE TITLE
New Ui: username and password column copy broken

### ISSUE THREAD

**Issue by georgesnow** [strongbox-password-safe/Strongbox#594]
Noticed a regression With the new Ui the double click of username or password opens the edit item sheet. It no longer copies username or password respectively

**Comment by strongbox-mark** [comment]
Interesting, I had never used that feature myself. I think we can try to bring this back, perhaps as a preference and I know some like the double click to edit...

**Comment by georgesnow** [comment]
Understood 🙁
I am cool if it’s a preference! It’s one those features I use regularly. particularly, from moving between keepass ports

**Comment by strongbox-mark** [comment]
This should be fixed for you now in 1.16.13 on the App Store. Please feel free to reopen if it's not as you expect. :)

**Comment by georgesnow** [comment]
@strongbox-mark it works! 👍thanks
