### ISSUE TITLE
Old email still visible in quick view panel after an edit

### ISSUE THREAD

**Issue by thepaulcooper** [strongbox-password-safe/Strongbox#595]
The steps to reproduce this are:

1) Select Search In - Username
2) Enter an email to be changed
3) Select one of the items from the list and hit Edit
4) Update the Username field and close the edit window.
5) The entry disappears from the list in the left-hand panel (because the email changed) but the old email remains in the quick view panel on the right.

I'm not sure what should be displayed but leaving the old entry visible in the quick view panel is confusing as one's initial thought is that the edit didn't work.  The same probably applies with searches and edits in other fields.

Strongbox Pro 1.16.12

**Comment by strongbox-mark** [comment]
Thanks for the report @thepaulcooper - We still have a bit of work to do no the email integration in the Beta, which will fix this.

**Comment by strongbox-mark** [comment]
Hi @thepaulcooper - this should be fixed for you with 1.16.13. Please feel free to re-open if this isn't fixed.
