### ISSUE TITLE
Ability to delete and/or trim unused Custom Icons

### ISSUE THREAD

**Issue by owenfiscus** [strongbox-password-safe/Strongbox#596]
I prefer the clean look. It would also be nice to set an icon for all the items in a folder.

Thanks!

**Comment by strongbox-mark** [comment]
Hi @owenfiscus - you can disable this for sure:

**iOS**
Database Settings > Customize View > Auto Fetch FavIcon

**macOS**
Database Settings > Automatically Download FavIcon...

Is that what you were looking for? 

Also, you can "batch set" all icons in our new macOS UI (NextGen UI). Simply select the items > Set Icon and choose your icon.

We also have an item on our backlog, to make new items copy the icon of their containing folder when created. Is that what you wanted?

**Comment by owenfiscus** [comment]
@strongbox-mark That's exactly what I'm looking for and the backlog item sounds like a great enhancement. Thanks for the quick reply!

**Comment by owenfiscus** [comment]
Hey @strongbox-mark sorry to bother again but its there a way to delete favicons that have already been downloaded from the selection window? Thanks!

<img width="786" alt="Screen_02 23 2022_10 18 38_AM" src="https://user-images.githubusercontent.com/8652398/155382321-c9154c91-12a2-4505-adf0-a0337461efad.png">

**Comment by strongbox-mark** [comment]
Hi @owenfiscus - there's no way to do this at present in Strongbox I'm afraid. We can alter the title of this bug/issue to make it a request for the ability to delete custom icons.

**Comment by strongbox-mark** [comment]
Hi @owenfiscus - This is possible now in both iOS/macOS. Look under Advanced Preferences > Strip Unused Icons on Save
