### ISSUE TITLE
How to use Markdown, not rendered

### ISSUE THREAD

**Issue by MichiFr** [strongbox-password-safe/Strongbox#598]
Hi!

Using the latest version on iPadOS 15.3.1, I've entered some Markdown texts in my database, but those lines are not rendered as expected. The appropriate option in preferences is enabled.

So, did I miss the obvious, is this a possible bug? Where or when  are those lines are showing up properly?
Btw, I guess Keepass Windows won't show those lines formatted correctly as Markdown, right?

Thanks,
Michael

**Comment by strongbox-mark** [comment]
Hi Michael, Any details, screenshots, recordings, sample markdown, examples would be v helpful, hard to say what you're seeing here, but it should work for you (in the notes field).

I'm afraid that's right, I don't believe KeePass on Windows supports Markdown.

**Comment by MichiFr** [comment]
Here you go. I expected the text below to be rendered in italic or in bold letters...

![BB8FFECF-D4C6-46A8-9085-C2162190158A](https://user-images.githubusercontent.com/28045390/155594970-39ad6dc5-ccce-4e19-8426-dcb53a9e9b3b.jpeg)

**Comment by strongbox-mark** [comment]
Hi @MichiFr - Could you check you've got Markdown Notes enabled under Preferences > Advanced > Miscellaneous > Markdown Notes?

It is Off by default, we did this for a soft release, but we've now updated the default to ON for new users (well the next release will).

**Comment by MichiFr** [comment]
Sure, I can confirm it's switched on. Sorry for this shot in German language, but I guess you get the meaning of the appropriate option, right?

![7361A5E7-0B6E-4DE3-9C6A-783C4367F397](https://user-images.githubusercontent.com/28045390/155766159-9c689efe-fce2-44b2-a98f-e5bfae101f33.jpeg)

**Comment by MichiFr** [comment]
Different story or possible cause: is this a pro feature?

**Comment by strongbox-mark** [comment]
Hi @MichiFr - It's a free feature so won't be that. 

Another thing it could be, do you have "Easy Read Font on All Fields" enabled? You can find it here:

Unlock Database > More button > Customize View > Details View > Easy Read Font on All Fields

It looks like you're using the Easy Read font in that screen shot? Can you toggle that off and see if it works for you?

**Comment by MichiFr** [comment]
You are genius! YES! That's it!

Thanks for this tip and solution! Never thought this has any influence on Markdown rendering. 
Perhaps worth a small hint on botb options?

**Comment by strongbox-mark** [comment]
Haha, sweet, glad you got it sorted. Yes, small hint somewhere for this is a good idea, will add to our backlog.
