### ISSUE TITLE
iOS: Autofill menu should not automatically choose entry

### ISSUE THREAD

**Issue by danielfomin96** [strongbox-password-safe/Strongbox#602]
Hello,
When I open the autofill menu in iOS Safari and the entry already exists for the website, the entry is automatically chosen and copied to the password field.
I find this to be possibly a bug because when opening the autofill menu it is often times the intention to be able to manually choose an entry and not automatically let it be chosen for you. This also interferes with the workflow of creating additional password entries for a website that already exists in the database.
I find that it would be great just having the possibility to see a good match to easily choose it manually instead of the menu choosing for me.
Would it be possible to remove the automatic usage of an entry when opening the autofill menu?

To illustrate my problem, here is an example case, where I do nothing in the menu itself but the entry is chosen and copied automatically:

https://user-images.githubusercontent.com/70371217/156624483-7f8528b9-fd04-4b70-940f-4c06709e379d.mp4

**Comment by milesmcclane** [comment]
I also find this rather annoying, as sometimes I have a secondary password for the same site which I cannot get to via autofill due to this. However, I have bought something similar up before and as I understand it’s a limitation with iOS?

**Comment by milesmcclane** [comment]
I also find this rather annoying, as sometimes I have a secondary password for the same site which I cannot get to via autofill due to this. However, I have bought something similar up before and as I understand it’s a limitation with iOS?

**Comment by strongbox-mark** [comment]
Hi, have you tried:

Database Preferences > AutoFill Preferences > General > Auto Select Single Match > Switch OFF

**Comment by danielfomin96** [comment]
Thank you very much!!! 
I did not know there was a autofill menu setting.
