### ISSUE TITLE
Allow saving new login credentials in Strongbox instead of Keychain

### ISSUE THREAD

**Issue by steebchen** [strongbox-password-safe/Strongbox#607]
Strongbox works fine when auto-filling credentials, but when adding new login details in Safari it seems it's only possible to save these in keychain. Is this not possible or is it just not built yet?

**Comment by strongbox-mark** [comment]
Hi @steebchen - It's just not built yet, but it's on the list!

**Comment by voltaireodactyl** [comment]
+1 for this -- I've got everything mostly working right now by using Strongbox on iOS + KeepassXC on Mac, but I still have no way to grab new logins from Safari. Would love to have Strongbox include this feature!

**Comment by ckranzinger** [comment]
Another vote for this feature!

**Comment by osopolar** [comment]
Is this working now? At least for Firefox and Chrome? Last time I tested it, it didn't … or I haven't seen it.

**Comment by strongbox-mark** [comment]
Hi @osopolar - The browser extension for Chrome/Firefox supports creating a new entry. You will see this option on the inline menu... Screenshot below:

<img width="391" alt="image" src="https://github.com/strongbox-password-safe/Strongbox/assets/64356496/34a8d6c4-8be4-4faa-9065-e64bf301f307">

**Comment by pictosun** [comment]
Any update on Safari for macOS supporting this feature? Mainly using Safari. With iOS it is working - but not with macOS.

**Comment by strongbox-mark** [comment]
Will hopefully get to this in the next release, eta about a month, but might happen sooner.

**Comment by strongbox-mark** [comment]
Hi all, this is now available with 1.58.27, you need to choose "Strongbox" from the AutoFill dropdown, then unlock your database > Create New button. Feel free to raise any new issues you come across. Going to close this one out.

**Comment by pictosun** [comment]
Hi. When trying to create a new entry it simply is not possible?! If I go to a website without any new entry I can see the macOS system lock symbol close to the field, but when clicking nothing happens. I cannot choose something. Strongbox only works, when I made some entry for a website. But creating new entries is not working.

Any error at my side?

**Comment by strongbox-mark** [comment]
Hi @pictosun - Hard to tell what you're seeing, could you send a screen recording and debug info to support@strongboxsafe.com and we'll get you fixed up.

**Comment by pictosun** [comment]
Any update concerning this bug? It still does not work? What about Sequoia - does it work over there?
