### ISSUE TITLE
Suggest favourites first

### ISSUE THREAD

**Issue by steebchen** [strongbox-password-safe/Strongbox#608]
When using the Strongbox autofill, all items are in some order, but I want my favourites to show first.

1PW does this quite well:

![image](https://user-images.githubusercontent.com/5013932/160790695-57d20b11-1090-4453-a529-eb09bb09b7a6.png)

It would be great if Strongbox could show the favourite items first.

**Comment by strongbox-mark** [comment]
I suppose the question is, do you want this Favourite login to appear everywhere on every username/password field for every site, or do you want it to just appear at the top of the suggestions for github.com?

**Comment by steebchen** [comment]
Ah, gotcha – I want it to appear only on at the top pf the suggestions for github.com.

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
I think this would be a nice enhancement. I've encounter this issue as well. The matched item I wanted was significantly down a lengthy list of possible matches. It would be nice to place the favorite item(s) at the top of the possible match list for quicker selection.

**Comment by strongbox-mark** [comment]
Yes, it would be nice to surface the favourite up top for sure. I'll take a look to see if it's possible to somehow control the ordering of the suggestions.

**Comment by strongbox-mark** [comment]
This should work for you now with 1.55.5. You'll need to open your databases in the main app first to update the QuickType database. Could you verify?

NB: If you have multiple databases using QuickType autofill, you can end up with stale entries/suggestions, so I'd recommend disabling AutoFill first for all databases, then switch it back on to clear the QuickType suggestions database.

**Comment by robojones** [comment]
I can confirm that the favorite accounts now are suggested first on my iPhone and iPad

**Comment by steebchen** [comment]
![image](https://user-images.githubusercontent.com/5013932/163554150-0ed3ac8a-9aa6-41d5-b181-3dccdfb54157.png)

🚀🚀🚀🚀🚀🚀

**Comment by strongbox-mark** [comment]
Awesome! Looks good!
