### ISSUE TITLE
Strongbox autofill not showing per default

### ISSUE THREAD

**Issue by steebchen** [strongbox-password-safe/Strongbox#609]
Sometimes there is no suggested fill info (it only shows 'Strongbox...'), but it does show after you manually click the lock icon:

https://user-images.githubusercontent.com/5013932/161206960-7b1cd71c-d688-4eec-96f1-853f5ab462a0.mov

Is there a reason for this or is this a bug? It only seems to happen in some cases, like on the GitHub password sudo prompt; it works fine on the normal GitHub logins.

**Comment by strongbox-mark** [comment]
I'm afraid this is all Apple code, hard to say what could be wrong. All Strongbox can do is tell the Apple AutoFill subsystem that it can provide username/password pair for url X. It's up to Apple then to display the suggestions in the appropriate location.
