### ISSUE TITLE
Native WebDAV/SFTP

### ISSUE THREAD

**Issue by mmcguill** [strongbox-password-safe/Strongbox#61]

**Comment by cyayon** [comment]
Hi,

Any news about this request ?
It's currently the only show stopper that prevent me to buy pro version on IOS and Mac.
ETA ?

thanks.

**Comment by strongbox-mark** [comment]
Hi, Yes, highly requested feature and is close to next inline after iOS advanced Sync/Merge and Offline Editing...

Would hope to get this out late Q1 2021.

**Comment by strongbox-mark** [comment]
HI @cyayon and @mlfreeman2 - This is available now on MacOS with 1.15.0. Reports are it is working well. Going to close this one out but let me know if spot any issues.
