### ISSUE TITLE
Add GitHub sponsors

### ISSUE THREAD

**Issue by steebchen** [strongbox-password-safe/Strongbox#610]
Might be worth to think about enabling GitHub sponsors on this GitHub :) 

Also, super unrelated, but I'm wondering why your commits are so weird and only use version names, instead of using actual commit messages?

![image](https://user-images.githubusercontent.com/5013932/161207258-91d05d3c-b7d8-4d7e-9f3e-82b2e1b0921f.png)

**Comment by strongbox-mark** [comment]
Hi! I think I tried to sign up for it when it initially launched but it was a nightmare of form filling. Perhaps that's improved so I'll look into it :) The best way to support us though is just via a subscription for our Pro edition. As for commits, yes, this is rather terse, no particular reason behind it, but usually just in a rush to get things push up to the repo. We'll try add some more detail in future. :)

**Comment by strongbox-mark** [comment]
Hi @steebchen - Sponsorship program was approved :) Thanks!
