### ISSUE TITLE
macOS: 1Password .1pif import containing sections, labels and empty fields doesn't group/handle it correctly

### ISSUE THREAD

**Issue by laserjay** [strongbox-password-safe/Strongbox#614]
As I'd like to switch over for known reasons, I'm evaluating the Pro version of Strongbox and tried importing my 1Password vault. 

I've been using sections, section titles, field labels and sometimes even empty field labels (as there was a section title anyway) to group some logins, eg. a page which I have one main login for, then a separate login per account grouped by sections and labeled appropriately. 

Importing entries like this gets really messy in Strongbox, as the grouping from 1Password doesn't get considered: section titles and hence sections don't get imported at all as far as I can tell, and if there are the duplicate field labels (username, password for example) per section, they all get grouped together and renamed with a UID appended. 

One one occasion (WiFi base station), it did import my SSID and password, also the SSID from the guest network, but it just omitted the secondary password field for the guest network. Usually it would import the second password field as another custom field with UID at least, but in that particular case, it just didn't.

Example:

Test entry created in 1Password, with section titles and labels:
<img width="398" alt="Screenshot 2022-04-06 at 10 29 31" src="https://user-images.githubusercontent.com/16119805/161938416-d20aa358-fbc5-4de8-a14f-ae0fd88e734b.png">

Same entry imported in Strongbox (as 1.pif):
<img width="382" alt="Screenshot 2022-04-06 at 10 34 42" src="https://user-images.githubusercontent.com/16119805/161936401-81ca2726-96c7-4801-8e01-0d978a701e82.png">

As you can see, the sections get ignored completely, and all other fields get mixed together as 'custom fields' with generated field/label names if duplicate.

For comparison, same entry imported into Minimalist password manager, which handles it as 1Password does:
<img width="490" alt="Screenshot 2022-04-06 at 10 35 36" src="https://user-images.githubusercontent.com/16119805/161936474-60337ec5-1aaa-45e9-ab22-78155c172a68.png">

(Sidenote: When I open the same .kdbx database generated by Strongbox with KeepassXC, I even lose all those custom field entries. Easy to replicate, for some reason I just can't screenshot KeepassXC, everytime I try to do it, I see the windows behind KeepassXC instead of the application, but that's for another issue tracker...)

**Comment by strongbox-mark** [comment]
Hi @laserjay - With release of 1.17.1 on macOS, you can now have the custom fields in your own preferred order (Preferences > Advanced > Sort Custom Fields > switch OFF).

This means you can control the display order. Would this work for you? You can control the order on the Edit screen by dragging and dropping the fields.

Unfortunately the import process isn't perfect, and sections/titles are not supported by the underlying KeePass format.

I think perhaps the custom fields are just not so easy to see in KeePassXC? Have a look in the advanced section for them.

**Comment by laserjay** [comment]
Hey Mark

The newly introduced sorting would certainly be a workaround, but not without prior preparation of the entries within 1Password, to avoid duplicate names and provide unique descriptors – if that hasn't been done, the import process scrambles the order of entries: eg. surely I could reorder username/password entries, but how to know which password belongs to which username afterwards? I'm afraid the import process doesn't let one know that some entries with some custom fields were renamed/re-ordered as I've stumbled upon that fact by mere coincidence as well. On first glance, everything looks fine and one might already delete the .1pif archive and delete 1Password and maybe stumble upon the fact weeks or months after the import. 

Maybe a note uphead (detecting custom fields during the import process?) to let one know to double-check if all entries are correct, maybe even point out which ones had custom fields, so to be able to go back, rename and re-import would be lovely. Espcially if more people are going to switch from 1Password to Strongbox in the near future.

Re the other thing: it's reproducible if you want to check yourself, but the entries aren't even within the advanced section within KeePassXC.

**Comment by strongbox-mark** [comment]
Will definitely take these points/issues into consideration on the next 1Password import iteration, there's a new 1Pux format which may make things a little easier...

**Comment by laserjay** [comment]
Interesting, what's new about that 1Pux format? As of 7.9.4, it still exports in .1pif

**Comment by strongbox-mark** [comment]
I'm not actually sure, it seems to be 1Password's new export format, it may actually be easier to parse. We haven't had a chance to look into it yet. Hopefully it's much more structured than the 1Pif mess.

**Comment by laserjay** [comment]
[Here's](https://support.1password.com/1pux-format/) some more info on the 1PUX (1Password Unencrypted Export Format)  for anyone wondering about it.

**Comment by svoop** [comment]
@strongbox-mark The problem with 1PUX: It takes 1P8 to export as 1PUX. In other words, you have to update from 1P7 (last version with local vaults) to 1P8 (data is forced into the cloud). It's the cloud bit which has people look for alternatives, but since 1P7 still works on today's macOS, it makes sense to wait for another "1Password import iteration" to land.

**Comment by strongbox-mark** [comment]
Just an update here, we released 1.58.5 recently and it has support now for the 1Pux format, as well as some minor improvements to the 1Pif import process (We try to prefix the custom fields if they are not unique with the section name they came from, and "Archived/Trashed" items are placed in the Recycle Bin)... It's still a little imperfect I'm afraid, because the import file formats are really under specified and obscure (this includes the new 1Pux format)... There's no way to guarantee what an database will look like when it's exported in 1Pux and so we do our best to grab as much information as we can having seen a few samples.
