### ISSUE TITLE
macOS: Ability to import 'Archive' from 1Password .1pif file into 'Recycle Bin'

### ISSUE THREAD

**Issue by laserjay** [strongbox-password-safe/Strongbox#615]
I've got <200 items in my 1Password vault which I'd love to transfer into Strongbox in the near future. It would be nice if the 'Archive' from 1Password could be considered as well during import (dialog to ask? checkbox?) and placed directly into the 'Recycle Bin'. 

It's not critical, but it might be relevant for users wanting to switch over to have all their entries, history and even archive, if the need arises to look up an old entry. While evaluating, I noticed Minimalist password manager does behave like that.

Speaking of import, it might make sense to have the 'Database' home view as 'All items' and showing (all items) within brackets, while subsequent groups within the tree as fraction of that. Currently, when I import all my items, database view says (0), while all the entries are split up into multiple groups containing all the entries each. Just a tad confusing I'd say.

**Comment by strongbox-mark** [comment]
Hi @laserjay - Yes, we've got this on our list for our next 1Password import iteration...

**Comment by strongbox-mark** [comment]
This is now available with 1.58.5.
