### ISSUE TITLE
OneDrive Credential Update Issue

### ISSUE THREAD

**Issue by JLWFuQrioea69ugsykvQcg** [strongbox-password-safe/Strongbox#616]
I recently changed my OneDrive credentials and I am unable to enter the new credentials into Strongbox without removing the existing databases and starting and adding it again.  Previously Strongbox would prompt me to enter my new credentials. Sometimes I would have to clear the existing session but either way I could get to it.  These are my only options at this time. Is this the only method going forward after changing OneDrive credentials. Mine change every 90 days. 

![image](https://user-images.githubusercontent.com/6074105/163265389-6fd8eb16-7c75-4ca2-9e9c-cd1636af1bcf.jpeg)

![image](https://user-images.githubusercontent.com/6074105/163265537-ad5fbd2e-950b-4389-b877-9e0b079891ff.jpeg)

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
I ended up deleting a single database and adding it again which resulting in having to authenticate against OneDrive using my updated credentials. The other two opened fine after that without having to delete and readd them. In hindsight I guess I could have just added a new, temporary database from OneDrive and then delete it without impacting my existing databases. I haven't had to go this route in the past.

**Comment by strongbox-mark** [comment]
Hi @JLWFuQrioea69ugsykvQcg - That is odd. 

Had you converted your old databases using the "Migrate to MSAL" button on the Advanced Preferences screen?

or was this a newly added database that is only now expiring?

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
I had previously converted them after the feature was released in a previous version.

**Comment by strongbox-mark** [comment]
OK, thanks @JLWFuQrioea69ugsykvQcg - Will monitor this, it might just been a migration issue. As long as you're able to re-add your OneDrive database successfully, this one might just be something we can workaround.

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
Sounds good. I'll try it again when I have to change my password in less than 90 days and see what happens.

**Comment by strongbox-mark** [comment]
Believe this is pretty stale and not receiving any reports of this lately.
