### ISSUE TITLE
macOS: DB Preferences visual "bugs"

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#618]
Noticed a few minor things in the Database Preferences:
* The "Close" Button is missing from the Preferences "Side Bar" Section.
* The "Close" Button is wider in the "Audit" section of the Preferences
* When Switching from the "Audit" section, which is taller that other sections, to another section in the Preferences the window does not always adjust the height properly. For example when Switching from "Audit" to "AutoFill".

**Comment by strongbox-mark** [comment]
Thanks, these should be quick ones to fix in the next release

**Comment by strongbox-mark** [comment]
Hi @dan-el - These should be fixed for you in 1.18.0. Please reopen if that's not the case.
