### ISSUE TITLE
Launching Strongbox via Dock or Spotlight DOES NOT work in SOME cases

### ISSUE THREAD

**Issue by strongbox-mark** [strongbox-password-safe/Strongbox#620]
from:  https://gist.github.com/dan-el/df9f86f80e3f11d249c61fdfc8e5628b - Test 2
A single database is set to auto launch.

- General / Show in System Menu Bar => ON
- General / Hide Dock Icon when all miniaturized or closed => OFF
- General / Quit Strongbox when all closed => OFF
- Advanced / Show Databases Manager When All Windows are Closed => OFF
- Advanced / Hide Databases Manager after Launching Database => ON

1) Launch Strongbox (via Dock, double click on Strongbox in "/Appplications", or Spotlight) and decrypt database.
2) The little dot appears under the Dock icon.
3) Close the App (red X) and the little dot DOES NOT disappear, Strongbox is still active in the System Menu Bar.

4) Launching Strongbox via Dock or Spotlight DOES NOT work in SOME cases. 

Launching Strongbox via double click on Strongbox in "/Appplications" works fine.

It is hit or miss - this is a new behaviour. It appears that if I switch focus to another app (e.g. by clicking an app window) and try to re-launch it is more likely to work launching the app.

**Comment by strongbox-mark** [comment]
We need more info on when this occurs. At the moment I'm struggling to reproduce this. @dan-el

**Comment by dan-el** [comment]
@strongbox-mark would a screen recording be helpful?

**Comment by strongbox-mark** [comment]
It might help, I'm not sure. I definitely believe it's an issue for you, but what we really need are clear steps to reproduce, otherwise there's no way to efficiently address.

**Comment by georgesnow** [comment]
Do you see Strongbox as the menu bar controlling app after you click the dock icon?

**Comment by dan-el** [comment]
@georgesnow Yes, I click the Dock Icon, no actual App window opens, but Strongbox is controlling the Menu Bar.

@strongbox-mark I tried the procedure as outlined in my test protocol again and I am not able to launch Strongbox at all anymore with the described combination of settings. Strange. I am also not sure why you can't reproduce the issue - is Strongbox launching normally for you with the combination of settings described in the test protocol?

**Comment by strongerbox** [comment]
hi, I have the same problem. 4 month ago I had it on my first machine and posted it on [Reddit](https://www.reddit.com/r/strongbox/comments/snjlfu/strongbox_wont_open_from_dock/?). Now I have it on my other machine aswell. Strongbox is running in the dock (with indicating point under the dock icon) and after clicking on the icon to open the window... nothing happens. :/

**Comment by simonneutert** [comment]
can confirm.  
opening the app via "cmd + space" opens strongbox, but I need to click it in the dock to show up.
macOS is up to date.

**Comment by strongbox-mark** [comment]
Hi all, I'm afraid I just can't reproduce this issue. The "SOME" in the title of this issue is the problem. Until it is specified we can't address. We really need an exact set of instructions to reproduce the problem...

For anyone else who would like to comment or say +1, please give much more detail, and a screen recording, otherwise there's just no way to address or fix the issue, and your comment will not contribute to the conversation.

**Comment by dan-el** [comment]
Hi @strongbox-mark,

With the steps described in the initial post of this issue I can reproduce the problem that Strongbox won't "launch" which I believe is due to the "Show in System Menu Bar" option since that option results in the Strongbox app never actually fully quitting and as mentioned in #621 the Strongbox process is not being notified about an attempt to launch the app if it's already running.

It seems the "solution" to the issue here is the same as in #621 which is the global hotkey or launching the app via the Menu Bar which still leaves us with the confusing situation that the Strongbox Dock Icon shows the app as active even with no active app window despite the Menu Bar Icon which does not have any app window. I'll send you a link to a screen recording showing how I am not able to launch the app from the Dock Icon, Spotlight, and the Finder via e-mail.

Maybe the Menu Bar icon should be outsourced into its own process to resolve this issue? The current situation is a cosmetic problem since the global hotkey provides a good workaround but the Dock Icon part in all of this is at least very confusing for the user.

**Comment by strongbox-mark** [comment]
Hi @dan-el - I believe this issue should be much improved/fixed for you with 1.57.0, could you check?

**Comment by dan-el** [comment]
Hi @strongbox-mark ,
See my recent reply in #621 - the "General / Always Show Dock Icon" setting still keeps me from launching Strongbox from the Dock or Spotlight if all DBs and the DB manager are closed but the menu bar icon is on. Launching through the menu bar icon does work however.

Another thing I noticed:
If I pin the Strongbox App Icon to my dock (via macOS drag and drop) and I use the menu bar icon I will see the "indicator dot" in the Dock if an app window is open (db manager, db) OR if the "General / Always Show Dock Icon" setting is on even when there is no app window open. And that is exactly when I cannot launch Strongbox from the Dock - always show on in combination with no app window open. **At this point I am not sure whether the "General / Always Show Dock Icon" setting is needed as it seems to be the thing causing the issues.** 

Le me know if you need a screen recording.

**Comment by dan-el** [comment]
Hi @strongbox-mark ,
With 1.57.3 (5072) from Testflight this issue seems to be resolved as well. I could not find a way to prevent Strongbox from launching properly.

**Comment by strongbox-mark** [comment]
As mentioned in #621 -  This should be fixed for you in 1.57.3 in the public App Store release now. 

Feel free to close if so :)

**Comment by dan-el** [comment]
I can no longer reproduce any launching issues.
The issue can be closed. Thank you!

**Comment by strongbox-mark** [comment]
Awesome! :)
