### ISSUE TITLE
MacOS: Add option to keep database unlocked after window close

### ISSUE THREAD

**Issue by bernarddavis** [strongbox-password-safe/Strongbox#623]
When I close the Strongbox window in the macOS app, Strongbox will prompt me to unlock the database again when I open the window again. Note that this is not after quitting Strongbox, just after closing the window with the red cross.

It would be great if there was an option to keep the database unlocked after closing the window. Even with Apple Watch unlocking it adds a few seconds to the workflow every time I want to open up StrongBox to search for a password.

**Comment by strongbox-mark** [comment]
That's interesting, so the current behaviour is by design, we just assume if you close a window you want your database locked. 

Could you use the miniaturize button instead to achieve what you want?

We could certainly look at hiding the database window on Close instead of locking.
