### ISSUE TITLE
Feature request :  add copy button in the "Show password" view

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#625]
Hi Mark , 

I haven't found a way to copy the password out of this view 

![image](https://user-images.githubusercontent.com/8161283/168073885-3aea350e-9162-4783-bc35-ffb08711da29.jpeg)

**Comment by strongbox-mark** [comment]
Why not just use the copy button in the previous screen, or the List/Browse View?

**Comment by F3000** [comment]
You are right . I have overseen it
