### ISSUE TITLE
Feature request (iOS) : easy copy of OTP code through clicking on the code

### ISSUE THREAD

**Issue by user858753257** [strongbox-password-safe/Strongbox#626]
Hi Mark ,

like discuses on Twitter . 

When user click on OTP code than copy it . 
When User clicks elsewhere in the field than process the copy witch is defined in the settings

**Comment by strongbox-mark** [comment]
This is available now.

**Comment by user858753257** [comment]
Where can I find it ? 

Clicking on OTP and in the field cooy the code . 
That works

**Comment by strongbox-mark** [comment]
We have a dedicated TOTP view which you can tap on to copy the code
