### ISSUE TITLE
[Enhancement] Cmd+Tab sequence on double-click on entry fields

### ISSUE THREAD

**Issue by Nozalys** [strongbox-password-safe/Strongbox#628]
Hello,

It would be nice if StrongboxSafe had an option to enable automatic cmd-tab event generation when user double-click on an entry's username or password column, to copy data. This option exists since a long time ago in KeePass for Windows (generates Alt+Tab sequence) and is very useful to copy a field and switch back immediately to the previous window (i.e.: a web browser) to paste data in the target form.

Regards.

**Comment by strongbox-mark** [comment]
Interesting idea, could be a quick one to implement. Will take a look at doing this shortly.

**Comment by Nozalys** [comment]
Hello, 
Is there any news on this feature ? I still don't see it in StrongboxSafe  for MacOS. Did I missed it ?

Thanks.

**Comment by strongbox-mark** [comment]
Hi we have a feature now called Hide on Copy, which should do this for you. You’ll find it under Clipboard settings. Could you confirm this does what you want?

**Comment by Nozalys** [comment]
Tanks, its a good starting point but it's not exactly the expected behaviour of my suggestion, and I don't feel the "minimize on copy" setting useful: because when StrongBox main window minimize to the dock (it's pretty "slow" with the MacOS animation) it does not put the expected application to the front (ie. the web browser), but it force the StrongBox database manager selection window on top. In fact, enabling this option does not reduce the user actions required, it increase it by one : I still need to press Cmd+Tab to go back to my browser.

**Comment by strongbox-mark** [comment]
Hi @Nozalys - You mention the "Minimize on Copy" setting in your reply, but I was referring to the "Hide on Copy" setting (appearing just above the Minimize on Copy checkbox). 

Have you tried that setting?

**Comment by Nozalys** [comment]
Excellent ! This is exactly the corresponding feature !

I taked about "minimize on copy" because I didn't paid attention that I still had an older version (1.58.3) and the "hide on copy" wasn't already implemented.

Thanks for your work.
