### ISSUE TITLE
Create New Entry remembers previous metadata (Username & Email)

### ISSUE THREAD

**Issue by 0b0e** [strongbox-password-safe/Strongbox#629]
Creating a new Strongbox item prepopulates:

**1. Username
2. Email**

This creates a erroneous data in the new entry.

- For **Username** it doesn't generally matter because in most use cases Username is overwritten/populated anyway.
- For **Email**, this creates a risk by putting an incorrect email address in an entry that it doesn't relate to. Email field is also hidden under my on-screen keyboard, so it's not even noticeable that incorrect data is being introduced.

You probably don't notice this bug if you mainly use one email address :)

Can this pre-populate be removed? Or have a Settings option to toggle prepopulate off?

![strongbox](https://user-images.githubusercontent.com/104311427/171357307-d57e4e64-4d3b-4ad7-95a6-f3005896037e.jpg)

Strongbox Premium Version 1.55.7
iOS 15.4.1

**Comment by strongbox-mark** [comment]
Hi @0b0e - You can change these "New Entry Defaults" under Preferences > Advanced > New Entry Defaults. Would that work for you?
