### ISSUE TITLE
[Feature Request] Equivalent Domains

### ISSUE THREAD

**Issue by zeyugao** [strongbox-password-safe/Strongbox#636]
Despite we can add multiple URLs in one entry for auto fill. But when we have multiple accounts under a site, it is an effort to add URLs so in many entries. If strongbox can support equivalent domains, it is a relief for users.

The dataset can be fetched from [this gist](https://gist.github.com/nitrocode/43e88ea31ed457b2ed69a0462794498c) or [from Apple](https://github.com/apple/password-manager-resources)

But I find that the keepass doesn't support it though.

**Comment by strongbox-mark** [comment]
Really good idea, thanks! Will try to add this in a coming release.

**Comment by strongbox-mark** [comment]
This is now available.
