### ISSUE TITLE
it does not work by add kdbx file with key file only

### ISSUE THREAD

**Issue by dtantono** [strongbox-password-safe/Strongbox#640]
Hi
I usually add kdbx file along key file to add the database. But on this time, I cannot login because it is being greyed out on the unlock button. Is it a bug?

**Comment by strongbox-mark** [comment]
Hi @dtantono - I'm not sure I understand. Would you be able to provide a little more detail. iOS/macOS? Any screenshots or a full set of instructions? You should be able to use a Key File with your DB without problem.

**Comment by dtantono** [comment]
Sorry, for the confusion and this is for iOS. But, recently I find that I just need to tap allow empty password for this. My question is if I want to unlock the database quickly with TouchID without go that screen below (Screenshot attached) I need to purchase the pro version. Is that so?
<img width="375" alt="Screenshot 2022-08-17 at 19 35 16" src="https://user-images.githubusercontent.com/29157187/185098488-10326c0f-57f1-40de-93b2-0346d050dd03.png">

**Comment by strongbox-mark** [comment]
That's right @dtantono - There's a 3 month free trial though, so check it out and see if it works for you... I'll close this one out now.
