### ISSUE TITLE
macOS: Left sidebar scrolling to the top

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#643]
Sometimes the left sidebar with the folder hierarchy jumps back to the top.
E.g. after creating a new db entry, after clearing an item from the recycle bin in the db, after committing and closing an entry, after saving the database, etc.

It is a cosmetic issue but a little annoying if you are working far down in the folder hierarchy with the occasional need to scroll back down.

**Comment by strongbox-mark** [comment]
Thanks @dan-el - Will see what we can do.

**Comment by strongbox-mark** [comment]
Hi @dan-el - This should be much improved in 1.56.3

**Comment by dan-el** [comment]
Looks good on my end! Thank you!
