### ISSUE TITLE
Unable to search by username

### ISSUE THREAD

**Issue by azfar** [strongbox-password-safe/Strongbox#647]
I have an entry and when I am searching its username (partial or whole) strongbox is not giving any results, I can search that entry by the subject still.

But at the same time other entries with same username are searchable!

**Comment by strongbox-mark** [comment]
Hi @azfar - Any more detail? Could you send debug info to support@strongboxsafe.com and preferably a screen recording?

**Comment by azfar** [comment]
My bad, I didn’t realized that search criteria was set to username instead
of all fields.
