### ISSUE TITLE
Change nickname is grayed out (mac os)

### ISSUE THREAD

**Issue by amund-ersland** [strongbox-password-safe/Strongbox#649]
The change nickname option under properties is grayed out. This would be a nice feature also on mac os

**Comment by amund-ersland** [comment]
It seems this should be possible with "change nickname" in the databasemanager. (I am on mac os) but this option is currently grayed out. In Ios I can change it. Here, the  nickname seems to be application specific, thus not saved to the db. What do you think of saving it as part of the db ?

**Comment by strongbox-mark** [comment]
Hi @amund-ersland - This should be fixed for you as of 1.56.4. We can consider your other suggestions separately.
