### ISSUE TITLE
Expand on 'duplicate entry' information

### ISSUE THREAD

**Issue by unicorn855** [strongbox-password-safe/Strongbox#652]
I wondered if it's possible to also show what other entries a specific password is duplicated in/similar to, rather than just saying that it *is* duplicated and/or similar? Could be a quality of life kind of thing, or is there already a workflow to show such information?

It's a joy to use the app regardless :-)

**Comment by strongbox-mark** [comment]
Yes, this should already be in place for you, simply click on the orange warning text on the Details pane (on macOS) to see it.

<img width="270" alt="image" src="https://user-images.githubusercontent.com/64356496/192731073-9d79a032-3fcf-4245-a275-b3ab37419189.png">

This is also possible on iOS.

**Comment by unicorn855** [comment]
Brilliant, thank you for pointing that out :-) It just didn't occur to me to tap the orange text (because I thought it's just text/information).

**Comment by georgesnow** [comment]
Oh my gosh I did not realize this. Awesome. Finally can consolidate some entries. Thank you!

**Comment by strongbox-mark** [comment]
Definitely need to improve discoverability here! Glad you like though! Closing this one out.
