### ISSUE TITLE
Feature request : Display OTP codes in dynamic island

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#654]
Concept :

![image](https://user-images.githubusercontent.com/8161283/198159151-a1bfc887-5260-48cd-9dc0-a6b3f2b2dbbd.jpeg)

**Comment by strongbox-mark** [comment]
Hi @F3000 - We need a lot more detail here, screenshots, instructions on how to reproduce, screen recordings, descriptions of the feature.

Currently this is extremely under specified and I'll have to close it. Feel free to re-open with **a lot** more detail.
