### ISSUE TITLE
Custom Fields 

### ISSUE THREAD

**Issue by PingSoup** [strongbox-password-safe/Strongbox#656]
Hello, would it be possible to make couple of enhancements to the Custom Fields. IMO, these are more of usability enhancements than cosmetics.

1) It would be very useful if one can change the order of Custom Fields as they appear (as list view), so that I can have to most used Custom Field at the top, or in a desired order.
2) Currently, the title of the Custom Fields are in grey, less prominent than the values in the Custom Fields. IMO, it should be the other way around. I would like see the title of the Custom Field more prominent. That way I can quickly see the Custom Field I am looking for and then look up the value in the field.

**Comment by PingSoup** [comment]
Sorry correcting/editing  #1).. " so that I am able to move the most used Custom Field to the top"

**Comment by strongbox-mark** [comment]
Hi @PingSoup - You should be able to do 1) already, just disable:

Settings > Advanced > Sort Custom Fields

Then you can go to the edit screen and drag and drop to re-order the fields.

For 2, ok thanks interesting, we might be able to fit this in with Font Size changes/configurability.

**Comment by PingSoup** [comment]
Hi @strongbox-mark - Thank you for reply. "Sort Custom Fields" is enabled "green", however, in edit mode, the feature is not working on iOS and macOS. Currently there is no way to move or reorder the fields.

**Comment by strongbox-mark** [comment]
Hi @PingSoup - Can you disable/uncheck the "Sort Custom Fields" checkbox, then you will be able to manually drag/drop the fields.

**Comment by svoop** [comment]
@strongbox-mark Is this a beta feature as of now? Can't seem to find it in 1.56.6.

**Comment by strongbox-mark** [comment]
Hi, yes, it is, it's on the Database Settings > Advanced screen at the bottom. Turn it off to allow custom ordering... This will be surfaced better in the next release, it'll be directly on the Details pane to toggle between Ascending or Custom order...

**Comment by svoop** [comment]
@strongbox-mark It works pretty well on macOS, however, there is one nasty oddity.

Given the following **sort: custom** custom fields:

<img width="453" alt="image" src="https://user-images.githubusercontent.com/7255/202438537-9db4bd71-a4c8-4202-b5eb-7b6966efb9c0.png">

Now double click on the first custom field name "aaa" and edit that very name from "aaa" to "aaa2", this field is moved automatically to the end thus messing up the custom sorting:

<img width="456" alt="image" src="https://user-images.githubusercontent.com/7255/202438419-37a8adaf-d563-4f39-8f9b-0759ba564317.png">

(Btw, what do you prefer in such a case: You reopening the existing issue or shall I create a new issue in the future?)

**Comment by strongbox-mark** [comment]
I see, must be a relic of how we're doing the editing, it's a deletion and then an addition when you edit a field name... Pretty small one, but it would be nice to fix... It's always best to open new issues and keep them as small and atomic as possible. But for now, I'll try fix this up in the next release.

**Comment by strongbox-mark** [comment]
Hi @svoop - This should be fixed for you in 1.57.3. 
To download and update to 1.57.3, you will need to go to the App Store, search for Strongbox, click on the correct version (the one you have installed now) and then you will see the "Update" button. Click that to Update :)

Could you confirm and close?

**Comment by svoop** [comment]
@PingSoup Looking good, thanks a bunch! (However, I can't close the issue, you'd have to do it it seems.)

**Comment by svoop** [comment]
@strongbox-mark Looking good, thanks a bunch! (However, I can't close the issue, you'd have to do it it seems.)

**Comment by strongbox-mark** [comment]
Cool, thanks!
