### ISSUE TITLE
Unlocking with Apple Watch on macOS

### ISSUE THREAD

**Issue by metawops** [strongbox-password-safe/Strongbox#661]
macOS 13.0.1 on MacBook Pro 14" (2021, M1 Max)
StrongBox 1.57.0 (Pro)
watchOS 9.1 (Apple Watch 7 linked to iPhone 14 Pro Max with iOS 16.1.1)

When I activate my Apple Watch in macOS Settings > Touch ID & Password it works exactly one time to decrypt the password database with the watch. When I then quit StrongBox and open it again only TouchID from the macBook works but the Apple Watch doesn't offer to unlock the database.
I have no idea if this is a StrongBox problem at all or an Apple/macOS/watchOS (or even iOS) problem but I just wanted to report it.

Am I the only one with this problem? 😳

**Comment by strongbox-mark** [comment]
That sounds very strange, can you still go to the Lock Screen and Login using your Apple Watch at this point? 

Does the Settings screen still say that Apple Watch Unlock is enabled?

**Comment by metawops** [comment]
I suspect some kind of macOS problem.
From the macOS lock screen unlocking with the Apple Watch doesn't work either.
In Strongbox in the database's settings dialog the Apple Watch unlock settings are still active (and selected).

In the macOS Settings app > Touch ID & Password my Apple Watch is still reported with an on switched switch.
So everything _looks_ normal – but doesn't work as expected. 

Currently clueless. 🤷‍♂️ 
Will reboot and check again and report back.

**Comment by strongbox-mark** [comment]
Weird... If it doesn't work on the macOS lock screen, then I suspect an Apple bug and one worth raising with them...

**Comment by metawops** [comment]
I'm pretty sure now that this has nothing to do with Strongbox but with macOS.
I was able to make it work again by following the steps outlined [here](https://www.lifewire.com/fix-apple-watch-not-unlocking-mac-5191765) – around step 6 it worked again.
