### ISSUE TITLE
Strongbox didn't get downgraded after the subscription expired

### ISSUE THREAD

**Issue by ghost** [strongbox-password-safe/Strongbox#662]
It's been almost two months since the $2.99 monthly subscription expired, and I still have access to the premium features without any issue.

**Comment by strongbox-mark** [comment]
That's interesting. Would you be able to send your debug info to support@strongboxsafe.com?

**Comment by strongbox-mark** [comment]
No, no issue at all there.

**Comment by strongbox-mark** [comment]
Yes, that might possible be relevant, but it seems like we might be a little too lenient here... We just assume that people are generally honest and try to stay out of their way. :)

**Comment by strongbox-mark** [comment]
Believe this one is fixed. Closing out.
