### ISSUE TITLE
Implement a custom copy type

### ISSUE THREAD

**Issue by francescotarantino** [strongbox-password-safe/Strongbox#665]
Hi,
I'm using Maccy to keep log of my clipboard and I added the Strongbox app to the ignored app list. Unfortunately, this solution doesn't work 100% of the time (sometime I find some of my passwords in my clipboard history).
I found out that if Strongbox used a custom copy type when copying a password, it could be set in the ignored list (https://github.com/p0deje/Maccy#ignore-custom-copy-types), and this solution should work 100% of the time.

**Comment by strongbox-mark** [comment]
I believe we tried this before and it broke regular copy/paste, and I believe it was for Maccy too. I can't remember the exact details but it seems setting a custom copy type isn't so straightforward. There's more info here: https://github.com/p0deje/Maccy/issues/125

**Comment by georgesnow** [comment]
I believe if you are just looking for clipboard managers to ignore copies. You set the type to conceal Maccy and other clipboard managers will honor the conceal type and ignore them from their history tracking

syntax isn’t perfect but basically you have to attach secondary pasteboard type which is “conceal” (there are others like transient) in addition to string utf8 type


````objective-c

NSString* type = [NSPasteboard.generalPasteboard setString: @"" forType:NSPasteboardTypeString];
NSPasteboard*  pb  = [NSPasteboard generalPasteboard];
[NSPasteboard.generalPasteboard clearContents];
[pb setString:"" forType:"org.nspasteboard.ConcealedType"]
[pb setString:@"concealme" forType:type]

````

**Comment by strongbox-mark** [comment]
Yes, I think we tried that before or something very similar... I can try again and put it behind an Advanced Preference defaulted OFF for the next release and then you can play with it and see if it works ok/doesn't break things...

**Comment by strongbox-mark** [comment]
That's great, we'll wait on @georgesnow to confirm and close.

**Comment by strongbox-mark** [comment]
Believe this one is fixed. Closing out.
