### ISSUE TITLE
Icon sizing issue (cosmetic)

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#666]
Steps to reproduce:
1. Open an entry in the database
2. On the right-hand side click on the "Group" dropdown
3. Built-in icons are rendered bigger than custom icons

Happens with the Keepass Classic and KeepassXC Icon sets, not with SF Symbols icon set.

**Comment by strongbox-mark** [comment]
Hi @dan-el - I see the issue, thanks. SHould be a quick one.

**Comment by dan-el** [comment]
@strongbox-mark Updated to 1.58.0 and it looks good now except the database icon on the very top of the list is still large.

**Comment by strongbox-mark** [comment]
Good catch! Missed that. Will fix in next release. :)

**Comment by strongbox-mark** [comment]
@dan-el - This should be fixed for you with 1.58.5 - could you confirm and close?

**Comment by dan-el** [comment]
Looks good now!
