### ISSUE TITLE
"Launch URL" transfers to OS empty string

### ISSUE THREAD

**Issue by Niko-CZ** [strongbox-password-safe/Strongbox#667]
"Launch URL" for custom URLs stopped to work with one of the latest releases. 
OS level handlers shows that content of URL is empty after slashes.
F.e. I have in URL:
ssh1://172.16.100.61 -l userX -pw passX -loghost "hostX"
OS receives:
ssh1://
*current version is: 1.57.2

**Comment by strongbox-mark** [comment]
Hi @Niko-CZ - This is on macOS correct? Does a normal https URL work? 

How are you verifying what the OS receives?

**Comment by strongbox-mark** [comment]
HI @Niko-CZ - Could you insert a %20 instead of a space? i.e. url encode this. e.g.

`ssh1://172.16.100.61%20-l%20userX`

Does that work?

**Comment by Niko-CZ** [comment]
Thanks a lot for returning back of old behavior in 1.58.0 :) you rock!

**Comment by strongbox-mark** [comment]
Oh fantastic, I meant to get back to you but it seems like it works, that's great. We automatically URL encode the URL now when launching, and that seems to do the trick.
