### ISSUE TITLE
Can I submit a new word list?

### ISSUE THREAD

**Issue by israelsaba** [strongbox-password-safe/Strongbox#668]
Let me know if I can upload a Brazilian Portuguese word list to the https://github.com/strongbox-password-safe/Strongbox/tree/master/resources/wordlists directory. From the looks of it I am able to upload it directly to github, but not sure it would help?

**Comment by strongbox-mark** [comment]
Hi @israelsaba - best to just send it to support@strongboxsafe.com I'll add it in to the build on the next release. Just let me know where it's from / what license it's under

**Comment by israelsaba** [comment]
Thanks for the info. Any preferred licensing scheme?

**Comment by strongbox-mark** [comment]
MIT would be great :)

**Comment by israelsaba** [comment]
Done, sent from israelsaba@gmail.com.

**Comment by israelsaba** [comment]
It's a 13MB file though I hope it goes through. Otherwise I can upload it to the cloud.

**Comment by strongbox-mark** [comment]
Got it, it's too big at that size to include in the binary, all of our lists currently contain 7776 words which is manageable, would you be able to find one of that size or reduce this one?

**Comment by israelsaba** [comment]
Yes, I'll do that and let you know here.

**Comment by israelsaba** [comment]
sent from israelsaba@gmail.com in the same thread as the last email
