### ISSUE TITLE
Tag separator interoperability: `,` not recognized

### ISSUE THREAD

**Issue by vszakats** [strongbox-password-safe/Strongbox#671]
Strongbox [recognizes](https://github.com/strongbox-password-safe/Strongbox/blob/c915e853df33179c2b46e9e788f83494c64385df/model/keepass/Entry.m#L129) `;` as a tag separator (in line with the available informal KDBX [specs](https://github.com/keepassxreboot/keepassxc-specs/blob/669af9172dfbae595f90cb6fe6639f62fbd07dbb/kdbx-xml/rfc.md#L511)).

The issue is that despite the spec, some clients (notably KeePassXC and `keepassxc-cli`) are saving tags with comma `,` separators. Opening such database in Strongbox results in a single concatenated tag for each entry, which is not usable:
![Screen Shot 2022-12-25 at 15 03 07](https://user-images.githubusercontent.com/1446897/209470949-1089522a-bde0-4502-8cbc-2e3ec4759d24.png)
vs the expected:
![Screen Shot 2022-12-25 at 15 26 31](https://user-images.githubusercontent.com/1446897/209471822-7dec520b-296b-4783-bca6-e63d2cd5eaad.png)

Other clients resolve this by recognizing multiple tag separators:
- [KeePass](https://github.com/ralish/KeePass/blob/e732fee6f3dacd6cf569e9408c1725833a8d9764/KeePassLib/Utility/StrUtil.cs#L1440)/[keepass2android](https://github.com/PhilippC/keepass2android/blob/56c35ac5739a402f9752a9f08cf87746b4620a84/src/KeePassLib2Android/Utility/StrUtil.cs#L1399), [MacPass](https://github.com/MacPass/KeePassKit/blob/789f86d0cd406460188c75c8811219e0c05f63ae/KeePassKit/IO/KDBX/KPKXmlTreeReader.m#L275)/[IOSKeePass](https://github.com/FrankHausmann/IOSKeePass/blob/4c24dd735c103fc67f328183f65aa1dd00573bbb/MiniKeePass/KeePassKit/IO/KDBX/KPKXmlTreeReader.m#L313), [KeePassDX](https://github.com/Kunzisoft/KeePassDX/blob/09988a858df569904ff2cb4bc2c58c9ff2725f9a/app/src/main/java/com/kunzisoft/keepass/database/element/Tags.kt#L77-L79): `,`, `;`.
- [KeePassXC](https://github.com/keepassxreboot/keepassxc/blob/3e3e87d3c59c7dbf5d424254f8c466592ced15c9/src/core/Entry.cpp#L427), [KeeWeb](https://github.com/keeweb/kdbxweb/blob/9b86a035a53f1827e427a0fc081bdcccc24f4f1b/lib/utils/xml-utils.ts#L14): `,`, `;` and `:`.

I wonder if Strongbox would be willing to also accept at least `,` (comma) for better tag interoperability with other clients?

**Comment by strongbox-mark** [comment]
Yes, not a bad idea, probably best to include all three separators for maximum compatibility.

**Comment by vszakats** [comment]
Thank you for implementing this in v1.58.0. Tag splitting now works perfectly in my tests (tested with `;`).

**Comment by strongbox-mark** [comment]
Yes, no problem :) One thing to note, I don't think KeePassXC is splitting on colon (:) despite that link above to their code. We've had a contact from one user mentioning this. I still think the right thing to do is maximize compatibility with other clients by splitting on all 3 delimiters. You may want to ping the KeePassXC crew about this.

**Comment by vszakats** [comment]
I'm happy with semicolons alone. Though one thing worthy to contact the KeePassXC crew is to include these details in the non-official specs.

Also thanks for the upgrade overall, it's a quite solid one!
