### ISSUE TITLE
Yubikey KeeChallenge remain the same after updating the database

### ISSUE THREAD

**Issue by gynet** [strongbox-password-safe/Strongbox#673]
What is the seed of the challenge-response implementation of Strongbox?  As I tested, if I update the database using StrongBox, I can still use the old response + master pass to decrypt the latest database(using KeeWeb); this is not expected; KeeWeb's implementation regenerates the response codes after each saving. 

 Is there any doc about the KeeChallenge implementation? Can StrongBox provide a way to rotate the challenge-response code?

**Comment by gynet** [comment]
I did verify a couple of times the issue is reproduced at StrongBox; however, no such issue if I did the update at KeeWeb with different laptops.  

## Testing scenario 
1. Having a database with Yubikey Challenge-response and putting it synced over Google Drive
2. Set KeeWeb to remember Challenge-response while the app is open
<img width="578" alt="image" src="https://user-images.githubusercontent.com/2174522/209861337-c13e66c7-b79e-45c3-9fd0-40600e47d18f.png">
4. Open the database in both StrongBox and KeeWeb
5. Make a change on StrongBox, for example, adding a note "test"  in one entry. save the change and commit, and save. 
6. Open KeeWeb, and sync the database; there is no Challenge-response promoted, and the change is directly synced to KeeWeb, and verify the entry added "test" in the note field. 

## Here is the database details: 

<img width="582" alt="image" src="https://user-images.githubusercontent.com/2174522/209860904-485676a8-802e-4fe5-a480-b00383389b02.png">

**Comment by gynet** [comment]
I think this is concerning because if the challenge-response did not get change per saving, then it lose the security advantage of using the feature

**Comment by strongbox-mark** [comment]
That would be a bug if that is the case, so we'll need to investigate. Will come back to you shortly, thanks for the extra info.

**Comment by strongbox-mark** [comment]
Hi @gynet - You were right on this, this is a bug with the KDBX4 serializer, so thanks for raising. We'll have a fix out in the next release, hopefully in the next week, which will rotate the challenge on each save as it should have. Will keep open until then, or if you like you can test a Testflight build if you prefer to verify sooner.

**Comment by strongbox-mark** [comment]
Hi @gynet - This should be fixed for you now with 1.58.1+ - Could you please verify and close if all ok? Thanks!

**Comment by gynet** [comment]
@strongbox-mark  I just verified, it works now, thanks!

**Comment by strongbox-mark** [comment]
Awesome, thank you and great catch.
