### ISSUE TITLE
No Close button or icon after creating and commiting a new entry

### ISSUE THREAD

**Issue by elharo** [strongbox-password-safe/Strongbox#674]
1. Create a new account entry
2. Set up passwords and username et al as needed.
3. Press Commit (not commit and close)

There's now no obvious way to close the dialog. In fact, one has to press "cancel" but "Cancel" does not mean close. Cancel is assumed to mean cancel the operation — that is, don't create the entry. 

Either give the dialog a close button or better yet a platform appropriate close icon on the window or both.

**Comment by strongbox-mark** [comment]
Hi there, that doesn't sound right and we're not seeing that on the latest build on the App Store (1.57.3).

There's a blue Close button at the bottom you can click after step 3. What version are you running there? or would you be able to provide a screen recording/screenshot of the issue? 

Also, hitting cancel in this scenario (or pressing Esc) is equivalent to close. Commit means commit, so you can uncommit from that point.

**Comment by elharo** [comment]
I'll check on version details and let you know. 

There is a meta-issue in play here. "Commit" is not a verb that's meaningful to non-technical end users. Ditto "Record", "Entry", and other similar database terms. The UI seems to expose implementation details in multiple places. Probably the best equivalent for an end user here is "Save".

**Comment by elharo** [comment]
The app seems to prevent itself from being screen captured but I'll push something through the analog hole. Meanwhile.


Strongbox 1.56.2 Debug Information at 2023-01-01 17:42:39.916
--------------------
App Version: com.markmcguill.strongbox [1.56.2 (5024)]

--------------------
Device
--------------------
Model: Mac13,1
CPU: ARM64E
System Name: MacOS
System Version: Version 12.6.2 (Build 21G320)

**Comment by elharo** [comment]
![IMG-4187](https://user-images.githubusercontent.com/1005544/210186716-fc5c7008-0f50-436f-a539-c985818cc97b.jpeg)

**Comment by strongbox-mark** [comment]
OK, thanks for that. Could you update to the latest on the App Store, there were some improvements to this UI over the last while. Hopefully should ameliorate some of your concerns.

**Comment by strongbox-mark** [comment]
Believe this is fixed. Closing out now.
