### ISSUE TITLE
Feature Request: Increase tag width in Details Panel

### ISSUE THREAD

**Issue by howdytom** [strongbox-password-safe/Strongbox#679]
Hello,

How can I increase the tag name width in the Details Panel? The complete tag name shows up on the left sidebar. The Details Panel trims tag name above 12 characters, though.

![strongbox-increase-tagname-width](https://user-images.githubusercontent.com/9871520/211791101-b7438a1d-1809-45e8-afb2-a7a2cbdde188.png)

**Comment by strongbox-mark** [comment]
Sure, we can look into improving that to something a little more comfortable.

**Comment by strongbox-mark** [comment]
Hi @howdytom - We've increased the width in a recent build, should hopefully be much improved.

**Comment by howdytom** [comment]
@strongbox-mark Sounds great. I will check it out. Thank you!
