### ISSUE TITLE
iOS: faulty search results with keyword "git" in search query

### ISSUE THREAD

**Issue by marcusique** [strongbox-password-safe/Strongbox#684]
I have a separate database with TOTP only. Whenever I want to find a TOTP for Github and enter "git" in the search field, the app returns all available TOTP entries. Same behavior on macOS as well.
![IMG_381D83FE7781-1](https://user-images.githubusercontent.com/23212368/220584430-dcbaee11-6eee-42fc-8d33-909e12b74036.jpeg)
**DB format:** KeePass 2 (4.0)
**App:** 1.58.7
**OS:** iOS 16.3.1

**Comment by strongbox-mark** [comment]
Wow, interesting find. I think what's happening here is it is finding "git" inside the OTPAuth URL for TOTPs. This URL contains a parameter called "di_git_s" which is matching. I think we'll need to add some special search code to avoid matching on these params.

**Comment by marcusique** [comment]
Works now. Thanks!
