### ISSUE TITLE
Missing favicon download option

### ISSUE THREAD

**Issue by skrull** [strongbox-password-safe/Strongbox#686]
Open database with keepassxc, create an item. Now open on strongbox and try to download the favicon. Select Icon Source shows KeePass & Database Icon Set or Media Library only

EDIT: keepassxc add https:// prefix to url. Removing it works.

**Comment by strongbox-mark** [comment]
Hi @skrull - There isn't very much information here, and I'm afraid I don't understand the issue you are seeing. Could you please provide much more detail, including steps you take on both KeePassXC and Strongbox, what you expect to see, what you do see.

Include sample URLs and some screenshots. Will close this out for now, but please open a new issue if you think there is a bug/problem, again with much much more detail.
