### ISSUE TITLE
Feature Request: ability to unlock with password + yubikey on autofill

### ISSUE THREAD

**Issue by G3NSVRV** [strongbox-password-safe/Strongbox#687]
## Description
Ability to unlock with password + yubikey on autofill

## Current Behaviour
Currently there is no way use autofill passwords when the database is configured using password + yubikey. Everything is greyed out and the only way to input password is by opening the app, unlock and copy and paste each field

## Expected Behaviour
We should be able to select the yubikey on the autofill popup

**Comment by strongbox-mark** [comment]
Hi, you can use YubiKeys in AutoFill on macOS, and for iOS we provide the "Virtual Hardware Key" solution:

https://strongbox.reamaze.com/kb/yubikey/why-doesnt-yubikey-work-in-autofill-mode

Strongbox cannot access physical YubiKeys in AutoFill on iOS due to system/library limitations.
