### ISSUE TITLE
Feature request: ability to set which folders are included in search and auto fill

### ISSUE THREAD

**Issue by shashimi7** [strongbox-password-safe/Strongbox#688]
Strongbox (iOS and macOS) already properly handle this property. For instance it already excludes from search and auto fill the folders flagged to not be included in search. As long as this property was set in another app such as KeePass itself on windows.

However Strongbox does not let user see this flag (not at all in iOS, possible to see on macOS after many clicks among all the properties); and it definitely does not let user change that property. Hence this request:
Please make this important property visible and editable in Strongbox!

**Comment by strongbox-mark** [comment]
HI @shashimi7 - This is available for you now in with 1.58.10/11. Feel free to reopen if you have any issues.

**Comment by shashimi7** [comment]
I forgot to say thank you! You rock. The feature is very well integrated. Excellent.
