### ISSUE TITLE
[Feature request] Check for port in URL/IP address

### ISSUE THREAD

**Issue by marcusique** [strongbox-password-safe/Strongbox#693]
Hi,

I have a lot of Docker containers running on my Raspberry Pi that I only access from within my LAN. They obviously have the same address (e.g. 192.168.0.254), but different ports, e.g.
- App 1: 192.168.0.254:8080
- App 2: 192.168.0.254:8083
- App 3: 192.168.0.254:5000

When I try to autofill a password on one of these apps, I assume StrongBox suggests the first password it finds (usually the one on top), meaning it disregards the port after `:`

This is what AutoFill suggests:
![Screenshot 2023-03-29 at 13 02 36](https://user-images.githubusercontent.com/23212368/228514467-f494aa61-e4db-4dcc-8cbe-976436a596e9.png)

And this is what I actually need:
![Screenshot 2023-03-29 at 13 02 42](https://user-images.githubusercontent.com/23212368/228515009-e5405ecd-23ec-4170-bc73-59a4b23f8e3a.png)

Not sure how many users will find it useful, but it would be great to add this functionality to StrongBox.
Thank you!

**Comment by strongbox-mark** [comment]
Unfortunately this is controlled by an Apple algorithm. Strongbox can only tell the system it has passwords for X set of urls. 

You should see improved results if you use the Strongbox browser plugin in Chrome/Firefox (if that's an option) but we aren't able to control the matching sorting algo in Safari at the moment to this degree of granularity.
