### ISSUE TITLE
1Password 1PUX Import empty "Password" Items

### ISSUE THREAD

**Issue by ae3ch** [strongbox-password-safe/Strongbox#694]
This error refers to Strongbox **1.58.12**

When importing a 1Password 1PUX backup of the 1Password 8 version, there is an error when importing entries of the type "Password". 
1Password allows creating logins, but also simple password entries, which contain only a password but no username and no URL. 

After importing the 1PUX file, all entries of the "Password" type are empty. Strongbox does not import passwords for these entries.

**Comment by strongbox-mark** [comment]
Hi @ae3ch - Thanks for the bug report. Would be able to attach a sample 1PUX exhibiting this issue?

**Comment by ae3ch** [comment]
Hi @strongbox-mark

Attached you will find an example 1PUX.

This export contains a regular login entry and one of the password entries. 
After the import, the password entry does look like this, no password is imported.


[1PasswordExport-Example.1pux.zip](https://github.com/strongbox-password-safe/Strongbox/files/11157237/1PasswordExport-Example.1pux.zip)

![Screenshot](https://user-images.githubusercontent.com/15161713/230040666-e8bbd435-2052-4201-aebc-80e6bbd35e16.png)

**Comment by strongbox-mark** [comment]
Thanks, will look into this...

**Comment by strongbox-mark** [comment]
This should be fixed now with 1.58.14. Thanks for raising. Will close off, but please let me know if there is any issue.
