### ISSUE TITLE
Cannot click on suggested item in Safari autofill popup

### ISSUE THREAD

**Issue by Kugelfang666** [strongbox-password-safe/Strongbox#695]
This seems to be similar to the bug mentioned here: https://github.com/strongbox-password-safe/Strongbox/issues/502

**Environment:**
MacOS 13.3.1
Safari: 16.4
Strongbox: 1.58.13

**Case 1**: The autofill popup suggested a matching item in my database:
I'm able to operate the popup with my mouse. This means that the item gets highlighted on mouseover etc. However, I cannot click on an item neither with the mouse nor with 'enter' on my keyboard to trigger the unlock process. A restart of Sarfari or the full Mac did not help. I disabled and re-enabled autofill with no effect. 

**Case 2**: The autofill popup does NOT show me a match. I click on 'Strongbox' and unlock. in the search menu I can find the right item select it and the User + PW gets autofilled into the correct fields.

**Comment by kumabon** [comment]
Same issue for me here. Same version of macOS / Safari / Strongbox.

One additional note for case 1, while I cannot select the suggested entries using mouse click or keyboard, I could use Touch ID to "click" after I mouseover an entry. My database remains unlocked the entire time.

Using Touch ID is not always convenient for me, as my MacBook Pro lid is often closed on my desktop.

Autofill / QuickType used to work previously. I am unable to pinpoint which recent update to macOS / Safari / Strongbox broke that feature

**Comment by Kugelfang666** [comment]
ok, i see, thanks for the feedback, would it maybe make more sense if you as app developer would file a bug
? I assume that as an enduser the feedback might not get the necessary attention

**Comment by kumabon** [comment]
Perhaps it'd be useful to note that QuickType works fine with build-in password manager. i.e. mouse click and Enter keystroke can select an item. I haven't tried another password manager supporting QuickType to see if it is also a problem tho...

Are you able to replicate the problem?

**Comment by strongbox-mark** [comment]
We’re getting reports this is fixed in the latest Safari beta. We have raised this and other issues with Apple but unfortunately we’ve never received any kind of response when we raise these, even as developers. It just goes into a black hole. The more people complain the more likely it is they will look at the issue.

**Comment by Kugelfang666** [comment]
Haven’t encountered this for quite some time, can be closed from my end

**Comment by strongbox-mark** [comment]
OK, fingers crossed Apple has fixed this in the meantime.

**Comment by kumabon** [comment]
Indeed the issue appears resolved for me as well. 

macOS 13.5
Safari 16.6
Strongbox 1.58.17
