### ISSUE TITLE
Allow hiding entries from implicit iOS autofill select box

### ISSUE THREAD

**Issue by alcroito** [strongbox-password-safe/Strongbox#703]
Hi. 

I have 10+ accounts for a specific web page url (+ additional fields), but i don't always use all of them. 

Whenever I visit the web page, i get an unwieldy select box trying to find my specific account.

I tried setting the favourite option on my main accounts, but that only adds a star next to the main accounts, it doesn't move them to the top of the auto fill list, so i still need to scroll.

It would be nice if it were possible to explicitly hide / skip certain accounts from the implicit auto fill list. Perhaps by applying a specific tag to them.

Thanks for the great app!

**Comment by strongbox-mark** [comment]
Hi, at the moment there's no individual setting for this. There are a couple of options I can think that might help though:

- Change the URL of the entries you don't want to something more cryptic or just remove them. Not sure if this is acceptable, and I know not a great solution
- Place the entries you don't want into a group, and mark the group as "Not Searchable". Not great either as they won't show up in any search

BTW, let me know if this on iOS or macOS? and if so on Safari or Chrome/Firefox? 

I can see the need for a nice switch to turn off an entry for AutoFill suggestion.

**Comment by alcroito** [comment]
Hi, it's iOS + Safari.

Ideally i'd still be able to search and select an entry once I press the key icon and go into the strongbox applet. 
I just don't want them to clutter the default list that shows up when pressing the key icon, before going into the app itself.

I'll try your suggestions and see if I can live with the UX of it. Proper support would be nice though.

Thanks!

**Comment by strongbox-mark** [comment]
Hi @alcroito - This is now available with 1.58.17 on iOS/macOS. Just:

Long Tap (or right click on macOS) on an Entry > Settings > Suggest in AutoFill > Switch OFF
