### ISSUE TITLE
MacOS App. Flickering control panel

### ISSUE THREAD

**Issue by Mikage777** [strongbox-password-safe/Strongbox#706]
Hello! Found a nasty visual issue. I have 1.58.14 version of Strongbox installed on MacOS. The application is running in full screen mode on one of the monitors. If you select the one in the list of entries where TOTP is specified, then some elements in the application interface begin to flicker. Not the most critical issue, but a little annoying.

Demo of the problem:

The application window is out of focus. Record selected with TOTP:

https://github.com/strongbox-password-safe/Strongbox/assets/5903264/47492858-bbc5-46bf-ac70-b3849fc4f463

The application window has focus. Record selected with TOTP:

https://github.com/strongbox-password-safe/Strongbox/assets/5903264/5471b508-3c62-496f-8303-caf263c859bc

**Comment by strongbox-mark** [comment]
Thanks @Mikage777 - This is just happening on full screen external monitor right? Does it happen outside of full screen, or on your built in display?

**Comment by Mikage777** [comment]
> Thanks @Mikage777 - This is just happening on full screen external monitor right? Does it happen outside of full screen, or on your built in display?

Hi! Yes, this only happens in full screen mode. Outside of this mode, everything is fine. But so far I noticed only on an external monitor, I could not reproduce it on the built-in display (because I could not remove focus from an application that is open in full screen mode)

**Comment by howdytom** [comment]
@Mikage777 Strongbox uses the macOS window UI. By default macOS window do not have 100% fill. Transparency is actually design feature. It looks like you do have a video, image or another window in the back. A Youtube video playback in the back could cause those flickering. I could be wrong, but I don't think it is related to the full screen mode.

Try to the reduce transparency. Open System Preferences → Accessibility → Reduce transparency

**Comment by strongbox-mark** [comment]
This is looks quite stale and I believe unrelated to anything Strongbox is doing. Closing out.
