### ISSUE TITLE
Crash on opening db

### ISSUE THREAD

**Issue by brian91292** [strongbox-password-safe/Strongbox#713]
I’m on the latest iOS 17 beta, this issue only started happening I believe after the second beta. Basically everytime I try to open my password database with a virtual or physical hardware key, strongbox crashes. This happens after I enter my master password and click “unlock”, or after I click cancel from the screen you enter your master password on. Also worth noting it happens regardless of whether I’m auto-filling from an app/safari or open the strongbox app directly.

I have also uploaded a video of the issue here:

[removed video]

Can provide more details/logs if requested.

Thanks!

**Comment by strongbox-mark** [comment]
Hi there, typically we don't support Beta operating systems, it's just too fluid, but in this case we have a fix available on Testflight now, and will hopefully be releasing an official update to the App Store during the week. Thanks for the report :)

**Comment by brian91292** [comment]
That’s great, thanks for the quick response and have a good day!
