### ISSUE TITLE
Impossible to switch databases using the Tab bar in some cases

### ISSUE THREAD

**Issue by howdytom** [strongbox-password-safe/Strongbox#716]
Usually I am working with 2 unlocked databases. Recently I noticed that the tab bar remains inactive when I try to click and switch to another database. It is impossible to click and open the other tab. This happening with locked and locked databases. As a workaround I have to close the tab bar and re-open the database. It looks like a bug to me and has been introduced on some of the recent updates.

**Comment by strongbox-mark** [comment]
Hi @howdytom, this should be fixed for you now with the release of 1.58.19 on the App Store now. You may need to search for Strongbox and click in to it to see the "Upgrade" button.

**Comment by howdytom** [comment]
@strongbox-mark This bug has been fixed. So far I did not experience it. Great Job!!
