### ISSUE TITLE
Right Click > Tag adds a tag called "Tag"

### ISSUE THREAD

**Issue by dan-el** [strongbox-password-safe/Strongbox#720]
1. Right click on a db entry
2. Click on "Tag" (not on one of the tags in the following menu)
3. A tag called "Tag" is added to the db entry

I am not sure this is expected behaviour. I'd rather expect nothing to happen instead of having a generic "Tag" added to the db entry. A tag should only be added when clicking on a tag from the list of tags.

**Comment by strongbox-mark** [comment]
HI @dan-el - This should be fixed for you in 1.58.25, could you confirm and close?

**Comment by dan-el** [comment]
Confirmed. Thank you!
