### ISSUE TITLE
Allow the option to change the default group where new entries get saved with the browser extension

### ISSUE THREAD

**Issue by MooseExplorer637** [strongbox-password-safe/Strongbox#722]
Currently, when creating new entries with the browser extension, they get automatically saved to the main database folder, and if you want to save the entry somewhere else you have to manually change it every time. Thus, it would be nice if the user could specify a default folder where the new entries would automatically be saved. This would be especially useful if you save all of your website logins into a particular sub-folder, which would then almost always be the place where you want to save your new entries when creating them with the browser extension.

**Comment by strongbox-mark** [comment]
This should be working for you now in the latest build. Strongbox will remember where you last saved an entry and default to that on the next create.
