### ISSUE TITLE
Feature request for enhancement to Passkey authentication process

### ISSUE THREAD

**Issue by JLWFuQrioea69ugsykvQcg** [strongbox-password-safe/Strongbox#724]
I have a website that uses a passkey to authenticate and then requires a TOTP code for 2FA. I would like Strongbox on iOS to automatically copy the TOTP code to memory for for subsequent pasting, similar to how it behaves when dealing with passwords.

**Comment by strongbox-mark** [comment]
This should work for you on 1.58.25, it was a bug in the previous release.

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
Just tried it and it works perfectly!  Thanks!
