### ISSUE TITLE
create a new passkey, freeze while unlocking

### ISSUE THREAD

**Issue by cryptosteve2** [strongbox-password-safe/Strongbox#728]
I want to create a new passkey on webauthn.io. I select a username and click Register. The system asks if I want to create a passkey in Strongbox. I confirm, select the database, it unlocks, I select the entry (e.g. root), click on "Create Passkey" and Strongbox hangs up with the message "Strongbox - unlocking". 

The whole thing happens reproducibly in most cases. How can I provide more information?
I see this in the changelog: BugFix: If you have multiple enabled AutoFill databases Passkey creation was blocked. 
I have two databases. If I disable AutoFill for one of these thre creation works. It may not be fixed for me :)

![20231021@184428@2x](https://github.com/strongbox-password-safe/Strongbox/assets/6260784/e83d2895-3438-4595-a1b0-d29ac09a7fc0)
![20231021@184502@2x](https://github.com/strongbox-password-safe/Strongbox/assets/6260784/4092a03d-e335-4287-adaa-43b526cac83b)
![20231021@184514@2x](https://github.com/strongbox-password-safe/Strongbox/assets/6260784/2c042299-ae1f-496e-a848-53008e0db8e8)
![20231021@184527@2x](https://github.com/strongbox-password-safe/Strongbox/assets/6260784/a3600dba-67cd-4dd6-ab42-02d02cb6d842)

Version: 1.58.27
Pro-Status: Pro (Lifetime)
App SKU: Non-Universal (macOS only, Outright Pro)
Pro Status: Lifetime Pro (App SKU is Pro)
Platform: MacOS Version 14.0 (Build 23A344)

**Comment by strongbox-mark** [comment]
Hi @cryptosteve2 - Does a device restart help? We've got another build coming soon that may also help

**Comment by cryptosteve2** [comment]
After a device restart AND switching autofill off and on again for my seconds database it seems to work now.

**Comment by strongbox-mark** [comment]
OK, still probably an issue that might crop up again, hopefully have this bug squashed in the upcoming .28 build... Probably out tomorrow or so...
