### ISSUE TITLE
Feature Request: Confirm Existing Entry Name When Saving a Passkey

### ISSUE THREAD

**Issue by elmedico27** [strongbox-password-safe/Strongbox#730]
When saving a passkey on an iOS device, upon selecting an existing entry to save the passkey, the dialog box only says "Are you sure?" with a yes/no selection.  To help prevent mis-taps, especially if selecting from a list of multiple existing entries, I'd like for the dialog box to say something like "Save this passkey to [ENTRY NAME]?"  (Alternatively, upon saving the passkey, the confirmation dialog could also include the entry name, but I see this as secondary to presenting the entry name _before_ saving.)

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
I agree that this would be very helpful. I've had to cancel the process a few times to make sure I picked the right entry because I was going too fast. Otherwise, passkeys seem to be working great in Strongbox.

**Comment by strongbox-mark** [comment]
@JLWFuQrioea69ugsykvQcg @elmedico27 - This one should be fixed for you now with 1.58.33

**Comment by elmedico27** [comment]
> @JLWFuQrioea69ugsykvQcg @elmedico27 - This one should be fixed for you now with 1.58.33

It is, and it works great! Thank you so much!
