### ISSUE TITLE
iOS issue with copy TOTP to clipboard

### ISSUE THREAD

**Issue by JLWFuQrioea69ugsykvQcg** [strongbox-password-safe/Strongbox#736]
I'm using the latest version of the Strongbox app on iOS 17.1.1. The copy TOTP to clipboard functionality doesn't seem to be working once I select the entry for auto fill. I do have the option enabled under auto fill settings. I've tried turning off auto fill and toggling that option but it's still not working. By not working I mean it's not copying the TOTP code to the clipboard because when I go to paste it's blank. Any suggestions?

**Comment by strongbox-mark** [comment]
Oh that's weird, have you tried a full device restart?

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
I did do that as well yesterday with no change. This morning while testing it worked as expected the first time. Subsequent times it failed to update the TOTP code stored on the clipboard so it was using the code from the first time. Now it entered the username and password, but doesn't store anything to the clipboard so there's nothing to paste. Yeah, so now it's back to not working and I've tried different entries.  Sometimes when I select "paste" it pastes my password from the entry I just auto filled.

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
I also tried it on my iPhone 14 running 17.1 and it's exhibiting the same behavior where it works the first time and subsequent tries fails.

**Comment by strongbox-mark** [comment]
Is this happening inside Safari or is it a third party app?

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
My issue has been in safari. I haven't tried this in a third party app.

**Comment by strongbox-mark** [comment]
Do you have convenience unlock switched on, and, does turning that off improve things?

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
I had it turned on and set for the 10 min. I turned it off and it seems to work more consistently now. I'll expires with it on my work phone and let you know.

**Comment by eyeseaevan** [comment]
I have the same exact issue, and I sent an email with a full screen recording and more extensive info to support@strongboxsafe.com from lmaevan@icloud.com

iOS 17.2 Beta FYI

**Comment by strongbox-mark** [comment]
Thanks @eyeseaevan - Got your mail, will investigate... Could you do the same as above:

> Do you have "AutoFill convenience unlock timeout" switched on, and, does turning that off improve things?

**Comment by strongbox-mark** [comment]
HI @JLWFuQrioea69ugsykvQcg @eyeseaevan - This should be fixed now with the release of 1.58.33, could you check/confirm?

**Comment by eyeseaevan** [comment]
> HI @JLWFuQrioea69ugsykvQcg @eyeseaevan - This should be fixed now with the release of 1.58.33, could you check/confirm?

Hey @strongbox-mark , sorry I wasn't able to reported on the suggested bug fix of setting convenience autolock to a shorter value. Anyway, on the previous release I disabled the convenience autolock and this seemed to fix the issue.

I just updated to the latest release and set convenience autolock to the longest value of 3 days and tested several sites including nextdns - which I had used as an example in my bug report email. It seems to be working well now, no freezing, the autofill is quick, and the clipboard is updated with 2fa.

If I later find any bugs with it I'll report, but it seems that this update has fixed it 🙂 Thank you

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
@strongbox-mark I'm only seeing 1.58.32 in the US iOS App Store at the time of this post. Maybe there's a delay in availability for me. I'll check it after the update comes available.

**Comment by strongbox-mark** [comment]
Sorry, .32 should also have the fix, .33 is on the way, waiting for Apple review

**Comment by strongbox-mark** [comment]
Hi @JLWFuQrioea69ugsykvQcg - Could you update to 1.58.35 and let me know if this fixes things for you?
