### ISSUE TITLE
Device does not support MFI Device

### ISSUE THREAD

**Issue by getlarge** [strongbox-password-safe/Strongbox#738]
To my great surprise I was able to use my Yubikey to open databases requiring HMAC-SHA1 challenge response (thanks to the USB-C to lightning adapter), even with my iPad Pro 4th generation.
But since today, I receive this error:
```
There was a problem opening the database.
Device does not support MFI Device
```

Could you explain what provoked this change of behaviour ? Might this be due to a change in a recent release ?

**Comment by getlarge** [comment]
Alright thanks for the info, then we can soon enjoy our Yubikey with our iPads :)
I'll let you close the issue once the release is made ?

**Comment by strongbox-mark** [comment]
Yep, for sure, thanks @getlarge

**Comment by getlarge** [comment]
Great news, thank you. I confirm that it works.
