### ISSUE TITLE
Feature Request: Add delete icon to toolbar

### ISSUE THREAD

**Issue by howdytom** [strongbox-password-safe/Strongbox#742]
Strongbox misses a delete button. It is possible to create and edit an entry, but not deleting items using the toolbar. Of course, you can delete entries via return or delete key or via menu bar → Item → Delete item. I think a visual delete button could be a reasonable improvement for new users.

**Comment by strongbox-mark** [comment]
This should be available for you in 1.58.38 available on the App Store now. Please let me know if that's not the case.
