### ISSUE TITLE
URL subdomain matching issue

### ISSUE THREAD

**Issue by comzine** [strongbox-password-safe/Strongbox#743]
I think this issue has become less pressing or stale, especially with the ability now to exclude individual entries from AutoFill (see #703 )... Please raise fresh issues for any remaining improvements.

_Originally posted by @strongbox-mark in https://github.com/strongbox-password-safe/Strongbox/issues/517#issuecomment-1649558280_
            

> Hi @georgesnow - I think/hope the sorting algorithm for subdomains/hosts is better in 1.58.10/11, would be interested to hear what you think or what's not working/working.

I do have 1.58.37. And I also have the same issue.
Autofill in portainer.example.com gives me the suggestion of c.example.com. In the list of other options I can choose portainer.istan.de and it says "From this domain".
Would be really nice, if there is a url matching feature like in KeepassXC.

**Comment by strongbox-mark** [comment]
Hi @comzine - is this on iOS/macOS, which browser?

Could you send a screen recording and precise URLs to support@strongboxsafe.com and we'll take a look?

**Comment by comzine** [comment]
Thanks for the quick answer. I sent a screen recording as you requested.

**Comment by strongbox-mark** [comment]
Got it, thanks @comzine - Unfortunately this is Apple's own sorting algorithm in Safari, we can tell Safari we have a login for X url, but it sorts those suggestions itself and it doesn't seem to do a very good job I'm afraid. This isn't something we can fix I'm afraid.

**Comment by tonyxu-io** [comment]
I really like how Bitwarden supports different ways of matching the URLs, by base domains, by host, or by regex. It's super flexible, and I'm using all these options depending on my use case.

**Comment by strongbox-mark** [comment]
Hi @tonyxu-io - That doesn't sound right, how are you verifying this? Would you be able to send a screen recording demonstrating the issue to support@strongboxsafe.com?

**Comment by tonyxu-io** [comment]
> Hi @tonyxu-io - That doesn't sound right, how are you verifying this? Would you be able to send a screen recording demonstrating the issue to [support@strongboxsafe.com](mailto:support@strongboxsafe.com)?

Thanks, just sent to the email.

**Comment by strongbox-mark** [comment]
In email correspondence we discovered there is a slight bug in sorting of URLs, they're not always sorted from most specific match as they should be when the match is beyond the PSL suffix. e.g.

1. https://abc.linked.com
1. https://grid.linked.com

when visiting https://some-sub-domain.grid.linkedin.com, URL 2 should be sorted as the best match. Currently this isn't the case. We'll work on fixing that. Thanks @tonyxu-io

**Comment by tonyxu-io** [comment]
> In email correspondence we discovered there is a slight bug in sorting of URLs, they're not always sorted from most specific match as they should be when the match is beyond the PSL suffix. e.g.
> 
> 
> 
> 1. https://abc.linked.com
> 
> 1. https://grid.linked.com
> 
> 
> 
> when visiting https://some-sub-domain.grid.linkedin.com, URL 2 should be sorted as the best match. Currently this isn't the case. We'll work on fixing that. Thanks @tonyxu-io 
> 
> 

Amazing! Good to know this will be fixed! This is my only pain point. Great job team I love this app!
