### ISSUE TITLE
BUG: Apple Watch unlock dialog doesn't go away if password is typed

### ISSUE THREAD

**Issue by Scryb** [strongbox-password-safe/Strongbox#744]
**Environment:** Mac OS 14.1.2, Strongbox 1.58.37
**Steps to reproduce:** Open Strongbox with database locked, wait for Apple Watch unlock dialog to appear, then type the password instead (reason for needing to: bad connection between Mac and watch, the double click side button to unlock thing doesn't always appear).
**Expected Result:** Database unlocks and unlock with watch dialog disappears.
**Actual Result:** Database unlocks but unlock with watch dialog stays open and needs to be canceled to close.

![Screenshot 2023-12-11 at 11 25 44](https://github.com/strongbox-password-safe/Strongbox/assets/1374099/78b3ff4a-d39f-42db-9823-190739395608)

**Comment by strongbox-mark** [comment]
Thanks, we'll see if this is a quick fix in the next release

**Comment by strongbox-mark** [comment]
This should be fixed for you in 1.58.38 available on the App Store now. Please let me know if that's not the case.
