### ISSUE TITLE
MacOS: Disable Sorting 

### ISSUE THREAD

**Issue by JLWFuQrioea69ugsykvQcg** [strongbox-password-safe/Strongbox#745]
I may be overlooking this option, but I'd like to disable sorting on the MacOS Strongbox app.  I can perform this option in both Keepass and the iOS Strongbox app.  The current options are either ascending or descending for the selected field.  Adding a new entry adds it to the end of the item list for the parent folder.  I'd like to see this view and manually sort as needed.  Am I overlooking a setting somewhere?

**Comment by strongbox-mark** [comment]
This is a little hidden but unfortunately haven't been able to find a better UX yet:

Database Settings > Advanced > Sort Items

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
ah perfect! I guess I should have looked a bit harder. The only downside is now I can't alternate between sorted ascending, sorted descending, and nonsorted simply by clicking the "Title" field for example.  This is the way Keepass behaves which makes it simple.  Maybe a future enhancement?

**Comment by strongbox-mark** [comment]
Yes, it's be nice to have a "Tri-State" sort on the column header, we did attempt to implement this a while back but it proved to be too difficult to implement in the time window we needed. We'll definitely revisit this.
