### ISSUE TITLE
Feature request: ”Strongbox Mini” (Mac menubar app with favs, categories and search)

### ISSUE THREAD

**Issue by Scryb** [strongbox-password-safe/Strongbox#746]
Just wanna start by saying you've done an *amazing* job so far on Strongbox. I'm a longtime 1Password user and a holdout on 1P 6. I tried Strongbox a couple of years ago but it wasn't quite up to my needs. Recently I got fed up with 1P 6 only working in Firefox so I started trialling both 1P 8 and Strongbox side by side, and I have to tell you: I'm definitely leaning towards Strongbox.

There are still some things that 1P has that Strongbox lacks, but from your [existing roadmap](https://www.reddit.com/r/strongbox/comments/zvt5kv/comment/j1twllg/?context=1) and the issues here I can see most of the things I'm missing (like autofill for payment cards) are being worked on 🙂

Now there's one thing that I will sorely miss from 1P 6 that isn't in either 1P 8 or Strongbox, which is the Mini app in the menubar. I know this would probably be a major undertaking so I don't have too much hope of it getting made, and it definitely isn't a must-have to choose Strongbox, but I'd still like to put it out there and see if maybe I'm not the only one who misses this from the old 1Password versions and would love to see it in Strongbox.

**Description:** When clicking the Strongbox icon in the menubar, a mini version of the full app opens instead of only a password generator. This could default to show either favorites or categories, or even suggestions based on the frontmost window (with settings available to users can customize). This screenshot shows how it looks in 1P 6 for comparison:

![Screenshot 2023-12-12 at 12 41 08](https://github.com/strongbox-password-safe/Strongbox/assets/1374099/5b79a5b2-b923-4065-b0ae-b0a2ed5a034a)

**Function:** The main use is to browse the database visually in a quick way while only covering a small part of the screen. Say you're looking for a payment card to fill in, but you don't remember exactly what it's called so searching isn't very effective. Being able to quickly navigate into the cards category and see the full list, you might remember it's somewhere in the middle of the list and bang, there it is and you can fill the details (automatically after that function is added, or manually by copying and pasting from the entry).

The use of nested menus (like regular menubar menus) is crucial as you don't have to click on anything to navigate from categories to entries to individual entry.

The Mini window should remember where it was for at least some time so you can copy one field, paste it in the app or browser you're working in, and then open it again to copy the next field. A button in each entry to pin it in a floating window, and the ability to make edits would make it perfect.

**Example of use:** 1) Stupid websites that require you to pick the "3rd, 7th and 10th character from your password" and similar nonsense – by finding the entry, pinning the window and revealing the password it's much quicker to pick those characters without hopping back and forth between that app/browser and the full Strongbox app.

**Comment by strongbox-mark** [comment]
Got it, yes, this would be a nice feature, and it's definitely on our roadmap... I think search would the first main function to be added there, and it would search across all open databases. You can see this functionality currently in our Chrome/Firefox extensions, so we just need to build it into the tray App. On top of this, if we had Credit Card types then we could easily have a submenu for that. I'm not 100% sure about building full navigation of the folder/group structure in though. Favourites also would be nice up here... 

Cheers for the kind words and the detailed feature request :)

**Comment by Scryb** [comment]
Just now I realized maybe my most used feature of the Mini app: From inside full screen apps. I was logging into a site in a browser running in Windows in Parallels (full screen, can't stand coherence mode) and needed to copy and paste the username and password. With 1P 6 Mini (or the new 1P 8 “Quick Access”) the mini window floats above the current window, including in full screen mode. With Strongbox I need to not only hop back and forth between apps but also between spaces, which takes longer due to the animation. Not to mention being a bit jarring.

Can't think of a way to solve this without either a menubar app or a floating view that can be summoned over full screen apps.

**Comment by strongbox-mark** [comment]
Hey @Scryb - we've got a new "Quick Search" available to search across any open databases, and that'll be the primary way to do that, we wouldn't see also having a tray app in addition to that. Hopefully Quick Search is useful enough for you. Going to close this out now, but feel free to open any other issues separately.

**Comment by Scryb** [comment]
Looks like it's gonna be a great addition, but one quick comment: You might want to warn users not to hide the app or it will behave weirdly. Since the quick search window is connected to the main app and not the menubar applet, if the main app is hidden and not just in the background, it will bring the main window to the front as well when you press shift-cmd-j or the menubar icon.

**Comment by strongbox-mark** [comment]
Thanks @Scryb - That doesn't sound right though, it shouldn't be connected with the hidden status of the app. Any weird behaviour you're seeing is a bug for sure and I'd like to know more about it. If you could send a screen recording to support@strongboxsafe.com I'm sure we can fix.
