### ISSUE TITLE
Creation of Android Version

### ISSUE THREAD

**Issue by ma-ideh** [strongbox-password-safe/Strongbox#751]
Hi, I’m wondering if it’s planned to release an android version of the app.. that way I can sync between my Mac and android device. Thanks for the consideration.

**Comment by strongbox-mark** [comment]
Hi, we don't have any concrete plans at the moment for something like this, but it is something we will continue to consider. The usual recommended tool for Android is KeePass2Android or KeePassDX though we don't have any personal experience with these, they will open a KeePass database for you which is compatible with Strongbox.

**Comment by strongbox-mark** [comment]
I'm not sure that it does, but you could get in touch with the author and see
