### ISSUE TITLE
Autofill Password with TouchID needs extra click in macos Safari

### ISSUE THREAD

**Issue by ericmoret** [strongbox-password-safe/Strongbox#760]
I am facing an issue with native Safari password autofill. This only happens when the password prompt on a separate page from the login. The first time, focus is given to the password field, the contextual menu showing the touchID option is not present. However when I click the key icon within the field, I do see the touchID menu entry popping up. See screenshots.
![Screenshot 2024-01-30 at 7 13 04 AM](https://github.com/strongbox-password-safe/Strongbox/assets/15149801/f3d3737b-53c9-4d49-9422-ee485b48fcf6)
![Screenshot 2024-01-30 at 7 13 22 AM](https://github.com/strongbox-password-safe/Strongbox/assets/15149801/2014f372-2afe-4c4f-ba27-0d8745b9f371)
![Screenshot 2024-01-30 at 7 13 36 AM](https://github.com/strongbox-password-safe/Strongbox/assets/15149801/e0f692a5-1fac-4560-9011-e6f58c518919)

**Comment by strongbox-mark** [comment]
Unfortunately this isn't something under our control, this is an Apple thing, the menu and the little icon is Apple GUI/Code until you select a suggestion. That's when Strongbox comes in.

**Comment by ericmoret** [comment]
I don't disagree that this may not directly be under Strongbox's control. However could it be possible that Apple's widget times out and does not display the expected icon when pulling from a third party provider as opposed to the native iCloud backend? If that was the case, could it be fixed by somehow optimizing the speed of the Strongbox backend?

**Comment by strongbox-mark** [comment]
I don't think that Apple's widget is timing out here, that's not it. The suggestions are stored in a system database (I believe it's a SQLite database under the hood). There's no direct connection/communication or contact with Strongbox to display these suggestions. Strongbox will be suspended or terminated anyway, not available to communicate with in the background (this is enforced on iOS, and tricky/awkward on macOS anyway).

Strongbox, when it unlocks a one of your password database updates the systems AutoFill suggestions database. Safari or other Apps, use System AutoFill which queries that AutoFill suggestions database. This will be super fast, I've never seen it take more than a few milliseconds. 

Just seems like some kind of display issue, best to raise with Apple.
