### ISSUE TITLE
Feature request: Preview in text mode

### ISSUE THREAD

**Issue by mietzen** [strongbox-password-safe/Strongbox#764]
I got some `.pem` certificates attached to some entries, when opening them in preview mode they look like this:
![image](https://github.com/strongbox-password-safe/Strongbox/assets/31704359/3ada089e-e701-4408-ac5c-f323b1922acf)
As you can see the default for `.pem` files is set to VS-Code on my system, I know it's one click more to open the file in VS-Code but I think it would be nice to have a preview as text mode. This way you don't have to hand the file over to a external application.

**Comment by strongbox-mark** [comment]
As mentioned in #765 - We don't control this window or display, perhaps there's a way to configure this, I'm not sure. This isn't something I think we can change from the Strongbox side.
