### ISSUE TITLE
[BUG] yubikey 5C NFC does not work.

### ISSUE THREAD

**Issue by Dividedby0KSJ** [strongbox-password-safe/Strongbox#773]
**Preliminaries**
I have ensured that:

- [Yes] I am running the latest version of Strongbox on the App Store by searching for Strongbox and clicking into it to see the Update button (or not)
- [Yes] I have performed a full restart of my device no matter how annoying that is

**Versions**
**On iOS (please complete the following information):**
 - Device: [iphoneSE2020 & iPad Air 5th gen]
 - OS: [ios 17.3.1 & ipadOS 17.3.1]

** Strongbox Version **
 - Version: [iphone pro 1.59.7 | iPad 1.59.8]

**Describe the bug**
Cannot use Yubikey 5C NFC to make a database or to add the key to an existing database.
On iPhone with NFC it spits out an error (see attached image) on iPad it just says insert key even after the key has been inserted.

**To Reproduce**
1. Create a database using hardware key.
2. Try and use yubikey 5C NFC with ether NFC on any port, or "lightning" on any port.
3. Error / No response

**Expected behavior**
That it would accept the key and use it to encrypt/decrypt the database.

**Screenshots & Recordings**
![image](https://github.com/strongbox-password-safe/Strongbox/assets/44017376/ecfdcb39-721b-4f1f-bba7-df8f5ca13f0e)

![image](https://github.com/strongbox-password-safe/Strongbox/assets/44017376/034b5ad2-26b7-4262-abd3-761bb9dd9c51)

**Additional context**
The yubikey works fine with my iPad on other things like Google.

**Comment by Dividedby0KSJ** [comment]
Additional screenshot from iPad


![image](https://github.com/strongbox-password-safe/Strongbox/assets/44017376/6e59ce6c-15c8-49a8-b9c3-802c8010b623)

**Comment by strongbox-mark** [comment]
Hi, have you seen our guide on configuring your YubiKey:

https://strongbox.reamaze.com/kb/yubikey/how-do-i-create-a-yubikey-protected

Is the device programmed for HMACSHA1 CR on one of its slots?

**Comment by fc757** [comment]
So, I'm not sure if this is the reason you are/were having that problem. But figured I throw this out there just in case. I was running into something similar when trying to unlock my database. It had been a while and I was on a new device, so I had to set up all the stuff again.

I was using NFC Slot 1 and my HMACSHA1 CR was on NFC Slot 2. Fred Sanford came down from the heavens and looked me right in the eye and said... `you big dummy'.
