### ISSUE TITLE
A small typo in a support article

### ISSUE THREAD

**Issue by MooseExplorer637** [strongbox-password-safe/Strongbox#774]
In [this](https://strongboxsafe.com/updates/move-your-passwords-from-bitwarden-to-keepass-on-mac-or-iphone/#guide) support article, where you have instructions for migrating from Bitwarden to Strongbox, you inadvertently write 1Password when you should have written Bitwarden.

"You now need to set a master password for your new Strongbox database. This can be the same as your old 1Password master password if you like".

**Comment by strongbox-mark** [comment]
Thank you! Should be fixed now :)
