### ISSUE TITLE
[BUG] QuickType and Autofill ignoring the port from visited URL

### ISSUE THREAD

**Issue by lukasl96** [strongbox-password-safe/Strongbox#777]
**Preliminaries**
I have ensured that:

- [x] I am running the latest version of Strongbox on the App Store by searching for Strongbox and clicking into it to see the Update button (or not)
- [x] I have performed a full restart of my device no matter how annoying that is

**Versions**
*On iOS (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 14 Pro Max
 - OS: [e.g. iOS8.1] iOS 17.3.1

** Strongbox Version **
 - Version: [e.g. 1.59.0] 1.59.9 Pro

**Describe the bug**
I have an Host in my internal network which provides multiple Webapps on different ports thorough docker.
When I want to log in on these Websites Strongbox usually suggests the wrong entry. Auto-Fill and QuickType are affected. I should be easily fixed when the search query includes the used port.

**To Reproduce**
1. Have Multiple Websites/Webapps on the same System (hostname or IP) on different ports
1. Go to one of the pages and click in an Login-Form
2. Check QuickType
3. Check Auto-Fill

**Expected behavior**
I expect Strongbox suggests the right entry matching on the following Part of the visited URL:
PROTOCOL://HOST:PORT

**Screenshots & Recordings**

**Additional context**

**Comment by strongbox-mark** [comment]
I believe this isn't something that we can fix on the Strongbox side. This is Apple's algorithm. Strongbox doesn't choose what to suggest, it can only tell the system it provides credentials for a certain URL. What to suggest is up to the Apple algo and it seems like it doesn't properly take ports into account I'm afraid.
