### ISSUE TITLE
[BUG] iOS 18 Convience unlock doesn't work with database keyhole

### ISSUE THREAD

**Issue by SUPERHAMSTERI** [strongbox-password-safe/Strongbox#785]
**Preliminaries**
I have ensured that:

- [X] I am running the latest version of Strongbox on the App Store by searching for Strongbox and clicking into it to see the Update button (or not)
- [X] I have performed a full restart of my device no matter how annoying that is

**Versions**
 - Device: iPhone 15 Pro
 - OS: 18

**Strongbox Version**
 - Version: 1.59.12

**Describe the bug**
Safari autofill says that credentials are incorrect when trying to use database with keyhole. 
Tested with new database without keyfile, and that works ok.

Readded database (Onedrive sync) and now it won't open at all (same error)

**Screenshots & Recordings**
![image](https://github.com/strongbox-password-safe/Strongbox/assets/20796404/7875faa7-7399-44c5-94b0-62bf5eddad0c)

**Additional context**
I know it's beta ;)

**Comment by tommylux** [comment]
Replicated on iOS 18.0 (22A5282m) development beta.
At first thought it was special characters but removing the key file it stated working. 

Workaround, (backup your files) then re-create the keyfile from IOS. The same files can then be used to unlock from other devices, windows etc.

Through testing a new keyfile created on Windows doesn't seem to work on iOS, but one created on iOS seems to work in Windows.

**Comment by strongbox-mark** [comment]
Yes, there does look to be an issue involving key files on iOS 18, we'll try to investigate when we can...

In the meantime, could you try;

1) Remove your database
2) Remove your imported Key File
3) Re-add your database and freshly re-import your key file.

Does that work?

**Comment by SUPERHAMSTERI** [comment]
> Yes, there does look to be an issue involving key files on iOS 18, we'll try to investigate when we can...
> 
> In the meantime, could you try;
> 
> 1. Remove your database
> 2. Remove your imported Key File
> 3. Re-add your database and freshly re-import your key file.
> 
> Does that work?

Tried that and that does not work.

**Comment by strongbox-mark** [comment]
Thanks @SUPERHAMSTERI - If you create a new database and create a new key file within Strongbox, does that work?

**Comment by tommylux** [comment]
> Thanks @SUPERHAMSTERI - If you create a new database and create a new key file within Strongbox, does that work?
Yes it seems to work, and the same keyfile seems to work in windows (keepass), but interestingly, you get an error when trying to open the file in StrongBox for Mac.

**Comment by strongbox-mark** [comment]
What error do you get on Mac? That's super unexpected

**Comment by tommylux** [comment]
> What error do you get on Mac? That's super unexpected

My first point of call was when it was broken, and re-creating a keyfile on IOS worked, was to copy that to windows and Mac..

At a glance, the same error that's from IOS, I can get a screen grab. But for clarity, the Mac is not in Beta - it uses the Keyfile generated from IOS. This semmed to work in windows when I copied the new KeyFile to OneDrive, using the same Keyfile from OneDrive on Mac seemed to cause the same error. But I could always double check.

**Comment by SUPERHAMSTERI** [comment]
Even more strange is that Keepassium can handle key file without problem (assumed that iOS 18 alters some metadata for privacy that causes it not to work at all but no, seems like it doesn't)

**Comment by zackeryfretty** [comment]
I'm also having a similar issue but I am **NOT** using the iOS beta, I'm having this issue on iOS 17. 

I use a virtual key for Autofill on iOS and after doing a sync from OneDrive this morning (which pulled in an update I made on my Mac -- also not using a beta) and I get the same credentials incorrect. 

The issue seems to be with my virtual key and I know it's correct. 

Could this be an issue with OneDrive's sync?

**Comment by SUPERHAMSTERI** [comment]
Looks like this is fixed in iOS 18 Beta 2. Maybe?

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
Yeah I noticed the same thing after updating to beta 2. I was using the 1.60 TestFlight version which did not work on beta 1, but now works on beta 2.

**Comment by strongbox-mark** [comment]
Yes, this should be fixed for you now with 1.60.0. Please let me know if that's not the case.
