### ISSUE TITLE
[BUG] Duplicate suggestions for one credential entry in the database

### ISSUE THREAD

**Issue by oasaleh** [strongbox-password-safe/Strongbox#786]
**Preliminaries**
I have ensured that:

- [X] I am running the latest version of Strongbox on the App Store by searching for Strongbox and clicking into it to see the Update button (or not)
- [x] I have performed a full restart of my device no matter how annoying that is

**Versions**
**On macOS (please complete the following information):**
 - OS: macOS Sonoma 14.5 (23F79)

**Strongbox Version**
 - Version: 1.59.11

**Describe the bug**
Multiple suggestions from one database entry are being suggested as if they're different entries/creds. Please note that I didn't enter any of the associated websites. It's automatically filled by Strongbox.

**Expected behavior**
Only one entry is suggested.

**Screenshots & Recordings**
<img width="929" alt="Screenshot 2024-06-14 at 11 25 29 AM" src="https://github.com/strongbox-password-safe/Strongbox/assets/56449814/cafeb747-edae-40ff-b9b9-0b14f5427a13">
<img width="418" alt="Screenshot 2024-06-14 at 11 24 04 AM" src="https://github.com/strongbox-password-safe/Strongbox/assets/56449814/15bb88dd-3ea4-441b-905f-c80daf3ec742">

**Comment by strongbox-mark** [comment]
Hi @oasaleh - This might be related to Associated Domains:

Database Settings > AutoFill > Advanced Settings > Include Associated Websites 

Could you try disabling that to see if it changes things?

**Comment by oasaleh** [comment]
@strongbox-mark, yes that fixed it. But I wouldn't want this to be the solution as "Include Associated Websites" is a nice feature!

**Comment by strongbox-mark** [comment]
@oasaleh - For sure, just wanted to confirm that was the source of the issue, will look into a fix for this...

**Comment by strongbox-mark** [comment]
@oasaleh This should be fixed for you with 1.60.0. Let me know if that's not the case.

**Comment by oasaleh** [comment]
Thank you. It's working properly now.
