### ISSUE TITLE
[BUG] Trying to open a database stored on google drive without internet forces relogin on next try.

### ISSUE THREAD

**Issue by turbocool3r** [strongbox-password-safe/Strongbox#789]
**Preliminaries**
I have ensured that:

- [*] I am running the latest version of Strongbox on the App Store by searching for Strongbox and clicking into it to see the Update button (or not)
- [*] I have performed a full restart of my device no matter how annoying that is

**Versions**
**On macOS (please complete the following information):**
 - OS: macOS Sonoma 14.5

** Strongbox Version **
 - Version: 1.60.5

**Describe the bug**
When I try to unlock a database I store on google drive and my mac isn't connected to the internet, the sync will fail. When I connect to the internet later and try unlocking the same database, Safari opens and I'm required to login into the google account again. That's inconvenient, especially considering I store the password in the same database.

**To Reproduce**
1. Create a database that is stored on a google drive.
2. Add some password to it.
3. Disable internet connection.
4. Try to unlock and sync this database.
5. Enable internet connection.
6. Try to unlock and sync this database again.
7. See safari being open.

**Expected behavior**
Safari isn't open and the database is successfully unlocked.

**Comment by strongbox-mark** [comment]
That doesn't sound right, thanks for the report, we'll try get that fixed for you in the next release.

**Comment by turbocool3r** [comment]
thanks!

**Comment by strongbox-mark** [comment]
This should be fixed for you with 1.60.8. Let me know if that's not the case!
