### ISSUE TITLE
[StrongBox Zero] Only non-recommended storage location available

### ISSUE THREAD

**Issue by akuropka** [strongbox-password-safe/Strongbox#795]
**Preliminaries**
I have ensured that:

- [X] I am running the latest version of Strongbox on the App Store by searching for Strongbox and clicking into it to see the Update button (or not)
- [X] I have performed a full restart of my device no matter how annoying that is

**Versions**
 - Device: iPhone 15 Pro Max
 - OS: iOS 18.0 (22A5316k)

** Strongbox Version **
 - Version: Pro 1.60.9 (Zero)

**Describe the bug**
If importing a database there's only a non-recommended storage location (Files) available.

**To Reproduce**
1. Go to "+" in the upper right corner.
2. Click on "Add Existing"
3. Observe note
4. Optional: Select "Files" as provider
5. Observe warning

**Expected behavior**
User may be irritated as there's only a non-recommended way to add an existing database.

**Additional context**
Also, the description talks about a sync process. Does this apply to the Zero version?
Maybe an import function to "Local Device" may be an option for recommended storage.

**Screenshots & Recordings**
![Screenshot 2024-07-29 at 09 16 18 jpeg](https://github.com/user-attachments/assets/16a45a12-caba-4888-9d4e-869780ff4a57)

**Comment by strongbox-mark** [comment]
Hi @akuropka - Thanks for the report, that is less than ideal, we'll see if we can come up with a less irratating experience here for Zero users.

**Comment by strongbox-mark** [comment]
@akuropka This should be much improved/more clear for you now with 1.60.15.
