### ISSUE TITLE
[BUG] TOTP Progress Bar stays at minimum

### ISSUE THREAD

**Issue by EdJoPaTo** [strongbox-password-safe/Strongbox#798]
**Preliminaries**
I have ensured that:

- [ ] I am running the latest version of Strongbox on the App Store by searching for Strongbox and clicking into it to see the Update button (or not)
- [x] I have performed a full restart of my device no matter how annoying that is

**Versions**
**On iOS (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 17.5.1

** Strongbox Version **
 - Version: 1.60.10 TestFlight build 4856

**Describe the bug**

The TOTP progress bar indicating its expiring soon stays at its minimum position. But the codes switch correctly and the blinking / color change seems also like normal.

**To Reproduce**
1. Navigate to an entry with a configured TOTP
2. See its progress bar

**Expected behavior**

The bar should get smaller and smaller until it refreshes to its full width with a new code

**Screenshots & Recordings**

![IMG_6744](https://github.com/user-attachments/assets/b497c3e7-55e7-4918-898f-b52158bece43)

**Comment by strongbox-mark** [comment]
Wow, had not spotted that, thanks @EdJoPaTo - We'll get it fixed in the next couple of days

**Comment by EdJoPaTo** [comment]
Works again with 1.60.10 (4861), so this can be closed or is there still something relevant on your side?

**Comment by strongbox-mark** [comment]
Yes, good to hear :) Closing...
