### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by georgesnow** [strongbox-password-safe/Strongbox#799]
New test flight .10 I tested the home tab and crashes anytime I try it.

I added home as another tab and in my case it was in the more section and I picked the Home Screen and it crashed

**Comment by strongbox-mark** [comment]
Thanks @georgesnow, would you be able to send the crash report to support@strongboxsafe.com? We're not seeing it reported in the dashboard so we're blind as to the cause.

**Comment by georgesnow** [comment]
Sent.

**Comment by strongbox-mark** [comment]
Thanks @georgesnow - Could you check if this happens on a brand new database? 

And lastly, if you can, see if a full uninstall/reinstall fixes it?

**Comment by georgesnow** [comment]
Doesn't happen with new database using the same sync method (strongbox sync). I also tried it on my other 2 databases (iCloud file sync). No issue. One difference all those databases are less than 10MB. The one that crashes is 117MB. 

I will the uninstall/reinstall but I am guessing it is memory issue due to the size of the database.

**Comment by georgesnow** [comment]
Uninstall and reinstall appears to have to stop the crashing.

**Comment by strongbox-mark** [comment]
Ok, super weird, the crash report was very odd too... Fingers crossed it's just a Heisenbug.

**Comment by georgesnow** [comment]
I haven't experienced again. closing.
