### ISSUE TITLE
[BUG] Strongbox is missing in the 2FA/TOTP option of macOS

### ISSUE THREAD

**Issue by Tekl** [strongbox-password-safe/Strongbox#800]
**Preliminaries**
I have ensured that:

- [x] I am running the latest version of Strongbox on the App Store by searching for Strongbox and clicking into it to see the Update button (or not)
- [x] I have performed a full restart of my device no matter how annoying that is

**Versions**
**On macOS (please complete the following information):**
 - OS: macOS 14.6 and macOS 15.1 Beta

**On iOS (please complete the following information):**
 - Device: iPhone 15
 - OS: iOS 18 Beta 5

**Strongbox Version**
 - Version: 1.60.2 (Pro)

**Describe the bug**
I can't select Strongbox as a TOTP-provider in the system settings of macOS. Other Apps like Minimalist Password are selectable. I don't know if it ever worked. I just stumbled upon the option and didn't even know that it was possible. In iOS I see 2FAS Auth but also not Strongbox.

**To Reproduce**
1. Go to 'General » Autofill & Passwords' (macOS 15) or 'General » Passwords » Password options' (macOS 14)
2. Click on the drop-down at 'Set Up Codes in'
3. Strongbox is missing In the drop-down

**Expected behavior**
I thought every Password Manager that utilizes Apples API will be selectable there.

**Screenshots & Recordings**

![CleanShot 2024-08-07 at 19 28 34](https://github.com/user-attachments/assets/6d753da7-16ce-4571-b1c2-963326cc06e3)

**Comment by strongbox-mark** [comment]
As with #750, this is now available with 1.60.17.
