### ISSUE TITLE
[BUG] Recurrent Face Id

### ISSUE THREAD

**Issue by O35dE** [strongbox-password-safe/Strongbox#801]
**Preliminaries**
I have ensured that:

- [ ] I am running the latest version of Strongbox on the App Store by searching for Strongbox and clicking into it to see the Update button (or not)
- [ ] I have performed a full restart of my device no matter how annoying that is

**Versions**

**On iOS (please complete the following information):**
 - Device: iPhone15
 - OS: iOS 17.6.1

** Strongbox Zero Version **
 - Version: 1.60.14

**Describe the bug**
Strongbox Zero, after the last update, I restarted the iPhone, and when I try to open the app ( I have Face Id + Pin enabled) the Face Id check becomes recurrent, it will not stop until you close the app.

**To Reproduce**
1. Open the app.
2. Face Id check repeats itself indefinitely.

**Expected behavior**
App should open normally after a single Face Id + Pin check.

**Comment by strongbox-mark** [comment]
Aware of the issue and a fix is now with Apple for review. Hopefully they'll approve shortly.
