### ISSUE TITLE
Git commit signing SSH Key

### ISSUE THREAD

**Issue by philxws692** [strongbox-password-safe/Strongbox#802]
Hey there, 

I am trying to make the switch from KeepassXC to Strongbox, but I did not find the possibility to sign my git commits with an SSH key stored in my database. Currently as KeepassXC adds all keys to the agent when unlocked, it is working perfectly. But due to the fact, that the keys stored in Strongbox do not leave the database, this is not working.

Is there any possibility to configure my git signing so that it asks Strongbox for the wanted private key? Just like when I am connecting to a server with an SSH Key.

Thanks in advance 😄

**Comment by strongbox-mark** [comment]
Hi there, have you seen the Git Commit Signing section of our help article here:

https://strongbox.reamaze.com/kb/ssh-agent/ssh-agent

Does that help?

**Comment by philxws692** [comment]
I actually saw this page, but I didn't scroll far enough and missed the important section `Setting SSH_AUTH_SOCK correctly`. 

Thank you very much
