### ISSUE TITLE
[BUG] AutoType Issue

### ISSUE THREAD

**Issue by JLWFuQrioea69ugsykvQcg** [strongbox-password-safe/Strongbox#808]
**Preliminaries**
I have ensured that:

- [x] I am running the latest version of Strongbox on the App Store by searching for Strongbox and clicking into it to see the Update button (or not)
- [x] I have performed a full restart of my device no matter how annoying that is

**Versions**
**On iOS (please complete the following information):**
 - Device: iPhone 15 PM
 - OS: 18.0 RC

** Strongbox Version **
 - Version: 1.60.19

**Describe the bug**
Strongbox autofill/quickfill is not populating login credentials when the Strongbox prompted entry is selected. This functionality works fine prior to update in the previous version.

**To Reproduce**
1. Go to a website with a login stored in Strongbox
2. Click on login box
3. Strongbox presents a credential to click to login
4. Click presented credential
5. Nothing happens where it used to populate the login credentials
6. Click on login box again
7. Click key icon and select credential from Strongbox list
8. Nothing happens where it used to populate the login credentials
9. Click key icon and this time select Strongbox to open Strongbox app, navigate to entry, select entry 
10. This time, credentials populate, and I'm logged in.

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
FWIW I reverted back to 1.60.18 and it's working as expected.

**Comment by strongbox-mark** [comment]
Thanks for the report @JLWFuQrioea69ugsykvQcg - Fix on the way and with Apple now.

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
As always, very much appreciated!!!

**Comment by strongbox-mark** [comment]
This should be fixed for you now @JLWFuQrioea69ugsykvQcg with 1.60.20. Let me know if that's not the case.

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
It works as expected thank you very much and thanks for closing this ticket
