### ISSUE TITLE
[BUG] Documentation is unclear: delete virtual hardware key

### ISSUE THREAD

**Issue by kissu** [strongbox-password-safe/Strongbox#809]
**Preliminaries**
I have ensured that:

- [x] I am running the latest version of Strongbox on the App Store by searching for Strongbox and clicking into it to see the Update button (or not)
- [x] I have performed a full restart of my device no matter how annoying that is

**Versions**
**On macOS (please complete the following information):**
 - OS: 14.6.1

**Strongbox Version**
 - Version: 1.60.19

**Describe the bug**
[This page](https://strongbox.reamaze.com/kb/yubikey/how-do-i-delete-a-virtual-hardware-key) is very unclear as to where to find the "show advanced" or even where the ⌥ (Option) key is supposed to be doing anything. Looked around the entire app but found nothing. :(

**Expected behavior**
Having 2 screenshots of where to find it would be very welcome. 🤗 

**Screenshots & Recordings**
Nothing here
![CleanShot 2024-09-14 at 10 39 16@2x](https://github.com/user-attachments/assets/4e76a96e-85f7-4c4f-8ab9-d594c92bc575)

Nothing here either
![CleanShot 2024-09-14 at 10 39 37@2x](https://github.com/user-attachments/assets/cd5662b4-df25-4f25-8f10-905f36de6a49)

**Comment by strongbox-mark** [comment]
Hi there, I'm sure we could add a screenshot here, but are you looking for the option key? This is on your keyboard beside the Command key.

**Comment by kissu** [comment]
No I know where the key itself is. 😂 
I just don't see where this is changing anything. Tried to hold it while looking around the entire UI with no apparent related change.

**Comment by strongbox-mark** [comment]
Haha, ok, sorry. And what happens when you do step 2:

> 2. Hold down the ⌥ (Option) key and click on the key you would like to delete.

**Comment by kissu** [comment]
Oooooh, click on a hardware key **while holding** as in my 2nd screenshot (even if you don't see anything happening + while being in a dropdown).
Okay, that works! But there is definitely no highlight or micro-interaction/icon/anything so I would have never guessed that move.
Okay, it's more of a UX issue then: it would be nice to have some kind of icon next to the key while holding ⌥. 😄

**Comment by strongbox-mark** [comment]
For sure, this one is a little cryptic! Sorry about that :) I'll add to our list to try improve this, almost Easter Egg level feature! 🤣
