### ISSUE TITLE
[Feature] Dark Icon variation for iOS 18/iPadOS 18

### ISSUE THREAD

**Issue by greatestview** [strongbox-password-safe/Strongbox#811]
With iOS 18, Apple introduced more app icon variants. To align with the developer guidelines, I’d like to suggest implementing a dark app icon variant. To do so, the app should provide a transparent icon with a blue Strongbox logo. The black background gradient would automatically be provided by iOS.

More information here: https://developer.apple.com/design/human-interface-guidelines/app-icons#Platform-considerations

Btw. Thank you for the good work!

**Comment by strongbox-mark** [comment]
Definitely like to do this, we’ll try to prioritise shortly!

**Comment by dan-el** [comment]
I think this works already with the "blue on white background" icon. ![image](https://github.com/user-attachments/assets/cd177197-adba-4d83-8add-de338bb65b97)
![image](https://github.com/user-attachments/assets/0376224d-a463-4b43-81da-0aeb8dfe7e26)

**Comment by strongbox-mark** [comment]
This should be available for you now with 1.60.21 by default (no need to select the custom White app icon) - Please reopen if that's not the case!

**Comment by greatestview** [comment]
Thank you! I have Strongbox Pro 1.60.22 installed, but in my installation still only the white backgrounded icon will be displayed with black background. The other icons will be displayed exactly as seen in this screen, e. g. default icon blue background white foreground won’t change to black background white foreground.

![IMG_9445](https://github.com/user-attachments/assets/56b98d4d-80ec-4c09-98d8-9f24c3405cd7)

Or did I misunderstand and the new implemented feature just auto-selects the white background blue foreground icon as default app icon?

**Comment by strongbox-mark** [comment]
Hi @greatestview - Could you try tapping the "Restore Default" or "Auf Standard zurucksetzen" button at the bottom of that screen instead of click on the icons at the top. Does that work for you?

**Comment by greatestview** [comment]
Yes, that works! Thank you 🥳

**Comment by dan-el** [comment]
Will we get Dark Mode icons for the non blue logo variations too? Would love to see it!
