### ISSUE TITLE
Crash on Database Authentication

### ISSUE THREAD

**Issue by JLWFuQrioea69ugsykvQcg** [strongbox-password-safe/Strongbox#813]
**Preliminaries**
I have ensured that:

- [x] I am running the latest version of Strongbox on the App Store by searching for Strongbox and clicking into it to see the Update button (or not)
- [x] I have performed a full restart of my device no matter how annoying that is

**Versions**
**On macOS (please complete the following information):**
 - OS: [e.g. macOS Sonoma 14.2]

**On iOS (please complete the following information):**
 - Device: iPhone 16 Pro Max
 - OS: iOS 18.1 beta six

** Strongbox Version **
 - Version: latest version available on the App Store as of 10/9/24

**Describe the bug**
The Strongbox app crashes when trying to authenticate to an existing database. I tried adding the same database as a new database and generates an incorrect credentials error. This same issue seem to have popped up in a previous version of Strongbox in the early iOS 18 betas. It was fixed at that time.

**To Reproduce**
1. Open Strongbox
2. Select existing database
3. App crashes while trying to authenticate via Face ID
4. Tried to add the same database as a new database.
5.  Strongbox generates an error about incorrect credentials, but I know they are correct.

**Expected behavior**
I expect a database open without any issues. 

**Screenshots & Recordings**
I sent the logs to Strongbox support. 

**Additional context**

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
What's interesting is that while I can't open the database via the app autofill on a website in Safari still seems to work fine if I'm selecting the Strongbox entry.

**Comment by strongbox-mark** [comment]
Thanks for the report @JLWFuQrioea69ugsykvQcg - aware of an issue with iOS 18.1 beta 6.

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
Thank you I appreciate the acknowledgment. As much as I love and use this app it's not worth all that effort to revert since that's the only issue I'm having so that's all the question. I guess I'm waiting around for either Apple to fix it or you to fix it.

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
Thank you for fixing this issue so quickly.  Much appreciated! I was hoping Apple's next beta would unbreak whatever they broke, but you beat them to it.
