### ISSUE TITLE
[feature/nitpick] TOTP tooltip mouseover

### ISSUE THREAD

**Issue by smopucilowski** [strongbox-password-safe/Strongbox#814]
**Preliminaries**
I have ensured that:

- [x] I am running the latest version of Strongbox on the App Store by searching for Strongbox and clicking into it to see the Update button (or not)
- [x] I have performed a full restart of my device no matter how annoying that is

**Versions**
**On macOS (please complete the following information):**
 - OS: [e.g. macOS Sonoma 14.2]
macOS Sonoma 15.0.1 (24A348)

** Strongbox Version **
 - Version: [e.g. 1.59.0]
Strongbox Pro 1.60.22

**Describe the bug**

<img width="255" alt="image" src="https://github.com/user-attachments/assets/c22e6ef7-aef3-4d1c-9628-5531f08ecbe6">

I'm an expert, but this wasn't immediately apparent to me that this is for (a form of) 2FA. I also had no clue what TOTP is, and there's no tooltip.
Perhaps this label could be 2FA / TOTP, with a tooltip saying "Time-based one-time password"

**Comment by strongbox-mark** [comment]
Thanks for the report, yes, it should be 2FA everywhere, not sure how this one slipped through the recent change to use 2FA... Will fix...

**Comment by smopucilowski** [comment]
You have my many thanks. The term "TOTP" also appears in documentation/news, such as for example: https://strongboxsafe.com/updates/autofill-keepass-passwords-on-mac-chrome-firefox-safari/

**Comment by strongbox-mark** [comment]
This should be fixed for you, in app at least in 1.60.23. Please let me know if that's not the case. Cheers.
