### ISSUE TITLE
[FEATURE] on iOS ability to know callerID of app

### ISSUE THREAD

**Issue by azfar** [strongbox-password-safe/Strongbox#817]
I was using another keepass app on ios which in case of no match (but you already have an entry for the that app/website) shows the callerid of the app which you can add to your keepass entry so next time it can match.

Something like that will be highly helpful.

**Comment by strongbox-mark** [comment]
Hi @azfar - This should already be available for you, it's called "Service ID", are you not seeing that?

**Comment by azfar** [comment]
Hi Mark,

Thanks for getting back.

When I am launching an app and then choosing Password > Strongbox, the app is opening in search mode and showing all entries but I can not see the "Service ID" so I can add it manually to my entry.

**Comment by strongbox-mark** [comment]
That's either a bug or the website/app isn't providing any id at all. If you go to say github.com on your device and choose sign-in, then select "Strongbox" rather than an existing autofill entry you should see the service id at the bottom. Do you see that?

**Comment by azfar** [comment]
You are correct Mark, not much options here. Thanks again for your time.

**Comment by strongbox-mark** [comment]
No worries @azfar
